project:
  type: website
  render:
    - "*.qmd"
    - "!basic-set-theory/"

website:
  title: "directknowledge"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



