# Direct Knowledge (2023 version)
# python -m http.server 8000
# 

project:
  type: book
  resources: 
    - assets
  post-render: 
    - html_revise.py
  render: 
    - "*.qmd"

book:
  title: "Direct Knowledge"
  author: "David A. Smith"
  #date: "3/2/2023"
  output-file: "hardcover"
  chapters:
    - index.qmd
    - references.qmd
  site-url: https://directknowledge.com
  page-navigation: true
  search: 
    location: sidebar
    type: textbox
  sidebar:
    style: "floating"
    collapse-level: 0
  navbar:
    title: "Direct Knowledge"
    background: light
    foreground: dark
    logo: assets/directknowledge-logo.svg
    logo-alt: Direct Knowledge Logo
    right: 
      - href: https://www.youtube.com/channel/UCi_E35l9kKfrxoQJRMbgMsg/
        icon: youtube
        aria-label: YouTube
  description: "Direct Knowledge: On the theory of connections, concepts, and geometry"
  favicon: assets/favicon.ico
  open-graph: true
  page-footer:
    center: 
      - text: "&copy; Copyright 2023, All Rights Reserved. David A. Smith"
        href: index.qmd
  repo-url: https://github.com/directknowledge/directknowledge.com
  repo-actions: [issue]
  isbn: "978-1-951290-10-8"
  language: "en"
  medium: "digital online"
  public-url: "https://directknowledge.com"
  publisher: "David A. Smith"

bibliography: references.bib

format:
  html:
    theme: cosmo
    anchor-sections: true
    collapse-level: 1
    link-external-icon: false
    link-external-newwindow: true
    toc: true
    toc-title: "Chapter Contents"
    toc-depth: 3
    toc-location: right
    smooth-scroll: true
    html-math-method:
      method: mathjax
      url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"	
    include-in-header: 
      - _html/head.html
    include-after-body: 
      - _html/organization.html
      - _html/website.html
      - _html/mathjax.html
      #- _html/analytics.html
  pdf:
    keep-tex: true
    toc: false
    documentclass: book
    classoption: [10pt,reqno,twopage,openany]
    include-in-header: 
      - _tex/packages.tex
      - _tex/commands.tex
    include-before-body:
      - _tex/titlepage-hardcover.tex
    include-after-body: 
      - _tex/makeindex.tex


