[[redirects]]
  from = "https://directknowledge-testing.netlify.app/*"
  to = "https://directknowledge.com"
  status = 301
  force = true
  [redirects.headers]
    X-From = "Netlify"
 
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "geolocation=(), microphone=()"
    Content-Security-Policy = '''
      form-action 'self';
      frame-src https://www.youtube.com/embed/ 
    '''

[[redirects]]
  from = "https://directknowledge.com/basicsettheory"
  to = "https://directknowledge.com/basic-set-theory/"
  status = 301

[[redirects]]
  from = "https://directknowledge.com/learningnumbertheory"
  to = "https://directknowledge.com/learning-number-theory/"
  status = 301

[[redirects]]
  from = "https://directknowledge.com/learninglinearalgebra"
  to = "https://directknowledge.com/learning-linear-algebra/"
  status = 301

[[redirects]]
  from = "https://directknowledge.com/exploringcalculus"
  to = "https://directknowledge.com/exploring-calculus/"
  status = 301

[[redirects]]
  from = "https://directknowledge.com/multivariablecalculcus"
  to = "https://directknowledge.com/multivariable-calculcus/"
  status = 301

[[redirects]]
  from = "https://directknowledge.com/polynomial-congruences/"
  to = "https://directknowledge.com/learning-number-theory/polynomial-congruences.html"
  status = 301

[[redirects]]
  from = "https://directknowledge.com/writing"
  to = "localhost:8000/blog/writing-mathematics/"
  status = 301
