# Learning Number Theory

project:
  type: book
  resources: 
    - assets
    - images
  post-render: 
    - ../_webtools/html_revise_lnt.py

book:
  title: "Learning Number Theory"
  chapters:
    - index.qmd
    - peanos-axioms.qmd
    - divisibility.qmd
    - unique-factorization.qmd
    - congruence-equations.qmd
    - eulers-theorem.qmd
    - quadratic-congruences.qmd
    - polynomial-congruences.qmd
    - references.qmd
  sidebar:
    title: "Learning Number Theory"
  site-url: https://directknowledge.com/learning-number-theory/
  description: "Learning Number Theory"
  isbn: "978-1-951290-12-2"

metadata-files:
  - ../_variables.yml
  - ../_meta/book-html.yml
  - ../_meta/format.yml
  #- _meta/_book-epub.yml
  #- _meta/_book-hardcover.yml
  - _meta/_book-paperback.yml
