# Learning Number Theory

project:
  type: book
  resources: 
    - assets
    - images
  post-render: 
    - ../_webtools/html_revise_lnt.py

book:
  title: "Learning Number Theory"
  chapters:
    - index.qmd
    - peanos-axioms.qmd
    - divisibility.qmd
    - euclidean-algorithm.qmd
    - unique-factorization.qmd
    - congruence-equations.qmd
    - eulers-theorem.qmd
    - quadratic-congruences.qmd
    #- polynomial-congruences.qmd
    - references.qmd
  sidebar:
    title: "Learning Number Theory"
  site-url: https://directknowledge.com/learning-number-theory/
  description: "Learning Number Theory"

format:
  html:
    include-in-header: 
      - ../_html/head-lnt.html
  pdf:
    keep-tex: true
    toc: false
    documentclass: book
    classoption: [10pt,reqno,twopage,openany]
    include-in-header: 
      - ../_control/packages-lnt.tex
      - ../_control/commands.tex
    include-before-body:
      - ../_control/topmatter.tex
    include-after-body: 
      - ../_control/makeindex.tex

metadata-files:
  - ../_meta/book.yml
  - ../_meta/format.yml
