# Tutorials

project:
  type: website
  post-render: 
    - ../_webtools/html_revise_tutorials.py
  render:
    - "*.qmd"
    - "!galois-connections/"
    - "!incidence-geometry/"
    #- "!mathematical-induction/"


website:
  title: "Tutorials"
  site-url: "https://directknowledge.com/tutorials"
  search: false
  repo-url: https://github.com/directknowledge/directknowledge.com
  repo-actions: [issue]
  navbar:
    title: "Direct Knowledge"
    background: light
    foreground: dark
    logo: ../assets/directknowledge-logo.svg
    logo-alt: Direct Knowledge Logo
    right: 
      - text: "Books"
        menu: 
          - text: "Basic Set Theory"
            href: ../basic-set-theory/
            icon: book
            aria-label: Basic Set Theory Book
          - text: "Learning Number Theory"
            href: ../learning-number-theory/
            icon: book
            aria-label: Learning Linear Algebra Book
          - text: "Learning Linear Algebra"
            href: ../learning-linear-algebra/
            icon: book
            aria-label: Learning Linear Algebra Book
          - text: "Single Variable Calculus"
            href: ../single-variable-calculus/
            icon: book
            aria-label: Single Variable Calculus Book
          - text: "Multivariable Calculus"
            href: ../multivariable-calculus/
            icon: book
            aria-label: Multivariable Calculus Book
      - text: "Articles"
        menu: 
          - text: "Blog"
            href: ../blog/
            icon: journal
            aria-label: Personal Blog
          - text: "Tutorials"
            href: ../tutorials/
            icon: journal
            aria-label: Tutorials
          - text: "Research"
            href: ../research/
            icon: journal
            aria-label: Research Articles
      - href: ../about.html
        text: "About"
      - href: https://www.youtube.com/channel/UCi_E35l9kKfrxoQJRMbgMsg/
        icon: youtube
        aria-label: YouTube
      - href: https://github.com/directknowledge
        icon: github
        aria-label: GitHub
  open-graph: true
  page-footer:
    center: 
      - text: "&copy; Copyright 2023, All Rights Reserved. DirectKnowledge.com"
        href: https://directknowledge.com


format:
  html:
    theme: cosmo
    anchor-sections: true
    link-external-icon: false
    link-external-newwindow: true
    smooth-scroll: true
    include-in-header: 
      - ../_html/head.html
      - ../_html/mathhead.html
    include-after-body: 
      - ../_html/organization.html
      - ../_html/website.html
      - ../_html/mathjax.html
      - ../_html/analytics.html

metadata-files:
  - _metadata.yml

