# Exploring Calculus

project:
  type: book
  resources: 
    - assets
    - images
  post-render: 
    - ../_webtools/html_revise_ec.py

book:
  title: "Exploring Calculus"
  chapters:
    - index.qmd
    - limits-and-continuity.qmd
    - intuitive-introduction-to-limits.qmd
    - techniques-for-finding-limits.qmd
    - continuous-functions.qmd
    - tangent-lines-and-rates-of-change.qmd
    - differentiation.qmd
    - derivative-as-a-function.qmd
    - basic-rules-of-differentiation.qmd
    - product-and-quotient-rules.qmd
    - role-of-the-derivative.qmd
    - derivatives-of-trigonometric-functions.qmd
    - chain-rule.qmd
    - implicit-differentiation.qmd
    - derivatives-of-inverse-functions.qmd
    - related-rates.qmd
    - linearization-and-differentials.qmd
    - parametric-curves.qmd
    - applications-of-derivatives.qmd
    - extreme-values.qmd
    - mean-value-theorem.qmd
    - monotonic-functions.qmd
    - concavity-and-inflection-points.qmd
    - limits-involving-infinity.qmd
    - curve-sketching.qmd
    - applied-optimization-problems.qmd
    - parametric-equations.qmd
    - indeterminate-forms.qmd
    - integration.qmd
    - indefinite-integrals.qmd
    - integration-by-substitution.qmd
    - area.qmd
    - definite-integral.qmd
    - fundamental-theorem-of-calculus.qmd
    - numerical-integration.qmd
    - applications-of-integrals.qmd
    - area-between-curves.qmd
    - volumes-of-solids-of-revolution.qmd
    - arc-length-and-surfaces-of-revolution.qmd
    - techniques-of-integration.qmd
    - integration-by-parts.qmd
    - trigonometric-integrals.qmd
    - trigonometric-substitution.qmd
    - partial-fractions.qmd
    - improper-integrals.qmd
    - infinite-series.qmd
    - sequences.qmd
    - infinite-series-and-convergence.qmd
    - integral-test-and-p-series.qmd
    - comparisons-of-series.qmd
    - alternating-series.qmd
    - ratio-and-root-tests.qmd
    - taylor-polynomials-and-approximations.qmd
    - power-series.qmd
    - taylor-and-maclaurin-series.qmd
    - references.qmd
  sidebar:
    title: "Exploring Calculus"
  site-url: https://directknowledge.com/exploring-calculus/
  description: "exploring-calculus"  


format:
  html:
    include-in-header: 
      - ../_html/head-ec.html
    include-before-body: 
      - ../_html/latex-macros.html
  pdf:
    keep-tex: true
    toc: false
    documentclass: book
    classoption: [10pt,reqno,twopage,openany]
    include-in-header: 
      - ../_control/packages-ec.tex
      - ../_control/commands.tex
    include-before-body:
      - ../_control/topmatter.tex
    include-after-body: 
      - ../_control/makeindex.tex

metadata-files:
  - ../_meta/book.yml
  - ../_meta/format.yml

