---
pagetitle: "Area Between Curves - Exploring Calculus"
---
# "Area Between Curves"

We explain, through several examples, how to find the area between curves (as a bounded region) using integration. We demonstrate both vertical and horizontal strips and provide several exercises.

When applying the definition for \index{the area between curves} **the area between curves** , finding the intersection points of the curves and sketching their graphs is crucial. 
These graphs often reveal whether we should use vertical or horizontal strips by determining which curve is the upper curve and which is the lower. 


## Area Between Curves Using Vertical Strips

::: {#def- } 
Let $f$ and $g$ be continuous functions on $[a,b],$ and suppose that ${f(x)\geq g(x)}$ for all $x$ in $[a,b].$
Then the area of the region between the graphs of $f$ and $g$ and the vertical lines $x=a$ and $x=b$ is 
\begin{equation}
\label{vs}
A=\int_a^b [f(x)-g(x)] \, dx.
\end{equation}
::: 

In particular, if $f(x)\geq g(x)=0,$ then \eqref{vs} yields 
the area of the region bounded by: the graph of $f,$ above the $x$-axis, and between the lines $x=a$ and $x=b$ as 
\begin{equation}
\label{funda}
A=\int_a^b f(x)\, dx.
\end{equation}
The reader is expected to be familiar with \eqref{funda} and also with the Fundamental Theorem of Calculus. 

::: {#exm- } 
Find the area of the region enclosed by the parabola $y=2-x^2$ and the line $y=-x.$
::: 

::: {.solution }
First we find the intersection points $(-1,1)$ and $(2,-2).$ 
Then we see that we have $f(x)=2-x^2 \geq g(x)=-x$ for all $x\in [-1,2]$ as required. 

Therefore the area between the curves is 
\begin{align*}
\int_a^b [f(x)-g(x)] \, dx
& =\int_{-1}^2[(2-x^2)-(-x)]\, dx \\
& = \int_{-1}^2 (2+x-x^2)\, dx
= \left[2x+\frac{x^2}{x}-\frac{x^3}{3}\right]_{-1}^2 \\
& =\left(4+\frac{4}{2}-\frac{8}{3}\right)-\left(-2+\frac{1}{2}+\frac{1}{3}\right)
=\frac{9}{2}
\end{align*}
as desired.
::: 

::: {#exm- } 
Find the area of the region in the first quadrant that is bounded above by $y=\sqrt{x}$ and below by the $x$-axis and the line $y=x-2.$
::: 

::: {.solution }
First we find the intersection point $(4,2).$ 
From a sketch of the graphs we see that we should consider the bounded region as two separate regions. 

We have $f(x)=\sqrt{x}\geq g(x)=0$ for all $x$ in $[0,2]$ and in the other region we have $f(x)=\sqrt{x}\geq g(x)=x-2$ for all $x$ in $[2,4].$ 
The total area is
\begin{align*}
& \int_0^2 \sqrt{x} \, dx +\int_2^4 (\sqrt{x}-x+2) \, dx \\
& \qquad =\left[\frac{2}{3}x^{2/3}\right]_0^2+\left[\frac{2}{3}x^{3/2}-\frac{x^2}{2}+2x\right]_2^4 \\ 
& \qquad =\left[\frac{2}{3}2^{2/3}\right]+\left[\frac{2}{3}4^{3/2}-\frac{4^2}{2}+2(4)\right] -\left[\frac{2}{3}2^{3/2}-\frac{2^2}{2}+2(2)\right]\\ 
& \qquad =\frac{10}{3}
\end{align*}
as desired.
::: 

::: {#exm- } 
Find the area of the shaded region between the curves $y=2x^2$ and $y=x^4-2x^2.$
::: 

::: {.solution }
First we find the intersection points $(0,0)$ and $(\pm 2, 8).$ 
From a sketch of the graph we see that we can use symmetry about the $y$-axis.
We have 
$$
{f(x)=2x^2\geq g(x)=x^4-2x^2}
$$ 
for all $x$ in $[0,2].$

The total area is
\begin{align*}
& 2 \int_{0}^2 [2x^2-(x^4-2x^2)]\, dx 
= 2 \int_{0}^2 (4 x^2 - x^4)\, dx \\
& \qquad = 2 \left(\left.\frac{4x^3}{3}-\frac{x^5}{5}\right|_0^2 \right)
= 2 \left(\frac{4(2)^3}{3}-\frac{(2)^5}{5} \right) 
= \frac{96}{5}
\end{align*}
as desired.
::: 

::: {#exm- } 
Find the area of the shaded region between the curves ${y=2x^3-x^2-5x}$ and $y=-x^2+3x.$
::: 

::: {.solution }
First we find the intersection points $(-2,-10),$ $(0,0),$ and $(2,2).$
From a sketch of the graphs wee see that we should break the bounded region into two regions. 

Notice that for all $x$ in $[-2,0]$ we have 
$$
f(x)= 2x^3-x^2-5x\geq g(x) = -x^2+3x
$$ 
and that for all $x$ in $[0,2]$ we have $f(x)= -x^2+3x\geq g(x) = 2x^3-x^2-5x.$
The total area is $16$ given by 
\begin{align*}
& \int_{-2}^0 [(2x^3-x^2-5x)-(-x^2+3x)] \, dx \\
& \qquad +
\int_0^2 [(-x^2+3x)-(2x^3-x^2-5x)]\, dx \\
& \qquad = 8+8 =16
\end{align*}
as desired.
::: 




## Area Between Curves Using Horizontal Strips

If a region's bounding curves are described by functions of $y,$ the approximating rectangles are horizontal instead of vertical and the basis formula has $y$ instead of $x.$ 

::: {#def- } 

Let $f$ and $g$ be continuous functions on $[c,d],$ and suppose that ${f(y)\geq g(y)}$ for all $y$ in $[c,d].$
Then the area of the region between the graphs of $f$ and $g$ and the horizontal lines $y=c$ and $y=d$ is 
\begin{equation}
A=\int_c^d [f(y)-g(y)] \, dy.
\end{equation}
::: 

In this equation $f$ always denotes the right-hand curve and $g$ the left-hand curve, so that $f(y)-g(y)$ is nonnegative. 

::: {#exm- } 
Find the area of the region in the first quadrant that is bounded above by $y=\sqrt{x}$ and below by the $x$-axis and the line $y=x-2.$
::: 

::: {.solution }
In this example we consider horizontal strips. 
Here we have 
$$
f(y)=y+2\geq g(y)=y^2
$$ 
for all $y$ in $[0,2]$ as is seen in the sketch of the region. 

The total area is
\begin{align*}
& \int_0^2 [y+2-y^2] \, dy 
= \left[2y+\frac{y^2}{2}-\frac{y^3}{3}\right]_0^2 
= 4+\frac{4}{2}-\frac{8}{3} 
= \frac{10}{3}
\end{align*}
as desired.
::: 

## Exercises

::: {#exr- } 
Find the areas of the regions enclosed by the lines and curves. 
 - $x=2y^2,$ $x=0,$ and $y=3$
- $y^2-4x=4,$ $4x-y=16$
- $y=\frac{x}{x^2+1},$ $y=-\frac{1}{2} x^2,$ $x=1$
- $x=y^3-y^2$ and $x=2y$
- $y=x\sqrt{4-x^2},$ $y=0$
- $y=\sqrt{x+3},$ $y=(x+3)/2$
- $x+y^2=3$ and $4x+y^2=0$
- $\sqrt{x}+\sqrt{y}=1,$ $x+y=1$
- $y=-x^3+x,$ $y=x^4-1$
- $y=\sin x,$ $y=x,$ $x=\pi/2,$ $x=\pi$
- $y=\cos x,$ $y=2-\cos x,$ $0\leq x \leq 2\pi$
- $x=1-y^2,$ $x=y^2-1$
 
::: 

::: {#exr- } 
Find the are of the region in the first quadrant bounded on the left by the $y$-axis and on the right by the curves $y=\sin x$ and $y=\cos x.$
::: 

::: {#exr- } 
Find the area of the region enclosed by the curve $y^2=x^2(1-x^2).$
::: 

::: {#exr- } 
Find the area, integrating with respect to $x$ and then $y,$ of the region between the curve $y=3-x^2$ and the line $y=-1.$ 
::: 

::: {#exr- } 
Use integration to find the area of the triangle with the given vertices $(-2,4),$ $(0,-2),$ and $(6,2).$
::: 

::: {#exr- } 
Find the area of the region in the first quadrant bounded on the left by the $y$-axis, below by the curve $x = 2\sqrt{y},$ above left by the curve $x = (y-1)^2,$  and above right by the line $x = 3- y.$
::: 

::: {#exr- } 
Find the area of the region bounded by the graph of the curve $y^2=x^3-x^2$ and the line $x=2.$
::: 

::: {#exr- } 
Find the value of $c$ such that the parabola $y =c x^2$ divides the region by the parabola $y=\frac{1}{9} x^2,$ and the lines $y=2,$ and $x=0$ into two subregions of equal area. 
::: 

::: {#exr- } 
Find the area of the region bounded by the parabola $y=x^2,$ the tangent line to this parabola at $(1,1)$ and the $x$-axis.
::: 

::: {#exr- } 
Find the values of $c$ such that at the area of the 
region bounded by the parabolas $ y=x^2 - c^2$ and $y= c^2 - x^2$ is 576. 
::: 

::: {#exr- } 
Find $a$  such that the line $x=a$ divides the region bounded by the graphs of the equations into two regions of equal area given $y=x,$ $y=4,$ and $x=0.$
::: 



