---
pagetitle: "Basic Rules of Differentiation - Exploring Calculus"
---
# "Basic Rules of Differentiation"

## Linearity

Computing the limit of the difference quotient can be tedious and require ingenuity; fortunately for a large number of common functions there is a better way to compute the derivative. In this section, we detail the \index{power rule}, \index{product rule} and the \index{quotient rule} **power rule}, \index{product rule} and the \index{quotient rule**  for differentiation. These rules greatly simplify the task of differentiation. We also give examples on how to find the tangent line give some geometric information; and to find the horizontal tangent lines to the graph of a given function.

The next theorem states the common procedural rules for taking derivatives. For example, the derivative of a sum of functions is the sum of the derivative functions. The same is not true for a product of functions. To convince yourself that the derivative of the product of two functions is not the product of the derivative functions try an example, say $f(x)=x^2$ and $g(x)=x^3.$

::: {#thm- } [Differentiation Rules]
Let $f$ and $g$ be functions. 
 
- (Constant Rule) 
If $f$ is a constant function, $f(x)=c$ for some real number $c,$ then $f'(x)=0.$
- (Power Rule) 
If $f$ is a power function, $f(x)=x^n$ for some real number $n$, then $f(x)=n x^{n-1}.$
- (Sum Rule) 
If $f=g+h$ for any differentiable functions $g$ and $h,$ then $f'=g'+h'.$
- (Difference Rule) 
If $f=g-h$ for any differentiable functions $g$ and $h,$ then $f'=g'-h'.$
- (Linearity Rule) 
If $f=a g+b h$ for any differentiable functions $g$ and $h$, and any two constants $a$ and $b$, then $f'=a g'+b h'.$
 
::: 


::: {#exm- } 
Find the derivative of the function $f(x)=\frac{4}{3}\pi  r^3.$
::: 

::: {.solution }
Since $\frac{4}{3}\pi  r^3$ is a constant with respect to $x$, we use the constant rule to find $f'(x)=0.$
::: 


::: {#exm- } 
Find the derivative of the function 
\[
f(x)=3x^4-7x^3+\sqrt[3]{x^2}-9.
\]
::: 

::: {.solution }
Using the power rule, linearity rule, and the sum rule, we find
\[
f'(x)=12x^3-12x^2+\frac{2}{3\sqrt[3]{x}}.
\square
\]
::: 


::: {#exm- } 
Find the derivative of the function 
\[
f(x)=\left(2x^3+3x\right)\left(x^2-3\right).
\]
::: 

::: {.solution }
Expand and use the linearity rule.
\square
::: 


::: {#exm- } 
Find the derivative of the function 
\[
f(x)=x\sqrt{x}+\frac{1}{x^2\sqrt{x}}.
\]
::: 

::: {.solution }
We can rewrite $f$ as $f(x)=x^{3/2}+x^{-5/2}$ so as to use the power rule to find,
\[
f'(x)=\frac{3}{2}x^{1/2}-\frac{5}{2}x^{-7/2}=\frac{3\sqrt{x}}{2}-\frac{5}{2\sqrt[2]{x^7}}.
\square
 \]
::: 

## Higher Order Derivatives


If $f$ is a differentiable function, then its derivative $f'$ is also a function, so $f'$ may have a derivative of its own, denoted by $(f')'=f''.$ 
This function $f''$ is called the \index{second derivative} **second derivative**  of $f.$  
Moreover, the second derivative may be differentiable. 
Further, the \index{third derivative} is defined as $(f'')'$ and is denoted by $f'''$; and the \index{fourth derivative} is defined as $(f''')'$ and is denoted by $f^{(4)} **third derivative} is defined as $(f'')'$ and is denoted by $f'''$; and the \index{fourth derivative} is defined as $(f''')'$ and is denoted by $f^{(4)** $, provided these functions exist. 
In general, if $f^{(n)}$ is differentiable, then $\left(f^{(n)}\right)'=f^{(n+1)}$ is the $(n+1)^{th}$ derivative of $f.$  
In Leibniz notation the first, second, third and $n$-th derivatives are
\begin{align*}
& y'=\frac{d y}{d x} \\
& y''=\frac{d }{d x}\left(\frac{d y}{d x}\right)=\frac{d^2y}{d x^2} \\
& y'''=\frac{d}{d x}\left(\frac{d^2y}{d x^2}\right)=\frac{d^3y}{d x^3} \\
& \cdots \\
&  y^{(n)}=\frac{d^ny}{d x^n}
\end{align*}
respectively.

::: {#exm- } 

Find the second order derivatives for the functions given above.
::: 

::: {#exm- } 

Find the first, second, and third derivatives of
\[
y=\left(-3x^2+x+82\right)(2x-12)\left(x^3\right).
\]
::: 

::: {.solution }
We could use the product rule but since we want higher order derivatives it will be quicker to expand first. We find,
\[
\left(-3x^2+x+82\right)(2x-12)\left(x^3\right)=-6 x^6+38 x^5+152 x^4-984 x^3
\]
Thus,
\begin{align*}
y' & =-36 x^5+190 x^4+608 x^3-2952 x^2 \\
y''& =-180 x^4+760 x^3+1824 x^2-5904 x \\
y''' & =-720 x^3+2280 x^2+3648 x-5904
\square
\end{align*}
::: 

## Exercises

::: {#exr- } 
Find the first derivative and the second derivative for each of the following.
 
\item $  y=x^2+x+8.$
\item $  y=\frac{4x^3}{3}-x+2 e^x.$
\item $  s=-2t^{-1}+\frac{4}{t^2}.$
\item $  r=\frac{1}{3s^2}-\frac{5}{2s}.$
\item $  r=2\left(\frac{1}{\sqrt{\theta }}+\sqrt{\theta }\right).$
 
::: 

::: {#exr- } 
Find the derivatives of all orders for each of the following.
 
\item $  y=\frac{x^4}{2}-\frac{3}{2}x^2-x.$
\item $  s=\frac{t^2+5t-1}{t^2}.$
\item $  w=3z^2e^z.$
 
::: 

::: {#exr- } 
(a) Find an equation for the line perpendicular to the tangent to the curve $y=x^3-4x+1$ at the point $(2,1).$ (b) What is the smallest slope on the curve? At what point on the curve does the curve have this slope? (c) Find equations for the tangents to the curve at the points where the slope of the curve is 8.
::: 

::: {#exr- } 
(a) Find equations for the horizontal tangents to the curve $y=x^3-3x-2.$ Also find equations for the lines that are perpendicular to these tangents at the points of tangency. (b) What is the smallest slope on the curve? At what point on the curve does the curve have this slope? Find an equation for the line that is perpendicular to the curve's tangent at this point.
::: 

::: {#exr- } 
The curve $y=a x^2+b x+c$ passes through the point $(1,2)$ and is tangent to the line $y=x$ at the origin. Find $a,$ $b,$ and $c.$
::: 

::: {#exr- } 
The curves $y=x^2+a x+b$ and $y=c x-x^2$ have a common tangent line at the point $(1,0).$ Find $a,$ $b,$ and $c.$
::: 

::: {#exr- } 
Show that the curve $y=6x^3+5x-3$ has no tangent lines with slope $4.$
::: 

::: {#exr- } 
At what points on the curve $y=x\sqrt{x}$ is the tangent line parallel to the line $3x-y+6=0.$
::: 

::: {#exr- } 
(a) Sketch the graph of the curve $y=\sin  x$ on the interval $-\frac{3\pi }{2}\leq x\leq 2\pi $ and their tangents at the $x$ values of $x=-\pi,$ $x=0,$ and $x=3\pi /2.$
(b) Sketch the graph of the curve $y=1+\cos  x$ on the interval $-\frac{3\pi }{2}\leq x\leq 2\pi $ and their tangents at the $x$ values of
$x=-\pi /3$ and $x=3\pi /2.$
::: 



