---
pagetitle: "Comparisons of Series - Exploring Calculus"
---
# "Comparisons of Series"


The Direct Comparison Test and the Limit Comparison Test are discussed. We work through several examples for each case and provide many exercises. Convergence tests for infinite series are only mastered through practice.


## Direct Comparison Test

The idea behind the comparison tests is to determine whether a series converges or diverges by comparing a given series to an already familiar series. 
For example, the series 
$$
\sum_{n=0}^\infty \frac{1}{e^n}
$$ 
is known to converge. 
Do you think the similar series
$$
\sum_{n=1}^\infty \frac{1}{e^n+1}
$$
also converges?
The idea is compare each term, so that the sequence of partial sums can be compared also. 
Notice that 
$$
\frac{1}{e^n+1} < \frac{1}{e^n}.
$$
This means that its partial sums must form a bounded increasing sequence, which as we know, is convergent. 



::: {#thm- } \label{Direct Comparison Test}
Suppose that $\sum a_n$ and $\sum b_n$ are series with positive terms. 
 - If $\sum b_n$ is convergent and $a_n\leq b_n$ for all $n$, then $\sum a_n$ is also convergent.
- If  $\sum b_n$ is divergent and $a_n \geq b_n$ for all $n$, then $a_n$ is also divergent. 
 
::: 

::: {.proof }
For the first part, the partial sums of $\sum a_n$ are bounded above by 
$$
M =a_1+a_2+\cdots +a_N +\sum_{n=N+1}^\infty c_n.
$$
Therefore, the partial sums form a nondecreasing sequence with a limit $L$ with $L\leq M$.
For the second part, the partial sums of $\sum a_n$ are not bounded from above.
Consider that if the partial sums of $\sum a_n$ are bounded above then the partial sums for $\sum b_n$ would be bounded by 
$$
M^* = b_1 +b_2 +\cdots b_N +\sum_{n=N+1}^\infty a_n
$$
and $\sum b_n$ would have to converge instead of diverge. 
::: 

::: {#exm- } 
Determine if the series $\sum_{n=2}^\infty \frac{1}{\sqrt{n}-1}$ is convergent or divergent.  
::: 

::: {.solution }
Let $a_n= \frac{1}{\sqrt{n} -1}$ and $b_n =\frac{1}{\sqrt{n}}$. 
Recall the series $\sum_{n=2}^\infty b_n$ is a divergent $p$-series. 
So by the Direct Comparison Test, with 
$$
a_n =\frac{1}{\sqrt{n} -1} > \frac{1}{\sqrt{n}} = b_n
$$
we see that the given series is divergent. 
::: 

::: {#exm- } 
Determine if the series $\sum_{n=1}^\infty \frac{5}{2n^2+4n+3}$ is convergent or divergent.  
::: 

::: {.solution }
Notice that for large $n$ the term $2n^2$ is dominate in the denominator. Observe that
$$
\frac{5}{2n^2+4n+3} < \frac{5}{2n^2}
$$
for all $n\geq 1$. 
Since we know that the series $\sum_{n=1}^\infty \frac{1}{n^2}$ is convergent, so is the series $\frac{5}{2}\sum_{n=1}^\infty \frac{1}{n^2}$.
Therefore the given series is convergent. 
::: 


## Limit Comparison Test

::: {#thm- } 
Suppose that $a_n>0$ and $b_n>0$ for all $n\geq N$.
 - If $\lim_{n\to \infty} \frac{a_n}{b_n} = c>0$, then $\sum a_n$ and $\sum b_n$ both converge of diverge. 
- If $\lim_{n\to \infty} \frac{a_n}{b_n} = 0$ and $\sum b_n$ converges, them $\sum a_n$ converges. 
- If $\lim_{n\to \infty} \frac{a_n}{b_n} = \infty$ and $\sum b_n$ diverges, then $\sum a_n$ diverges. 
 
::: 


::: {#exm- } 
Determine if the series $\sum_{n=1}^\infty \frac{1}{2\sqrt{n}+\sqrt[3]{n}}$ converges or diverges. 
::: 

::: {.solution }
By the Limit Comparison Test with
$$
\lim_{n\to\infty} \frac{\frac{1}{2\sqrt{n}+\sqrt[3]{n}}}{1/\sqrt{n}} = \lim_{n \to \infty} \frac{1}{2+n^{-1/6}} =\frac{1}{2},
$$
we see that the series diverges since the $p$-series $\sum_{n=1}^\infty \frac{1}{\sqrt{n}}$ diverges.
::: 

::: {#exm- } 
Determine if the series $\sum_{n=1}^\infty \frac{n+1}{n^2\sqrt{n}}$ converges or diverges. 
::: 

::: {.solution }
By the Limit Comparison Test with
$$
\lim_{n\to\infty} \frac{\frac{n+1}{n^2\sqrt{n}}}{\frac{1}{n^{3/2}}} = \lim_{n \to \infty} \frac{n+1}{n} = 1, 
$$
we see that the series converges since the $p$-series $\sum_{n=1}^\infty \frac{1}{n^{3/2}}$ converges.
::: 

::: {#exm- } 
Determine if the series $\sum_{n=2}^\infty \frac{1}{(\ln n)^2}$ converges or diverges. 
::: 

::: {.solution }
By the Limit Comparison Test with
$$
\lim_{n\to\infty} \frac{1/(\ln n)^2}{1/n} = \lim_{n \to \infty} \frac{n}{(\ln n)^2} = \lim_{n \to \infty} n =\infty, 
$$
we see that the series diverges since the $p$-series $\sum_{n=1}^\infty \frac{1}{n}$ diverges.
::: 


::: {#exm- } 
Determine if the series $\sum_{n=1}^\infty \frac{\ln n}{n^2}$ converges or diverges. 
::: 

::: {.solution }
Recall that the series $\sum_{n=1}^\infty \frac{1}{n}$ diverges but that the series $\sum_{n=1}^\infty \frac{1}{n^2}$ converges. 
However the Limit Comparison test with these two series, is inconclusive. 
Consider instead the series $\sum_{n=1}^\infty \frac{1}{n^{3/2}}$.
We find that 
$$
\lim_{n \to \infty} \frac{\ln n/n^2}{1/n^{3/2}} 
= \lim_{n \to \infty} \frac{\ln n}{\sqrt{n}} 
=0
$$
Therefore, by the Limit Comparison Test the given series converges. 
::: 



## Exercises

::: {#exr- } 
Determine whether the series converges or diverges. 
\begin{multicols}{3}
 - $\sum_{n=1}^\infty \frac{1}{n^2+2}$
- $\sum_{n=3}^\infty \frac{1}{n-2}$
- $\sum_{n=1}^\infty \frac{1}{3+2^n}$
- $\sum_{n=2}^\infty \frac{1}{n^{2/3}-1}$
- $\sum_{n=1}^\infty \frac{1+4^n}{1+3^n}$
- $\sum_{n=1}^\infty \frac{1}{3n^2+2}$
- $\sum_{n=1}^\infty \frac{n+4^n}{n+6^n}$
- $\sum_{n=1}^\infty \frac{1}{\sqrt{n}-1}$
- $\sum_{n=1}^\infty \frac{1}{4\sqrt[3]{n}-1}$
- $\sum_{n=3}^\infty \frac{3^n}{2^n-4}$
- $\sum_{n=1}^\infty \frac{2+\sin n}{3^n}$
- $\sum_{n=1}^\infty e^{-n^2}$
 
\end{multicols}
::: 


::: {#exr- } 
Determine whether the series converges or diverges. 
\begin{multicols}{3}
 - $\sum_{n=1}^\infty \frac{\sin^2 n}{2^n}$
- $\sum_{n=1}^\infty \frac{1+\cos n}{n^2}$
- $\sum_{n=1}^\infty \frac{1}{n!}$
- $\sum_{n=1}^\infty \frac{2n}{3n-1}$
- $\sum_{n=1}^\infty \frac{1}{\sqrt{n}+1}$
- $\sum_{n=1}^\infty \frac{n^2}{n!}$
- $\sum_{n=1}^\infty \frac{2n^2+n}{\sqrt{4n^7}+3}$
- $\sum_{n=1}^\infty \frac{(\ln n)^2}{n^{3/2}}$
- $\sum_{n=1}^\infty \frac{1}{(1+\ln n)^2}$
- $\sum_{n=1}^\infty \frac{\sqrt{n}+\ln n}{n^2+1}$
- $\sum_{n=1}^\infty \frac{\sqrt[n]{n}}{n^2}$
- $\sum_{n=1}^\infty \frac{1}{n\sqrt[n]{n}}$
 
\end{multicols}
::: 

::: {#exr- } 
Show that if $a_n > 0$  and $\lim_{n\to \infty} n a_n \neq 0$, then $\sum a_n$ is divergent. 
::: 

::: {#exr- } 
If $\sum_{n=1}^\infty a_n$ is a convergent series of nonnegative numbers, can anything be said about $\sum_{n=1}^\infty (a_n/n)$? Justify your conclusion. 
::: 

::: {#exr- } 
Show that if $\sum a_n$ is a convergent series of nonnegative terms, then $\sum a_n^2$ converges. 
::: 

::: {#exr- } 
Show that if $a_n > 0$ and $\sum a_n$ is convergent, then$\sum \ln(1+a_n)$ is convergent. 
::: 


