---
pagetitle: "Continuous Functions - Exploring Calculus"
---
# Continuous Functions

## Continuity at a Point


::: {#def- } 
A function is \index{continuous} **continuous**  at a point $c$ means 
 
- $f(c)$ is defined,
- $\lim _{x\to c}f(x)$ exists, and 
- $\lim _{x\to c}f(x)=f(c).$
::: 

## Discontinuity


::: {#exm- } 
Find three examples of how a \index{discontinuity} **discontinuity**  might arise.
::: 

::: {.solution }   
 First, the function 
 $$
  \displaystyle f(x)=\frac{x^2-2x+1}{x-1}
 $$ 
 is discontinuous at $x=1$ because $f(1)$ is not defined. 
 So one type of discontinuity is a \index{hole} **hole**  in the function. 
  
 Secondly, the function 
$$
f(x)=
\begin{cases}
x^2+1 & x\geq 0 \\ -x^2-2 & x<0
\end{cases}
$$
is discontinuous at $x=0$ because $\lim _{x\to 0^-}f(x)=-2$ and $\lim _{x\to 0^+}f(x)=1;$ thus $\lim _{x\to 0}f(x)$ does not exist and so $f$ has a discontinuity at $x=0.$ 
This type of discontinuity is called a \index{jump} **jump**. 
 
Thirdly, the function
$$
f(x)=\frac{x-1}{x-2}
$$ 
is discontinuous at $x=2$ because $f(2)$ is not defined and this type of discontinuity is called a \index{pole} **pole**  because $f(x)\to+\infty $ as $x\to 2^+$. 
::: 

## Continuous Functions


::: {#thm- } 
If $f$ and $g$ are functions that are continuous at $x=c$ then $f\pm g,$ $f g,$ $f/g,$and $f\circ g$ are continuous at $x=c,$ provided that $c$ is in the domain of the function. 
::: 

::: {#exm- }  
Give some examples of continuous functions.
::: 

::: {.solution }   
For example, the functions $2x^2-2x+5,$ (polynomial), $\displaystyle\frac{x-1}{x}$ (rational), $\csc  x$ (trigonometric), and $\sec ^{-1}x$ (inverse trigonometric) are continuous on their domains. 
Also the functions 
$$
 \displaystyle 2x^2-2x+5+\frac{x-1}{x}(\csc  x),
$$ 
$\displaystyle\sec ^{-1}\left(\frac{x-1}{x}\right),$ and $\displaystyle\left(2x^2-2x+5\right)\left(\frac{x-1}{x}\right)$ are continuous functions on their domains. 
::: 


::: {#thm- } 
If $f$ is a 
 
- polynomial function, 
- rational function, 
- trigonometric function, or 
- inverse trigonometric function, 
 
then $f$ is continuous where it is defined.
::: 


::: {#thm- } [Composition Limit Theorem]
If $\lim _{x\to c}g(x)=L$ and $f$ is a continuous function at $L,$ then 
$$
\lim _{x\to c}(f\circ g)(x)=f(L).
$$
::: 


::: {#exm- } 
Use the \index{composition} **composition**  limit theorem to evaluate the following limits. 
$$
\lim _{x\to 3} \left(x^2+3\right)^2
\quad\text{and}\quad
\lim _{x\to \pi /4} \sin ^4 x.
$$
::: 


::: {.solution }   
By the composition limit theorem, we have 
$$
\lim _{x\to 3}\left(x^2+3\right)^2 
=\left(\lim _{x\to 3}\left(x^2+3\right)\right)^2
=12^2
=144.
$$
By the composition limit theorem, we have  
$$
\lim _{x\to \pi /4}\sin ^4x
=\left(\lim _{x\to \pi /4}\sin  x\right){}^4
=\left(\frac{\sqrt{2}}{2}\right)^4
=\left(\frac{1}{4}\right).
 $$
::: 

## One-Sided Continuity


::: {#def- } 
The function $f$ is \index{continuous from the right} **continuous from the right**  at $c$ if and only if 
$$
\lim _{x\to c^+}f(x)=f(c)
$$ 
and it is \index{continuous from the left} **continuous from the left**  at $c$ if and only if 
$$
\lim _{x\to c^-}f(x)=f(c).
$$
::: 


::: {#exm- }  
Give an example of a function that is continuous from the right (or \index{right continuous} **right continuous** ) at $x=0.$
::: 

::: {.solution }   
The function $f(x)=\sqrt{x}$ is continuous from the right at $x=0$ because $\lim _{x\to 0^+}\sqrt{x}=0.$ 
::: 

## Determining Parameters for Continuity


::: {#exm- } 
Find constants $a$ and $b$ so that 
$$
\begin{cases}
a x^2+b & x>2 \\ 4 & x=2 \\ x^2-a x+b & x<2
\end{cases}
$$
is continuous on $\mathbb{R}$.
::: 

::: {.solution }   
Since $f$ is defined on $\mathbb{R},$ and $f$ is continuous for all $x\neq 2$ for any $a$ and $b$ that we choose, itis left to find an $a$ and $b$ such that  $\lim _{x\to 2^+}a x^2+b=4$ and $\lim _{x\to 2^-}\left(x^2-a x+b\right)=4.$
Thus we have the system $4 a+b=4$ and $4-2 a+b=4.$ 
Solving this system we have, $a=2/3$ and $b=4/3.$ 
 ::: 


::: {#exm- } 
Find constants $a$ and $b$ such that $f$ is continuous at $x=1$ where 
$$
\begin{cases}
a x+b & x>1 \\ 3 & x=1 \\ x^2-4x+b+3 & x<1
\end{cases}
$$
::: 

::: {.solution }   
To have continuity at $x=1$ we must have $\lim _{x\to 1^-}f(x)=3$ and $\lim _{x\to 1^+}f(x)=3,$ thus $a (1)+b=3$ and $(1)^2-4(1)+b+3=3.$ 
Therefore, $a+b=3$ and $b=3.$ 
So $a+3=3$ and $a=0.$ 
::: 

## Removable Continuity


::: {#exm- } 
Determine the value for which $f(2)$ should be assigned, if any, to have 
$$
 \displaystyle f(x)=\sqrt{\frac{x^2-4}{x-2}}
$$ 
continuous at $x=2.$
::: 

::: {.solution }   
Since $\lim _{x\to 2^-}f(x)=2$ and $\lim _{x\to 2^+}f(x)=2$ we have $\lim _{x\to 2}f(x)=2.$ 
Therefore, if we define $f(2)=2$ the function $f$ will be continuous at $x=2.$ 
::: 

## Intermediate Value Theorem


::: {#thm- } [Intermediate Value Theorem]
If $f$ is a continuous function on the closed interval $[a,b]$ and $L$ is some number strictly between$f(a)$ and $f(b)$, then there exists at least one number $c$ on the open interval $(a,b)$ such that $f(c)=L.$
::: 


::: {#exm- } 
The population (in thousands) of a colony of bacteria $t$ minutes after the application of a toxin is given by the function 
$$
P(t)=
\begin{cases}
t^2+1 & \text{if } 0\leq t<5 \\ -8t+66 & \text{if } t\geq 5
\end{cases}
$$
\ 
- When does the colony die out?
- Show that at some time between $t=2$ and $t=7,$ the population is $9,000.$
::: 

::: {.solution }   
Since 
$$
\lim _{t\to 5^+}P(t)=\lim _{t\to 5^+}(-8t+66)=26
$$ 
and 
$$
\lim _{t\to 5^-}P(t)=\lim _{t\to 5^-}\left(t^2+1\right)=26$$  we know that $P$ is continuous at $t=5$ and thus, also for all $t\geq 0.$ 
(a) The colony dies out when $-8t+66=0$ which means $t=33/4\approx 8.25.$ 
Therefore, the colony dies out in 8 minutes and 15 seconds. 
 
(b) Since $P(2)=5,$ $P(7)=10,$ and $P$ is continuous on $(2,7),$ the intermediate value theorem yields at least one number $c$ between 2 and 7 such $P(c)=9.$ 
Therefore, there is some time $t=c$ between $t=2$ and $t=7$ such that the population is 9,000. 
::: 


## Exercises

::: {#exr- } 
Sketch the graph of the function 
$$ 
f(x)=
\begin{cases}
x^2-1 & -1\leq  x<0 \\ 2x & 0<x<1 \\ 1 & x=1 \\ -2x+4 & 1<x<2 \\ 0 & 2<x<3.
\end{cases} 
$$
Use the graph of the function $f$  to answer the following.
\ 
- Does $f(-1)$  exist?
- Does the limit, $\lim _{x\to -1^+}f(x)$  exist?
- Does the limit, $\lim _{x\to -1^+}f(x)=f(-1)$?
- Does $f(1)$  exist?
- Does the limit, $\lim _{x\to 1}f(x)$  exist?
- Does the limit, $\lim _{x\to 1}f(x)=f(1)$  exist?
- Is $f$  defined at $x=2?$ 
- Is $f$  continuous at $x=2?$ 
- At what values is $f$  continuous?
- What value should be assigned to $f(2)$ , to make the extended function continuous at $x=2?$ 
- To what new value should $f(1)$  be assigned to remove the discontinuity?
::: 

::: {#exr- } 
For each of the following functions determine the largest set on which the function will be continuous. 
 
- $g(x)=\frac{x+1}{x^2-4x+3}$ 
- $g(x)=\frac{1}{|x|+1}-\frac{x^2}{2}$ 
- $g(x)=\frac{\sqrt{x^4+1}}{1+\sin ^2x}$ 
- $g(x)=\sqrt[4]{3x-1}$ 
::: 

::: {#exr- } 
For each of the following functions find constants $a$  and $b$  so that the function will be continuous for all $x$  in the domain.
 
- $f(x)=\begin{cases} \frac{\tan  a x}{\tan  b x} & x<0 \\ 4 & x=0 \\ a x+b & x>0 \end{cases}$ 
- $f(x)=\begin{cases}\frac{\sqrt{a x+b}-1}{x} & x\neq 0 \\ 1 & x=0\end{cases}$  
- $f(x)=\begin{cases}a x+3 & x<1 \\ 5 & x=1 \\ x^2+b & x>1\end{cases}$ 
::: 

::: {#exr- } 
Let $u(x)=x$  and 
$f(x)=\begin{cases}0 & x\neq 0 \\ 1 & x=0\end{cases}$. 
Show, for this given $u$  and $f$ , that 
$$
\lim _{x\to 0}f[u(x)]\neq f\left(\lim _{x\to 0}u(x)\right).
$$
::: 

::: {#exr- } 
If a function $f$  is not continuous at $x=c$ , but can be made continuous at $x=c$  by being assigned a new value of that point, it is said to have a \emph{removable discontinuity} at $x=c.$  Which of the following functions have a removable discontinuity at $x=c$ ?
 
- $f(x)=\frac{2x^2+x-15}{x+3}$  at $c=-3$ 
- $f(x)=\frac{x-2}{|x-2|}$  at $c=2$ 
- $f(x)=\frac{2-\sqrt{x}}{4-x}$  at $c=4$ 
- $f(x)=\frac{2-x}{4-\sqrt{x}}$  at $c=16$ 
::: 

::: {#exr- } 
Prove that the function $f(x)=x^3-x^2+x+1$  must have at least one real root. 
::: 

::: {#exr- } 
Prove that the function $(x)=\sqrt{x+3}-e^x$  must have at least one real root. 
::: 

::: {#exr- } 
Find a function(s) with the following properties. (a) Find functions $f$  and $g$  such that $f$  is discontinuous at $x=1$  but $f g$  is continuous there. (b) Give an example of a function defined for all real numbers that is continuous at only one point. 
::: 




