---
pagetitle: "Curve Sketching - Exploring Calculus"
---
# "Curve Sketching"


## Curve Sketching as a Procedure


The following steps can be used to graph many commonly used functions.

    
\setlength\itemsep{2.1ex} 
- If given a function, determine the domain and range.
- If possible algebraically simplify the function.
\item Test for symmetry with respect to the $x$-axis, $y$-axis, and the origin.
- Determine any $x$-intercepts and $y$-intercepts.
- Determine any vertical asymptotes.
- Determine any horizontal asymptotes.
- Determine the first order critical numbers.
- Apply the First Derivative Test. 
- Apply the Second Derivative Test. 
- Determine the second order critical numbers.
- Apply the Concavity Test. 
- Determine any vertical tangents.
- Determine any cusps.
- Plot Points.
- Sketch the curve.
 

## Vertical Tangents and Cusps

There are four possibilities for unbounded behavior of a derivative $f'(x)$ around a given real number $c.$ 

::: {#def- } 

Suppose the function $f$ is continuous at the point $P(c,f(c)).$ 
   
- The graph of $f$ has a \index{vertical tangent} **vertical tangent**  at $P$ if one of the following holds.  
    
- $\lim _{x\to c^+}f'(x)=\lim _{x\to c^-}f'(x)=+\infty $ 
\item $ \lim _{x\to c^+}f'(x)=\lim _{x\to c^-}f'(x)=-\infty $
 
- The graph of $f$ has a \index{cusp} **cusp**  at $P$ if one of the following holds.  
\vspace{.3cm}
    
- $\lim _{x\to c^+}f'(x)=+\infty$ and $\lim _{x\to c^-}f'(x)=-\infty $
- $\lim _{x\to c^+}f'(x)=-\infty $ and $\lim _{x\to c^-}f'(x)=+\infty $
 
 
::: 


::: {#exm- }  
Sketch the graph of 
\[
f(x)=3x^{3/5}\left(5-x-4x^2\right)
\] 
and explain why there is a vertical tangent at $x=0$.
:::  


::: {.solution } 
Using the product rule the derivative of the function $f$ is
\begin{align*}
f'(x) & =\frac{9}{5}x^{-2/5}\left(5-x-4x^2\right)+3x^{3/5}(-1-8x) \\
& =\frac{9\left(5-x-4x^2\right)}{5x^{2/5}}+\frac{\left(5x^{2/5}\right)\left(3x^{3/5}\right)(-1-8x)}{5x^{2/5}} \\
& =\frac{9\left(5-x-4x^2\right)}{5x^{2/5}}+\frac{15x(-1-8x)}{5x^{2/5}} \\
& =\frac{45-24 x-156 x^2}{5 x^{2/5}}. 
\end{align*}
To determine any vertical tangents we consider where $f'(x)$ is undefined. Notice that at $x=0$ the derivative is undefined but $f(0)=0.$ Thus, the point $(0,0)$ is a candidate for a being a vertical tangent to the graph of $f.$ We check the following limits to determine if $(0,0)$ is a vertical tangent. Since 
$45-24 x-156 x^2\to 45$ and $5 x^{2/5}\to -\infty $ as $x\to 0^-,$
\[\lim _{x\to 0^-}\frac{45-24 x-156 x^2}{5 x^{2/5}}=+\infty .\]
Since $45-24 x-156 x^2\to 45$ and $5 x^{2/5}\to -\infty $ as $x\to 0^-,$ 
\[\lim _{x\to 0^+}\frac{45-24 x-156 x^2}{5 x^{2/5}}=+\infty .\]
Therefore the function $f$ has a vertical tangent at  $(0,0)$ which can be seen from the sketch of the graph of $f.$ 
(see Figure ~\ref{fig:graph17}). 
::: 


::: {#exm- }  
Sketch the graph of $f(x)=x^{2/3}\left(x^2+5x-20\right)$ and explain why there is a cusp at $x=0$.
::: 

::: {.solution } 
Using the product rule we find the derivative as 
\begin{align*}
 f'(x) & =\frac{2}{3}x^{-1/3}\left(x^2+5x-20\right)+x^{2/3}(2x+5)  \\
& =\frac{2\left(x^2+5x-20\right)}{3x^{1/3}}+\frac{3x^{1/3}x^{2/3}(2x+5)}{3x^{1/3}} \\
& =\frac{2x^2+10x-40}{3x^{1/3}}+\frac{3x(2x+5)}{3x^{1/3}} \\
& =\frac{2x^2+10x-40}{3x^{1/3}}+\frac{6x^2+15x}{3x^{1/3}} \\
& =\frac{8 x^2+25 x-40}{3 \sqrt[3]{x}}.
\end{align*}
To determine any cusps we consider where $f'(x)$ is undefined. Notice that at $x=0$ the derivative is undefined but $f(0)=0.$ Thus the point $(0,0)$ is a candidate for a being a cusp for the graph of the function $f$. We check the following limits to determine if $(0,0)$ is a cusp. Since $8x^2+25x-40\to -40$ and $3 \sqrt[3]{x}\to -\infty $ as $x\to 0^-,$  
\[\lim _{x\to 0^-}\frac{8 x^2+25 x-40}{3 \sqrt[3]{x}}=+\infty .\]
Since $8x^2+25x-40\to -40$ and $3 \sqrt[3]{x}\to +\infty $ as $x\to 0^+,$ 
\[\lim _{x\to 0^+}\frac{8 x^2+25 x-40}{3 \sqrt[3]{x}}=-\infty .\]
Therefore the function $f$ has a cusp at $(0,0)$ which can be seen from the sketch of the graph of $f.$ 
(see Figure ~\ref{fig:graph18}). 
::: 



::: {#exm- }  
Determine any vertical tangents and cusps for the function 
\[
f(x)=x^{2/3} (x - 1)^{1/3}.
\]
::: 


::: {.solution } 
To find the vertical tangents and cusps we check where the first derivative is undefined. The derivative of $f$ is 
\[f'(x)=\frac{x^{2/3}}{3 (x-1)^{2/3}}+\frac{2 \sqrt[3]{x-1}}{3 \sqrt[3]{x}}=\frac{3 x-2}{3 (x-1)^{2/3} \sqrt[3]{x}}.\]
Therefore the points $(0,0)$ and $(1,0)$ are candidates for where a vertical tangent and cusp might occur. The function $f$ has a vertical asymptote at $x=1$ since 
\[
\lim_{x\to 1^-}f'(x)=\lim_{x\to 1^-} \frac{3 x-2}{3 (x-1)^{2/3} \sqrt[3]{x}} = +\infty   
%\lim_{x\to 1^+}f'(x)=\lim_{x\to 1^+} \frac{3 x-2}{3 (x-1)^{2/3} \sqrt[3]{x}} = +\infty  
\]
The function $f$ has a cusp at $x=0$ since 
\[\lim_{x\to 0^-}f'(x)=\lim_{x\to 0^-} \frac{3 x-2}{3 (x-1)^{2/3} \sqrt[3]{x}} = +\infty  
% \lim_{x\to 0^+}f'(x)=\lim_{x\to 0^+} \frac{3 x-2}{3 (x-1)^{2/3} \sqrt[3]{x}} = -\infty .
\]
(see Figure ~\ref{fig:graph19}). 
::: 

::: {#exm- }  
Sketch the graph of the rational function
\[
f(x)=\frac{2x^2}{x^2-1}
\]
showing all special features.
::: 


::: {.solution } 
The domain of $f$ is 
\[
\left\{x\left|x^2-1\neq 0\right.\right\}
=\{x|\neq \pm 1\}
=(-\infty ,-1)\cup (-1,1)\cup (1,+\infty ).
\]
The $x$ and $y$ intercepts are both $0.$ Since $f(-x)=f(x)$ the function is even and so the curve is symmetric about the $y$-axis. Since
\[
\lim _{x\to \pm \infty}\frac{2x^2}{x^2-1}
=\lim _{x\to \pm \infty}\frac{2}{1-\frac{1}{x^2}}=2
\]
the line $y=2$ is a horizontal asymptote. Since the denominator is 0 when $x\pm 1,$ we compute the following limits: 
\[
\begin{array}{cc}
 \displaystyle 
\lim _{x\to 1^+}\frac{2x^2}{x^2-1}
=+\infty  &  \displaystyle \lim _{x\to 1^-}\frac{2x^2}{x^2-1}
=-\infty  \\[10pt]
 \displaystyle 
\lim _{x\to -1^+}\frac{2x^2}{x^2-1}
=-\infty  &  \displaystyle \lim _{x\to -1^-}\frac{2x^2}{x^2-1}
=+\infty 
\end{array}
\]
Therefore, the lines $x=1$ and $x=-1$ are vertical asymptotes.
Next we find the derivative function.
\[ f'(x)=\frac{4x\left(x^2-1\right)-2x^2(2x)}{\left(x^2-1\right)^2}=\frac{-4x}{\left(x^2-1\right)^2}.\]
Since $f'(x)>0$ when $x<0$ $(x\neq -1)$ and $f'(x)<0$ when $x>0$ $(x\neq 1),$ $f$ is increasing on $(-\infty ,-1)$ and $(-1,0)$ and decreasing on $(0,1)$ and $(1,+\infty ).$ The only critical number is $x=0.$ Since $f'$ changes sign from positive to negative at $0,$
$f(0)=0$ is a local maximum by the First Derivative Test. 
Also, 
\[f''(x)=\frac{-4\left(x^2-1\right)^2+4x(2)\left(x^2-1\right)(2x)}{\left(x^2-1\right)^4}=\frac{12x^2+4}{\left(x^2-1\right)^3}\]
Since $12x^2+4>0$ for all $x,$ we have
$f''(x)>0 \Longleftrightarrow x^2-1>0 \Longleftrightarrow |x|>1$
and 
$f''(x)<0 \Longleftrightarrow  |x|<1.$
Thus the curve is concave downward on the intervals $(-\infty ,-1)$ and $(1,+\infty )$ and concave downward on $(-1,1).$ There is no point of inflection since $1$ and $-1$ are not in the domain of $f.$ 
(see Figure ~\ref{fig:graph20}). 
::: 

::: {#exm- }  
Sketch the graph of the trigonometric function 
\[
f(x)=2 \cos  x+\sin  2 x
\]
showing all special features.
::: 

::: {.solution } 
The domain of the function $f$ is $\mathbb{R}.$ The $y$-intercept is $(0,2)$ since $f(0)=2.$ The $x$-intercepts occur when $2 \cos  x+\sin  2x=2 \cos  x+2 \sin  x \cos  x=2 \cos  x(1+\sin  x)=0$ which is precisely when $x=\pi /2$ and $x=3\pi /2$, because we need only consider $[0,2\pi ]$ since function is periodic via, 
\[f(x+2\pi )=2 \cos  (x+2\pi )+\sin  [2(x+2\pi )]=2\cos  x+\sin  2x=f(x).\]
There are no vertical asymptotes nor horizontal asymptotes. 
The first derivative of $f$ is,
\begin{align*}
f'(x)& =-2 \sin  x+2 \cos  2x =-2(2 \sin x-1)(\sin x+1).
\end{align*}
Thus, $f'(x)=0$ when $\sin  x=1/2$ or when $\sin  x=-1,$ so in $[0,2\pi ]$ we only consider the critical numbers $x=\pi /6$, $x=5\pi /6,$ and $x=3\pi /2.$ Applying the First Derivative Test we find: 
\[
\begin{array}{c|c|c|l}
 \text{Interval} & f & f' & \text{Conclusion} \\ \hline
 0<x<\pi /6 &   & + & \text{increasing} \\
 x=\pi /6 & 3\left.\sqrt{3}\right/2 & 0 & \text{relative maximum}  \\
 \pi /6<x<5\pi /6 &   & - & \text{decreasing} \\
 x=5\pi /6 & -3\left.\sqrt{3}\right/2 & 0 & \text{relative minimum} \\
 5\pi /6<x<3\pi /2 &   & + & \text{increasing} \\
 x=3\pi /2 & 0 & 0 & \text{horizontal tangent} \\
 3\pi /2<x<2\pi  &   & + & \text{increasing}
\end{array}
\]
The second derivative of $f$ is,
\[ f''(x)=-2\cos  x-4 \sin  2x=-2 \cos  x (1+4 \sin  x)\]
so the second order critical numbers are $x=\pi /2,3\pi /2, \alpha _1,$ and $\alpha _2$ where $\sin  \alpha _1=-\frac{1}{4}$ and $\sin
 \alpha _2=-\frac{1}{4}.$ Applying the Concavity Test we find, 
\[
\begin{array}{c|c|c|l}
 \text{Interval} & f & f'' & \text{Conclusion} \\ \hline
 0<x<\pi /2 &   & - & \text{concave down} \\
 x=\pi /2 & 0 & 0 & \text{inflection point} \\
 \pi /2<x<\alpha _1 &   & + & \text{concave up} \\
 x=\alpha _1 & f\left(\alpha _1\right) & 0 & \text{inflection point} \\
 \alpha _1<x<3\pi /2 &   & - & \text{concave down} \\
 x=3\pi /2 & 0 & 0 & \text{inflection point} \\
 3\pi /2<x<\alpha _2 &   & + & \text{concave up} \\
 x=\alpha _2 & f\left(\alpha _2\right) & 0 & \text{inflection point} \\
 \alpha _2<x<2\pi  &   & - & \text{concave down}
\end{array}
\]
::: 


## Exercises

::: {#exr- } 
Evaluate the following limits.
    
- $\lim _{x\to 0^-}\frac{5}{2x}$  
- $\lim _{x\to -8^+}\frac{2x}{x+8}$  
- $\lim _{x\to 0}\frac{-1}{x^2(x+1)}$  
- $\lim _{x\to 0}\frac{-1}{x^2(x-1)}$  
- $\lim _{x\to 0^+}\frac{2}{x^{1/5}}$  
- $\lim _{x\to \frac{\pi}{2}^-}\tan  x$  
 
::: 

::: {#exr- } 
Find the limits for the following functions.
\ 
- $f(x)=\frac{1}{x^2-4}$  as $x\to 2^+,$  $x\to 2^-,$  $x\to -2^+,$  and $x\to -2^-.$  
- $f(x)=\frac{x^2-1}{2x+4}$  as $x\to -2^+,$  $x\to -2^-,$  $x\to 1^+,$  and $x\to 0^-.$  
- $f(t)=2-\frac{3}{t^{1/3}}$  as $t\to 0^+,$  and $t\to 0^-.$  
- $f(x)=\left(\frac{1}{x^{1/3}}-\frac{1}{(x-1)^{4/3}}\right)$  as $x\to 0^+,$  $x\to 0^-,$  $x\to 1^+,$  and $x\to 1^-.$  
 
::: 

::: {#exr- } 
Graph the following rational functions and include the graphs and equations of their asymptotes.
 
- $f(x)=\frac{-3}{x-3}$ 
- $f(x)=\frac{x^2}{x-1}$ 
- $f(x)=\frac{x^2-1}{2x+4}$  
- $f(x)=\frac{x^3-x^2+x-1}{(2x+3)(2x-1)}$  
 
::: 

::: {#exr- } 
For each of the following sketch the graph of a function $y=f(x)$  that satisfies the conditions.
\ 
- $f(0)=0,$  $f(1)=2,$  $f(-1)=-2,$  $\lim _{x\to -\infty }f(x)=-1,$  and $\lim _{x\to \infty }f(x)=1$ 
- $f(2)=1,$  $f(-1)=0,$  $\lim _{x\to \infty }f(x)=0,$  $\lim _{x\to0^+}f(x)=\infty ,$  $\lim _{x\to 0^-}f(x)=-\infty ,$  and $\lim _{x\to -\infty }f(x)=1$  
- $\lim _{x\to \pm \infty }g(x)=0,$  $\lim _{x\to 3^-}g(x)=-\infty,$  and $\lim _{x\to 3^+}g(x)=+\infty $   
 
::: 

::: {#exr- } 
Sketch the graph of the function 
\[
f(x)=
\left\{
\begin{array}{cc} 
-(x+1)^2+1 & -1\leq x\leq 0 \\ 
x^2 & 0<x<1 \\ 1 & 1<x<2 \\ 
2 & x=2 \\ 1 & 2<x\leq  3
\end{array}
\right.
\]
and then use the graph to determine which the following statements about the function $y=f(x)$  are true and which are false? 
 
- $\lim _{x \to -1^+}f(x)=1$ 
- $\lim _{x\to  2}f(x)$  does not exist
- $\lim _{x\to 2}f(x)=2$ 
- $\lim _{x\to 1^-}f(x)=2$ 
- $\lim _{x\to 1^+}f(x)=1$ 
- $\lim _{x\to 1}f(x)$  does not exist
- $\lim _{x\to 0^+}f(x)=\lim _{x\to 0^-}f(x)$ 
- $\lim _{x\to c}f(x)$  exists at every $c$  in the open interval $(-1,1)$ 
- $\lim _{x\to c}f(x)$  exists at every $c$  in the open interval $(1,3)$ 
- $\lim _{x\to -1^-}f(x)=0$ 
- $\lim _{x\to 3^+}f(x)$  does not exist
 
::: 

::: {#exr- } 
Sketch the graph of the function 
$$
f(x)=\left\{
\begin{array}{cc} 3-x & x<2 \\ 2 & x=2 \\ \frac{x}{2} & x>2\end{array}\right.
$$ 
and then use the graph to determine the following?
\ 
- $\text{Find} \lim _{x\to 2^+}f(x),$  $\lim _{x\to 2^-}f(x),$  and $f(2).$ 
- Does $\lim _{x\to 2}f(x)$  exist? If so, what is it? If not, why not?
- Find $\lim _{x\to -1^-}f(x)$  and $\lim _{x\to -1^+}f(x).$ 
- Does $\lim _{x\to -1}f(x)$  exist? If so, what is it? If not, why not? 
 
::: 

::: {#exr- } 
Let $g(x)=\sqrt{x}\sin \left(\frac{1}{x}\right).$  Use the graph of $g$  to determine the following.
\ 
- Does $\lim _{x\to 0^+}g(x)$  exist? If so, what is it? If not, why not?
- Does $\lim _{x\to 0^-}g(x)$  exist? If so, what is it? If not, why not?
- Does $\lim _{x\to 0}g(x)$  exist? If so, what is it? If not, why not?
 
::: 

::: {#exr- } 
Sketch the graph of the function 
$$
f(x)=\left\{\begin{array}{cc} x^3 & x\neq 1 \\ 0 & x=1\end{array}\right..
$$  
Find $\lim _{x\to 1^-}f(x)$  and $\lim _{x\to 1^+}f(x).$  Does $\lim _{x\to 1}f(x)$  exist? If so, what is it? If not, why not? 
::: 

::: {#exr- } 
Sketch the graph of the function 
$$
f(x)=\left\{\begin{array}{cc} 
1-x^2 & x\neq 1 \\ 
2 & x=1\end{array}
\right..
$$  
Find $\lim _{x\to 1^-}f(x)$  and $\lim _{x\to 1^+}f(x).$  Does $\lim _{x\to 1}f(x)$  exist? If so, what is it? If not, why not? 
::: 

::: {#exr- } 
Sketch the graph of the function  
\[
f(x)=\left\{
\begin{array}{ll} x & -1\leq x<0 \quad \text{or} \quad 0<x\leq 1 \\ 1 & x=0 \\ 0 & x<-1 \quad \text{or} \quad x>1.\end{array}\right.\] 
\ 
- What is the domain and range of $f?$ 
- At what points $c,$  if any does $\lim _{x\to c}f(x)$  exist?
- At what points does only the left-hand limit exist?
- At what points does only the right-hand limit exist?
 
::: 

::: {#exr- } 
Find the following one-sided limits algebraically.
 
- $\lim _{x\to 2^+} \frac{x(2x+5)}{(x+1)(x^2+x)}$  
- $\lim _{h\to 0^+}\frac{\sqrt{h^2+4h+5}-\sqrt{5}}{h}$  
- $\lim _{x\to 1^+}\frac{\sqrt{2x}(x-1)}{|x-1|}$  
 
::: 

::: {#exr- } 
Find the following two-sided limits. 
 
- $\lim _{t\to 0}\left(\frac{\sin  k t}{t}\right)$  where $k$  is a constant
- $\lim _{x\to 0}\left(\frac{\tan  2x}{x}\right)$ 
- $\lim _{x\to 0}\left(6x^2(\cot  x)(\csc  2x)\right)$ 
- $\lim _{h\to 0}\left(\frac{\sin  (\sin  h)}{\sin  h}\right)$ 
- $\lim _{\theta \to 0}\left(\frac{\sin  \theta }{\sin  2\theta }\right)$ 
 
::: 

::: {#exr- } 
Find the limits for the following functions for both $x\to +\infty $  and $x\to -\infty $ .
 
- $f(x)=\pi -\frac{2}{x^2}$ 
- $f(x)=\frac{-5+\left(\frac{7}{x}\right)}{3-\left(\frac{1}{x}\right)}$ 
- $f(\theta )=\frac{\cos  \theta }{3 \theta }$  
- $f(x)=e^{-x}\sin  x$  
- $f(x)=\frac{2x+3}{5x+7}$ 
- $f(x)=\frac{x+1}{x^2+3}$  
- $f(x)=\frac{9x^4+x}{2x^4+5x^2-x+6}$  
- $f(x)=\frac{2\sqrt{x}+x^{-1}}{3x-7}$  
- $f(x)=\frac{x^{-1}+x^{-4}}{x^{-2}-x^{-3}}$ 
    
::: 



