---
pagetitle: "Derivative as a Function - Exploring Calculus"
---
# Derivative as a Function

## The Definition of Derivative

The first main idea of calculus is of course, the limit. A \index{limiting process} **limiting process**  can be used in the study of curves in general; but the derivative the main limiting  process that has lead to the development of calculus. 


Given a function $f$ of  a real variable $x$ and a positive change in $x$, say $\Delta  x$, the  expression 
$$
\frac{f(x+\Delta  x)-f(x)}{\Delta  x}
$$ 
is called the \index{difference quotient} **difference quotient**  and is the formula for the slope of a secant line to the graph of $f$ through the points $(x,f(x))$ and $(x+\Delta  x,f(x+\Delta  x)).$ 

The limiting process illustrated in the examples below was first developed by the French mathematician Pierre de Fermat. The following definition was realized by Newton and Leibniz.


::: {#def- } 
The \index{derivative of a function} **derivative of a function**  $y=f(x)$ for any $x$ is defined by
$$
f'(x)=\lim _{h\to 0}\frac{f(x+h)-f(x)}{h}
$$
provided this limit exists. The derivative is also denoted by $\frac{d y}{d x};$ and other common notations are $y'$, $\frac{d f}{d x}$, and
$D_x(y).$ Also the limit is sometimes denoted by
$$
\frac{d y}{d x}=\lim _{\Delta  x\to 0}\frac{\Delta  y}{\Delta  x}=\lim _{\Delta  x\to 0}\frac{f(x+\Delta  x)-f(x)}{\Delta  x}=f'(x).
$$
The process of finding the derivative is called \index{differentiation} **differentiation**. A function $f$ is called \index{differentiable} **differentiable** at $x$ when the defining limit exists; and we say that $f$ is \index{differentiable} on $(a,b)$ when $f$ is differentiable at every point in $(a,b).$
::: 

## Taking the Derivative Using the Definition

In the following examples we illustrate how to find the derivative function using the definition of the derivative. 


::: {#exm- } 
Find the derivative of the function using the definition of the derivative given $f(x)=x^3$ at $(1,1).$
::: 

::: {.proof }[Solution]
By definition we compute the limit, as follows,
\begin{align*}
f'(x) & =  \lim _{\Delta  x\to 0}\frac{f(x+\Delta  x)-f(x)}{\Delta  x}  \\
& =  \lim _{\Delta  x\to 0}\frac{x^3+3 x^2 (\Delta  x)+3 x (\Delta  x)^2+(\Delta  x)^3-x^3}{\Delta  x} \\
& =  \lim _{\Delta  x\to 0}\frac{3 x^2 (\Delta  x)+3 x (\Delta  x)^2+(\Delta  x)^3}{\Delta  x}  \\
& =  \lim _{\Delta  x\to 0}\left( 3 x^2 +3 x (\Delta  x)+(\Delta  x)^2 \right) 
=  3 x^2
\end{align*}
which is the derivative of $f$ for any $x.$ At $x=1,$ we have $f'(1)=1.$
::: 


::: {#exm- } 
Find the derivative of the function using the definition of the derivative given $f(x)=\sqrt[3]{x}$ at $(8,2).$
::: 

::: {.proof }[Solution]
By the definition of the derivative,  
\begin{align*}
f'(x) & = \lim _{\Delta  x\to 0}\frac{f(x+\Delta  x)-f(x)}{\Delta  x} 
=\lim _{\Delta  x\to 0}\frac{\sqrt[3]{(x+\Delta  x)}-\sqrt[3]{x}}{\Delta  x} \\
& =\lim _{\Delta  x\to 0}\left(\frac{\sqrt[3]{(x+\Delta  x)}-\sqrt[3]{x}}{\Delta  x}\right)\left(\frac{\sqrt[3]{(x+\Delta  x)^2}+\sqrt[3]{(x+\Delta  x)x}+\sqrt[3]{x^2}}{\sqrt[3]{(x+\Delta  x)^2}+\sqrt[3]{(x+\Delta  x)x}+\sqrt[3]{x^2}}\right) \\
& =\lim _{\Delta  x\to 0}\left(\frac{x+\Delta  x-x}{\Delta  x\left(\sqrt[3]{(x+\Delta  x)^2}+\sqrt[3]{(x+\Delta  x)x}+\sqrt[3]{x^2}\right)}\right) \\
& =\lim _{\Delta  x\to 0}\left(\frac{1}{\sqrt[3]{(x+\Delta  x)^2}+\sqrt[3]{(x+\Delta  x)x}+\sqrt[3]{x^2}}\right) 
 =\lim _{\Delta  x\to 0}\frac{1}{3\sqrt[3]{x^2}}
\end{align*}
which is the derivative of $f$ for any $x.$ At $x=8,$ we have $f'(8)=\frac{1}{12}.$
::: 

 
## Finding an Equation of the Tangent Line


::: {#thm- } 
The slope of the tangent line to the function at $\left(x_0,f\left(x_0\right)\right)$ is $m=f'\left(x_0\right)$ and $y=f'\left(x_0\right)\left(x-x_0\right)+f\left(x_0\right)$ is an equation of the tangent line to the graph of $f$ at $x=x_0$.
::: 

::: {.proof }
By definition, the \index{slope of the tangent line} **slope of the tangent line**  at $x_0$ is $f'(x_0)$, therefore an equation of the tangent line that passes through $\left(x_0,f\left(x_0\right)\right)$ is $y=f'\left(x_0\right)\left(x-x_0\right)+f\left(x_0\right).$
::: 

::: {#exm- } 
Differentiate the function $\displaystyle f(x)=x+\frac{9}{x}$ and find the slope of the tangent line at the point where $x=-3.$
::: 

::: {.proof }[Solution]
To find the slope of the tangent line we determine the derivative of the function,
\begin{align*}
f'(x) & =\lim _{\Delta  x\to 0}\frac{f(x+\Delta  x)-f(x)}{\Delta  x} \\ 
& =\lim _{\Delta  x\to 0}\frac{3\sqrt{-(x+\Delta  x)}-3\sqrt{-x}}{\Delta  x} \\ 
& =\lim _{\Delta  x\to 0}\left(3\frac{\sqrt{-(x+\Delta  x)}-\sqrt{-x}}{\Delta  x}\right)\left(\frac{\sqrt{-(x+\Delta  x)}+\sqrt{-x}}{\sqrt{-(x+\Delta  x)}+\sqrt{-x}}\right) \\ 
& =\lim _{\Delta  x\to 0}\left(3\frac{-(x+\Delta  x)-(-x)}{\Delta  x\left(\sqrt{-(x+\Delta  x)}+\sqrt{-x}\right)}\right) \\ 
& =\lim _{\Delta  x\to 0}\left(3\frac{-\Delta  x}{\Delta  x\left(\sqrt{-(x+\Delta  x)}+\sqrt{-x}\right)}\right) \\ 
& =\lim _{\Delta  x\to 0}\left(\frac{-3}{\sqrt{-(x+\Delta  x)}+\sqrt{-x}}\right) \\ 
& =-\frac{3}{2 \sqrt{-x}}
\end{align*}
which is the derivative of the function $f$ for any $x<0.$ At $x=-2,$ we have
$$
f'(-2)=-\frac{3}{2 \sqrt{-(-2)}}=-\frac{3\sqrt{2}}{4}.
$$
Therefore, an equation of the tangent line at $x=-2$ is
\begin{align*}
& y=f'\left(x_0\right)\left(x-x_0\right)+f\left(x_0\right) =-\frac{3\sqrt{2}}{4} (x+2)+3\sqrt{2}.
\end{align*}
::: 


::: {#exm- } 
Find an equation of the tangent line to the graph of 
$$
g(x)=\frac{1-x}{2+x}
$$
 at $x=-1.$
::: 

::: {.proof }[Solution]
To find the slope of the tangent line we compute the derivative of the function,
\begin{align*}
g'(x) & =\lim _{\Delta  x\to 0}\frac{f(x+\Delta  x)-f(x)}{\Delta  x} \\ 
& =\lim _{\Delta  x\to 0}\frac{\frac{1-(x+\Delta  x)}{2+(x+\Delta  x)}-\frac{1-x}{2+x}}{\Delta  x} \\ 
& =\lim _{\Delta  x\to 0}\frac{\left(\frac{1-(x+\Delta  x)}{2+(x+\Delta  x)}\right)\left(\frac{2+x}{2+x}\right)-\left(\frac{1-x}{2+x}\right)\left(\frac{2+(x+\Delta x)}{2+(x+\Delta  x)}\right)}{\Delta  x} \\ 
& =\lim _{\Delta  x\to 0}\frac{-3\Delta  x}{\Delta  x(2+(x+\Delta  x))(2+x)} \\ 
& =\lim _{\Delta  x\to 0}\frac{-3}{(2+(x+\Delta  x))(2+x)} \\ 
& =\frac{-3}{(2+x)^2}
\end{align*}
At $x=-1,$ we have
$$
g'(-1)=\frac{-3}{(2+(-1))^2}=-3.
$$
Therefore, an equation of the tangent line at $x=-1$ is
$$
y=f'\left(x_0\right)\left(x-x_0\right)+f\left(x_0\right) = -3 (x+1)+2.
$$
::: 

## Examples of Non-differentiable Functions


::: {#exm- } 
Give three examples of functions $f$ where $f$ is not differentiable at $x=c$ but $f$ is continuous at
$x=c.$
::: 

::: {.proof }[Solution]
The function $f(x)=|x|$ is not differentiable at $x=0$ since
$$
\lim _{h\to 0^-}\frac{f(0+h)-f(0)}{h}=\lim _{h\to 0^-}\frac{|h|}{h}=-1
$$
$$
\lim _{h\to 0^+}\frac{f(0+h)-f(0)}{h}=\lim _{h\to 0^+}\frac{|h|}{h}=1
$$
which proves the two-sided limit (the derivative) 
$$
\lim _{h\to 0}\frac{f(0+h)-f(0)}{h}
$$
does not exist. 
This type of example where the function is not differentiable is called a \index{corner point} **corner point** . 
 
Secondly, the function $f(x)=\sqrt[3]{x^2}$ is not differentiable at $x=0$ since
$$
\lim _{h\to 0^-}\frac{f(0+h)-f(0)}{h}=\lim _{h\to 0^-}\frac{\sqrt[3]{h^2}}{h}
=\frac{1}{\sqrt[3]{h}}=-\infty
$$
$$
\lim _{h\to 0^+}\frac{f(0+h)-f(0)}{h}=\lim _{h\to 0^+}\frac{\sqrt[3]{h^2}}{h}
=\frac{1}{\sqrt[3]{h}}=+\infty
$$
which proves the two-sided limit (the derivative) 
$$
\lim _{h\to 0}\frac{f(0+h)-f(0)}{h}
$$ 
does not exist. 
This type of example where the function is not differentiable is called a \index{vertical tangent} **vertical tangent** .  
 
Thirdly, the function
$$ 
f(x)=
\begin{cases}
x-1 & \text{ if } x<0 \\   
2x & \text{ if } x\geq  0
\end{cases}
$$
is not differentiable at $x=0$ since
$$
\lim _{h\to 0^-}\frac{f(0+h)-f(0)}{h}=\lim _{h\to 0^-}\frac{h}{h}=1
$$
$$
\lim _{h\to 0^+}\frac{f(0+h)-f(0)}{h}=\lim _{h\to 0^+}\frac{2h}{h}=2
$$
which proves the two-sided limit (the derivative) 
$$
\lim _{h\to 0}\frac{f(0+h)-f(0)}{h}
$$
does not exist. 
In this third example, does $f$ have a corner point at $x=0$ or is it a vertical tangent at $x=0$?
::: 

::: {#exm- } 

Compute the difference quotient for the function defined by
$$
f(x)=\left\{
\begin{array}{cc}
 \displaystyle \frac{\sin  x}{x} & \text{ if } x\neq 0 \\ 
 1 & \text{ if } x=0
\end{array}
\right .
$$
Do you think $f$ is differentiable at $x=0$? If so, what is the equation of the tangent line at $x=0$?
::: 

::: {.proof }[Solution]
For $x\neq 0,$ we find,
$$
f'(x)=\lim _{h\to 0}\frac{f(x+h)-f(x)}{h}=\lim _{h\to 0 }\frac{\frac{\sin (x+h)}{x+h}-\frac{\sin  x}{x}}{h}.
$$
At $x=0$ we have,
$$
f'(0)=\lim _{h\to 0 }\frac{\frac{\sin (h)}{h}-1}{h}.
$$
Using a table of values to compute the limit we infer that $f'(0)=0$
and so the equation of the tangent line is $y=1.$
::: 

## Differentiability Implies Contunuity


::: {#thm- } 
If a function $f$ is differentiable at $x=c,$ then it is also continuous at $x=c$.
::: 

::: {.proof }
Assume that $f$ is a differentiable function, then by definition
$$
f'(c) =\lim _{\Delta  x\to 0}\frac{f(c+\Delta  x)-f(c)}{\Delta  x}
$$
exists, and therefore we can use the product rule for limits with
\begin{align*}
& \lim _{\Delta  x\to 0}f(c+\Delta  x)-f(c) \\ 
& \qquad =\lim _{\Delta  x\to 0}\frac{f(c+\Delta  x)-f(c)}{\Delta  x}\Delta  x \\ 
&\qquad =\left( \lim _{\Delta  x\to 0}\frac{f(c+\Delta  x)-f(c)}{\Delta  x} \right)\left( \lim _{\Delta  x\to 0}\Delta  x \right)\\ 
&\qquad =f'(c)(0) \\ 
& \qquad =0
\end{align*}
Whence, 
$$
\lim _{\Delta  x\to 0}f(c+\Delta  x)=f(c)
$$
and so $f$ is continuous at $x=c.$
::: 

## Exercises

::: {#exr- } 
Using the definition of the derivative find the derivative for each of the following functions. 
 
-   $f(x)=2\sqrt{x}-3$
-   $g(x)=\frac{1}{2\sqrt{x}-3}$
-   $f(x)=e^{2x+1}$
::: 

::: {#exr- } 
Find an equation of the tangent line at the indicated point for each of the following: 
 
-   $f(x)=3\sqrt{-x}$ at $x=-2$
-   $f(z)=\frac{1-z}{2 z}$ at $z=-1$
-   $f(x)=4-x^2$ at $x=1$
-   $y=2x^3$ at $x=2$
::: 

::: {#exr- } 
(a) If possible, give an example of a function that is continuous on $(-\infty ,+\infty )$ but does not have a derivative at $x=2.$ Sketch and
explain. (b) If possible, give an example of a function that is continuous and increasing on $(-\infty ,2),$ continuous and decreasing on $(2,+\infty),$ discontinuous at $x=2,$ and does not have a derivative at $x=2.$ Sketch and explain.
::: 

::: {#exr- } 
Using the definition find the derivative function given
$$
g(x)=\left\{
\begin{array}{cc}
 -2x+3 & \text{if}\text{   }x<\frac{3}{2} \\
 -\left(x-\frac{3}{2}\right)^2 & \text{if}\text{  }x\geq  \frac{3}{2}
\end{array}
\! \right..
$$
::: 

::: {#exr- } 
Using the definition find the derivative for each of the following functions.
 
-   $v(t)=t-\frac{1}{t}$
-   $f(x)=(x+1)^3$
-   $s(t)=1-3t^2$
-   $w(z)=z+\sqrt{z}$
::: 

::: {#exr- } 
Using the alternative definition for the derivative of a function: 
$$
  f'(x)=\lim _{z\to x}\frac{f(z)-f(x)}{z-x}
$$
find the derivative of each of the following functions. 
 
-   $f(x)=\frac{x}{x-1}$ 
-   $g(x)=\frac{x-1}{x+1}$
-   $h(x)=(x+1)^3$
-   $p(t)=2-3t^2$
::: 

::: {#exr- } 
Using the definition of the derivative find the derivative for each of the following functions. 
 
-   $f(x)=2\sqrt{x}-3$
-   $g(x)=\frac{1}{2\sqrt{x}-3}$
-   $f(x)=e^{2x+1}$
::: 

::: {#exr- } 
Find an equation of the tangent line at the indicated point for each of the following: 
 
-   $f(x)=3\sqrt{-x}$ at $x=-2$
-   $f(z)=\frac{1-z}{2 z}$ at $z=-1$
-   $f(x)=4-x^2$ at $x=1$
-   $y=2x^3$ at $x=2$
::: 

::: {#exr- } 
(a) If possible, give an example of a function that is continuous on $(-\infty ,+\infty )$ but does not have a derivative at $x=2.$ Sketch and
explain. (b) If possible, give an example of a function that is continuous and increasing on $(-\infty ,2),$ continuous and decreasing on $(2,+\infty),$ discontinuous at $x=2,$ and does not have a derivative at $x=2.$ Sketch and explain.
::: 

::: {#exr- } 
Using the definition find the derivative function given
$$
g(x)=\left\{
\begin{array}{cc}
 -2x+3 & \text{if}\text{   }x<\frac{3}{2} \\
 -\left(x-\frac{3}{2}\right)^2 & \text{if}\text{  }x\geq  \frac{3}{2}
\end{array}
\! \right..
$$
::: 

::: {#exr- } 
Using the definition find the derivative for each of the following functions.
 
-   $v(t)=t-\frac{1}{t}$
-   $f(x)=(x+1)^3$
-   $s(t)=1-3t^2$
-   $w(z)=z+\sqrt{z}$
::: 

::: {#exr- } 
Using the alternative definition for the derivative of a function: 
$$
 \displaystyle f'(x)=\lim _{z\to x}\frac{f(z)-f(x)}{z-x}
$$
find the derivative of each of the following functions. 
 
-   $f(x)=\frac{x}{x-1}$ 
-   $g(x)=\frac{x-1}{x+1}$
-   $h(x)=(x+1)^3$
-   $p(t)=2-3t^2$
::: 



