---
pagetitle: "Indeterminate Forms - Exploring Calculus"
---
# Indeterminate Forms


We say that $\lim _{x\to \infty }\frac{3^x-1}{x^3}$ has the intermediate form\index{intermediate form} $\frac{\infty }{\infty } **intermediate form} $\frac{\infty }{\infty ** $ because $3^x\to \infty $ and $x^3\to \infty $ as $x\to \infty $ 

In this section we will consider the following seven indeterminate forms
\[
\frac{\infty }{\infty }, \qquad
\frac{0}{0}, \qquad
\infty-\infty, \qquad
0\cdot \infty, \qquad
\infty^0, \qquad
0^0,  \qquad
1^{\infty}.
\]


## l'H\^opital's Rule

Our main investigative tool will be l'H\^opital's rule which says that the limit of a quotient of functions $f$ and $g$ is equal to the limit of the quotient of their derivatives $f'$ and $g'$ provided some conditions are satisfied. 
It is especially important to verify the conditions regarding the limits of $f$ and $g$ before applying l'H\^opital's rule. 


::: {#thm- } [l'H\^opital's Rule] 
Suppose $f$ and $g$ are differentiable functions and $g'(x)\neq 0$ on an open interval $I$ that contains
$c$. 
Suppose 
\[
\lim _{x\to c}\frac{f(x)}{g(x)}
\]
produces an intermediate form $\frac{0}{0}$ or $\frac{\infty }{\infty
}$ and that 
\[
\lim _{x\to c}\frac{f'(x)}{g'(x)}\]
exists or is infinite, then 
\[
\lim _{x\to c}\frac{f(x)}{g(x)}=\lim _{x\to c}\frac{f'(x)}{g'(x)}.
\]
::: 

\begin{remark}
Keep in mind that l'H\^opital's' rule also holds if
$x\to c$ is replaced by $x\to c^+,$ $x\to c^-,$ $x\to \infty ,$ $x\to -\infty .$ 
\end{remark}

To illustrate l'H\^opital's Rule we will evaluate several limits.

## Indeterminate Forms $0/0$ and $\infty/\infty$

::: {#exm- }  

Evaluate $\ds \lim _{x\to \infty }\frac{\ln  x}{x}$ using l'H\^opital's rule. 
::: 

::: {.solution } 
The given limit has the indeterminate form $\frac{\infty }{\infty }$ since $\lim _{x\to
\infty }\ln  x=+\infty $ and $\lim _{x\to +\infty }x=+\infty .$ 
We apply l'H\^opital's rule to evaluate the limit as follows 
\[
\lim _{x\to +\infty }\frac{\ln  x}{x}=\lim _{x\to +\infty }\frac{\frac{1}{x}}{1}=0.
\square
\]
::: 


::: {#exm- }  
Evaluate 
\[
\lim _{x\to -\infty }\frac{x^2}{e^{-x}}
\] 
using l'H\^opital's rule. 
:::  

::: {.solution } 
The given limit has the indeterminate form $\frac{\infty }{\infty }$ since $\lim _{x\to
-\infty }x^2=+\infty $ and $\lim _{x\to -\infty }e^{-x}=+\infty .$ 
We apply l'H\^opital's rule to evaluate the limit as follows
\[
\lim _{x\to -\infty }\frac{x^2}{e^{-x}}=\lim _{x\to -\infty }\frac{2x}{-e^{-x}}=\lim _{x\to -\infty }\frac{2}{e^{-x}}=0.
\] 
Thus illustrating that L'Hopital's rule can be used multiple times. 
::: 


We are justified in calling $\frac{\infty}{\infty}$ an indeterminate form since 
\[
\lim _{x\to +\infty }\frac{\ln  x}{x}=0 \neq 1=\lim _{x\to 0 }\frac{\sin  x}{x}.
\]

::: {#exm- }  
Evaluate 
\[
\lim _{x\to 0 }\frac{\sin x}{x}
\] 
using l'H\^opital's rule. 
::: 

::: {.solution } 
The given limit has the indeterminate form $\frac{0}{0 }$ since $\lim _{x\to
0 }\sin x=0 $ and $\lim _{x\to 0 }x=0 .$ 
We apply l'H\^opital's rule to evaluate the limit as follows
\[
\lim _{x\to 0 }\frac{\sin  x}{x}=\lim _{x\to 0 }\frac{\cos x}{1}=1.
\square
\]
::: 

::: {#exm- }  
Evaluate 
\[
\lim _{x\to 0}\frac{e^{2x}-1}{x}
\] 
using l'H\^opital's rule.
:::  

::: {.solution } 
The given limit has the indeterminate form $\frac{0}{0}$ since $\lim _{x\to 0}e^{2x}-1=0$ and $\lim _{x\to 0}x=0.$ 
We apply l'H\^opital's rule to evaluate the limit as follows
\[
\lim _{x\to 0}\frac{e^{2x}-1}{x}=\lim _{x\to 0}\frac{2 e^{2 x}}{1}=2.
\square
\]
::: 

We are justified in calling $\frac{0}{0}$ an indeterminate form since 
\[
\lim _{x\to 0 }\frac{\sin  x}{x}=1 \neq 2=\lim _{x\to 0}\frac{e^{2x}-1}{x}.
\]

::: {#exm- }  
Evaluate 
\[
\lim _{x\to 0} \frac{a^x-b^x}{x}
\] 
using l'H\^opital's rule, where $a,b>0$.
:::  

::: {.solution } 
The given limit has the indeterminate form $\frac{0}{0}$ since $\lim _{x\to 0}a^x-b^x=0$ and $\lim _{x\to 0}x=0.$ 
We apply l'H\^opital's rule to evaluate the limit as follows
\[
\lim _{x\to 0}\frac{a^x-b^x}{x}=\lim _{x\to 0}\frac{(\ln a) a^x-(\ln b) b^x}{1}=\ln a-\ln b=\ln \frac{a}{b}.
\square
\]
::: 


## Indeterminate Forms $\infty-\infty$ and $0\cdot \infty$ 


::: {#exm- }  
Evaluate 
\[
\lim _{x\to +\infty }e^{-x}\sqrt{x}
\]
using l'H\^opital's rule. 
:::  

::: {.solution } 
The given limit has indeterminate form $0\cdot \infty $ since $\lim _{x\to +\infty }e^{-x}=0$ and $\lim _{x\to +\infty }\sqrt{x}=+\infty .$ 
We apply l'H\^opital's rule to evaluate the limit as follows 
\[
\lim _{x\to +\infty }\frac{\sqrt{x}}{e^x}=\lim _{x\to +\infty }\frac{\frac{1}{2\sqrt{x}}}{e^x}=\lim _{x\to +\infty }\frac{1}{2\sqrt{x}e^x}=0.
\square
\]
::: 


::: {#exm- }  
Evaluate 
\[
\lim _{x\to 1^+ } \left(\frac{1}{\ln x}-\frac{1}{x-1}\right)
\]
using l'H\^opital's rule. 
:::  

::: {.solution } 
The given limit has indeterminate form 
$\infty -\infty$ since 
$\lim_{x\to 1^+ }\frac{1}{\ln x}=+\infty$ and 
$\lim_{x\to 1^+ }\frac{1}{x-1}=+\infty .$ 
We apply l'H\^opital's rule to evaluate the limit as follows 
\begin{align*}
& \lim _{x\to 1^+ } \left(\frac{1}{\ln x}-\frac{1}{x-1}\right)
=\lim _{x\to 1^+ } \frac{x-1-\ln x}{(x-1)\ln x} 
=\lim _{x\to 1^+ } \frac{1-\frac{1}{x}}{\ln x+\frac{x-1}{x}} \\
& \qquad =\lim _{x\to 1^+ }\frac{x-1}{x\ln x+x-1}
=\lim _{x\to 1^+ } \frac{1}{\ln x+x\left(\frac{1}{x}\right)+1}
=\frac{1}{2}
\square
\end{align*}
::: 



## Indeterminate Forms $\infty^0$, $0^0$, and $1^{\infty}$

The limit
\[
\lim_{x\to a} f(x)^{g(x)}
\]
is said to an indeterminate form of the type 
 
\item[] $\infty^0$ \quad if $\lim_{x\to a} f(x)=\infty$ and $\lim_{x\to a} g(x)=0$, \\[-5pt]
\item[] $0^0$ \quad \ if $\lim_{x\to a} f(x)=0$ and $\lim_{x\to a} g(x)=0$, and \\[-5pt]
\item[] $1^{\infty}$ \quad if $\lim_{x\to a} f(x)=1$ and $\lim_{x\to a} g(x)=\pm \infty$.
 
With these indeterminate forms we can apply the identity $f(x)^{g(x)}=e^{g(x)\ln f(x)}$. 
Since we know that the exponential function is continuous, we can use 
\[
\lim_{x\to a} f(x)^{g(x)}=\lim_{x\to a}e^{g(x)\ln f(x)}=e^{\left( \displaystyle \lim_{x\to a} g(x)\ln f(x)\right)}
\]
and then possibly apply  l'H\^opital's rule, of course we must first check whether or not $\lim_{x\to a} g(x)\ln f(x)$ exists first.


::: {#exm- }  
Evaluate 
\[
\lim _{x\to 0^+}(\sin  x)^x
\]
using l'H\^opital's rule. 
:::  

::: {.solution } 
The given limit has the indeterminate form $0^0$ since $\lim _{x\to 0^+} \sin  x=0$ and $\lim _{x\to 0^+}x=0.$ 
Since $\lim _{x\to 0^+}\ln  (\sin  x)=+\infty $ and $\lim _{x\to 0^+}\frac{1}{x}=+\infty $ we have indeterminate form of $\frac{\infty}{\infty }$ and so we apply l'H\^opital's rule to evaluate the following limit 
\[ 
\lim _{x\to 0^+} x \ln \sin  x
=\lim _{x\to 0^+}\frac{\ln  (\sin  x)}{\frac{1}{x}} 
=\lim _{x\to 0^+}\frac{\frac{\cos  x}{\sin  x}}{\frac{-1}{x^2}}
=\lim _{x\to 0^+}\frac{-x^2}{\tan  x}
=\lim _{x\to 0^+}\frac{-2x}{\sec ^2x}
=0.
\]
Therefore, since the exponential function is continuous,
\[
\lim _{x\to 0^+}(\sin  x)^x 
=\lim _{x\to 0^+} e^{x \ln \sin  x} 
= e^{\displaystyle \left( \lim _{x\to 0^+} x \ln \sin  x\right) } 
%=e^{\left(\displaystyle \lim _{x\to 0^+}\frac{\ln  (\sin  x)}{\frac{1}{x}}\right)}
=e^0
=1.
\square
\]
::: 

::: {#exm- }  
Evaluate 
\[
\lim _{x\to +\infty }x^{1/x}
\]
using l'H\^opital's rule. 
:::  

::: {.solution } 
The given limit has the indeterminate form $\infty ^0$ since $\lim _{x\to \infty }\frac{1}{x}=0$ and $\lim _{x\to +\infty }\frac{1}{x}=+\infty .$  
Since $\lim _{x\to \infty}\ln  x=+\infty $ and $\lim _{x\to \infty}x=+\infty $ the following limit has indeterminate form $\frac{\infty }{\infty }$ and so we apply l'H\^opital's rule as follows
\[
\lim _{x\to +\infty }\frac{1}{x}\ln x
=\lim _{x\to +\infty }\frac{\frac{1}{x}}{1}
=0
\]
Since the exponential function is continuous 
\[
\lim _{x\to +\infty }x^{1/x}
=\lim _{x\to +\infty }e^{\frac{1}{x}\ln x} 
=e^{\left(\displaystyle \lim _{x\to +\infty }\frac{1}{x}\ln x \right)}
=e^0 
=1.
\square
\]
::: 


::: {#exm- }  
Evaluate 
\[
L=\lim _{x\to 0^+}(1+\sin  4x)^{\cot  x}
\]
using l'H\^opital's rule. 
:::  

::: {.solution } 
The given limit has the indeterminate form $1^{\infty }$ since $\lim _{x\to 0^+}1+\sin 4x=1$ and $\lim _{x\to 0^+}\cot  x=+\infty .$ 
Notice $\lim _{x\to 0^+}\frac{\ln (1+\sin  4x)}{\tan  x}$ has indeterminate form $\frac{0}{0}$ since $\lim _{x\to 0^+}\ln (1+\sin  4x)=0$
and $\lim _{x\to 0^+}\tan  x=0.$ 
We apply l'H\^opital's rule to find
\[
\lim _{x\to 0^+}\frac{\ln (1+\sin  4x)}{\tan  x}
=\lim _{x\to 0^+}\frac{\frac{4\cos  4x}{1+\sin  4x}}{\sec ^2x}
=\frac{\frac{4}{1+0}}{1}
=4.
\]
Since the exponential function is continuous
\begin{align*}
\lim _{x\to 0^+}(1+\sin  4x)^{\cot  x} 
& =\lim _{x\to 0^+}e^{\cot  x \ln (1+\sin  4x)} \\
& =e^{\left( \displaystyle \lim _{x\to 0^+} \cot  x \ln (1+\sin  4x) \right)} 
=e^4.
\square
\end{align*}

::: 


## Change of Variable

In the next example we show how making a change of variable can simplify the process of evaluating a limit.

::: {#exm- }  

Evaluate 
\[
\lim _{x\to +\infty }x^5\left[\sin \left(\frac{1}{x}\right)-\frac{1}{x}+\frac{1}{6x^3}\right]
\]
using l'H\^opital's rule. 
:::  

::: {.solution } 
We make a change of variable to simplify the expression, namely $u=\frac{1}{x}.$ 
Since $u\to 0$ as $x\to +\infty ,$ we have
\begin{align*}
\lim _{x\to +\infty }x^5\left[\sin \left(\frac{1}{x}\right)-\frac{1}{x}+\frac{1}{6x^3}\right] 
=\lim _{u\to 0}\frac{\sin (u)-u+\frac{1}{6}u^3}{u^5} 
\end{align*}
Now we have indeterminate form $\frac{0}{0}$ and so applying l'H\^opital rule several times yields
\begin{align*}
& =\lim _{u\to 0}\frac{\sin (u)-u+\frac{1}{6}u^3}{u^5} 
=\lim _{u\to 0}\frac{(\cos  u)-1+\frac{1}{2}u^2}{5u^4} 
=\lim _{u\to 0}\frac{(-\sin  u )+u}{20u^3}  \\
& =\lim _{u\to 0}\frac{(-\cos u )+1}{60u^2}    
=\lim _{u\to 0}\frac{\sin  u }{120 u} 
=\lim _{u\to 0}\frac{\cos  u }{120}  
=\frac{1}{120}.
\square
\end{align*}
::: 


## l'H\^opital's Rule Fails

In this final example we illustrate one way in which l'H\^opital's rule can fail even though the value of the limit is finite.


::: {#exm- }  
Try to evaluate 
\[
\lim _{x\to +\infty }\frac{x+\sin  x}{x-\cos  x}
\]
using l'H\^opital's rule.
:::  

::: {.solution } 
This limit has indeterminate form since
\[
\lim _{x\to +\infty }(x+\sin  x)=+\infty \hspace{.5cm}\text{and}\hspace{.5cm} \lim _{x\to +\infty }(x+\cos  x)=+\infty .
\]
If we try to apply L'Hospitals's Rule we find, 
\[ \lim _{x\to +\infty }\frac{x+\sin  x}{x-\cos  x}=\lim _{x\to \infty }\frac{1+\cos  x}{1+\sin  x}\]
but the limit 
$\lim _{x\to \infty }\frac{1+\cos  x}{1+\sin  x}$
does not exist because of osculating behavior, so we can not use l'H\^opital's rule. 
To correctly find this limit we divide by $x$ as follows 
\[
L=\lim _{x\to +\infty }\frac{x+\sin  x}{x-\cos  x}
=\lim _{x\to +\infty }\frac{\frac{x}{x}+\frac{\sin  x}{x}}{\frac{x}{x}-\frac{\cos  x}{x}}
=\frac{1+0}{1-0}
=1.
\square
\]
::: 


## Exercises

::: {#exr- } 
Use l'H\^opital's rule to find the following limits.
    
\item $\lim _{x\to 2}\frac{x-2}{x^2-4}.$ 
\item $\lim _{x\to 1}\frac{x^3-1}{4x^3-x-3}.$
\item $\lim _{x\to -5}\frac{x^2-25}{x+5}.$
\item $\lim _{x\to 0}\frac{\sin  x^2}{x}.$
\item $\lim _{x\to 0}\frac{\sin  x -x}{x^3}.$
\item $\lim _{x\to \pi /2}\frac{1-\sin  x}{1+ \cos  2x}.$
\item $\lim _{x\to \pi /2}\frac{\ln  ( \csc  x)}{\left(x-\frac{\pi }{2}\right)^2}.$
\item $\lim _{x\to \left(\frac{\pi }{2}\right)^-}\left(x-\frac{\pi }{2}\right)\sec  x.$ 
\item $\lim _{x\to 0}\frac{\left(\frac{1}{2}\right)^x-1}{x}.$
\item $\lim _{x\to 0^+}\frac{\ln  \left(e^x-1\right)}{\ln  x}.$ 
\item $\lim _{x\to \infty }(\ln  2x-\ln (x+1)).$
\item $\lim _{x\to 0^+}\left(\frac{3x+1}{x}-\frac{1}{\sin  x}\right).$
\item $\lim _{x\to 0}\frac{\cos  x-1}{e^x-x-1}.$
\item $\lim _{x\to \infty } x^2e^{-x}.$
\item $\lim _{x\to \infty }(\ln  x)^{1/x}.$
\item $\lim _{x\to \infty  }x^{1/ \ln  x}.$ 
\item $\lim _{x\to \infty }(1+2x)^{1/ 2 \ln  x}.$ 
\item  $\lim _{x\to 0^+}\frac{\sqrt{x}}{\sqrt{\sin  x}}.$ 
 
::: 

::: {#exr- } 
Let 
\[
f(x)=\left\{
\begin{array}{cc}
 x+2 & x\neq 0 \\
 0 & x=0
\end{array}
\right.
\qquad \text{and} \qquad  
g(x)=\left\{
\begin{array}{cc}
 x+1 & x\neq 0 \\
 0 & x=0
\end{array}
\right.
\] 
Show that $\lim _{x\to 0}\frac{f'(x)}{g'(x)}=1$ but 
$\lim _{x\to 0}\frac{f(x)}{g(x)}=2$.  Explain why this does not contradict l'H\^opital's Rule. 
::: 

::: {#exr- } 
Find constant $a$ and $b$ so that 
$\lim _{x\to 0}\left(\frac{\sin  2x}{x^3}+\frac{a}{x^2+b}\right)=1.$
::: 

::: {#exr- } 
Find all values of $a$ and $b$ so that 
$\lim _{x\to 0}\frac{\sin  a x+b x}{x^3}=36.$
::: 

::: {#exr- } 
Find the values of $a$ so that 
$\lim _{x\to 0}\frac{a-\cos  b x}{x^2}=2.$
::: 

::: {#exr- } 
For a certain value of $a,$ the limit 
$\lim _{x\to +\infty }\left(x^4+5x^3+3\right)^a-x$ is finite and nonzero. 
Find $a$ and then use l'H\^opital's rule to compute the limit.
::: 

::: {#exr- } 
Evaluate $\lim _{x\to a}\frac{\sqrt{2a^3x-x^4}-a\sqrt[3]{a^2x}}{a-\sqrt[4]{a x^3}}.$
::: 

::: {#exr- } 
Determine which values of constants $a$ and $b$ is it true that 
\[\lim _{x\to 0}\left(x^{-3}\sin  7x+a x^{-2}+b\right)=-2?\]
::: 


