---
pagetitle: "Indefinite Integrals - Exploring Calculus"
---
# Indefinite Integrals

## Antiderivatives

We go over antidifferentation by defining an antiderivative function and working out examples on finding antiderivatives. 
We also concentrate on the following problem: if $F$ is an antiderivative of the continuous function $f,$ then any other antiderivative of $f$ must have the form $F(x)+C$ where $C$ is some constant.  
Thus showing, if a function $F(x)$ is an antiderivative of the function $f(x)$ then so is $F(x)+C$ where $C$ is called an arbitrary constant. 
The mean value theorem will be used to show that all derivatives of $f(x)$ are of the form $F(x)+C$ and that there are no others.


::: {#def- } 
A function $F$ is called an \index{antiderivative} **antiderivative**  of a given function $f$ on an interval $I$ if $F'(x)=f(x)$ for all $x$ in $I.$ 
::: 


::: {#thm- } 
If $F$ is an antiderivative of the continuous function $f,$ then any other antiderivative $G$, of $f$ must have the form $G(x)=F(x)+C$ where $C$ is some constant. 
::: 

::: {.proof }
We show that if $F$ is differentiable in $[a,b]$ and $F'(x)=0$ for all $x$ in $[a,b],$ then $F(x)=F(a)$ for all $x$ in $[a,b].$
By the mean-value theorem applied to $[a,x]$ for any $x$ such that $a<x\leq b,$  
$$
\frac{F(x)-F(a)}{x-a}=F'(c)=0
$$
where $a<c<x.$ 
Thus $F(x)=F(a)=0,$ so $F(x)=F(a),$ and $F(x)$ is constant in $[a,b].$ 
So in fact, for $F'(x)=f(x)$ with all $x$ in $[a,b],$ if we suppose $G'(x)=f(x)$ also for $x$ in $[a,b]$ then 
$$
\frac{d(G(x)-F(x))}{dx}=G'(x)-F'(x)=0.
$$
Thus $G(x)-F(x)=G(a)-F(a).$ 
If we let $C=G(a)-F(a),$ then $G(x)=F(x)+C.$ 
::: 

The notation $\int f(x) \, dx=F(x)+C$ where $C$ is an arbitrary constant means that $F$ is an antiderivative of $f.$ 
The function $F$ is called the
\index{indefinite integral} **indefinite integral**  of $f$ and satisfies the condition that $F'(x)=f(x)$ for all $x$ in the domain of $f.$ 
It is important to remember that
$F(x)+C$ represents a family of functions. 


## Integral Notation

::: {#exm- }  

Find the family of antiderivatives of the function $f(x)=\sin  x$ and write an equation using the indefinite integral notation. 
::: 

::: {.solution } 
If $F(x)=-\cos  x,$ then $F'(x)=\sin  x,$ and so an antiderivative of sine is $-\cos  x.$ 
Thus the general antiderivative is $G(x)=-\cos  x+C.$ 
Therefore, $\int \sin  xdx=-\cos  x+C$ where $C$ is an arbitrary constant. 
::: 


::: {#exm- }  
Find the family of antiderivatives of the function $f(x)=x^n$, $n\geq 0,$ and write an equation using the indefinite
integral notation.
::: 

::: {.solution } 
Since 
$$
\frac{d}{dx}\left(\frac{x^{n+1}}{n+1}\right)=\frac{(n+1)x^n}{n+1}=x^n
$$ 
the general antiderivative of $f$ is 
$$
F(x)=\frac{x^{n+1}}{n+1}+C,
$$
where $C$ is a constant, which is valid for $n\geq 0$ because $f(x)=x^n$ is defined on the interval $(-\infty ,+\infty ).$ 
Therefore, 
$$
\int x^n \, dx=\frac{x^{n+1}}{n+1}+C
$$
where $C$ is an arbitrary constant and $n\geq 0.$
::: 


::: {#thm- }  
Suppose $f$ and $g$ are integrable functions and $a$, $b$, and $c$ are constants. 
Then 
 
- $\displaystyle \int c f(u)du=c\int f(u) \, du$
- $\displaystyle \int [f(u)+g(u)] \, du=\int f(u) \, du+\int g(u) \, du$
- $\displaystyle \int [f(u)-g(u)] \, du=\int f(u) \, du-\int g(u) \, du$
- $\displaystyle \int [a f(u)du+b g(u)] \, du=a\int  f(u)du+b \int g(u) \, du$
::: 

::: {#thm- } 

Suppose $C$ is an arbitrary constant. 
Then  
$$
\int x^n \, dx=
\begin{cases}
 \displaystyle \frac{x^{n+1}}{n+1}+C & n\neq -1 \\ 
 \ln |x|+C & n=-1.
\end{cases}
$$
::: 


::: {#thm- } 
Suppose $u$ is a differentiable function of $x$ and $C$ is an arbitrary constant. 
 
 
- $\displaystyle \int 0 \, du=0+C$
- $\displaystyle \int e^u \, du=e^u+C$
- $\displaystyle\int  \sin  u \, du=-\cos  u+C$
- $\displaystyle\int  \cos  u \, du=\sin  u+C$
- $\displaystyle\int  \sec ^2 u \, du=\tan  u+C$
- $\displaystyle\int  \sec  u \tan  u \, du=\sec u+C$
- $\displaystyle\int  \csc  u \cot  u \, du=-\csc  u+C$
- $\displaystyle\int  \csc ^2 u \, du=-\cot  u+C$
- $\displaystyle\int \frac{1}{\sqrt{1-u^2}} \, du=\sin ^{-1}u+C$
- $\displaystyle\int \frac{1}{1+u^2} \, du=\tan ^{-1}u+C$
- $\displaystyle\int \frac{1}{|u|\sqrt{u^2-1}} \, du=\sec ^{-1}u+C$
 
::: 


::: {#exm- }  
Find the general antiderivative of the function 
$$
f(x)=\frac{x^2}{x^2+1}.
$$
::: 

::: {.solution } 
Since
$$
\frac{x^2}{x^2+1}=\frac{x^2+1-1}{x^2+1}=1-\frac{1}{x^2+1}
$$
we find 
\begin{align*}
\int \frac{x^2}{x^2+1} \, dx & =\int \left(1-\frac{1}{x^2+1}\right) \, dx 
\\ & 
=\int dx-\int \frac{1}{x^2+1} \, dx 
=x-\tan ^{-1}x+C.
\end{align*}
::: 


::: {#exm- }  
Find the general antiderivative of the function 
$$
f(x)=\left(1+\frac{1}{x}\right)\left(1-\frac{4}{x^2}\right).
$$
:::  

::: {.solution } 
We want to evaluate $\int \left(1+\frac{1}{x}\right)\left(1-\frac{4}{x^2}\right)dx.$ 
Since
$$
\left(1+\frac{1}{x}\right)\left(1-\frac{4}{x^2}\right)=1+\frac{1}{x}-\frac{4}{x^2}-\frac{4}{x^3}
$$
we use the linearity rule and the power rule to find
\begin{align*}
\int \left(1+\frac{1}{x}\right)\left(1-\frac{4}{x^2}\right)dx & 
=\int \left(1+x^{-1}-4x^{-2}-4x^{-3}\right) \, dx \\
& =x+\ln x+\frac{4}{x}+\frac{2}{x^2}+C.
\end{align*}
::: 


::: {#exm- }  
Find $f(x)$ given $f''(x)=x+\sqrt{x},$ $f(1)=1,$ and $f'(1)=2.$
::: 

::: {.solution } 
First we find $f'$ by
$$
f'(x)=\int \left(x+\sqrt{x}\right) \, dx=\frac{x^2}{2}+\frac{2 x^{3/2}}{3}+C
$$
where $C$ is some constant which can be determined with $f'(1)=2.$ 
So
$$
f'(1)=\frac{(1)^2}{2}+\frac{2 (1)^{3/2}}{3}+C=\frac{7}{6}+C=2 \qquad \Longrightarrow \qquad C=\frac{5}{6}.
$$
So in fact
$$
f'(x)=\frac{x^2}{2}+\frac{2 x^{3/2}}{3}+\frac{5}{6}.
$$
Now to find $f$ we follow the same procedure
$$
f(x)=\int \left(\frac{x^2}{2}+\frac{2 x^{3/2}}{3}+\frac{5}{6}\right) \, dx=\frac{x^3}{6}+\frac{4 x^{5/2}}{15}+\frac{5 x}{6}+K
$$
where $K$ is a constant which can be determined with $f(1)=1.$ 
So
$$
f(1)=\frac{(1)^3}{6}+\frac{4 (1)^{5/2}}{15}+\frac{5 (1)}{6}+K=\frac{19}{15}+K=1\qquad \Longrightarrow \qquad K=-\frac{4}{15}.
$$
Therefore
$$
f(x)=\frac{x^3}{6}+\frac{4 x^{5/2}}{15}+\frac{5 x}{6}-\frac{4}{15}
$$ 
as desired. 
::: 




## Finding Area

::: {#thm- } [Area Function]
If $f$ is a continuous function such that $f(x)\geq 0$ for all $x$ on the closed interval $[a,b],$
then the area bounded by the curve $y=f(x),$ the $x$-axis, and the vertical lines $x=a$ and $x=t,$ viewed as a function of $t,$ is an antiderivative
of $f(t)$ on $[a,b].$
::: 

::: {#exm- }  
Find the area under the parabola $y=x^2$ over the interval $[0,1].$
::: 

::: {.solution } 
Since $f(x)=x^2$ is a continuous function with $f(x)\geq 0$ for all $x$. 
The area function is given by 
$$
A(t)=\int t^2 \, dt=\frac{1}{3}t^3+C$$ 
and we can determine $C$ using $A(0)=0$ and so 
$$
A(0)=\frac{1}{3}(0)^3+C=0 \qquad \Longrightarrow \qquad C=0
$$ 
which means $A(t)=\frac{1}{3}t^3.$ 
Therefore the area under the curve from $[0,1]$ is $A(1)=\frac{1}{3}(1)^3=\frac{1}{3}.$
::: 




## Applications of Integration

In the next example we find the demand function given the marginal revenue. 

::: {#exm- }  
A manufacturer estimates that the marginal revenue of a certain commodity is $R'(x)=240+0.1x$ when $x$ units are produced. 
Find the demand function $p(x).$
::: 

::: {.solution } 
Since
$$
R(x)=\int R'(x)dx=\int (240+0.1x) \, dx=240 x+0.05x^2+C
$$
and because $R(x)=x p(x),$ where $p(x)$ is the demand function, we must have $R(0)=0$ so that $240(0)+0.05(0)+C+0$ yielding $C=0$ and 
$$
p(x)=\frac{R(x)}{x}=\frac{240x+0.05x^2}{x}=240+0.05x.
$$
::: 

::: {#exm- }  
A ball is thrown upward with a speed of 48 ft/s from the edge of a cliff 432 feet above the ground. 
Find its height above the ground $t$ seconds later. 
When does it reach its maximum height? 
When does it hit the ground?
::: 

::: {.solution } 
The motion is vertical and we choose the positive direction to be upward. 
At time $t$ the distance above the ground is $s(t)$ and the velocity $v(t)$ is decreasing. 
Therefore the acceleration must be negative $a(t)=\frac{dv}{dt}=-32.$ 
Taking the antiderivative  
$$
v(t)=\int a(t) \, dt=-32t+C.
$$ 
To determine $C$ we use the given information of $v(0)=48.$ 
Thus $v(0)=-32(0)+C=48$ and so $C=48$ and $v(t)=-32t+48.$ 
It follows the ball reaches its maximum height at $v(t)=0$ which means $t=\frac{48}{32}s=1.5s.$ 
Taking the antiderivative   
$$
s(t)=v'(t)=\int (-32t+48) \, dt=-16 t^2+48 t+K
$$ 
and using $s(0)=432$ we find that $s(0)=-16 (0)^2+48 (0)+K=432$ and so $K=432.$ 
Therefore the height function is 
$$
s(t)=-16 t^2+48 t+432
$$ 
and so the ball hits the ground when $s(t)=0$ meaning $t=\frac{3+3\sqrt{13}}{2}\approx 6.9 s$ by using the quadratic formula. 
::: 

::: {#exm- }  
A company has found that the rate of change of its average cost for a product is 
$$
\bar{C}'(x)=\frac{1}{4}-\frac{100}{x^2}
$$
where $x$ is the number of units and cost is in dollars. 
The average cost of producing 20 units is 40,000 dollars. 

- Find the average cost function for the product. 
- Find the average cost of 100 units of the product. 
::: 

::: {.solution } 
To find $\bar{C}(x)$ we integrate, so 
$$
\bar{C}(x)=\int \left(\frac{1}{4}-\frac{100}{x^2}\right) \, dx=\frac{x}{4}+\frac{100}{x}+K
$$
to find the constant $K$ we use the given that the average cost of producing 20 units is 40,000. 
So we find the constant $K$ by 
$\bar{C}(20)=\frac{20}{4}+\frac{100}{20}+K=10+K=40000$ which means $K=40000-10=39990.$ 
(a) So the average cost function for the product is $\bar{C}(x)=\frac{x}{4}+\frac{100}{x}+39990.$ 
(b) The average cost of 100 units of the product is 
$$
\bar{C}(10)=\frac{10}{4}+\frac{100}{10}+39990=\frac{80005}{2}=40002.5
$$ 
dollars.
::: 

::: {#exm- }  
An excellent film with a very small advertising budget must depend largely on world-of-mouth advertising.
In this case, the rate at which weekly attendance might grow can be given by
$$
\frac{dA}{dt}=\frac{-100}{(t+10)^2}+\frac{2000}{(t+10)^3}
$$
where $t$ is in the time in weeks since release and $A$ is attendance in millions. 

- Find the function that describes weekly attendance at this film. 
- Find the attendance at this film in the tenth week. 
::: 

::: {.solution } 
The function that describes weekly attendance at this film is found by integration 
\begin{align*}
A(t)& =\int \frac{dA}{dt} \, dt 
=\int \left(\frac{-100}{(t+10)^2}+\frac{2000}{(t+10)^3}\right) \, dt \\
& =\int \left(\frac{-100}{(t+10)^2}+\frac{2000}{(t+10)^3}\right) \, dt 
=\frac{100}{t+10}-\frac{1000}{(t+10)^2}+K
\end{align*}
where $t$ is in the time in weeks since release and $A$ is attendance in millions. 
When $t=0$ the attendance was 0 and so we find $K$ by 
$$
A(0)=\frac{100}{0+10}-\frac{1000}{(0+10)^2}+K=K=0.
$$ 
Thus 
$$
A(t)=\frac{100}{t+10}-\frac{1000}{(t+10)^2}
$$ 
and so the attendance at this film in the tenth week is 
$$
A(10)=\frac{100}{10+10}-\frac{1000}{(10+10)^2}=\frac{5}{2}=2.5
$$ 
million people.
::: 

::: {#exm- }  
Suppose the marginal cost for a product is $\overline{M C}=60\sqrt{x+1}$ and its fixed cost is 340.00.
If the marginal revenue for the product is $\overline{M R}=80x,$ find the profit or loss from the production and sale of (a) 3 units (b) 8 units.
::: 

::: {.solution } 
The marginal cost is $\overline{M C}=60\sqrt{x+1}$ and so the cost function is fond by integration 
$C(x)=\int 60\sqrt{x+1}dx=40 (1+x)^{3/2}+K$ where $K$ is a constant. 
Since $C(0)=340$ we find $K=300$ and so the cost function is $C(x)=40 (1+x)^{3/2}+30.$ 
The marginal revenue is $\overline{MR}=80x$ and so the revenue function is found by integration $R(x)=\int 80 xdx=40 x^2.$ 
Thus the profit function for this product is
$$
P(x)=R(x)-C(x)=40 x^2-40 (1+x)^{3/2}-300.
$$
(a) The loss from the sale of 3 units is $P(3)=40 (3)^2-40 (1+(3))^{3/2}-300=-260$ dollars.
(b) The profit from the sale of 8 units is $P(8)=40 (8)^2-40 (1+(8))^{3/2}-300=1180$ dollars. 
::: 


## Constant-Difference Theorem

The following theorem says that two functions with equal derivatives on an open interval differ by a constant on that interval. 

::: {#thm- } [Constant-Difference Theorem]
Let $f$ and $g$ be functions that are continuous on $[a,b]$ and differentiable on $(a,b).$ 
If $f'(x)=g'(x)$
for all $x$ in $(a,b),$ then $f-g$ is constant on $(a,b);$ that is, $f(x)=g(x)+k$ where $k$ is a constant.
::: 

::: {.proof }
Let $F(x)=f(x)-g(x).$ 
Then $F'(x)=f'(x)-g'(x)=0$ for all $x$ in $(a,b).$ 
Thus by the Zero Derivative Theorem, $F(x)=k$ for some constant $k$ and so $f(x)=g(x)+k$ as desired.
::: 

::: {#exm- }  
Let $g(x)=\sqrt{x^2+5}.$ 
Find a function $f$ with $f'(x)=g'(x)$ and $f(2)=1.$
::: 

::: {.solution } 
Let $f(x)=\sqrt{x^2+5}+k$ where $k$ is some constant to be determined. 
Then $f'(x)=g'(x)$ and to determine $k$ we use $f(2)=1$ to obtain  $f(2)=\sqrt{2^2+5}+k=3+k=1.$ 
Therefore, $f(x)=\sqrt{x^2+5}-2$ is the function we desire. 
::: 

::: {#exm- }  
Show that $f(x)=\frac{x+4}{5-x}$ and $g(x)=\frac{-9}{x-5}$
differ by a constant. 
Are the conditions of the constant difference theorem satisfied? Does $f'(x)=g'(x).$
::: 

::: {.solution } 
We simplify
$f'(x)=g'(x)=\frac{9}{(x-5)^2}$ 
which is valid on any interval not containing $x=5.$ 
Thus on any interval not containing $x=5,$ the constant difference theorem applies. 
In fact, when $x\neq 5$,  we have
$$
f(x)-g(x)=\frac{x+4}{5-x}-\frac{-9}{x-5}=-1
$$
::: 

::: {#exm- }  
Let $f(x)=(x-2)^3$ and $g(x)=\left(x^2+12\right)(x-6).$ 
Use $f$ and $g$ to demonstrate the Constant-Difference Theorem.
::: 

::: {.solution } 
The functions $f$ and $g$ are polynomial functions so they are continuous and differentiable for all real numbers. 
Also, 
$$
f'(x)=3(x-2)^2=3x^2-12x+4=(2x)(x-6)+\left(x^2+12\right)=g'(x)
$$
for all real numbers. 
By the Constant Difference Theorem, we have $f(x)=g(x)+k$ for some real number $k.$ 
::: 

The following theorem is a partial converse to the statement that the derivative of a constant is 0.

::: {#thm- } [Zero-Derivative Theorem]
Let $f$ be a function that is continuous on $[a,b]$ and differentiable on $(a,b).$ 
If $f'(c)=0$ for all $c$ in $(a,b)$ then $f$ is constant on $[a,b].$
::: 

::: {.proof }
If $x_1$ and $x_2$ are different points in $[a,b]$ then by the Mean Value Theorem there exists a $c$ in $\left(x_1,x_2\right)$
such that
$$
f'(c)=\frac{f\left(x_2\right)-f\left(x_1\right)}{x_2-x_1}.
$$
By hypothesis $f'(c)=0$ and so $f\left(x_2\right)-f\left(x_1\right)=0.$ 
Since $x_1$ and $x_2$ were chosen arbitrarily, $f$ is a constant function on $[a,b].$ 
::: 

::: {#exm- }  
Consider $f(x)=\left\{
\begin{array}{ll}
 1 & x\geq  0 \\
 -1 & x<0
\end{array}
\right..$ 
Notice that $f'(x)=0$ for all $x$ in the domain, but $f$ is not a constant. 
Does this example contradict the Zero-Derivative Theorem? 
::: 

::: {.solution } 
No it does not, rather it shows that the assumptions of the zero-derivative theorem are necessary. 
::: 


## Exercises

::: {#exr- } 
Find an antiderivative for the following sets of functions $f(x)$, $g(x)$, and $h(x)$. Write out an equation using an indefinite integral and each of these functions.

- $f(x)=2x,$ $g(x)=x^2,$ and $h(x)=x^2-2x+1$
- $f(x)=-3x^{-4},$ $g(x)=x^{-4},$ and $h(x)=x^{-4}+2x+3$ 
- $f(x)=\frac{-2}{x^3},$ $g(x)=\frac{1}{2 x^3}$ and $h(x)=x^3-\frac{1}{x^3}$ 
- $f(x)=\frac{2}{3}x^{-1/3},$ $g(x)=\frac{1}{3}x^{-2/3}$ and $h(x)=\frac{-1}{3}x^{-4/3}$ 
-    
$f(x)=\frac{1}{3x},$ $g(x)=\frac{2}{5x},$ and $h(x)=1+\frac{4}{3x}-\frac{1}{x^2}$ 
- $f(x)=\sec ^2x,$ $g(x)=\frac{2}{3}\sec ^2\frac{x}{3}$ and $h(x)=-\sec ^2\frac{3x}{2}$ 
- $f(x)=e^{-2x}$ $g(x)=e^{4x/3},$ and $h(x)=e^{-x/5}.$ 
- $f(x)=3^x,$ $g(x)=2^{-x},$ and $h(x)=\left(\frac{5}{3}\right)^x.$ 
- $f(x)=x-\left(\frac{1}{2}\right)^x$ $g(x)=x^2+2^x,$ and $h(x)=\pi ^x-x^{-1}.$ 
::: 



