---
pagetitle: "Integral Test and P-Series - Exploring Calculus"
---
# Integral Test and P-Series

We motivate and discuss the Integral Test for convergence of an infinite series. We demonstrate how the convergence (or divergence) of a $p$-series can be determined using the Integral Test.


## The Integral Test

Recall that the Harmonic series 
\begin{equation}
\label{harmonicseries}
\sum_{n=1}^\infty \frac{1}{n}
= \frac{1}{1}+  \frac{1}{2}  + \frac{1}{3} + \frac{1}{4} + \cdots 
\end{equation}
diverges. 
What about the following series? 
\begin{equation}
\label{ptwoseries}
\sum_{n=1}^\infty \frac{1}{n^2}
= \frac{1}{1^2}+  \frac{1}{2^2}  + \frac{1}{3^2} + \frac{1}{4^2} + \cdots 
\end{equation}
The Integral Test compares an infinite series to an improper integral in order to determine convergence or divergence.
For example, to determine the convergence or divergence of 
\eqref{ptwoseries} we will determine the convergence or divergence of 
\begin{equation}
\label{ptwoint}
\int_{1}^\infty \frac{1}{x^2}\, dx.
\end{equation}
To do so, let $f(x)=1/x^2$ and consider that \eqref{ptwoint} represents the area under the graph of $f$ from $[1,+\infty)$. 
Thus we find that 
\begin{align*}
\int_{1}^\infty \frac{1}{x^2}\, dx 
= \lim_{b\to +\infty} \left. - \frac{1}{x}\right|_1^b 
= \lim_{b\to +\infty} \left(-\frac{1}{b} + 1\right) 
= 1.
\end{align*}
Consider the following figure.
Notice that the sum of the areas of the rectangles under the graph of $f(x)=1/x^2$ is less than the area under the graph.
Therefore, we have
\begin{align*}
s_n & = \frac{1}{1^2}+  \frac{1}{2^2}  + \frac{1}{3^2} + \frac{1}{4^2} + \cdots +\frac{1}{n^2} \\
& = f(1) + f(2) + f(3) + f(4) + \cdots + f(n) \\
& < f(1) + \int_1^\infty \frac{1}{x^2} \, dx \\
& =1 + 1 = 2. 
\end{align*}
This show that the sequence of partial sums of $\sum_{n=1}^\infty \frac{1}{n^2}$ are bounded above and the series converges. 
In fact it is well-known that 
\begin{equation}
\sum_{n=1}^\infty \frac{1}{n^2} = \frac{\pi^2}{6}
\end{equation}
as was famously proven by Euler. 
Our argument here, for the convergence of $\sum_{n=1}^\infty \frac{1}{n^2}$ relies heavily on the fact that $f(x)=1/x^2$ is a continuous, positive, and decreasing function on $[1,\infty)$.

::: {#thm- } \label{Integral Test}
Suppose that $f$ is a continuous, positive, and decreasing function on $[1,\infty)$. 
If $f(n)=a_n$, for $n\geq 1$, then 
$$
\sum_{n=1}^\infty a_n 
\qquad \text{and}\qquad
\int_1^\infty f(x) \, dx
$$
either both converge or both diverge.
::: 

::: {#exm- } 
Determine if the series $\ds\sum_{n=1}^\infty\frac{8\tan^{-1}n}{1+n^2}$ converges or diverges. 
::: 

::: {.solution }
Let
$$
f(x)= \frac{8\tan^{-1}x}{1+x^2}
$$ 
and notice that $f$ is a continuous, positive, and decreasing function on $[1,\infty)$. 
Using $u= tan^{-1} x$ we see that the improper integral converges 
\begin{align*}
\int_{1}^\infty \frac{8\tan^{-1}x}{1+x^2}\, dx 
& = \int_{\pi/4}^{\pi/2} 8 u \, du 
= 4\left(\frac{\pi^2}{4}-\frac{\pi^2}{16}\right)
= \frac{3\pi^2}{4}.
\end{align*}
Therefore, the series converges by the Integral Test. 
::: 

::: {#exm- } 
Determine if the series $\ds\sum_{n=1}^\infty\frac{8 n}{1+n^2}$ converges or diverges. 
::: 

::: {.solution }
Let
$$
f(x)= \frac{8x}{1+x^2}
$$ 
and notice that $f$ is a continuous, positive, and decreasing function on $[1,\infty)$. 
Using $u= 1+x^2$ we see that the improper integral diverges 
\begin{align*}
\int_{1}^\infty \frac{8 x}{1+x^2} \, dx 
& = 4 \int_{2}^{+\infty} \frac{1}{u} \, du 
= 4 \lim_{b \to \infty} \left.\ln u\right|_2^b
= +\infty.
\end{align*}
Therefore, the series diverges by the Integral Test. 
::: 




## $p$-Series

::: {#def- } 
A \index{$p$-series} **$p$-series**  is an infinite series of the form
$$
\sum_{n=1}^\infty \frac{1}{n^p}
$$
where $p$ is a constant. 
::: 

What is the difference between a geometric series and a $p$-series?
In a geometric series the exponent is a variable, i.e $\sum (1/2)^n$ is a geometric series. 
In a $p$-series the variable is in the base, i.e $\sum (1/n)^2$ is a $p$-series.

::: {#exm- } 
Let $p>1$ be a real number. 
Determine if the series $\ds\sum_{n=1}^\infty\frac{1}{n^p}$ converges or diverges. 
::: 

::: {.solution }
Let $f(x)= 1/x^p$  and notice that $f$ is a continuous, positive, and decreasing function on $[1,\infty)$. 
We see that the improper integral converges 
\begin{align*}
\int_{1}^\infty \frac{1}{x^p} \, dx 
& = \lim_{b\to +\infty}\left. \frac{x^{1-p}}{1-p} \right|_{1}^b
= \lim_{b\to +\infty}\left(\frac{1}{1-p}(b^{1-p}-1)\right)
= \frac{1}{1-p}.
\end{align*}
Therefore, the series converges by the Integral Test. 
::: 

::: {#exm- } 
Let $p\leq1$ be a real number. 
Determine if the series $\ds\sum_{n=1}^\infty\frac{1}{n^p}$ converges or diverges. 
::: 

::: {.solution }
If $p=1$, we have the harmonic series which diverges, and in fact 
$$
\int_{1}^\infty \frac{1}{x} \, dx 
$$ 
diverges also. 
Now assume that $p<1$. 
Again we let $f(x)= 1/x^p$ and notice that $f$ is a continuous, positive, and decreasing function on $[1,\infty)$. 
We see that the improper integral diverges 
\begin{align*}
\int_{1}^\infty \frac{1}{x^p} \, dx 
& = \lim_{b\to +\infty}\left. \frac{x^{1-p}}{1-p} \right|_{1}^b
= \lim_{b\to +\infty}\left(\frac{1}{1-p}(b^{1-p}-1)\right)
= +\infty.
\end{align*}
Therefore, the series diverges by the Integral Test. 
::: 

Combining the two previous examples together we have the following theorem. 


::: {#thm- } 
The $p$-series $\ds\sum_{n=1}^\infty \frac{1}{n^p}$ converges if $p>1$ and diverges if $p\leq 1$.
::: 

Unfortunately, there is no theorem to give us the sum of a $p$-series 



## Exercises

::: {#exr- } 
Use the Integral Test to determine whether the series diverges or converges.  
\begin{multicols}{3}
 - $\ds\sum_{n=1}^\infty \frac{1}{n^2+1}$
- $\ds\sum_{n=1}^\infty \frac{\ln n}{n}$
- $\ds\sum_{n=1}^\infty \frac{n+2}{n+1}$
 
 
::: 


::: {#exr- } 
Determine whether the series diverges or converges.  
\begin{multicols}{3}
 - $\ds\sum_{n=1}^\infty \frac{1}{n^2}$
- $\ds\sum_{n=1}^\infty \frac{1}{10^n}$
- $\ds\sum_{n=1}^\infty \frac{3}{\sqrt{n}}$
- $\ds\sum_{n=1}^\infty \frac{1}{\sqrt{n}}$
- $\ds\sum_{n=1}^\infty n^{-1.001}$
- $\ds\sum_{n=1}^\infty \frac{3n+2}{n(n+1)}$
- $\ds\sum_{n=1}^\infty \frac{n^2}{e^n}$
- $\ds\sum_{n=2}^\infty \frac{\ln n}{n}$
- $\ds\sum_{n=3}^\infty \frac{(1/n)}{(\ln n) \sqrt{\ln^2 n-1}}$
- $\ds\sum_{n=1}^\infty \frac{1}{n(1+\ln^2 n)}$
- $\ds\sum_{n=1}^\infty \frac{n}{n^4+1}$
- $\ds\sum_{n=1}^\infty\frac{1}{n^3 +n}$
 
 
::: 


::: {#exr- } 
Are there any values of $x$ for which $\ds\sum_{n=1}^\infty (1/ (nx))$ converges? 
::: 

::: {#exr- } 
Explain why the Integral Test does not apply to the series 
$$
\sum_{n=1} \frac{(-1)^n}{n}.
$$
::: 

::: {#exr- } 
Find the values of $p$ for which the series is convergent.
\begin{multicols}{3}
 - $\ds\sum_{n=2}^\infty \frac{1}{n (\ln n)^p}$
- $\ds\sum_{n=1}^\infty \frac{\ln n}{n^p}$
- $\ds\sum_{n=1}^\infty n (1+n^2)^p$
 
 
::: 


::: {#exr- } 
Find the value(s) of $a$ for which the series converges. 
Justify your answer. 
 
 - $\ds\sum_{n=1}^\infty \left(\frac{a}{n} -\frac{1}{n+1}\right)$
- $\ds\sum_{n=1}^\infty \left(\frac{a}{n+1} - \frac{1}{n+2}\right)$
 
 
::: 


::: {#exr- } 
Use the Integral Test to determine the convergence or divergence of the $p$-series.
\begin{multicols}{3}
 - $\ds\sum_{n=1}^\infty \frac{1}{n^{1/2}}$
- $\ds\sum_{n=1}^\infty \frac{1}{n^5}$
- $\ds\sum_{n=1}^\infty \frac{1}{\sqrt[5]{n}}$
- $\ds\sum_{n=3}^\infty \frac{1}{(n-2)^4}$
- $\ds\sum_{n=1}^\infty \frac{3}{n^{5/3}}$
- $\ds\sum_{n=1}^\infty \frac{1}{\sqrt[3]{27k^2}}$
 
 
::: 


