---
pagetitle: "Integration By Parts - Exploring Calculus"
---
# Integration By Parts


Here we motivate and elaborate on an integration technique known as integration by parts. We also demonstrate repeated application of this formula to evaluate a single integral. The reduction formula for integral powers of the cosine function and an example on its use is also presented.


## Introduction

There are many techniques of integration. 
Consider for example, the following three integrals.
\begin{equation}
\int\frac{4}{x^2+9}\, dx
\qquad 
\int\frac{4x}{x^2+9}\, dx
\qquad 
\int\frac{4x^2}{x^2+9}\, dx
\end{equation}

How would you integrate these?
The first uses the arctangent function, the second uses logarithms, and the third uses division. 
Can you integrate these three integrals? 


## The Integration by Parts Formula

Let $f$ and $g$ be differentiable functions.
Recall the product rules implies that $fg$ is a differentiable function and that 
\begin{equation}
[f(x) g(x) ]' = f'(x) g(x) + f(x) g'(x). 
\end{equation}
If we integrate both sides we obtain
\begin{equation}
\int [f(x) g(x) ]' dx 
= \int f'(x) g(x) \, dx + \int f(x) g'(x) \, dx. 
\end{equation}
It may happen that one of the integrals on the right-hand side is easier to integrate than the other.

::: {#thm- } \label{Integration by Parts}
Let $u=f(x)$ and $v=g(x)$ be differentiable functions. 
The differentials are $du= f'(x) \, dx$ and $dv= g'(x) \, dx$ and the formula
\begin{equation}
\int u \, dv = u v -\int v\, du 
\end{equation}
is called \index{integration by parts} **integration by parts** .
::: 

::: {#exm- } 
Find $\int x e^x \, dx.$
::: 

::: {.solution }
Let $u=x$ and $dv=e^x \, dx$. 
Then $du =dx$ and $v = e^x$, we have
\begin{equation}
\int x e^x \, dx= x e^x - \int e^x \, dx = x e^x - e^x +C
\end{equation}
where $C$ is an arbitrary constant. 
::: 

::: {#exm- } 
Find $\int x \sin x \, dx.$
::: 

::: {.solution }
Let $u=x$ and $dv=\sin x \, dx$. 
Then $du =dx$ and $v = -\cos x$, we have
\begin{equation}
\int x \sin x \, dx= - x \cos x - \int (-\cos x) \, dx = -x \cos x + \sin x +C
\end{equation}
where $C$ is an arbitrary constant. 
::: 

::: {#thm- } 
Let $f(x)$ and $g(x)$ be differentiable functions. 
Then 
\begin{equation}
\int_a^b f(x) g'(x)\, dx = \left. f(x)g(x) \right|_a^b - \int_a^b g(x) f'(x) \, dx.
\end{equation}
::: 

::: {#exm- } 
Find $\int_e^{e^2} \ln x \, dx.$
::: 

::: {.solution }
Let $u=\ln x$ and $dv=dx$.
Then $du =(1/x) dx$ and $v = x$, we have
\begin{equation}
\int_e^{e^2} \ln x \, dx = \left.x \ln x\right|_e^{e^2} - \int_e^{e^2} x\left(\frac{1}{x}\right)\, dx = \left. \left(x \ln x -x\right)\right|_e^{e^2} = e^2
\end{equation}
or approximately 7.3891. 
::: 



## Solving for Unknown Integral

::: {#exm- } 
Find $\int \sec^3 x\, dx$.
::: 

::: {.solution }
Let $u=\sec x$ and $dv=\sec^2 x$.
Then $du = \sec x\tan x\, dx$ and ${v=\int \sec^2 x\, dx}$. 
We have 
\begin{align*}
\int \sec^3 x \, dx
& = \sec x \tan x -\int \tan^2 x \sec x\, dx \\
& = \sec x \tan x -\int (\sec^2x-1)\sec x\, dx \\
& = \sec x \tan x -\int \sec^3x\, dx +\int \sec x\, dx \\
& = \sec x \tan x - \int \sec^3x\, dx + \ln \vert \sec x + \tan x\vert.
\end{align*}
Combining these together we have
\begin{equation}
2 \int \sec^3 x \, dx = \sec x \tan x + \ln \vert \sec x + \tan x\vert +C
\end{equation}
where $C$ is an arbitrary constant. 
Therefore we finally have
\begin{equation}
\int \sec^3 x \, dx = \frac{1}{2}\sec x \tan x +\ln \sqrt{\sec x + \tan x} +C
\end{equation}
as desired.
::: 


## Repeated Use of Integration by Parts


::: {#exm- } 
Find $\int e^x \cos x \, dx$.
::: 

::: {.solution }
Let $u=e^x$ and $dv=\cos x \, dx$.
Then $du=e^x$ and $v=\sin x$. 
We find that 
\begin{equation}
\int e^x \cos x \, dx = e^x \sin x -\int e^x \sin x\, dx.
\end{equation}
Let $u=e^x$ and $dv=\sin x \, dx$.
Then $du=e^x$ and $v=-\cos x$. 
We find that 
\begin{align*}
\int e^x \cos x \, dx 
& = e^x \sin x - \left( -e^x \cos x -\int e^x (-\cos x) \, dx \right)  \\
& = e^x \sin x +e^x \cos x -\int e^x \cos x \, dx.
\end{align*}
Combining these together we have
\begin{equation}
2\int e^x \cos x \, dx = e^2 \sin x +e^x \cos x + C
\end{equation}
or in other words
\begin{equation}
\int e^x \cos x\, dx = \frac{e^x \sin x +e^x \cos x}{2} +C
\end{equation}
where $C$ is an arbitrary constant. 
::: 




## Reduction Formulas

::: {#exm- } 
Demonstrate the repeated use of integration by parts by proving the reduction formula
\begin{equation}
\int \cos^nx \, dx 
= \frac{1}{n} \sin x \cos^{n-1} x+\frac{n-1}{n} \int \cos^{n-2} x \, dx
\end{equation}
where $n$ is an integer greater than 2.
::: 

::: {.solution }
Let $u=\cos^{n-1}x$ and $dv=\cos x \, dx$.
Then we have 
$$
du =(n-1)\cos^{n-2} x (-\sin x)\, dx
$$ 
and $v=\sin x$.
Therefore
\begin{align*}
\int \cos^n \, dx & 
= \cos^{n-1}\sin x +(n-1) \int \sin^2 x \cos^{n-2} x\, dx \\
& = \cos^{n-1} x \sin x+ (n-1)\int (1-\cos^2 x)\cos^{n-2} x \, dx \\
& = \cos^{n-1}\sin x +(n-1) \int\cos^{n-2} x \, dx -(n-1)\int \cos^n x\, dx
\end{align*}
Combining these together we have
\begin{equation}
n\int \cos^n x\, dx = \cos^{n-1}\sin x +(n-1)\int \cos^{n-2}x \, dx.
\end{equation}
The final result is 
\begin{equation}
\int \cos^nx \, dx 
= \frac{\sin x \cos^{n-1}x}{n} +\frac{n-1}{n} \int \cos^{n-2} x \, dx
\end{equation}
where $C$ is an arbitrary constant. 
::: 

::: {#exm- } 
Find $\int \cos ^5x\, dx$. 
::: 

::: {.solution }
We will use the reduction formula with $n=5$ and $n=3$.
We have 
\begin{align*}
\int\cos^5 \, dx & = \frac{\cos^4 \sin x}{5}+\frac{4}{5}\int \cos^3\, dx \\
& = \frac{\cos^4 \sin x}{5}+\frac{4}{5} 
\left( \frac{1}{3}\cos^2 \sin x +\frac{2}{3}\sin x \right) +C \\
& = \frac{1}{5}\cos^4 \sin x + \frac{4}{15} 
\cos^2 \sin x + \frac{8}{15}\sin x +C
\end{align*}
where $C$ is an arbitrary constant. 
::: 


## Exercises


::: {#exr- } 
Evaluate the following integrals.
\begin{multicols}{3}
 - $\int x\sin 3x \, dx$
- $\int (\ln x)^2 \, dx$
- $\int 2x e^{3x}\, dx$
- $\int \tan^{-1} x \, dx$
- $\int \cos^{-1}(2x)\, dx$
- $\int x\sec^2 x \, dx$
- $\int \frac{xe^x}{(x+1)^2} \, dx$
- $\int x\sin x\cos x\, dx$
- $\int x^2 e^{4x}\, dx$
 
 
::: 


::: {#exr- } 
Evaluate the following definite integrals.
\begin{multicols}{3}
 - $\int_0^1 x e^{-5x}\, dx $
- $\int_0^{\ln 2} \ln 2x \,dx$
- $\int_1^{e^2} x^2 \ln x \, dx$
- $\int_{0}^{1/\sqrt{2}} y \tan^{-1}\, dy$
- $\int_0^{\pi/8} x \sec^2 2x \, dx$
- $\int_0^1 x \arcsin^2 \, dx$
 
 
::: 


::: {#exr- } 
Evaluate the integral by making a $u$-substitution and then integration by parts. 
\begin{multicols}{3}
 - $\int e^{\sqrt{x}}\, dx$
- $\int x^5 e^{x^2}\, dx$
- $\int \cos \sqrt{x} \, dx$
 
 
::: 

::: {#exr- } 
Use the reduction formulas to evaluate the integral. 
\begin{multicols}{4}
 - $\int \sec^4 x \, dx$
- $\int \tan^4x \, dx$
- $\int^{\pi/2}_0 \sin^5 x \, dx$
- $\int \cos^5 x \, dx$
 
 
::: 

::: {#exr- } 
Find the area of the region between $y=x\sin x$ and $y=x$ for $0\leq x \leq \pi/2$. 
::: 


::: {#exr- } 
Find the area of the region under the graph of $y=(\ln x)^2$ n the interval $[1,e]$. 
::: 

::: {#exr- } 
Find the area of the region under the graph of $y=\frac{xe^x}{(1+x)^2}$ on the interval $[0,1]$. 
::: 

::: {#exr- } 
Given the region bounded by the graph of $y=x\cos x$, $y=0$, $x=-1$, and $x=1$. 
Find the area of the region. 
Find the volume of the solid generated by revolving abut the $x$-axis. 
::: 

::: {#exr- } 
The region bounded by the graph pf $y=e^{x/2}\cos x$, $x=0$, $y=0$, and $x=\pi/2$ is revolved about eh $x$-axis.
Find the volume if the solid generated. 
::: 


::: {#exr- } 
If $f(0)=g(0)$ and $f''$ and $g''$ are continuous, prove that 
\begin{equation}
\int_0^a f(x)g''(x) \, dx = f(a) g'(a) -f'(a) g(a) + \int_0^a f''(x)g(x) \, dx.
\end{equation}
::: 


::: {#exr- } 
The region bounded by the graphs of $y=\sin x$, $y=0$, $x=0$, and $x=\pi$ is revolved about the line $x=-1$.
Find the volume if the solid generated. 
::: 

::: {#exr- } 
Suppose that $f(1)=2$, $f(4)=7$, $f'(1)=5$, $f'(4)=3$, and $f''$ is continuous.
Find the value of $\int_1^4 x f''(x) \, dx$. 
::: 

::: {#exr- } 
Use integration by parts to show that 
$$
\int f(x) \, dx = x f(x) -\int x f'(x)\, dx.
$$
::: 


::: {#exr- } 
Use the method of cylindrical shells to find the volume generated by rotating the region bounded by $y=e^{-x}$, $y=0$, $x=-1$, $x=0$, about $x=1$. 
::: 

::: {#exr- } 
Use integration by parts to establish the reduction formula 
 - $\int \sin^n x \, dx = -\frac{1}{n} \cos x \sin^{n-1} x+\frac{n-1}{n} \int \sin^{n-2} x \, dx$
- $\int x^n \sin x \, dx = -x^n \cos x + n \int x^{n-1} \cos x \, dx$
- $\int x^n \cos x \, dx = -x^n \sin x + n \int x^{n-1} \sin x \, dx$
 
::: 


