---
pagetitle: "Numerical Integration - Exploring Calculus"
---
# Numerical Integration


## Left and Right Endpoints

The left and right rules are the most straight-forward to learn. 
They can be applied with either uniform width subintervals or varying width subintervals.
They consist of using a Riemann sum where the subinterval representatives are chosen as the left-endpoints or the right-endpoints, respectively.


::: {#thm- } 
Let $f$ be a continuous function on $[a,b]$ and let 
$$
\mathcal{P}=\left\{a=x_0,x_1,\cdots,x_{k-1,}x_k,\cdots,x_n=b\right\}
$$ 
be a partition
of the interval $[a,b].$ 
Then the Riemann sum formed by using left-endpoints as the subinterval representatives $x_k{}^*$ is 
$$
\int_a^b f(x) \, dx \approx  \sum _{k=1}^n f\left(x_k{}^*\right)\Delta  x_k=\sum _{k=1}^n f\left(x_{k-1}\right)\Delta  x_k
$$ 
and the Riemann sum formed by using
right-endpoints as the subinterval representatives $x_k{}^*$ is 
$$
\int_a^b f(x) \, dx \approx  \sum _{k=1}^n f\left(x_k{}^*\right)\Delta  x_k=\sum
_{k=1}^n f\left(x_k\right)\Delta  x_k
$$ 
where in both cases $\Delta  x=x_k-x_{k-1}.$ 
The first formula is called the \index{left rule} **left rule** and the second formula the \index{right rule} **right rule**.
::: 


::: {#exm- } 
Consider $f(x)=e^{-x^2}$ on $[0,2]$ and let { }$\mathcal{P}=\left\{0,\frac{1}{2},1,\frac{3}{2},2\right\}$
be a partition of the interval $[0,2]$ (so $\Delta  x=\frac{1}{2}$). 
::: 

::: {.solution }
Then the Riemann sum formed by using left-endpoints as the subinterval representatives
$x_k{}^*$ is 
$$
\int_0^2 e^{-x^2} \, dx \approx \frac{1}{2}e^{-(0)^2}+\frac{1}{2}e^{-\left(\frac{1}{2}\right)^2}+\frac{1}{2}e^{-(1)^2}+\frac{1}{2}e^{-\left(\frac{3}{2}\right)^2}\approx
1.12604
$$
 
The Riemann sum formed by using right-endpoints as the subinterval representatives $x_k^*$ is 
$$
\int_0^2 e^{-x^2} \, dx \approx \frac{1}{2}e^{-\left(\frac{1}{2}\right)^2}+\frac{1}{2}e^{-(1)^2}+\frac{1}{2}e^{-\left(\frac{3}{2}\right)^2}+\frac{1}{2}e^{-(2)^2}\approx 0.635198.
$$ 
Consider that as $n$ increases then so does the estimation of the area. 
Note that a somewhat accurate estimation is $0.882081.$ 
However, because a fairly large number of rectangles are needed for a good approximation there are other common techniques which do not use rectangles.
::: 



## Midpoint Rule
The midpoint rule uses a Riemann sum where the subinterval representatives are the midpoints of the subintervals. 
For some functions it may be easy to choose a partition that more closely approximates the definite integral using midpoints.


::: {#thm- } [Midpoint Rule]
Let $f$ be a continuous function on $[a,b]$ and let 
$$
\mathcal{P}=\left\{a=x_0,x_1,\cdots,x_{k-1,}x_k,\cdots,x_n=b\right\}
$$
be a partition of the interval $[a,b].$ 
Then the Riemann sum formed by using midpoints as the subinterval representatives $x_k{}^*$ is 
$$
\int_a^b f(x) \, dx \approx  \sum _{k=1}^n f\left(x_k{}^*\right)\Delta  x_k=\sum _{k=1}^n f\left(\frac{x_k+x_{k-1}}{2}\right)\Delta  x_k
$$ 
where $\Delta
 x_k=x_k-x_{k-1}.$
::: 


::: {#exm- } 
Consider $f(x)=e^{-x^2}$ on $[0,2]$ and let $\mathcal{P}=\left\{0,\frac{1}{2},1,\frac{3}{2},2\right\}$ be a partition of the interval $[0,2]$ (so $\Delta  x=\frac{1}{2}$). 
Use the midpoint rule.
::: 

::: {.solution }
Then the Riemann sum formed by using midpoints as the subinterval representatives
$x_k^*$ is 
$$
\int_0^2 e^{-x^2} \, dx \approx \frac{1}{2}e^{-\left(\frac{1}{4}\right)^2}+e^{-\left(\frac{3}{4}\right)^2}+\frac{1}{2}e^{-\left(\frac{5}{4}\right)^2}+\frac{1}{2}e^{-\left(\frac{7}{4}\right)^2}\approx
1.16768
$$
Consider that as $n$ increases then so does the estimation of the area. 
Note that a somewhat accurate estimation is $0.882081.$ 
However, because a fairly large number of rectangles are needed for a good approximation there are other common techniques which do not use rectangles. 
::: 



## Trapezoidal Rule
The trapezoidal rule uses trapezoids instead of rectangles to approximate the definite interval over a closed bounded interval. 
By using points on the graph of the function determined by a uniform width partition of the interval the upper boundary of the trapezoid is formed. 
Recall that the area of a trapezoid is one half the width times the sum of the two heights; and by using this formula we can add up the areas to approximate the
definite integral. 
Of course the more subintervals, (or said another way: the more trapezoids) the better accuracy of the estimation. 

Consider $y=-x^2+1$ on $[0,1]$ and say we want to find the area. 
We could use rectangles as in a Riemann sum; however from inspection of the following diagram it might seem more reasonable to use trapezoids:
The area is underestimated but not as much as using rectangles would (with the same partition).

::: {#thm- } [Trapezoidal Rule]
The trapezoidal rule estimates the definite integral of $f$ over $[a,b]$ using the formula 
$$
\int_a^b f(x) \, dx \approx \frac{1}{2}\left[f\left(x_0\right)+2f\left(x_1\right)+2f\left(x_2\right)+\cdots+2f\left(x_{n-1}\right)+f\left(x_n\right)\right]\Delta x
$$
where $x_k=a+k \Delta  x$ and $\Delta  x=\frac{b-a}{n}.$ 
The trapezoidal rule formula can be simplified as follows
\begin{align*}
& \int_a^b f(x) \, dx \approx \frac{1}{2}\left[f\left(x_0\right)+2f\left(x_1\right)+2f\left(x_2\right)+\cdots.+2f\left(x_{n-1}\right)+f\left(x_n\right)\right]\Delta x \\
& =\frac{1}{2}[f(a)+2f(a+\Delta  x)+2f(a+2\Delta  x)+ \cdots+2f(a+(n-1) \Delta  x)+f(b)]\frac{b-a}{n} \\
%& =\left(\frac{f(a)+f(b)}{2}\right)\left(\frac{b-a}{n}\right)+\left[f\left(a+\frac{b-a}{n}\right)+f\left(a+2\frac{b-a}{n}\right)+ \cdots+f\left(a+(n-1) \frac{b-a}{n}\right)\right]\frac{b-a}{n} \\
& =\left(\frac{f(a)+f(b)}{2}\right)\left(\frac{b-a}{n}\right)+\left(\frac{b-a}{n}\right)\sum _{k=1}^{n-1} f\left(a+k\frac{b-a}{n}\right)
\end{align*}
which is particularly nice if you want to program or pass a limit. 
::: 


::: {#exm- } 
Consider $f(x)=e^{-x^2}$ on $[0,2]$ and let { }$\mathcal{P}=\left\{0,\frac{1}{2},1,\frac{3}{2},2\right\}$ be a partition
of the interval $[0,2]$ (so $\Delta  x=\frac{1}{2}$). 
Then
$$
\int_0^2 e^{-x^2} \, dx \approx \left(\frac{e^{-0^2}+e^{-2^2}}{4}\right)+\frac{1}{2}\sum _{k=1}^3 e^{-\left(\frac{k}{2}\right)^2}\approx
0.880619
$$
which is a much better estimation than using rectangles with the same partition.
::: 

::: {#thm- } 
[Error in the Trapezoidal Rule] If $f$has a continuous second derivative on $[a,b],$ then the error $E_n$ in approximating 
$$
\int_a^b f(x) \, dx
$$ 
by the trapezoidal rule satisfies:
$$
\left|E_n\right|\leq  \frac{(b-a)^3}{12n^2}M
$$
where $M$ is the maximum value of $|f\text{''}(x)|$ on $[a,b].$
::: 



## Simpson's Rule

Instead of rectangles and trapezoids Simpson's rule uses parabolic arcs. 
The formula obtained for Simpson's rule requires using uniform width subintervals and an even number of them. 

Consider $y=-x^2+1$ on $[0,1]$ and say we want to find the area. 
We could use rectangles as in a Riemann sum; however many graphs have curvature as so maybe using strips with parabolic arc will yield better estimates with less work. 
That is instead if rectangles or trapezoids: let's use $\texttt{"}$strips$\texttt{"}$ with parabolic arcs.
If $\mathcal{P}=\left\{x_0, x_1,\cdots,x_n\right\}$ is a partition of $[a,b]$ with $x_0=a$ and $x_n=b$ and if we pass a parabolic arc
through the points, three at a time say, the points with $x$-coordinates $x_0, x_1, x_2$ then those with $x_2, x_{3,} x_4$ and so on. 
It can be shown that the area of the region under the parabolic curve $y=f(x)$ on the interval $\left[x_{2k-2},x_{2k}\right]$ has area given by
$$
\frac{1}{3}\left[f\left(x_{2k-2}\right)+4f\left(x_{2k-1}\right)+f\left(x_{2k}\right)\right]\Delta  x
$$
where $\Delta  x=\frac{b-a}{n}.$ 
Thus, to estimate $\int_a^b f(x) \, dx$ we can add up the strips as follows.



::: {#thm- } [Simpson's Rule]
Simpson's rule estimates the definite integral of $f$ over $[a,b]$ using the formula
\begin{align*}
& \int_a^b f(x) \, dx \approx \frac{1}{3}\left[f\left(x_0\right)+4f\left(x_1\right)+2f\left(x_2\right)+4f\left(x_3\right)+ \right. \\ 
& \qquad \qquad \qquad  \qquad  \qquad \left. 2f\left(x_4\right)+\cdots +4f\left(x_{n-1}\right)+f\left(x_n\right)\right]\Delta  x
\end{align*}
where $x_k=a+k \Delta  x,$ $\Delta  x=\frac{b-a}{n},$ and $n$ is an even integer. 
::: 


::: {#exm- } 
Consider $f(x)=e^{-x^2}$ on $[0,2]$ and let { }$\mathcal{P}=\left\{0,\frac{1}{2},1,\frac{3}{2},2\right\}$ be a partition
of the interval $[0,2]$ (so $\Delta  x=\frac{1}{2}$). 
$$
\quad \int_0^2 e^{-x^2} \, dx \approx \frac{1}{6}\left(e^{-0^2}+4e^{-\left(\frac{1}{2}\right)^2}+2e^{-(1)^2}+4e^{-\left(\frac{3}{2}\right)^2}+e^{-(2)^2}\right)\approx 0.881812
$$
which is a much better estimation than using rectangles with the same partition.
::: 


::: {#thm- } [Error in the Simpson Rule] 
If $f$has a continuous fourth derivative on $[a,b],$ then the error $E_n$ (n even) in approximating 
$$
\int_a^b f(x) \, dx
$$ 
by the Simpson rule satisfies:
$$
\left|E_n\right|\leq  \frac{(b-a)^5}{180n^4}M
$$
where $M$ is the maximum value of $\left|f^{(4)}(x)\right|$ on $[a,b].$
::: 


::: {#exm- } 
Consider $f(x)=e^{-x^2}$ on $[0,2]$ and let $\mathcal{P}=\left\{0,\frac{1}{2},1,\frac{3}{2},2\right\}$
be a partition of the interval $[0,2]$. 
Find the error in the approximation 
$$
\int_0^2 e^{-x^2} \, dx \approx \frac{1}{6}\left(e^{-0^2}+4e^{-\left(\frac{1}{2}\right)^2}+2e^{-(1)^2}+4e^{-\left(\frac{3}{2}\right)^2}+e^{-(2)^2}\right)\approx 0.881812
$$
::: 

::: {.solution }
We compute 
 
- $f'(x)=-2 e^{-x^2} x$, 
- $f'' (x)=-2 e^{-x^2}+4 e^{-x^2} x^2,$
- $f'''(x)=12 e^{-x^2} x-8 e^{-x^2} x^3$
- $f^{(4)}(x)=12 e^{-x^2}-48 e^{-x^2} x^2+16 e^{-x^2} x^4$
  
We plot the fourth derivative obtaining: and so there is a maximum at $x=0.$ 
We obtain $f^{(4)}(0)=12 =M.$ 
Therefore, the error is less than $\frac{32}{1804^4}(12)=0.00833333.$
::: 



