---
pagetitle: "Power Series - Exploring Calculus"
---
# Power Series


We introduce power series and discuss convergence of power series. 
Finding the interval of convergence and finding the radius of convergence is explained through several examples. 
We also discuss term-by-term differentiation and integration power series.  

## What are Power Series?

We begin with the definition of power series. 

::: {#def- } 
Let $x$ be a variable. 
An infinite series of the form 
$$
\sum_{n=0}^\infty a_n x^n = a_0 + a_1 x +a_2 x^2  +\cdots + a_n x^n + \cdots 
$$
is called a \index{power series} **power series** .
More generally, an infinite series of the form 
$$
\sum_{n=0}^\infty a_n (x-c)^n =a_0 + a_1 (x-c) +a_2 (x-c)^2  +\cdots + a_n (x-c)^n + \cdots 
$$
is called a \index{power series centered at} **power series centered at**  $c.$
::: 

For example, 
$$
\sum_{n=0}^\infty \frac{(x-1)^n}{n+1} 
= 1 + \frac{x-1}{2} + \frac{(x-1)^2}{3} + \frac{(x-1)^3}{4} + \cdots
$$
is a power series in $x-1.$ 
The series 
$$
\sum_{n=0}^\infty \frac{(-1)^n(x+4)^n}{n!} 
= 1-(x+4) + \frac{(x+4)^2}{2!} - \frac{(x+4)^3}{3!} + \cdots
$$
is a power series centered $-4.$
More generally, the Taylor series 
$$
\sum_{n=0}^\infty \frac{f^{(n)}(x_0)}{n!} (x-x_0)^n
$$
is a power series in $x-x_0.$

For each $x$, the power series is an infinite series of constants that we can test for convergence or divergence. 
A power series may diverge for some values of $x$ and converge for other values. 
We emphasize that a power series is a function
$$
f(x) = a_0 + a_1 x +a_2 x^2  +\cdots + a_n x^n + \cdots 
$$
whose domain is the set of all $x$ for which the power series converges. 


## Convergence of Power Series

The set of values of $x$ for which the series is convergent is always an interval, either a finite interval, the infinite interval $(-\infty, +\infty)$, or a collapsed interval such as $\{0\}.$ 
The following theorem guarantees this is always the case. 

::: {#thm- } 
For any power series centered at $c$
$$
\sum_{n=0}^\infty a_n (x-c)^n
$$ 
there are only three possibilities:
 

- The series converges only when $x=c.$


\item The series converges for all $x.$
- There is a positive real number $R$ such that the power series converges whenever ${|x-c|<R}$ and diverges whenever $|x-c|>R.$ 
  
The number $R$ is called the \index{radius of convergence} **radius of convergence** . 
::: 

In other words every power series has a radius of convergence, where in case 1 the radius of convergence is 0, in case 2 the radius of convergence is $\infty$, and in case 3 the radius of convergence is $R.$
\par
In case three, there are four possibilities that may occur for a given series to converge.
The \index{interval of convergence} **interval of convergence**  of a series can be any of the possibilities:
$$
(c-R, c+R) \qquad
(c-R, c+R] \qquad
[c-R, c+R) \qquad
[c-R, c+R] 
$$
In this case we have $|x-c|<R$ which means that 
$$
c-R < x < c+R.
$$ 
However, the endpoints of this interval must be check individually, that is, if $x=c\pm R$ the series might converge at one or both endpoints or it might diverge at both endpoints. 

::: {#exm- } 
For which values of $x$ is the power series 
$$
\sum_{n=0}^\infty n! \, x^n
$$ 
convergent?  
::: 

::: {.solution }
Notice that the series converges when $x=0.$ 
Assume $x\neq 0.$ Let $a_n =n!x^n$ and we use the Ratio Test. 
We have 
\begin{align*}
\lim_{n\to \infty} \left\vert\frac{a_{n+1}}{a_n}\right\vert
=\lim_{n\to \infty} \left\vert\frac{(n+1)! \, x^{n+1}}{n! \, x^n}\right\vert
=\lim_{n\to \infty} (n+1) |x| =\infty.
\end{align*}
By the Ratio Test the series diverges whenever $x\neq 0.$ 
::: 

::: {#exm- } 
Find the interval of convergence and radius of convergence for the power series 
$$
\sum_{n=0}^\infty\frac{x^n}{n!}.
$$
::: 

::: {.solution }
We apply the Ratio Test for absolute convergence.
We have
\begin{align*}
\rho 
& = \lim_{n\to +\infty} \left\vert\frac{a_{n+1}}{a_n}\right\vert
= \lim_{n\to +\infty} \left\vert\frac{x^{n+1}}{(n+1)!}\frac{n!}{x^n}\right\vert \\
& = \lim_{n\to +\infty} \left\vert\frac{x}{n+1}\right\vert
= 0
\end{align*}
By the Ratio Test for absolute convergence, the series converges absolutely for all values of $x$ since $\rho<1.$
The interval of convergence is $(-\infty, +\infty)$ and the radius of convergence is $R=+\infty.$ 
::: 

::: {#exm- } 
Find the interval of convergence and radius of convergence for the power series 
$$
\sum_{n=0}^\infty \frac{(-1)^n x^n}{3^n (n+1)}.
$$
::: 

::: {.solution }
We apply the Ratio Test for absolute convergence.
We have
\begin{align*}
\rho 
& = \lim_{n\to +\infty} \left\vert\frac{a_{n+1}}{a_n}\right\vert
= \lim_{n\to +\infty} \left\vert\frac{x^{n+1}}{3^{n+1}(n+2)}\frac{3^n(n+1)}{x^n}\right\vert \\
& = \lim_{n\to +\infty} \frac{|x|}{3}\frac{k+1}{k+2}
= \frac{|x|}{3}\lim_{n\to +\infty} \frac{k+1}{k+2}
= \frac{|x|}{3}
\end{align*}
By the Ratio Test for absolute convergence, the series converges absolutely if $|x|<3$ and diverges if $|x|>3.$ The Ratio Test is inconclusive whenever $|x|=3.$ 
These cases must be considering separately. 
If $x=3$, then the series is a conditionally convergent harmonic series:
$$
\sum_{n=0}^\infty \frac{(-1)^n}{n+1}.
$$
If $x=-3$, then the series is a divergent harmonic series:
$$
\sum_{n=0}^\infty \frac{1}{n+1}.
$$
Thus, the interval of convergence for the given power series is $(-3, 3]$ and the radius of convergence is $R=3.$ 
::: 

::: {#exm- } 
Find the interval of convergence and radius of convergence for the power series 
$$
\sum_{n=1}^\infty \frac{(x-2)^n}{\sqrt{n}}.
$$
::: 

::: {.solution }
We apply the Ratio Test for absolute convergence.
We have
\begin{align*}
\rho 
& = \lim_{n\to +\infty} \left\vert\frac{a_{n+1}}{a_n}\right\vert
= \lim_{n\to +\infty} \left\vert\frac{(x-2)^{n+1}}{\sqrt{n+1}}\frac{\sqrt{n}}{(x-2)^n}\right\vert \\
& = |x-2|\lim_{n\to +\infty} \sqrt{\frac{k}{k+1}}
 = |x-2|
\end{align*}
By the Ratio Test for absolute convergence, the series converges absolutely if $|x-2|<1$ and diverges if $|x-2|>1.$ 
The Ratio Test is inconclusive whenever $|x-2|=1.$ 
These cases must be considering separately. 
If $x=3$, then the series is a divergent $p$-series with $p=1/2$: 
$$
\sum_{n=1}^\infty \frac{1}{\sqrt{n}}.
$$
If $x=1$, then the series is a convergent alternating series:
$$
\sum_{n=1}^\infty \frac{(-1)^n}{\sqrt{n}}.
$$
Thus, the interval of convergence for the given power series is $[1, 3)$ and the radius of convergence is $R=1.$ 
::: 


## Differentiating and Integrating Power Series

In advanced calculus it is proven that a power series can be differentiated (integrated) term by term at each interior point of its interval of convergence. 

::: {#thm- } 
Suppose that the power series $\sum a_n (x-c)^n$ converges for $|x-c|<R$ and defines a function $f$ on that interval. 
\label{Differentiation and Integration of Power Series}
 - Then $f$ is differentiable for $|x-c|<R$, and $f'$ is found by differentiating the power series for $f$ term by term; that is 
$$
f'(x) = \sum n a_n (x-c)^{n-1}. 
$$
for $|x-c|<R.$
- The integral of $f$ is found by integrating the power series for $f$ term by term; that is 
$$
\int f(x)\, dx =  \sum a_n \frac{(x-c)^{n+1}}{n+1} +C. 
$$
for $|x-c|<R$, where $C$ is an arbitrary constant. 
 
::: 

This theorem makes no conclusion about convergence of the differentiated (integrated) series to at the endpoints.

::: {#exm- } 
Consider the power series 
$$
f(x) = \frac{1}{1-x} 
= \sum_{n=0}^\infty x^n 
= 1+x +x^2 +\cdots + x^n + \cdots, \quad 
|x|<1.
$$  
 - Differentiate this power series term by term to find the power series for $f'$ and identify the function it represents.
- Integrate this power series term by term and identify the function it represents.
 
::: 

::: {.solution }
Differentiating this power series we find that
\begin{align*}
f'(x) 
& = 1 + 2 x +\cdots + n x^{n-1} + \cdots \\
& = \sum_{n=0}^\infty n x^n. 
\end{align*}
Therefore, whenever $|x|<1$ we have
$$
f'(x)  
=\frac{1}{(1-x)^2} 
= \sum_{n=0}^\infty (n+1) x^n.
$$
as desired. 
In this case, substituting $x=\pm 1$ into the power series for $f'$ reveals that the series diverges at both endpoints. 
\par
Integrating this power series we find that
\begin{align*}
\int f(x) \, dx
& = x + \frac{x^2}{2} + \cdots + \frac{x^{n}}{n} + \cdots \\
& = \sum_{n=0}^\infty (n+1) x^n 
\end{align*}
Therefore, whenever $|x|<1$ we have
$$
\int f(x) \, dx
=  - \ln |1-x| 
= \sum_{n=0}^\infty \frac{x^n}{n}.
$$
as desired. 
Multiplying both sides by 1 we obtain a power series representation for $\ln(1-x)$:
$$
\ln(1-x) = -\sum_{n=0}^\infty \frac{x^n}{n}.
$$
When $x=1$ the series is divergent by comparing to the divergent harmonic series.
When $x=-1$ the series converges to $\ln 2.$ 
::: 



## Functions Represented by Power Series

::: {#exm- } 
Find a power series representation for $\tan^{-1}(x)$ by integrating a power series representation of $f(x)=1/(1+x^2).$ 
::: 

::: {.solution }
The series 
$$
f(t) = \frac{1}{1+t^2}  = 1 - t^2 + t^4 - t^6 + \cdots 
$$
converges on the open interval $-1 < t < 1.$
Therefore, 
\begin{align*}
\tan^{-1} x 
& = \int_0^x \frac{1}{1+t^2} \, dt 
= \left. t - \frac{t^3}{3} +\frac{t^5}{5} - \frac{t^7}{7} + \cdots \ \right|_0^x \\
& = x - \frac{x^3}{3} +\frac{x^5}{5} - \frac{x^7}{7} + \cdots \\
& = \sum_{n=0}^\infty  \frac{(-1)^n x^{2n+1}}{2n+1} 
\end{align*}
for $-1 < x < 1.$ 
::: 

::: {#exm- } 
Find a power series representation for $\ln(1+x)$ by integrating a power series representation of $f(x)=1/(1+x).$ 
::: 

::: {.solution }
The series 
$$
f(t) = \frac{1}{1+t}  = 1 - t + t^2 -t^3 + \cdots 
$$
converges on the open interval $-1 < t < 1.$
Therefore, 
\begin{align*}
\ln(1+x) 
& = \int_0^x \frac{1}{1+t} \, dt 
= \left. t - \frac{t^2}{2} +\frac{t^3}{3} -\frac{t^4}{4} + \cdots \ \right|_0^x \\
& = x - \frac{x^2}{2} +\frac{x^3}{3} -\frac{x^4}{4} + \cdots \\
& = \sum_{n=0}^\infty  \frac{(-1)^{n-1} x^{n-1}}{n} 
\end{align*}
for $-1 < x < 1.$ 
::: 


## Combining Power Series

A power series defines a function in its interval of convergence. 
When power series are combined algebraically, new functions are defined. 

::: {#thm- } \label{Combining Power Series}
Suppose that $\sum a_n x^n$ and $\sum b_n x^n$ converge to $f(x)$ and $g(x)$, respectively, on an interval $I.$
 - The power series $\sum (a_n \pm b_n) x^n$ converges to $f(x)\pm g(x)$ on $I.$ 
- The power series $\sum a_n x^{n+m}$ converges to $f(x)x^m$ for all $x\neq 0$ in $I$ provided that $m$ is an integer such that $n+m\geq 0$ for all terms of the power series $\sum a_n x^{n+m}.$ If $x=0$, the series converges to $\lim_{x\to 0} x^m f(x).$ 
- If $h(x) = b x^m$, where $m$ is a positive integer and $b$ is a nonzero real number, the power series $\sum a_n (h(x))^n$ converges to the composite function $f(h(x))$, for all $x$ such that $h(x)$ is in $I.$ 
 
::: 

::: {#exm- } 
Consider the geometric series 
$$
\frac{1}{1-x} 
= \sum_{n=0}^\infty x^n 
= 1+x +x^2 +\cdots + x^n + \cdots, \quad 
|x|<1
$$  
find the power series and interval of convergence for the functions
$$
f(x)= \frac{x^5}{1-x} \qquad \text{and} \qquad g(x)=\frac{1}{1-2x}.
$$
::: 

::: {.solution }
We notice that 
$$
f(x) = \frac{x^5}{1-x} = x^5 (1+x+x^2 +x^3 +\cdots ) = \sum_{n=0}^\infty x^{n+5}.
$$
This series has a ratio $r=x$ and converges when $|r|=|x|<1.$
The interval of convergence is $|x| < 1.$ 
For the function $g$, we use $2x$ for $x$ in the power series for $1/(1-x)$ and find that
$$
g(x)=\frac{1}{1-2x} = 1+(2x)+(2x)^2+ \cdots = \sum_{n=0}^\infty (2x)^{n}.
$$
This geometric series has a ratio $r=2x$ and converges if $|r|=|2x|<1.$ 
In other words, the interval of convergence is $|x|<1/2.$ 
::: 

::: {#exm- } 
Find a power series for $f(x)=\frac{3x-1}{x^2-1}.$
::: 

::: {.solution }
Using partial fraction we have
$$
\frac{3x-1}{x^2-1} = \frac{2}{x+1} +\frac{1}{x-1}.
$$
By adding the two geometric power series 
$$
\frac{2}{x+1} = \frac{2}{1-(-x)} = \sum_{n=0}^\infty 2(-1)^n x^n, \quad |x|<1
$$
and
$$
\frac{1}{x-1} = \frac{-1}{1-x} = - \sum_{n=0}^\infty x^n, \quad |x|<1
$$
we obtain
$$
\frac{3x-1}{x^2-1} 
= \sum_{n=0}^\infty 2(-1)^n x^n - \sum_{n=0}^\infty x^n
= \sum_{n=0}^\infty (2(-1)^n-1)x^n
$$
with an interval of convergence of $(-1,1).$ 
::: 



## Exercises

::: {#exr- } 
Find the radius and interval of convergence for each power series. 
For what values of $x$ does the series converge absolutely or conditionally?
\begin{multicols}{3}
 - $\ds\sum_{n=1}^\infty \frac{(3x-2)^n}{n}$
- $\ds\sum_{n=1}^\infty (-1)^{n-1} n x^n$
- $\ds\sum_{n=1}^\infty \frac{(-1)^n(x+2)^n}{n}$
- $\ds\sum_{n=1}^\infty \frac{n! x^n}{(2n)!}$
- $\ds\sum_{n=0}^\infty \frac{n x^n}{4^n (n^2+1)}$
- $\ds\sum_{n=1}^\infty \frac{(3x-1)^n}{n^3+n}$
- $\ds\sum_{n=1}^\infty \frac{(-1)^{n+1}(x+2)^n}{n 2^n}$
- $\ds\sum_{n=1}^\infty \frac{x^n}{n (\ln n)^2}$
- $\ds\sum_{n=0}^\infty \frac{x^n}{\sqrt{n^2+3}}$
- $\ds\sum_{n=1}^\infty \frac{n^n(3x+5)^n}{(2n)!}$
- $\ds\sum_{n=0}^\infty (\ln n) x^n$
- $\ds\sum_{n=1}^\infty \frac{(-1)^{n-1}(x-2)^n}{n 3^n}$
 
\end{multicols}
::: 

::: {#exr- } 
Show that the series 
$$
\sum_{n=1}^\infty \frac{\sin(n^3 x)}{n^2}
$$ 
converges for all values of $x$, but that
$$
\sum_{n=1}^\infty \frac{d}{dx}\left(\frac{\sin(n^3 x)}{n^2}\right)
$$ 
diverges for all values of $x.$
Why does this not contradict \ref{Differentiation and Integration of Power Series}?
::: 

::: {#exr- } 
Find the radius and interval of convergence for each power series. 
For what values of $x$ does the series converge absolutely or conditionally?
\begin{multicols}{3}
 
- $\ds\sum_{n=1}^\infty \frac{x^{2n}}{(2n)!}$
- $\ds\sum_{n=1}^\infty \frac{(-1)^nx^n}{n!}$
- $\ds\sum_{n=1}^\infty \frac{(-1)^{n+1}(x-4)^n}{n 9^n}$
- $\ds\sum_{n=1}^\infty \frac{(x-3)^{n-1}}{3^{n-1}}$
- $\ds\sum_{n=1}^\infty \frac{n! x^n}{(2n)!}$
- $\ds\sum_{n=1}^\infty \frac{(x-3)^{n+1}}{(n+1)4^{n=1}}$
 
\end{multicols}
::: 

::: {#exr- } 
Find a power series representation for the function and determine the interval of convergence. 
\begin{multicols}{2}
 - $\ds f(x) = \frac{1}{1+x}$
- $\ds f(x) = \frac{1}{9+x^2}$
- $\ds f(x) = \frac{1+x}{1-x}$
- $\ds f(x) = \frac{3}{1-x^4}$
- $\ds f(x) = \frac{x^2}{(1-2x)^2}$
- $\ds f(x) = \arctan(x/3)$
 
\end{multicols}
::: 

::: {#exr- } 
(a) Use differentiation to find a power series representation for 
$$
f(x)=\frac{1}{(1+x)^2}
$$
Find the radius of convergence. 
Use part (a) to find a power series for 
$$
f(x)=\frac{1}{(1+x)^3}. 
$$
Use part (b) to find a power series for 
$$
f(x)=\frac{x^2}{(1+x)^3}. 
$$
::: 

::: {#exr- } 
Use the power series for $\tan^{-1}x$ to prove the following expression for as the sum of an in?nite series: 
$$
\pi = 2\sqrt{3}\sum_{n=0}^\infty \frac{(-1)^n}{(2n+1) 3^n}.
$$
::: 

::: {#exr- } 
Suppose that $f$ and $g$ are functions defined by 
$$
f(x)=\sum_{n=0}^\infty \frac{(-1)^n x^{2n+1}}{(2n+1)!} 
\qquad \text{and} \qquad 
g(x)= \sum_{n=0}^\infty \frac{(-1)^n x^{2n}}{(2n)!}.
$$
 - Find the intervals of convergence of $f$ and $g.$
- Show that $f'(x) = g(x)$ and $g'(x) = -f(x).$
- Identify the functions $f$ and $g.$ 
 
::: 

::: {#exr- } 
Find a power series representation for the function, centered at $c$, and determine the interval of convergence. 
\begin{multicols}{2}
 - $\ds f(x) = \frac{1}{3-x}$, $c=1$
- $\ds f(x) = \frac{5}{2x-3}$, $c=-3$
- $\ds f(x) = \frac{3}{3x+4}$, $c=0$
- $\ds f(x) = \frac{4x}{x^2+2x-3}$, $c=0$
- $\ds f(x) = \frac{5}{5+x^2}$, $c=\pi/4$
- $\ds f(x) = \frac{2}{6-x}$, $c=-2$
 
\end{multicols}
::: 


::: {#exr- } 
Use the power series $\frac{1}{1+x} = \sum_{n=0}^\infty (-1)^n x^n$ to determine a power series, centered at $0$, for the function. 
Identitfy the interval of convergence. 
 - $\ds h(x)= \frac{x}{x^2-1} = \frac{1}{2(1+x)}-\frac{1}{2(1-x)}$
- $\ds h(x)= \frac{2}{(x+1)^3} \frac{d^2}{dx^2}\left(\frac{1}{x+1}\right)$
- $\ds h(x) = \ln(1-x^2) \int \frac{1}{1+x}\, dx  -\int \frac{1}{1-x}\, dx$
 
::: 



