---
pagetitle: "Ratio and Root Tests - Exploring Calculus"
---
# Ratio and Root Tests


The Ratio Test and the Root Tests are criterions for the convergence of an infinite series. We provide several examples using these convergence tests and several exercises.

## The Ratio Test

The Ratio Test is a criterion for the convergence (a convergence test) of an infinite series $\sum a_n$. 
It depends on the quantity 
\begin{equation}
\label{rt}
\lim_{n\to+\infty} \frac{a_{n+1}}{a_n}.
\end{equation}
to determine convergence or diverges. 
The Ratio Test fails if the limit in \eqref{rt} is 1. 

::: {#thm- } 
Let $\sum a_n$ be a series with positive terms and suppose that
$$
\label{ratiotest}
\rho = \lim_{n\to+\infty} \frac{a_{n+1}}{a_n}.
$$
 - If $\rho<1$, the series converges. 
- If $\rho >1$ or $\rho  =+\infty$, the series diverges. 
- If $\rho=1$, the series may converge or diverge. 
 
::: 

::: {#exm- } 
Use the Ratio Test to determine whether the series $\sum_{n=1}^\infty \frac{1}{n!}$ converges or diverges.
::: 

::: {.solution }
We find 
\begin{align*}
\rho = \lim_{n\to \infty} \frac{a_{n+1}}{a_n} 
= \lim_{n\to \infty} \frac{1/(n+1)!}{1/n!} 
= \lim_{n\to\infty}  \frac{1}{n+1} = 0.
\end{align*}
Since $\rho <1$ the series converges by the Ratio Test.  
::: 

::: {#exm- } 
Use the Ratio Test to determine whether the series $\sum_{n=1}^\infty \frac{n}{2^n}$ converges or diverges.
::: 

::: {.solution }
We find 
\begin{align*}
\rho = \lim_{n\to \infty} \frac{a_{n+1}}{a_n} 
= \lim_{n\to \infty} \frac{(n+1)/2^{n+1}}{n/2^n} 
= \lim_{n\to\infty}  \frac{n+1}{2n} = \frac{1}{2}.
\end{align*}
Since $\rho <1$ the series converges by the Ratio Test.  
::: 

::: {#exm- } 
Use the Ratio Test to determine whether the series $\sum_{n=1}^\infty \frac{n^n}{n!}$ converges or diverges.
::: 

::: {.solution }
We find 
\begin{align*}
\rho = \lim_{n\to \infty} \frac{a_{n+1}}{a_n} 
= \lim_{n\to \infty} \frac{(n+1)^{n+1}/(n+1)!}{n^n/n!} 
= \lim_{n\to\infty}  \left(1+\frac{1}{n}\right)^n = e.
\end{align*}
Since $\rho >1$ the series diverges by the Ratio Test.  
::: 

::: {#exm- } 
Use the Ratio Test to determine whether the series $\sum_{n=1}^\infty \frac{1}{2n-1}$ converges or diverges.
::: 

::: {.solution }
We find 
\begin{align*}
\rho = \lim_{n\to \infty} \frac{a_{n+1}}{a_n} 
= \lim_{n\to \infty} \frac{1/(2(n+1)-1)}{1/(2n-1)} 
= \lim_{n\to\infty}  \frac{2n-1}{2n+1} = 1.
\end{align*}
Since $\rho =1$ the Ratio Test fails. 
However, the Integral Test proves that the series  diverges since
$$
\int_1^{+\infty} \frac{1}{2x-1} \, dx 
= \lim_{b\to +\infty} \int_1^b \frac{1}{2x-1} \, dx 
=  \left. \lim_{b\to +\infty} \frac{1}{2}  \ln(2x-1)\right|_1^b
=+ \infty
$$
as desired. 
::: 



## The Root Test

The Root Test is a criterion for the convergence (a convergence test) of an infinite series $\sum a_n$. 
It depends on the quantity 
\begin{equation}
\label{roott}
\lim_{n\to+\infty} \sqrt[n]{a_n}.
\end{equation}
to determine convergence or diverges. 
The Root Test fails if the limit in \eqref{roott} is 1. 

::: {#thm- } 
Let $\sum a_n$ be a series with positive terms and suppose that
$$
\label{roottest}
\rho = \lim_{n\to+\infty} \sqrt[n]{a_n}.
$$
 - If $\rho<1$, the series converges. 
- If $\rho >1$ or $\rho  =+\infty$, the series diverges. 
- If $\rho=1$, the series may converge or diverge. 
 
::: 

::: {#exm- } 
Use the root test to determine whether the series 
$$
\sum_{n=1}^\infty \left(\frac{4n^2-3}{7n^2+6}\right)^n
$$ 
converges or diverges.
::: 

::: {.solution }
We find 
\begin{align*}
\rho = \lim_{n\to \infty}  \sqrt[n]{\left(\frac{4n^2-3}{7n^2+6}\right)^n} 
= \lim_{n\to \infty}  \frac{4n^2-3}{7n^2+6} 
= \frac{4}{7}
\end{align*}
Since $\rho <1$ the series converges. 
::: 

::: {#exm- } 
Use the root test to determine whether the series $\sum_{n=1}^\infty \frac{2^n}{n^{10}}$  converges or diverges by the Root Test.  
::: 

::: {.solution }
We find 
\begin{align*}
\rho = \lim_{n\to \infty}  \sqrt[n]{\frac{2^n}{n^{10}}} 
= \lim_{n\to \infty}  \frac{2}{(n^{1/n})^{10}}
= 2
\end{align*}
Since $\rho >1$ the series diverges by the Root Test.  
::: 

::: {#exm- } 
Use the root test to determine whether the series $\sum_{n=1}^\infty \frac{e^{2n}}{n^n}$ converges or diverges.
::: 

::: {.solution }
We find 
\begin{align*}
\rho = \lim_{n\to \infty}  \sqrt[n]{\frac{e^{2n}}{n^n}} 
= \lim_{n\to \infty}  \frac{e^{2n/n}}{n^{n/n}}
= \lim_{n\to \infty}  \frac{2^2}{n}
= 0
\end{align*}
Since $\rho <1$ the series converges by the Root Test.  
::: 

::: {#exm- } 
Determine whether the series 
$$
\sum_{n=1}^\infty (-1)^{n-1}\frac{2^{n+3}}{(n+1)^n}
$$ 
is absolutely convergent, conditionally convergent, or divergent. ::: 

::: {.solution }
We find
\begin{align*}
\rho = \lim_{n\to \infty}  \sqrt[n]{\left|(-1)^{n-1}\frac{2^{n+3}}{(n+1)^n}\right|} 
= \lim_{n\to \infty}  \left|\frac{2^{n+3}}{(n+1)^n}\right|^{1/n}
= \lim_{n\to \infty}  \frac{2^{1+3/n}}{n+1}
= 0
\end{align*}
Since $\rho <1$ the series is absolutely convergent by the Root Test.  
::: 




## Exercises

::: {#exr- } 
Use the Ratio Test to determine the convergence or divergence of the series.
\begin{multicols}{3}
 
- $\ds\sum_{n=0}^\infty \frac{n!}{3^n}$
- $\ds\sum_{n=1}^\infty \frac{1}{n!}$
- $\ds\sum_{n=1}^\infty \frac{5^n}{n^4}$
- $\ds\sum_{n=1}^\infty \frac{n^2}{4^n}$
- $\ds\sum_{n=1}^\infty \frac{n!}{n 3^n}$
- $\ds\sum_{n=1}^\infty \frac{n^n}{2^n}$
- $\ds\sum_{n=1}^\infty \frac{(n!)^2}{(3n)!}$
- $\ds\sum_{n=1}^\infty \frac{n^6}{n!}$
- $\ds\sum_{n=1}^\infty n \left(\frac{1}{2}\right)^n$
 
 
::: 

::: {#exr- } 
Use the Root Test to determine the convergence or divergence of the series.
\begin{multicols}{3}
 
- $\ds\sum_{n=1}^\infty \frac{1}{4^n}$
- $\ds\sum_{n=1}^\infty \left(\frac{12n^3_n}{9n^2+n+1}\right)^n$
- $\ds\sum_{n=1}^\infty \left(\frac{n-2}{5n+1}\right)^n$
- $\ds\sum_{n=1}^\infty \left(\frac{n}{n+1}\right)^{2n^2}$
- $\ds\sum_{n=1}^\infty \frac{n}{3^n}$
- $\ds\sum_{n=1}^\infty \frac{n}{e^n}$
- $\ds\sum_{n=1}^\infty \frac{(n!)^n}{(n^n)^2}$
- $\ds\sum_{n=1}^\infty \frac{2^n n!}{n^n}$
- $\ds\sum_{n=1}^\infty \left(\frac{n!}{n^3}\right)$
 
 
::: 


::: {#exr- } 
Which of the series converge, and which diverge? 
Give reasons for your answers.
 
 - $\ds\sum_{n=1}^\infty n^2 e^{-n}$
- $\ds\sum_{n=1}^\infty (1-e^{-n})^n$
- $\ds\sum_{n=1}^\infty \frac{100}{n}$
- $\ds\sum_{n=1}^\infty \frac{n!}{10^n}$
- $\ds\sum_{n=1}^\infty \frac{10}{2\sqrt{n^3}}$
- $\ds\sum_{n=1}^\infty \frac{(-2)^n}{3^n}$
- $\ds\sum_{n=1}^\infty \frac{1}{4+2^{-n}}$
- $\ds\sum_{n=1}^\infty \frac{2^n}{4n^2-1}$
- $\ds\sum_{n=1}^\infty \left(1- \frac{1}{3n}\right)^n$
- $\ds\sum_{n=1}^\infty \frac{(-1)^n 3^n}{n 2^n}$
- $\ds\sum_{n=1}^\infty \frac{n \ln n}{2^n}$
- $\ds\sum_{n=1}^\infty \frac{(-3)^n}{3\cdot 5 \cdot 7 \cdots (2n+1)}$
 
 
::: 

::: {#exr- } 
Determine whether the series is convergent, absolutely convergent, conditionally convergent, or divergent.
 
 - $\ds\sum_{n=3}^\infty \frac{(-1)^n}{n\sqrt{\ln n}}$
- $\ds\sum_{n=1}^\infty \frac{10^n}{(n+1)4^{2n+1}}$
- $\ds\sum_{n=1}^\infty \frac{\cos(n+1)}{n \sqrt{n}}$
- $\ds\sum_{n=1}^\infty \frac{(-1)^n}{n^4}$
- $\ds\sum_{n=1}^\infty \frac{(-1)^{n-1}\tan^{-1} n}{n^2}$
- $\ds\sum_{n=1}^\infty \frac{n!}{100^n}$
- $\ds\sum_{n=2}^\infty \frac{(-10^n}{(\ln n)^n}$
- $\ds\sum_{n=1}^\infty (-1)^n \frac{n}{\sqrt{n^3+2}}$
- $\ds\sum_{n=1}^\infty (-1)^n \tan\left(\frac{1}{n}\right)$
- $\ds\sum_{n=1}^\infty \frac{\sin 4n}{4^n}$
- $\ds\sum_{n=1}^\infty \frac{(-n)^n}{[(n+1)\tan^{-1} n]^n}$
- $\ds\sum_{n=1}^\infty (-1)^{n+1}\frac{n^22^n}{n!}$
 
 
::: 

::: {#exr- } 
Show that the ratio and root tests fail on $p$-series.
::: 

::: {#exr- } 
Show that the ratio and root tests fail on series $\ds\sum_{n=1}^\infty \frac{1}{(\ln n)^p}$.
::: 


::: {#exr- } 
The terms of a series are de?ned recursively by the equations $a_1=2$, 
$$
a_{n+1}= \frac{2+\cos n}{\sqrt{n}}a_n.
$$
Determine whether $\sum a_n$ converges or diverges. 
::: 

::: {#exr- } 
Around 1910, the mathematician Srinivasa Ramanujan discovered the formula 
$$
\frac{1}{\pi} 
= \frac{2\sqrt{2}}{9801} \sum_{n=0}^\infty \frac{(4n)!(1103+26390n)}{(n!) 396^{4n}}.
$$
Verify that the series is convergent. 
::: 


::: {#exr- } 
Find the values of the parameter $p>0$ for which the series 
$$
\sum_{n=1}^\infty \left(1-\frac{p}{n}\right)^n
$$ converges. 
::: 


