---
pagetitle: "Sequences - Exploring Calculus"
---
# Sequences


Sequences are introduced. The limit of a sequence and various limits rules are studied, including the squeeze theorem. The convergence of a bounded monotonic sequence is explained.

## Introduction to Sequences

Basically, a \emph{sequence} is a function whose domain is a set of integers.

::: {#def- } 
A \index{sequence} $\{a_n\} **sequence} $\{a_n\** $ is a function whose domain is the set of positive integers. 
The functional values $a_1$, $a_2$, \ldots, $a_n$ are the \index{terms} **terms**  of the sequence, and the term $a_n$ is called the $n$th term of the sequence. 
::: 

::: {#exm- } 
List the terms of the sequence.
 
 - $a_n=1/n$
- $a_n = n/(1+n)$
 
 
::: 

::: {.solution }
The first 5 terms in the first sequence are $1, 1/2, 1/3, 1/4$ and $1/5$. 
The first 5 terms in the second sequence are 
$$
\frac{1}{2}, \frac{2}{3}, \frac{3}{4}, \frac{4}{5}, \frac{5}{6}.
$$
where the index in both examples is $n$ and $n=1, 2, 3, \ldots.$
::: 

::: {#exm- } 
Find an expression for the $n$th term of the sequence. 
 
 - $\frac{1}{2}, \frac{1}{4}, \frac{1}{8}, \frac{1}{16}, \ldots$
- $\frac{1}{2}, -\frac{2}{3}, \frac{3}{4}, -\frac{4}{5}, \ldots$
 
 
::: 

::: {.solution }
For the first sequence, the denominators of the four known terms have been expressed as powers of 2. 
This suggests that the denominator of the $n$th term is $2^n$.
Thus, the sequence can be expressed as 
$$
\frac{1}{2}, \frac{1}{4}, \frac{1}{8}, \frac{1}{16}, \ldots, \frac{1}{2^n}, \ldots
$$
Notice that the second sequence has alternating signs and that notice that the $n$th term in the sequence can be obtained by multiplying the $n$th term by $(-1)^{n+1}$.
Thus, the sequence can be expressed as 
$$
\frac{1}{2}, -\frac{2}{3}, \frac{3}{4}, -\frac{4}{5}, \ldots, (-1)^{n+1}\frac{n}{n+1}, \ldots
$$
as desired.
::: 

::: {#exm- } 
List the first five terms of the recursively defined sequence $a_1=1$, $a_2=1$, $a_{n+1}=a_n+a_{n-1}$ for $n > 2$. 
::: 

::: {.solution }
The sequence is called the Fibonacci sequence. 
The first 11 terms are $1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89$. 
::: 


## The Limit of a Sequence

A sequence $\{a_n\}$ has a \index{limit} **limit** , written 
$$
\lim_{n\to \infty} a_n = L
\label{limconv}
$$
if $a_n$ can be made as close to $L$ as we please by taking $n$ sufficiently large. 
If the limit in \eqref{limconv} exists the sequence is said to \index{converge} **converge** .
Otherwise we say that the sequence \index{diverges} **diverges** . 

::: {#def- } 
A sequence $\{a_n\}$ \index{converges} **converges**  to $L$, written
$$
\lim_{n\to \infty} a_n = L
$$
if for every $\epsilon >0$ there exists a positive integer $N$ such that $|a_n - L <\epsilon$ whenever $n>N$. 
::: 

::: {#thm- } 
If $\lim_{x\to \infty} f(x) =L$ and $\{a_n\}$ is a sequence defined by $a_n=f(n)$ where $n$ is a positive integer, then $\lim_{n\to \infty} a_n =L$. 
::: 

::: {#thm- } 
If $\{a_n\}$ and $\{b_n\}$ are convergent sequences and $c$ is a constant, then
 - $\lim_{n\to \infty} (a_n + b_n) = \lim_{n\to \infty} a_n + \lim_{n\to \infty} b_n$
- $\lim_{n\to \infty} (a_n - b_n) = \lim_{n\to \infty} a_n - \lim_{n\to \infty} b_n$
- $\lim_{n\to \infty} c a_n = c \lim_{n\to \infty} a_n$
- $\lim_{n\to \infty} (a_n b_n) = \lim_{n\to \infty} a_n \lim_{n\to \infty} b_n$
- $\lim_{n\to \infty}\frac{a_n }{b_n} = \frac{\lim_{n\to \infty} a_n}{\lim_{n\to \infty} b_n}$ whenever $\lim_{n\to \infty} b_n \neq 0$
- $\lim_{n\to \infty} a_n^p = \left[ \lim_{n\to \infty} a_n \right]^p$, if $p > 0$ and $a_n > 0$.
 
::: 

::: {#exm- } 
Determine if the sequence $\left\{\frac{n}{2n+1}\right\}$ converges or diverges. 
::: 

::: {.solution }
We find that 
\begin{align*}
\lim_{n\to \infty} \frac{n}{2n+1} 
& = \lim_{n\to \infty} \frac{1}{2+1/n} \\
& = \frac{\lim_{n\to \infty} 1}{\lim_{n\to \infty}(2+1/n)} \\
& =  \frac{\lim_{n\to \infty} 1}{\lim_{n\to \infty} 2+ \lim_{n\to \infty} 1/n} \\
& = \frac{1}{2+0} =\frac{1}{2}
\end{align*}
::: 

::: {#exm- } 
Determine if the sequence $\left\{(-1)^{n+1}\frac{n}{2n+1}\right\}$ converges or diverges. 
::: 

::: {.solution }
The sequence diverges as it oscillates between $1/2$ and $-1/2$. 
::: 

::: {#exm- } 
Determine if the sequence $\left\{(-1)^{n+1}\frac{1}{n}\right\}$ converges or diverges. 
::: 

::: {.solution }
Notice that $1/n\to -$ as $n\to \infty$. 
Thus the product $(-1)^{n+1}(1/n)$ oscillates between positive and negative values. 
Since the odd numbered terms are approaching 0 and the even numbered terms also approaching zero, thus 
$$
\lim_{n\to\infty}  (-1)^{n+1}\frac{1}{n} = 0
$$
so the sequence converges to 0. 
::: 

::: {#exm- } 
Determine if the sequence $\left\{3-2n\right\}$ converges or diverges. 
::: 

::: {.solution }
Since $\lim_{n \to \infty} (3-2n) = -\infty$, the sequence diverges. 
::: 


::: {#exm- } 
Find the limit of the sequence $\left\{\frac{n}{2^n}\right\}$.
::: 

::: {.solution }
The expression 
$$
\lim_{n\to\infty} \frac{n}{2^n}
$$
is an indeterminate type of the form $\infty/\infty$, so l'Hopital's rule is applied by using the function $f(x)=x$ and $g(x)=2^x$. 
We have
$$
\lim_{x\to \infty} \frac{x}{2^x} 
= \lim_{x\to \infty} \frac{1}{2^x \ln 2} = 0
$$
from which we conclude that 
$$
\lim_{n\to\infty} \frac{n}{2^n} = 0
$$
as desired. 
::: 


## The Squeeze Theorem for Limits

If we are able to compare a sequence with two other familiar convergent sequences, then we can apply the squeeze theorem.

::: {#thm- } \label{Squeeze Theorem}
If $a_n \leq b_n \leq c_n$, for $n\geq n_0$ and 
$$
\lim_{n\to \infty} a_n = \lim_{n\to \infty} c_n =L,
$$ 
then $\lim_{n\to \infty} b_n = L$.
::: 

::: {#exm- } 
Find the limit of the sequence 
$$
b_n =\frac{\cos n}{n^2+1}.
$$
::: 

::: {.solution }
Notice that $-1\leq \cos n \leq 1$, for all $n$, and so 
$$
-\frac{1}{n^2+1} \leq \frac{\cos n}{n^2+1} \leq \frac{1}{n^2+1}.
$$
Letting 
$$
a_n =-\frac{1}{n^2+1}
\qquad \text{and}\qquad 
c_n=\frac{1}{n^2+1},
$$ 
we have $a_n \leq b_n \leq c_n$ for $n\geq 1$. 
Therefore, by the Squeeze Theorem we have 
$$
\lim_{n\to \infty} b_n =0. 
$$
as desired.
::: 


::: {#exm- } 
Show that if $\lim_{n\to \infty} |a_n|=0$, then $\lim_{n\to \infty} a_n =0$.
::: 

::: {.solution }
Notice that $-|a_n| \leq a_n \leq |a_n|$. 
However, since   
$$
\lim_{a_n \to \infty} -|a_n| = \lim_{a_n \to \infty} |a_n| =0
$$
by the squeeze theorem,  $\lim_{n\to \infty} a_n =0$ follows at once.
::: 

::: {#thm- } 
If $\lim_{n\to \infty} a_n =L$ and the function $f$ is continuous at $L$, then
$$
\lim_{n\to \infty} f(a_n)= f(L).
$$
::: 

::: {#exm- } 
Show that if $\lim_{n\to \infty} a_n=0$, then $\lim_{n\to \infty} |a_n| =0$.
::: 

::: {.solution }
Assume that $\lim_{n\to \infty} a_n=0$ and recall that $f(x)=|x|$ is continuous at $0$. 
Therefore, 
$$
\lim_{n\to \infty} f(a_n)
= \lim_{n\to \infty} |a_n|
= |0| =0
$$
as desired.
::: 






## Monotonic Sequences and Bounded Sequences

The sequence of natural numbers $1, 2, 3, 4, \ldots$ is strictly increasing sequence. 
The sequence 
$$
\frac{1}{2}, \frac{3}{4}, \ldots, \frac{n}{n+1},\ldots
$$ 
is also a strictly increasing sequence. 
The constant sequence $\{4\}$ is a nondecreasing sequence. 

In general, a sequence $\{a_n\}$ is called \index{strictly increasing} **strictly increasing**  whenever 
$$
a_1 < a_2 < a_3 < \cdots < a_n < \cdots 
$$
and is called \index{increasing} **increasing**  whenever 
$$
a_1 \leq a_2 \leq a_3 \leq \cdots \leq a_n \leq \cdots  
$$
Similarly, a sequence $\{a_n\}$ is called \index{strictly decreasing} **strictly decreasing**  whenever 
$$
a_1 > a_2 > a_3 > \cdots > a_n > \cdots 
$$
and is called \index{decreasing} **decreasing**  whenever 
$$
a_1 \geq a_2 \geq a_3 \geq \cdots \geq a_n \geq \cdots  
$$

::: {#def- } 
A sequence $\{a_n\}$ is \index{monotonic} **monotonic**  when its terms are nondecreasing 
$$
a_1 \leq a_2 \leq a_3 \leq \cdots \leq a_n \leq \cdots 
$$
or when its terms are nonincreasing
$$
a_1 \geq a_2 \geq a_3 \geq \cdots \geq a_n \geq \cdots.  
$$
::: 

::: {#exm- } 
Show that the sequence
$$
\frac{1}{2}, \frac{3}{4}, \ldots, \frac{n}{n+1},\ldots
$$ 
is a strictly increasing sequence. 
::: 

::: {.solution }
Let $a_n =\frac{n}{n+1}$. 
Then 
$$
a_{n+1} = \frac{n+1}{n+2}
$$
and so 
$$
a_{n+1}- a_n 
= \frac{n+1}{n+2}
= \frac{n}{n+1}
= \frac{1}{(n+1)(n+2)} >0.
$$
Whence $a_{n+1} > a_n$ for all $n\geq 1$. 
By definition, the given sequence is a strictly increasing sequence. 
Another approach is to use the function $f(x)=x/(x+1)$ and the first derivative test. 
::: 


The sequence of natural numbers $1, 2, 3, 4, \ldots$ has no upper bound. 
The sequence 
$$
\frac{1}{2}, \frac{3}{4}, \ldots, \frac{n}{n+1},\ldots
$$ 
is bounded above by $1$. 
In fact, 1 is the least upper bound. 
The constant sequence $\{4\}$ is bounded above and below. 

::: {#def- } 
Let $\{a_n\}$ be a sequence. 
 - A sequence $\{a_n\}$ is \index{bounded above} **bounded above**  when there is a real number $M$ such that $a_n \leq M$ for all $n$. 
The number $M$ is called an \index{upper bound} **upper bound**  of the sequence. 
- A sequence $\{a_n\}$ is \index{bounded below} **bounded below**  when there is a real number $N$ such that $N \leq a_n$ for all $n$. 
The number $N$ is called a lower bound of the sequence. 
- A sequence $\{a_n\}$ is \index{bounded} **bounded**  when it is bounded above and bounded below. 
 
::: 

::: {#thm- } \label{Bounded Convergence Theorem}
If a sequence $\{a_n\}$ is bounded and monotonic, then it converges. 
::: 

::: {#exm- } 
Show that the sequence $\left\{\frac{e^n}{n!}\right\}$ converges and find its limit. 
::: 

::: {.solution }
Fist we show that the sequence is strictly decreasing.
Let $a_n =\frac{e^n}{n!}$. 
We have 
\begin{equation}
\label{strdec}
\frac{a_{n+1}}{a_n} 
= \frac{\frac{e^{n+1}}{(n+1)!}}{\frac{e^n}{n!}} 
= \frac{e^{n+1} n!}{e^n (n+1)!}
= \frac{e}{n+1}.
\end{equation}
Whence $a_{n+1} < a_n$ for all $n\geq 1$. 
Since every term in the sequence is positive, it is bounded below by $0$. 
By the Bounded Convergence Theorem, we know that the sequence converges.
By \eqref{strdec}, the sequence is given by the recursion formula
$$
a_{n+1} = \frac{e}{n+1} a_n.
$$
Passing the limit on both sides we obtain
$$
\lim_{n \to \infty} a_{n+1} 
= \lim_{n \to \infty} \left(\frac{e}{n+1} a_n\right)
= \lim_{n \to \infty} \left(\frac{e}{n+1}\right) \lim_{n \to \infty} \left(a_n\right)
= 0.
$$
Therefore, the sequence converges to 0.
::: 






## Exercises


::: {#exr- } 
Write the first five terms of the sequence.
 
 - $a_n = \frac{ (-1)^{n+1} 2^n}{n+1}$
- $a_n =\frac{n+1}{3n-1}$
- $a_n = \sin \frac{n\pi}{2}$
- $a_1=4, a_{n+1}= \frac{a_n}{a_n-1}$
- $a_n = \frac{2^n}{(2n)!}$
- $a_n = \frac{1\cdot 3 \cdot 5 \cdots (2n-1)}{n!}$
- $a_1 =3$, $a_{n+1}= 2a_n -1$
- $a_1=2, a_{n+1}=3a_n +1$
 
 
::: 


::: {#exr- } 
Find an expression for the $n$th term of the sequence. 
 
 - $\left\{\frac{1}{2}, \frac{2}{3}, \frac{3}{4}, \frac{4}{5}, \frac{5}{6}, \ldots \right\}$
- $\left\{\frac{1}{1\cdot 2}, \frac{2}{2\cdot 3}, \frac{3}{3\cdot 4}, \frac{4}{4\cdot 5}, \ldots \right\}$
- $\left\{-\frac{1}{4}, \frac{2}{9}, -\frac{3}{16}, \frac{4}{25}, \ldots\right\}$
- $\left\{1, -\frac{2}{3}, \frac{4}{9}, -\frac{8}{27}, \ldots\right\}$
 
 
::: 


::: {#exr- } 
Which of the sequences converge and which diverge? 
Find the limit of each convergent sequence. 
 
 - $a_n = \frac{n+(-1)^n}{n}$
- $a_n =\sqrt{n+1}$
- $a_n = \frac{2n+1}{1-2\sqrt{n}}$
- $a_n =\frac{n^2-1}{2n^2+1}$
- $a_n= \frac{n+3}{n^2+5n+6}$
- $a_n = (-1)^n\frac{n+2}{3n+1}$
- $a_n = \left(1+\frac{2}{n}\right)^n$
- $a_n = \frac{1-n^3}{70-4n^2}$
- $a_n = 1+\left(\frac{-2}{e}\right)^n$
- $a_n = \frac{3^n}{n^3}$
- $a_n = \sqrt[n]{2^{1-3n}}$
- $a_n =\frac{1\cdot 3\cdot 5 \cdots (2n-1)}{n!}$
- $a_n =\sqrt[n]{n^2+n}$
- $a_n = \frac{1}{n^2} +\frac{2}{n^2}+ \frac{3}{n^2}+\cdots + \frac{n}{n^2}$
- $a_n = \frac{1}{n}\int_1^n \frac{1}{x}\, dx$
- $a_n = \frac{1+2+3+\cdots + n}{n+2}-\frac{n}{2}$
 
 
::: 

::: {#exr- } 
Determine if the sequence $a_n = \frac{\ln(n+2)}{n+2}$ is increasing, decreasing or bounded. 
::: 

::: {#exr- } 
Which of the following properties are satisfied by the sequence $\left\{\frac{(-1)^n}{n}\right\}$? 
::: 

::: {#exr- } 
Compute the limit of the convergent sequence $\left\{\sqrt[n]{n}\right\}$. 
::: 

::: {#exr- } 
Find the 5th term of the recursively defined sequence $a_1=2$, $a_2=4$, and $a_{n+1}=2a_n-a_{n-1}$ for $n\geq 2$.
::: 

::: {#exr- } 
Find $\lim_{n\to \infty} \frac{(-1)^n}{n}$. 
::: 

::: {#exr- } 
Determine whether the sequence $\left\{\frac{2^n+1}{e^n}\right\}$ converges or diverges. 
If it converges, find its limit.
::: 

::: {#exr- } 
Identify the sequence below for which $\{|a_n|\}$ converges but $\{a_n\}$ does not.
::: 

::: {#exr- } 
Which is the largest set of $r$ such that the sequence $\{r^n\}$ converge?
::: 

::: {#exr- } 
Write the first five terms of the sequence $\{a_n \}$ where $a_1=1$ and ${a_{n+1}=3a_n-2}$.
::: 

::: {#exr- } 
Determine if the sequence $\{a_n\}$ given by $a_n=\frac{2n^2+1}{n}$ converges or diverges.
If it converges, find its limit. 
::: 


::: {#exr- } 
Find the limit of the following sequences or state that they diverge. 
\begin{multicols}{3}
 - $a_n = \frac{\cos n}{n}$
- $a_n = \frac{2\tan^{-1}n}{n^3+4}$
- $a_n =\frac{n \sin^3(n\pi/2)}{n+1}$
 
 
::: 


::: {#exr- } 
Determine whether the sequence is increasing, decreasing, or not monotonic. Is the sequence bounded? 
\begin{multicols}{3}
 - $a_n = \frac{1}{2n+3}$
- $a_n =4-\frac{1}{n}$
- $a_n = \frac{2n-3}{3n+4}$
- $a_n=\left(\frac{2}{3}\right)^n$
- $\sin \frac{n\pi}{6}$
- $a_n = \frac{\ln(1/n)}{n}$
 
 
::: 



::: {#exr- } 
Suppose that $f(x)$ is a differentiable for all $x$ in $[0,1]$ and that $f(0)=0$.
Define the sequence $\{a_n\}$ by the rule $a_n=n f(1/n)$. 
Show that $lim_{n\to \infty} a_n = f'(0)$. 
\begin{multicols}{3}
 - $a_n= n \tan^{-1}\left(\frac{1}{n}\right)$
- $a_n =  n\left(e^{1/n}-1\right)$
- $a_n = n \ln \left(1+\frac{2}{n}\right)$
 
 
::: 


