---
pagetitle: "Tangent Lines and Rates of Change - Exploring Calculus"
---
# Tangent Lines and Rates of Change

## Average Rate of Change


::: {#def- } 
Suppose $y$  is a function of $x,$  say $y=f(x).$  
When a change in the variable is made from $x$  to $x+\Delta  x,$ there is a corresponding change to the $y,$ namely $\Delta  y=f(x+\Delta  x)-f(x)$. 
The \index{average rate of change} **average rate of change**  of $y$  with respect to $x$  is 
\[
\frac{\Delta  y}{\Delta  x}=\frac{f(x+\Delta x)-f(x)}{\Delta  x}
\]
and is also known as the \index{difference quotient} **difference quotient** .
::: 


::: {#exm- } 
Let $f(x)=\sqrt{x^2-9}.$ 
Find the average rate of change from $x=3$  to $x=6.$ 
::: 

::: {.solution }
The average rate of change of $f$  from $x=3$  to $x=6$  is given by, 
\[
\frac{f(x+\Delta  x)-f(x)}{\Delta  x}=\frac{f(6)-f(3)}{6-3}=\frac{\sqrt{6^2-9}-\sqrt{3^2-9}}{3}= \sqrt{3}
 \]
 which is also the slope of the secant line through $(3,0)$  and $\left(6,3 \sqrt{3}\right).$ 
::: 

In general, suppose an object moves along a straight line according to an equation of motion $s=f(t),$ where $s$ is the \index{displacement} (\index{directed distance} **displacement} (\index{directed distance** ) of the object from the origin at time $t.$  
The function $f$ that describes the motion is called the \index{position function} **position function**  of the object. 
In the time interval from $t=a$ to $t=a+h$  the change in position is $f(a+h)-f(a)$ and the \index{average velocity} **average velocity**  over this time interval is 
\[
\frac{f(a+h)-f(a)}{h}
\] 
which is the same as the slope of the secant line through these two points.

::: {#exm- } 
If a billiard is dropped from a height of 500 feet, its height $s$  at time $t$  is given by the position function $s=-16t^2+500$  where $s$  is measured in feet and $t$  is measured in seconds. 
Find the average velocity over the intervals $[2,2.5]$ and $[2,2.6]$.  
::: 

::: {.solution }
For the interval $[2,2.5],$ the object falls from a height of $s(2)=-16(2)^2+500=436$  feet to a height of $s(2.5)=-16(2.5)^2+500=400.$  
The average velocity is 
\[
\frac{\Delta  s}{\Delta  t}=\frac{s(2.5)-s(2)}{2.5-2}=\frac{400-436}{2.5-2}=-72.
\]
For the interval $[2,2.6],$ the object falls from a height of $s(2)=436$  feet to a height of $s(2.6)=391.84.$  
The average velocity is 
\[
\frac{\Delta  s}{\Delta  t}=\frac{s(2.6)-s(2)}{2.6-2}=\frac{391.84-436}{2.6-2}=-73.6.
\]
Note that the average velocities are negative indicating that the object is moving downward.
::: 


## Instantaneous Rate of Change

The difference quotient 
\[
\frac{\Delta  y}{\Delta  x}=\frac{f\left(x_2\right)-f\left(x_1\right)}{x_2-x_1}
\]
is the average rate of change of $y$  with respect to $x$  over the interval $\left[x_1,x_2\right]$ and can be interpreted as the slope of the secant line.
Its limit as $\Delta x\to 0$  is the derivative at $x=x_1$ and is denoted by $f'\left(x_1\right).$  
We interpret the limit of the average rate of change as the interval becomes smaller and smaller to be the instantaneous rate of change. 
Often, different branches of science have specific interpretations of the derivative.


As $\Delta  x\to 0$  the average rate of change approaches the \index{instantaneous rate for change} **instantaneous rate for change** ; that
is, 
\[
\lim _{\Delta  x\to 0} \frac{\Delta  y}{\Delta  x} = f'(x)
\] 
and is also known as the \index{derivative} **derivative**  of $f$  at $x.$ 


::: {#exm- } 
Let $ \displaystyle f(x)=\frac{x^2-x+5}{3-x}.$  
Find the instantaneous rate of change at $x=2.$ 
::: 

::: {.solution }
Since 
$$
 \displaystyle f'(x)=\frac{-x^2+6 x+2}{(x-3)^2},
$$ 
the instantaneous rate for change of $f$ at $x=2$ is given by, 
\[
f'(2)=\frac{-2^2+6 (2)+2}{(2-3)^2}=10.
\square
\] 
::: 

## What is a Tangent Line?

The tangent line problem is widely considered to be the instigating idea behind the derivative. 
Computing the slope of a tangent line was a problem that the French mathematician \index{Pierre de Fermat} **Pierre de Fermat**  developed. 
Picking up on these ideas were \index{Isaac Newton} and \index{Gottfried Liebniz} **Isaac Newton} and \index{Gottfried Liebniz** , who then developed differential calculus.

For a general curve it is not easy to define what is meant by a tangent line; for example a tangent line might mean a line touches  the curve only once, but this does not work in all cases. 
Figure \ref{fig:tangentlines} shows examples of tangent lines.


The important idea to remember is that a tangent line is a local concept, we say the \index{tangent line} **tangent line**  at a point.

In our first example we will calculate a series of functions whose graphs are \index{secant lines} **secant lines**  to the graph of a given function $f$  and use them to infer an equation of the tangent line at a point.

::: {#exm- } 
Let $f(x)=2x^3-2x+2$.
Find an equation of the line that passes through the points $(1/2,5/4)$ and $(1,2)$  and sketch the graph of both $f$ and the secant line. 
The equation of the secant line is $y= \frac{3}{2} x+\frac{1}{2}$.

Do the same for the points $(1/2,5/4)$  and $(3/4,43/32)$. 
We find an equation of the secant line is $y=\frac{3}{8}x+\frac{17}{16}$.
We repeat this process several times and display the information in the following table.
\[
\begin{array}{l|l|l|l} \small
\Delta  x & (x,f(x)) & (x+\Delta  x,f(x+\Delta  x)) & \text{Equation of secant line} \\ \hline
 0.5 & (0.5,1.25) & (1,2) & y=1.5 x+0.5  \\
 0.25 & (0.5,1.25) & (0.75,1.34375)   & y=0.375 x+1.0625 \\
 0.125 & (0.5,1.25) & (0.625,1.23828) & y=-0.09375 x+1.29688  \\
 0.0625 & (0.5,1.25) & (0.5625,1.23096) &  y=-0.304688 x+1.40234 \\
 0.03125 & (0.5,1.25) & (0.53125,1.23737) & y=-0.404297 x+1.45215 \\
 0.015625 & (0.5,1.25) & (0.515625,1.24293) & y=-0.452637 x+1.47632
\end{array}
\]

From this table what would you say is the equation for the tangent line of the function $f(x)=2x^3-2x+2$ at $(1/2,1/4)$? 
Explain your conclusion. 
We infer the tangent line is $y=-\frac{1}{2}x+\frac{1}{2}$.
::: 

The difference quotient 
\[
\frac{\Delta  y}{\Delta  x}=\frac{f\left(x_2\right)-f\left(x_1\right)}{x_2-x_1}
\]
is the average rate of change of $y$  with respect to $x$  over the interval $\left[x_1,x_2\right]$ $_{}$  and can be interpreted as the slope of the secant line.
Its limit as $\Delta x\to 0$  is the derivative at $x=x_1$  and is denoted by $f'\left(x_1\right).$  
We interpret the limit of the average rate of change as the interval becomes smaller and smaller to be the instantaneous rate of change. 
Often,different branches of science have specific interpretations of the derivative.

As $\Delta  x\to 0$  the average rate of change approaches the \index{instantaneous rate for change} **instantaneous rate for change** ; that
is, 
\[
\lim _{\Delta  x\to 0} \frac{\Delta  y}{\Delta  x} = f'(x)
\] 
and is also known as the \index{derivative} **derivative**  of $f$  at $x.$ 

## Equation of Tangent Line



::: {#thm- } 
If $f'(a)$  exists then an \index{equation of the tangent line} **equation of the tangent line**  to the curve $y=f(x)$  at the point $(a,f(a))$ is 
$
y-f(a)=f'(a)(x-a).
$ 
::: 


::: {#exm- } 
Find equations of the tangent lines to the curve 
$\ds
y=\frac{x-1}{x+1}
$ 
that are parallel to the line $x-2y=1$.
::: 

::: {.solution }
The line $x-2y=1$  has slope $m=1/2$ and we use this with the derivative of 
$y=(x-1)/(x+1)$ to find the $x$. 
Since $y'=2/(x+1)^2$ we have $1/2=(2/((x+1)^2))$. 
Solving $(x+1)^2=4$ for $x$ we get $x=1$ and $x=-3$. 
Therefore, the points of tangency are at $(1,0)$  and $(-3,2)$.  
The tangent lines are found by using $y=1/2 x+b$  where $b=y-1/2 x$  with $(1,0)$  and $(-3,2)$. 
We find $b=-1/2$  and $b=7/2$ respectively. 
Therefore, equations of the tangent lines are  $y=\frac{1}{2}x-\frac{1}{2}$  and $y=\frac{1}{2} x+\frac{7}{2}$.
::: 


::: {#exm- } 
How many tangent lines to the curve $y=x/(x+1)$ pass through the point $(1,2)$? 
At which points do these tangent lines touch the curve?
::: 

::: {.solution }
All tangent lines through $(1,2)$  have the form $y-2=m (x-1)$  where $m=y'(x)=\frac{1}{(x+1)^2}.$  
Since we our looking for the intersection (point of tangency) we eliminate $y$  as follows: 
$$
y=\frac{x}{x+1}=\frac{1}{(x+1)^2}(x-1)+2.
$$ 
Solving for $x$ we obtain, $x=-2\pm \sqrt{3}.$ 
Thus there are two tangent lines and they are tangent at the point 
$$
\left(-2\pm \sqrt{3},\frac{-2\pm \sqrt{3}}{-2\pm \sqrt{3}+1}\right).
$$ 

::: 

::: {#exm- } 
Find equations of both tangent lines through the point $(2,-3)$ that are tangent to the parabola $y=x^2+x.$ 
::: 

::: {.solution }
All tangent lines through $(2,-3)$  have the form $y+3=m (x-2)$  where $m=y'(x)=2x+1.$  
Since we our looking for the intersection (point of tangency) we eliminate $y$  as follows: 
$$
y=x^2+x=(2x+1)(x-2)-3.
$$ 
Solving for $x$ we obtain, $x=-1$  and $x=5.$  
Thus there are two tangent lines and they are tangent at the points $(-1,0)$  and $(5,30).$  
The tangent lines are $y=-x-1$  and $y=11 x-25.$  
::: 

## Horizontal Tangent Lines


::: {#thm- } 
If $f'(a)=0$  then the equation of the tangent line to the curve $y=f(x)$  at the point $(a,0)$  is $y=f(a)$  and $f$  is said to have \index{a horizontal tangent line} **a horizontal tangent line**  at $x=a.$ 
::: 


::: {#exm- } 
For what values of $x$  does the graph of $f(x)=2x^3-3x^2-6x+87$  have a horizontal tangent?
::: 

::: {.solution }
To find the horizontal tangent lines we find where the derivative is 0. 
We compute, $y'(x)=6 x^2-6 x-6.$  
So we need to solve $6 x^2-6 x-6=0.$  
We find, $6 x^2-6 x-6=0$  and so $x^2-x-1=0$. 
And using the quadratic formula we have $x=\frac{1}{2} \left(1\pm \sqrt{5}\right).$  
Thus, the values of $x$  where the tangent lines are horizontal are $\frac{1}{2} \left(1\pm \sqrt{5}\right).$ 
::: 

::: {#exm- } 
Find the points on the curve $y=x^3-x^2-x+1$  where the tangent line is horizontal.
::: 

::: {.solution }
To find the horizontal tangent lines we find where the derivative is 0. 
We compute, $y'(x)=3 x^2-2 x-1$. 
So we need to solve $3 x^2-2 x-1=0.$  
Using the quadratic formula we have $x=-\frac{1}{3}$  and $x=1.$  
Thus, the values of $x$ where the tangents lines are horizontal are $1$  and $-1/3.$ 
::: 

## Relative Rate of Change

Next we illustrate the importance of the relative rate of change, as compared to the difference between the absolute rate of change and the average rate of change. 
The absolute change is not the same as the average rate of change. 
Namely, the \index{absolute change} **absolute change**  is just the differences in the values of $f$  at the boundary of the interval $[x,\Delta  x],$  namely $f(x+\Delta  x)-f(x);$  whereas the average rate of change is the absolute change divided by the size of the interval: 
\[
\frac{f(x+\Delta  x)-f(x)}{\Delta  x}.
\] 
The average rate of change is sometimes more useful; for example, suppose you want to know how long it takes to make some money and not just the size of the money made (absolute change). 
Knowing the rate at which the money is being made, (the average rate of change over a given time interval) is often useful.

::: {#exm- } 
Temperature readings $T$  (in degrees Celsius) were recorded every hour starting at midnight on a day in April. 
The time $x$  is measured in hours from midnight.
\[
\begin{array}{c|ccccccccccccc}
 x (h) & 0 & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12 \\ \hline
 T (C) & 6.5 & 6.1 & 5.6 & 4.9 & 4.2 & 4.0 & 4.0 & 4.8 & 6.1 & 8.3 & 10.0 & 12.1 & 14.3
\end{array}
\]
\[
\begin{array}{c|cccccccccccc}
 x (h) & 13 & 14 & 15 & 16 & 17 & 18 & 19 & 20 & 21 & 22 & 23 & 24 \\ \hline
 T (C) & 16.0 & 17.3 & 18.2 & 18.8 & 17.6 & 16.0 & 14.1 & 11.5 & 10.2 & 9.0 & 7.9 & 7.0
\end{array}
\]
\ 
- Find the average rates of change of temperatures with respect to time from noon to 3:00 p.m., 2:00 p.m. and 1:00 p.m. 
- Estimate the instantaneous rate of change at noon.
 
::: 

::: {.solution }
The average rates of change are, respectively,
\[
\frac{\Delta  T}{\Delta  x}=\frac{T(15)-T(12)}{3}=\frac{18.2-14.3}{3}=1.3 \, C/h 
\]
\[
\frac{\Delta  T}{\Delta  x}=\frac{T(14)-T(12)}{2}=\frac{17.3-14.3}{2}=1.5 \, C/H
\]
\[
\frac{\Delta  T}{\Delta  x}=\frac{T(13)-T(12)}{1}=\frac{16.0-14.3}{1}=1.7 \, C/h
\]
We plot the given data and use them to sketch a smooth curve that approximates the graph of the temperature function. Then we draw that tangent line at the point $P$  where $x=12$  and after measuring the sides of the triangle  we estimate that the slope of the tangent line is 
\[
\frac{18.3-8}{14-8.5}=\frac{10.3}{5.5}\approx 1.9
\] 
and so the instantaneous rate of change of temperature with respect to time at noon is about $1.9 C/h.$   
::: 

Sometimes we are not interested in the instantaneous rate of change and instead we may want a relative rate of change (percentage). 
For example suppose a student makes a 39 on a test, this would be a very good grade if the score is out of 40 points. 
However if the score was out of a total of 100 points then the grade is not so good.

::: {#def- } 
Let $y=f(x),$  then the \index{relative rate of change} **relative rate of change**  at $x=x_0$  is the ratio 
$$
\frac{f'\left(x_0\right)}{f\left(x_0\right)}.
$$ 
::: 

::: {#exm- } 
Let $f(x)=\sqrt{x}.$  
Find the relative rate of change at $x=5$  and $x=75.$ 
::: 

::: {.solution }
Since $f'(x)=\frac{1}{2 \sqrt{x}}.$  
The relative rate of change of $f$  at $x=5$  is
\[
\frac{f'(5)}{f(5)}=\frac{\frac{1}{2 \sqrt{5}}}{\sqrt{5}}=\frac{1}{10} \approx 0.1 \text{ or } 10\%.
\]
The relative rate of change of $f$  at $x=75$  is
\[
\frac{f'(75)}{f(75)}=\frac{\frac{1}{2 \sqrt{75}}}{\sqrt{75}} =\frac{1}{150} \approx 0.00666667 \text{ or } 0.6\%.
 \]
::: 

Often we are more interested in the relative rate of change of a quantity instead of the instantaneous rate of change. 
If instance, if you are earning $25,000/\text{yr}$  and receive a 5,000 raise, you would probably be very please. 
However, if you were making $100,000/\text{yr}$  you may not be as please since the relative change is not as much. 
With the $100,000/\text{yr}$  pay you only have a  $5,000/100,000=0.05=5\%$ increase whereas with the $25,000/\text{yr}$  pay you have a better percentage increase of  $5,000/25,000=0.20=20\%.$ 

::: {#exm- } 
Let $f(x)=2x^2-3x+5.$  
\ 
- Find the average rate of change from $x=2$  to $x=4.$  
- Find the instantaneous rate of change at $x=2.$  
- Find the relative rate of change of $f$  at $x=2$ 
 
::: 

::: {.solution }
The average rate of change of $f$  from $x=2$  to $x=4$  is given by,
\[
\frac{f(x+\Delta  x)-f(x)}{\Delta  x}
=\frac{\left(2(4)^2-3(4)+5\right)-\left(2(2)^2-3(2)+5\right)}{2}
=9
\]
Since $f'(x)=4x-3,$  the instantaneous rate for change of $f$  at $x=2$  is given by, $f'(2)=4(2)-3$  $=5.$   The relative rate of change of $f$  at $x=2$  is
\[
\frac{f'(2)}{f(2)}=\frac{5}{2(2)^2-3(2)+5} =\frac{5}{7} \approx 0.714286  \text{ or } 71\%.
\square
\]
::: 

## Exercises

::: {#exr- } 
Find a function(s) with the following properties. (a) Find functions $f$  and $g$  such that $f$  is discontinuous at $x=1$  but $f g$  is continuous there. (b) Give an example of a function defined for all real numbers that is continuous at only one point. 
::: 

::: {#exr- } 
(a) Find an equation of the secant line to the graph of $y=x^2-2x$  through the points $(1,-1)$  and $(-1,3)$ .
(b) Find an equation of the tangent line to the graph of $y=x^2-2x$  at the point $(1,-1)$ .
::: 

::: {#exr- } 
(a) Find the average rate of change of $f(x)=x^2+3x$  over the interval $[0,1]$ .
(b) Find the instantaneous rate of change of $f(x)=x^2+3x$  at $x=0$ .
::: 

::: {#exr- } 
A ball is thrown straight down from the top of a 220-foot building with an initial velocity of 120 meters per second. What is the velocity after 5 seconds? After 10 seconds?
::: 

::: {#exr- } 
To estimate the height of a building, a stone is dropped from the top of the building into a pool of water at ground level. How high is the building if the splash is seen $6.8$  seconds after the stone is dropped?
::: 

::: {#exr- } 
Let $s(t)=-t^3+3t^2-3t$  be the position function of a body moving on a coordinate line, with $s$  in meters and $t$  in seconds. (a) Find the body's displacement and average velocity for the time interval $0\leq t\leq 3.$  (b) Find the body's speed and acceleration at the endpoints of the time interval $0\leq t\leq 3.$  (c) When, if ever, during the time interval $0\leq t\leq 3$  does the body change direction?
::: 

::: {#exr- } 
(a) Let $s(t)=\frac{25}{t^2}-\frac{5}{t}$  be the position function of a body moving on a coordinate line, with $s$  in meters and $t$  in seconds. (b) Find the body's displacement and average velocity for the time interval $1\leq t\leq 5.$  (c) Find the body's speed and acceleration at the endpoints of the time interval $1\leq t\leq 5.$  When, if ever, during the time interval $1\leq t\leq 5$  does the body change direction?
::: 

::: {#exr- } 
(a) Let $s(t)=\frac{25}{t+5}$  be the position function of a body moving on a coordinate line, with $s$  in meters and $t$  in seconds. (b) Find the body's displacement and average velocity for the time interval $-4\leq t\leq 0.$  (c) Find the body's speed and acceleration at the endpoints of the time interval $-4\leq t\leq 0.$  When, if ever, during the time interval $-4\leq t\leq 0$  does the body change direction?
::: 

::: {#exr- } 
If an arrow is shot upward on the moon with a velocity of $58 m/s,$  its height in meters after $t$  seconds is given by $h=58t-0.83t^2.$  (a) Find the velocity of the arrow after $1 s.$  (b) Find the velocity of the arrow when $t=a.$  (c) When will the arrow hit the moon? (d) With what velocity will the arrow hit the moon?
::: 

::: {#exr- } 
If a cylindrical tank holds $100,000$  gallons of water, which takes $1 h$  to drain from the bottom of the tank, then Torricelli's Law given the volume $V$  of water remaining in the tank after $t$  minutes as 
$$
V(t)=100,000\left(1-\frac{t}{60}\right)^2, \qquad 0\leq t\leq 60.
$$  
Find the rate at which the water is flowing out of the tank after 20 minutes.
::: 

::: {#exr- } 
Verify that the average over the time interval $\left[t_0-\Delta  t,t_0+\Delta  t\right]$  is the same as the instantaneous velocity at $t=t_0$  for the position function $s(t)=\frac{-1}{2}a t^2+c.$ 
::: 

::: {#exr- } 
Let $s(t)=t^2-3t+2$  be the position function of a body moving on a coordinate line, with $s$  in meters and $t$  in seconds. (a) Find the body's displacement and average velocity for the time interval $0\leq t\leq 2.$  (b) Find the body's speed and acceleration at the endpoints of the time interval $0\leq t\leq 2.$  (c) When, if ever, during the time interval $0\leq t\leq 2$  does the body change direction?
::: 

::: {#exr- } 
At time $t$  the position of a body moving along the $s$ -axis is $s=t^3-6t^2-9t m.$  (a) Find the body's acceleration each time the velocity is zero. (b) Find the body's speed each time the acceleration is zero. (c) Find the total distance traveled by the body from $t=0$  to $t=2.$ 
::: 

::: {#exr- } 
A rock is thrown vertically upward from the surface of the moon at a velocity of 24 m/se (about 86 km/h) reaches a height of $s=24t-0.8t^2$  meters in $t$  sec. (a) Find the rock's velocity and acceleration at time $t.$  (b) How long does it take the rock to reach its highest point? (c) How high does the rock go? (d) How long does it take the rock to reach half its maximum height?
::: 

::: {#exr- } 
Had Galileo dropped a cannonball from the Tower of Pisa, 179 ft above the ground, the ball's height above the ground $t$  sec into the fall would have been $s=179-16t^2.$  (a) What would have been the ball's velocity, speed, and acceleration at time $t?$  (b) About how long would it have taken the ball to hit the ground? (c) What would have been the balls velocity at the moment of impact?
::: 



