---
pagetitle: "Taylor and Maclaurin Series - Exploring Calculus"
---
# Taylor and Maclaurin Series


The Taylor series of a function is a representation as power series whose terms are calculated from the values of the function's derivatives at a single point (the center). 
If the Taylor series is centered at zero, then that series is also called a Maclaurin series.
We discuss the Maclaurin series of the sine and cosine functions and examine precisely when the Maclaurin series for thses functions converges. 


## Taylor Series and Maclaurin Series

It is not a big step to extend the notions of Maclaurin and Taylor polynomials to series by not stopping the summation index at $n$. 
Thus, we have the following definition. 

::: {#def- } 
If $f$ is represented by a power series $f(x)=\sum a_n (x-c)^n$ for all $x$ in an open interval $I$ containing $c$, then
\begin{equation}
f(x) = \sum_{n=0}^\infty \frac{f^{(n)}(c)}{n!}(x-c)^n 
\end{equation}
where $f^{(0)}$ denotes $f$. 
::: 

::: {#exm- } 
Find the Maclaurin series for $f(x)=e^x$. 
::: 

::: {.solution }
The $n$th Maclaurin polynomial for $e^x$ is 
$$
p_n(x) = \sum_{k=0}^n \frac{x^k}{k!}. 
$$
Thus the Maclaurin series for $e^x$ is
$$
\sum_{n=0}^\infty \frac{x^n}{n!}. 
$$
as needed.
::: 

::: {#exm- } 
Find the Maclaurin series for $f(x)=\sin x$. 
::: 

::: {.solution }
The $n$th Maclaurin polynomial for $\sin x$ is 
$$
p_n(x) = \sum_{k=0}^n (-1)^{k}\frac{x^{2k+1}}{(2k+1)!}.
$$
Thus the Maclaurin series for $\sin x$ is
$$
\sum_{n=0}^\infty (-1)^{n}\frac{x^{2n+1}}{(2n+1)!}
$$
as needed.
::: 

::: {#exm- } 
Find the Maclaurin series for $f(x)=\cos x$. 
::: 

::: {.solution }
The $n$th Maclaurin polynomial for $\cos x$ is 
$$
p_n(x) = \sum_{k=0}^n (-1)^{k}\frac{x^{2k}}{(2k)!},
$$
Thus the Maclaurin series for $\cos x$ is
$$
\sum_{n=0}^\infty (-1)^{n}\frac{x^{2n}}{(2n)!}
$$
as needed.
::: 

::: {#exm- } 
Find the Maclaurin series for $f(x)=1/(1-x)$. 
::: 

::: {.solution }
The $n$th Maclaurin polynomial for $1/(1-x)$ is 
$$
p_n(x) = \sum_{k=0}^n x^k.  
$$
Thus the Maclaurin series for $\cos x$ is
$$
\sum_{n=0}^\infty x^n 
$$
as needed.
::: 



## Convergence of Taylor Series

Our next result is often called \index{Taylor's Theorem} and the remainder given in the theorem is called the \index{Lagrange form of the remainder} **Taylor's Theorem} and the remainder given in the theorem is called the \index{Lagrange form of the remainder** .

::: {#thm- } 
\label{tayloertheorem}
Let $f$ have derivatives of order through $n+1$ in an open interval $I$ centered at $c$, then, for each $x$ in $I$, there exists $z$ between $x$ and $c$ such that 
$$
f(x) = \sum_{n=0}^n \frac{f^{(n)}(c)}{n!}(x-c)^n  + R_n(x)
$$
where
$$
R_n(x) = \frac{f^{n+1}(z)}{(n+1)!} (x-c)^{n+1}.
$$
::: 

Given a function $f$, we know how to write its Taylor series centered at a point $c$, and we know how to find its interval of convergence. 
How do we know that the series actually converges to $f$? 
The remaining task is to determine when the Taylor series for $f$ actually converges to $f$ on its interval of convergence. 

::: {#thm- } 
\label{contay}
If $\lim_{n\to\infty} R_n=0$ for all $x$ in the interval $I$, then the Taylor series for $f$ converges and equals to $f(x)$,
$$
f(x) = \sum_{n=0}^\infty \frac{f^{(n)}(c)}{n!}(x-c)^n.
$$
::: 

::: {#exm- } 
Show that the Maclaurin series for $f(x)=e^x$ converges to $f(x)$ for all $x$. 
::: 

::: {.solution }
The Maclaurin series for $e^x$ is
$$
\sum_{n=0}^\infty \frac{x^n}{n!}
$$
which converges for all real numbers.
The Taylor remainder is
$$
R_n(x) = \frac{e^z}{(n+1)!} x^{n+1}
$$ 
for some $z$ between $x$ and $0$. 
Thus 
$$
|R_n(x)| \leq \frac{e^{|x|}}{(n+1)!} |x|^{n+1}. 
$$
Therefore, for arbitrary $x$ fixed, we find that 
\begin{align*}
\lim_{n\to \infty} \left|R_n(x)\right|
= \lim_{n\to \infty} \left|\frac{e^c}{(n+1)!} x^{n+1}\right|
= 0
\end{align*}
By \ref{contay}, the Taylor series for $e^x$ converges to $e^x$. 
::: 

::: {#exm- } 
Show that the Maclaurin series for $f(x)=\sin x$ converges to $f(x)$ for all $x$. 
::: 

::: {.solution }
The Maclaurin series for $\sin x$ is
$$
\sum_{n=0}^\infty (-1)^{n}\frac{x^{2n+1}}{(2n+1)!}
$$
which converges for all real numbers.
Notice that $f^{(n+1)}(z)=\pm \sin c$ or $f^{(n+1)}(z)=\pm \cos z$. 
In any case we have that $|f^{n+1}(z)|\leq 1$ for all real numbers $z$. 
Thus 
$$
|R_n(x)| = \frac{f^{(n+1)}(z)}{(n+1)!} |x|^{n+1} 
\leq \frac{|x|^{n+1}}{(n+1)!}. 
$$
Therefore, for arbitrary $x$ fixed, we find that 
\begin{align*}
\lim_{n\to \infty} \left|R_n(x)\right|
= \lim_{n\to \infty} \left|\frac{|x|^{n+1}}{(n+1)!}\right|
= 0
\end{align*}
By \ref{contay}, the Taylor series for $\sin x$ converges to $\sin x$. 
::: 



## Exercises

::: {#exr- } 
Find the Taylor polynomial $p_n(x)$ and the Taylor remainder $R_n(x)$ for the function $f$ and the values of $c$ and $n$. 
 - $f(x)=x^4+3x^3+2x+3$, $c=-1$, $n=4$
- $f(x)=\sqrt{x}$, $c=4$, $n=3$
- $f(x)=\cos x$, $c=\pi/4$, $n=3$
- $f(x)=\cos 2x$, $c=\pi/6$, $n=3$
 
::: 


::: {#exr- } 
Use the definition of Taylor series to find the Taylor series, centered at $c$, for the function.
 
 
- $f \displaystyle (x)=\frac{1}{x}$, $c=1$
- $ \displaystyle f(x)=x e^x$, $c=1$
- $f(x)=\sin 3x$, $c=0$
- $f(x)=e^x$, $c=1$
- $f(x) = \tan x$, $c=\pi/4$
- $\tan 2x$, $c=0$
 
 
::: 

::: {#exr- } 
Prove that the Maclaurin series for the function converges to the function for all x.
 
 - $f(x)=\sin x$
- $f(x)=e^{-x}$
- $f(x)=e^{-2x}$
- $f(x)=\sin + \cos x$
 
 
::: 

::: {#exr- } 
Use the binomial series to find the Maclaurin series for the function.
 
 - $ \displaystyle f(x)\frac{1}{\sqrt{1-x}}$
- $ \displaystyle f(x)=\frac{1}{4+x^2}$
- $ \displaystyle f(x)=\frac{1}{(1+x)^4}$
- $ \displaystyle f(x)= \sqrt[4]{1+x}$
 
 
::: 

::: {#exr- } 
Find the Maclaurin series for the function.
 
 - $ \displaystyle f(x)=e^{x^2/3}$
- $ \displaystyle f(x)=x^2 \sin x$
- $ \displaystyle g(x)=e^{-4x}$
- $ \displaystyle h(x)=\cos x^{3/2}$
- $ \displaystyle f(x)=\cos^2 x$
- $ \displaystyle h(x)=x^2 \cos x^2$
 
 
::: 



