---
pagetitle: "Trigonometric Integrals - Exploring Calculus"
---
# Trigonometric Integrals

Integrals involving powers of sine and cosine and integrals involving powers of secant and tangent are studied. We also discuss integrals of products of sine and cosine functions involving different angles. Proficiency using trigonometric identities is assumed.

## Integrals Involving Powers of Sine and Cosine

The goal now is to evaluate integrals involving trigonometric functions. 
These techniques will be indispensable we using trigonometric substitutions.  
We begin with a simple example that demonstrates some of the ideas in this sections. 

::: {#exm- } 
Evaluate $\int \sin^3 x\, dx$. 
::: 

::: {.solution }
We write $\sin^3 x = \sin^2 x\sin x= (1-\cos^2 x)\sin x$ and use this with the substitution $u=\cos x$ as follows
\begin{align*}
\int \sin^3 x\, dx 
& = \int (1-\cos^2 x)\sin x\,  dx 
= - \int (1-u^2) \, du \\
& =  -  u + \frac{1}{3} u^3 +C 
= -\cos x +\frac{1}{3} \cos^3 x +C
\end{align*}
where $C$ is an arbitrary constant. 
::: 

The identity $\sin^2x + \cos^2 x=1$ allows use to convert back and forth between powers of sine and cosine as needed. 

::: {#thm- } 
If $m$ and $n$ are positive integers, then the integral 
\begin{equation}
\int \sin^m x \cos^n x \, dx
\label{pwoersincos}
\end{equation}
can be evaluated by one of the three methods. 
 - If $m$ is odd, then split off a factor of $\sin x$, apply the identity $\sin^2 x=1-\cos^2 x$, and make the substitution $u=\cos x$. 
- If $n$ is odd, then split off a factor of $\cos x$, apply the identity $\cos^2 x=1-\sin^2 x$, and make the substitution $u=\sin x$
- If $m$ and $n$ are both even, use the identities 
$$
\sin^2 x=\frac{1}{2}(1-\cos 2x)\qquad
\cos^2 x=\frac{1}{2}(1+\cos 2x)
$$ 
to reduce the powers on $\sin x $ and $\cos x$.
 
::: 

::: {#exm- } 
Evaluate $\int_0^{\pi/3} \sin^4 3x \cos^3 3x \, dx$.
::: 

::: {.solution }
Notice that $n=3$ is odd, so we have
\begin{align*}
\int_0^{\pi/3} \sin^4 3x \cos^3 3x \, dx 
 & = \int_0^{\pi/3} \sin^43x (1-\sin^2 3x) \cos 3x \, dx \\
 & = \left[ \frac{1}{15}\sin^5 3x -\frac{1}{21} \sin^7 3x\right]_0^{\pi/3}
= 0
\end{align*}
as desired.
::: 

::: {#exm- } 
Evaluate $\int \sin^3 x \cos^2 x\, dx$.
::: 

::: {.solution }
Notice that $m=3$ is odd, so we have
\begin{align*}
\int \sin^3 x \cos^2 x\, dx 
& = \int(1-\cos^2 x) \cos^2 x \sin x\, dx \\
& = \int(\cos^2 x-\cos^4 x)\sin x \, dx 
= -\frac{1}{3}\cos^3 x+\frac{1}{5}\cos^5 x +C
\end{align*}
where $C$ is an arbitrary constant.
::: 

::: {#exm- } 
Evaluate $\int \sin^2 x \cos^4 x\, dx$.
::: 

::: {.solution }
Notice that both $m$ and $n$ are even, so we have
\begin{align*}
\int \sin^2 x\cos^4 x \, dx 
& = \frac{1}{8}\int(1-\cos 2x)(1+\cos 2x)^2 \, dx \\
& = \frac{1}{8}\int (1-\cos^2 2x)(1+\cos 2x)\, dx \\
& = \frac{1}{8}\int \sin^2 2x \, dx + \frac{1}{8}\int \sin^2 2x \cos 2x \, dx \\
& = \frac{1}{16} \int (1-\cos 4x)\, dx +\frac{1}{48} \sin^3 2x  \\
& = \frac{1}{16} x -\frac{1}{64}\sin 4x +\frac{1}{48} \sin^3 2x +C
\end{align*}
where $C$ is an arbitrary constant.
::: 




## Integrals Involving Powers of Secant and Tangent

Recall the basic formulas from before:
\begin{equation}
\frac{d}{dx}(\tan x) = \sec^2 x
\qquad 
\int \tan x \, dx = \ln |\sec x|+ C 
\end{equation}
and for the secant function 
\begin{equation}
\frac{d}{dx}(\sec x) = \sec x \tan x
\qquad 
\int \sec x \, dx =\ln |\sec x +\tan x| +C.
\end{equation}

::: {#exm- } 
Evaluate $\int \tan^3 x\, dx$. 
::: 

::: {.solution }
We use the identity $\tan^2 x = \sec^2 x-1$ and we have
\begin{align*}
\int \tan^3 x \, dx 
& = \int \tan x \tan^2 x \, dx 
=\int \tan x(\sec^2 x-1)\, dx  \\
& = \int \tan x \sec^2 x \, dx - \int \tan x \, dx 
= \frac{\tan^2 x}{2} -\ln |\sec x | + C
\end{align*}
as desired. 
::: 

::: {#thm- } 
If $m$ and $n$ are positive integers, then the integral 
\begin{equation}
\int \sec^m x \tan^n x \, dx
\label{pwoersectan}
\end{equation}
can be evaluated by one of the three methods. 
 - If $m$ is even, then split off a factor of $\sec x$, apply the identity $\sec^2 x=1+\tan^2 x$, and make the substitution $u=\tan x$. 
- If $n$ is odd, then split off a factor of $\sec^2 x$, apply the identity $\tan^2 x=\sec^2 x-1$, and make the substitution $u=\sec x$. 
- If $m$ is odd and $n$ is even, use the identity $\tan^2 x =\sec^2x -1$ and the reduction formula for powers of $\sec x$, namely 
\begin{equation}
\int \sec^n x \, dx = \frac{1}{n-1} \sec^{n-2} x \tan x +\frac{n-2}{n-1} \int \sec^{n-2} x \, dx
\end{equation}
for a positive integer $n$ great than 1.
 
::: 

::: {#exm- } 
Evaluate $\int \sec^4 x \tan^9 x \, dx$.
::: 

::: {.solution }
Notice that $m=4$ is even. 
We let $u =\tan x$ so that $du = \sec^2 x$. 
We have
\begin{align*}
\int  \sec^4 x \tan^9 x \, dx 
& = \int u^9 (u^2+1)\, du 
= \int (u^11 + u^9) \, du \\
& = \frac{u^{12}}{12} +\frac{u^{10}}{10} +C
= \frac{1}{12} \tan^{12}x +\frac{1}{10} \tan^{10} x +C
\end{align*}
where $C$ is an arbitrary constant.
::: 

::: {#exm- } 
Evaluate $\int \sec^7 x \tan^5 x \, dx$.
::: 

::: {.solution }
Notice that $n=5$ is odd. 
We let $u =\sec x$ so that $du = \sec x \tan x$. 
We have
\begin{align*}
\int \sec^7 x \tan^5 x \, dx 
& = \int \tan^4 x \sec^6 x \sec x\tan x \, dx \\
&= \int (\sec^2 x-1)^2 \sec^6 x\sec x \tan x\, dx \\
& = \int (u^2 -1)^2 u^6 \, du = \int (u^{10}-2u^8 +u^6)\, du \\
& = \frac{u^{11}}{11} -2\left(\frac{u^9}{9}\right) +\frac{u^7}{7} +C \\
& = \frac{1}{11} \sec^{11} x -\frac{2}{9} \sec^9 x +\frac{1}{17} \sec x +C
\end{align*}
where $C$ is an arbitrary constant.
::: 





## Integrals Involving Products of Different Angles

Integral involving product of sine and cosines functions with different angle we will make use the trigonometric formulas:
\begin{align}
& \sin m x \, \sin n x =\frac{1}{2}\left(\cos[(m-n)x] - \cos[(m+n)x]\right) \\
& \sin m x \, \cos n x =\frac{1}{2}\left(\sin[(m-n)x] + \sin[(m+n)x]\right) \\
& \cos m x \, \cos n x =\frac{1}{2}\left(\cos[(m-n)x] + \cos[(m+n)x]\right)
\end{align}


::: {#exm- } 
Evaluate $\int \sin 5x \sin 7x \, dx$.
::: 

::: {.solution }
We have 
\begin{align*}
\int \sin 5x \sin 7x \, dx
& = \frac{1}{2}\left(\cos(-2x)\, dx -\int \cos 12x \, dx\right) \\
&  = \frac{1}{2}\left(\cos 2x\, dx -\int \cos 12x \, dx\right) \\
& = \frac{1}{2} \left(\frac{\sin 2x }{2} -\frac{\sin 12 x}{12}\right) +C \\
& = \frac{\sin 2x}{4}- \frac{\sin 12x }{24} +C
\end{align*}
where $C$ is an arbitrary constant.
::: 

::: {#exm- } 
Evaluate $\int \sin 3x \cos 7x \, dx$.
::: 

::: {.solution }
We have 
\begin{align*}
\int \sin 3x \cos 7x \, dx
& = \frac{1}{2}\left(\sin (-4x)\, dx +\int \sin 10x \, dx\right) \\
& = \frac{1}{2}\left(\frac{\cos(-4x)}{4} - \frac{\cos 10x }{10}\right) +C \\
& = \frac{\cos 4x}{8}-\frac{\cos 10x}{20}+ C
\end{align*}
where $C$ is an arbitrary constant.
::: 

::: {#exm- } 
Evaluate $\int \cos x \cos 2x \, dx$.
::: 

::: {.solution }
We have 
\begin{align*}
\int \cos x \cos 2x \, dx
& = \frac{1}{2}\left(\int \cos(-x)\, dx+ \int \cos 3x \, dx\right) \\
& = \frac{\sin x}{2}+\frac{\sin 3x}{6} + C
\end{align*}
where $C$ is an arbitrary constant.
::: 





## Exercises

::: {#exr- } 
Evaluate the integrals.
 
 
- $\ds\int_0^\pi \sin^5 \left(\frac{x}{2}\right) \, dx$
- $\ds\int \sin^6 x \cos^3 x \, dx$
- $\ds\int \sin^3 x \cos x\, dx$
- $\ds\int_{-\pi/2}^{\pi/2} \cos^3 x \, dx$
- $\ds\int_{0}^{\pi/2} \cos^5 x \, dx$
- $\ds\int \cos^4 x \, dx$
- $\ds\int_0^\pi \sin^4 (3t)\, dt$
- $\ds\int_0^\pi 8 \sin^4 y \cos^2 y \, dy$
- $\ds\int_0^\pi \cos^6 \theta\, d\theta$
- $\ds\int_0^\pi \sin^2 x \cos^4 x \, dx$
- $\ds\int_0^{\pi/4} 8 \cos^3 2\theta \sin 2 \theta \, d\theta$
- $\ds\int_0^\pi \sin^2 t \cos^4 t \, dt$
- $\ds\int x \cos^2 x\, dx$
- $\ds\int e^x \sec^3 e^x \, dx$
- $\ds\int_{\pi/4}^{\pi/2} \cot^3 x \, dx$
 
 
::: 

::: {#exr- } 
Evaluate the integrals.
 
 
- $\ds\int_0^{\pi/2} \sin x \cos x\, dx$
- $\ds\int \sin 3 \theta \sin 4\theta\, d\theta$
- $\ds\int \cot^3 x \csc^3 x \, dx$
- $\ds\int_0^\pi \cos 3x \cos 4x \, dx$
- $\ds\int \frac{\sin^3 x }{\sec^2 x} \, dx$
- $\ds\int (\tan^2 +\tan^4 x)\, dx$
- $\ds\int \frac{\cos x+ \sin x }{\sin 2x}\, dx$
- $\ds\int_{-\pi/2}^{\pi/2} \cos x \cos 7x \, dx$
- $\ds\int \frac{1}{\csc x\cot^2 x}\, dx$
- $\ds\int \frac{1}{\cos x -1}\, dx$
- $\ds\int \frac{1-tan^x}{\sec^2 x}\, dx$
- $\ds\int \sin 3x \sin 6x \, dx$
 
 
::: 

::: {#exr- } 
Find the length of the curve $y = \ln (\cos x)$ on the interval $\left[0,\frac{\pi}{3}\right]$.
::: 

::: {#exr- } 
Find the are under the graph of $y=\sin^2 \pi x$ on the interval $[0,1]$. 
::: 

::: {#exr- } 
Find the area of the region bounded by the curves $y=\sin^2 x$ and $y=\cos^2 x$ on $-\pi/4 \leq x \leq \pi/4$.
::: 

::: {#exr- } 
Find the area enclosed by the graphs of $y =\sin^4 x$, $y=\cos^4 x$, $x=0$, and $x=\pi/4$. 
::: 

::: {#exr- } 
Find the volume of the solid generated by revolving the region under the graph of 
$$
f(x)= \frac{\sin x}{\cos^3 x}
$$
on $\left[0, \frac{\pi}{4}\right]$ about the $x$-axis. 
::: 

::: {#exr- } 
Evaluate $\int \sin x \cos x \, dx$ four different ways. 
Two of them using $u$-substitutions, a third using integration by parts and a fourth using a trigonometric identity. 
::: 

::: {#exr- } 
Prove that 
$$
\int_{-\pi}^{\pi} \sin mx \cos nx \, dx =0
$$ where $m$ and $n$ are positive integers. 
::: 

::: {#exr- } 
Prove that 
$$
\int \cos^m x\sin^n x \, dx = -\frac{\cos^{m+1} x\sin^{n-1} x}{m+n} + \frac{n-1}{m+n} \int \cos^m x \sin^{n-2} x \, dx 
$$
where $m$ and $n$ are positive integers. 
::: 

::: {#exr- } 
Prove that 
$$
\int \sec^n x \, dx = \frac{1}{n-1} \sec^{n-2} x \tan x +\frac{n-2}{n-1} \int \sec^{n-2} x \, dx
$$ 
where $n$ is a positive integers. 
::: 



