---
pagetitle: "Volumes of Solids of Revolution - Exploring Calculus"
---
# Volumes of Solids of Revolution

 
Finding the volume of the solid generated by rotating a bounded planar region about an axis of rotation is discussed. We cover the disk method, the washer method, and method of cylindrical shells. We provide several examples of solids generated by revolving around both vertical and horizontal lines.

The solid generated by rotating a plane region about an axis in its plane is called a \index{solid of revolution} **solid of revolution** . 

::: {#def- } 
The \index{volume} **volume**  of a solid of known integrable cross-sectional area $A(x)$ from $x=a$ to $x=b$ is the integral of $A$ from $a$ to $b$,
\begin{equation}
\label{defvol}
V=\int_a^b A(x) \, dx
\end{equation}
::: 

Throughout our discussion we assume that $A(x)$ is integrable and in particular, we assume that the reader is familiar with the Fundamental Theorem of Calculus. 



## The Disk Method


::: {#thm- } \label{Disk Method: Horizontal Axis}
Let $A(x)$ be the cross-sectional area of a disk of radius $R(x)$, the distance of the planar regions's boundary from the axis of revolution. 
The volume of the solid of revolution about the $x$-axis is 
\begin{equation}
V = \int_a^b A(x) \, dx = \int_a^b \pi [ R(x) ]^2 \, dx.
\end{equation}
::: 

::: {#exm- } 
Find the volume of the solid that results when the region enclosed by $y=9-x^2$ and $y=0$
 is revolved about the $x$-axis. 
::: 

::: {.solution }
First we sketch the region bounded by the given curves. 
We use $R(x)=9-x^2$ and find the volume 
\begin{align*}
V & = \pi \int_{-3}^3 (9-x^2)^2 \, dx \\
& = \pi \int_{-3}^3 (81-18x^2+x^4) \, dx 
= \frac{1296\pi}{5}
\end{align*}
as desired. 
::: 

::: {#exm- } 
Find the volume of the solid generated when the region bounded by the graph of $f(x)=\sqrt{x}+1$ and the line $y=2$ on the interval $[0,1]$, is revolved about the line $y=2$.
::: 

::: {.solution }
First we sketch the bounded region. 
The radius is given by 
\begin{equation}
R(x)= 2-(\sqrt{x}+1) = 1-\sqrt{x}
\end{equation}

We find the volume using the Disk Method
\begin{align*}
V = \pi \int_0^1(1-\sqrt{x})^2 \, dx = \pi \int_0^1 (1-2\sqrt{x}+x) \, dx = \frac{\pi}{6}
\end{align*}
as desired.
::: 





::: {#thm- } \label{Disk Method: Vertical Axis}
Let $A(y)$ be the cross-sectional area of a disk of radius $R(y)$, the distance of the planar regions's boundary from the axis of revolution. 
The volume of the solid of revolution about the $y$-axis is 
\begin{equation}
V = \int_a^b A(y) \, dy = \int_a^b \pi [ R(y) ]^2 \, dy.
\end{equation}
::: 

::: {#exm- } 
Find the volume of the solid that results when the region enclosed by the curves $y=0$, $y=\ln x$, $y=2$, and $x=0$ is revolved about the $y$-axis.
::: 

::: {.solution }
First we sketch the bounded region. 
The radius is given by $R(y)=e^y$. 

We find the volume using the Disk Method
\begin{equation}
V= \pi \int_0^2 e^{2y} \, dy = \frac{\pi(e^4-1)}{2}
\end{equation}
as desired.
::: 

::: {#exm- } 
Find the volume of the solid that results when the region enclosed by $y=\sqrt{x}$, $y=0$, and $x=9$ is revolved about the line $x=9$.
::: 

::: {.solution }
First we sketch the bounded region. 
The radius is given by ${R(y)=9-y^2}$. 

We find the volume using the Disk Method
\begin{align*}
V & = \pi \int_0^3 (9-y^2)^2 \, dy \\
& = \pi \int_0^3 (81-18y^2+y^4)\, dy 
= \frac{648\pi}{5}
\end{align*}
as desired. 

::: 

## The Washer Method


::: {#thm- } \label{Washer Method: Horizontal Axis}
Let $A(x)$ be the cross-sectional area of a disk of outer radius $R(x)$ and inner radius r(x).  
The volume of the solid of revolution about the $x$-axis is 
\begin{equation}
V = \int_a^b A(x) \, dx =  \int_a^b \pi \left( [ R(x) ]^2 - [ r(x) ]^2 \right) \, dx.
\end{equation}
::: 

::: {#exm- } 
Use the washer method to find the volume of the solid generated when the region bounded by $y=x$ and $y=2\sqrt{x}$ is revolved about the $x$-axis. 
::: 

::: {.solution }
First we sketch the bounded region. 
The outer radius is $R(x)=2\sqrt{x}$ and the inner radius is $r(x)=x$.

We find the volume using the Washer Method
\begin{align*}
V & = \pi \int_0^4 ( (2\sqrt{x})^2-x^2)\, dx \\
& = \pi \left.(2x^2-x^3/3)\right\vert_0^4 = \pi(32-64/3) = \frac{32\pi}{3}. 
\end{align*}
as desired.
::: 

::: {#exm- } 
Find the volume for the region bounded by the graphs of $y=2\sin x$ and the $x$-axis on $[0,\pi]$ is revolved around the line $y=-2$.
::: 

::: {.solution }
First we sketch the bounded region. 

The washer has outer radius $R(x)=2+2\sin x$ and inner radius $2$, so using the Washer Method the volume is 
\begin{align*}
V & = \pi \int_0^\pi ((2+2\sin x)^2 -2^2) \, dx = \pi \int_0^8 (8\sin x+4\sin^2 x)\, dx \\
& = \pi \int_0^8 (8\sin x+2(1-\cos 2x))\, dx = \pi \left.(-8\cos x+2x-sin 2x)\right\vert_0^\pi \\
& = \pi(8+2\pi+8) = 2\pi (\pi +8)
\end{align*}
as desired. 
::: 

::: {#thm- } \label{Washer Method: Vertical Axis}
Let $A(y)$ be the cross-sectional area of a disk of outer radius $R(y)$ and inner radius r(y).  
The volume of the solid of revolution about the $y$-axis is 
\begin{equation}
V = \int_c^d A(y) \, dy = \int_c^d \pi \left( [ R(y) ]^2 - [ r(y) ]^2 \right) \, dy.
\end{equation}
::: 

::: {#exm- } 
Find the volume of the solid that results when the region enclosed by the curves $x=1-y^2$, $x=2+y^2$, $y=1$, $y=-1$ is revolved about the $y$-axis.
::: 

::: {.solution }
First we sketch the bounded region. 

The washer has outer radius $R(y)=2+y^2$ and inner radius $r(y)=1-y^2$, so using the Washer Method the volume is 
\begin{align*}
V & = \pi \int_{-1}^1 [(2+y^2)^2-(1-y^2)^2] \, dy \\
& = \pi \int_{-1}^1 (3+6y^2) \, dy 
= 10\pi
\end{align*}
as desired. 
::: 

::: {#exm- } 
Find the volume of the solid generated by the region bounded by $y=\ln x$ and the $y$-axis on the interval $0\leq y \leq 1$ and is revolved about the line $x=-1$. 
::: 

::: {.solution }
First we sketch the bounded region. 

The washer has outer radius $R(y)=1+e^y$ and inner radius $r(y)=1$, so using the Washer Method the volume is 
\begin{align*}
V & = \pi \int_0^1 ((e^y+1)^2-1^2) \, dy \\
& = \pi \int_0^1 (2 e^y +e^{2y}) \, dy 
= \pi \left.\left( 2e^y +\frac{1}{2} e^{2y}\right)\right\vert_0^1 \\
&  = \pi \left(2e+\frac{1}{2} e^2 -\frac{5}{2}\right) = \frac{\pi}{2} (e^2+4e-5).
\end{align*}
as desired. 
::: 







## The Shell Method


::: {#thm- } \label{Shell Method: Vertical Axis}
Let $f$ be a continuous nonnegative function of $x$ on $[a,b]$, where $0\leq a\leq b$, and let $R$ be the region under  the graph of $f$ on the interval $[a,b]$.
The volume $V$ of the solid of revolution generated by revolving $R$ about the $y$-axis is
\begin{equation}
\label{shellmethod}
V = \lim_{n\to \infty} \sum_{k=1}^n 2\pi c_k f(c_k) \Delta x = \int_a^b 2\pi x f(x) \, dx.
\end{equation}
::: 

::: {#exm- } 
Find the volume of the solid obtained by rotating about the $y$-axis the region bounded by $y=2x^2-x^3$ and $y=0$. 
::: 

::: {.solution }
First we sketch the bounded region. 

The circumference is $2\pi x$ and height is $f(x)=2x^2-x^3$ so by the Shell Method the volume is 
\begin{align*}
V & = \int_0^2 (2\pi x)(2x^2-x^3) \, dx 
= 2\pi \int_0^2 (2x^3-x^4) \, dx = \frac{16}{5}\pi
\end{align*}
as desired. 
::: 

::: {#exm- } 
Find the volume of the solid formed by revolving the region bounded by the graphs of $y=x^3+x+1$, $y=1$, and $x=1$ about the line $x=2$. 
::: 

::: {.solution }
First we sketch the bounded region. 

Notice the variable of integration should be $x$ and so we find the volume using the Shell Method, 
\begin{align*}
V & = 2\pi \int_0^1 (2-x)(x^3+x+1-1)\, dx \\
& = 2\pi \int_0^1 (-x^4+2x^3-x^2+2x)\, dx 
= \frac{29\pi}{15}
\end{align*}
as desired. 
::: 

::: {#thm- } \label{Shell Method: Horizontal Axis}
Let $f$ be a continuous nonnegative function of $y$ on $[c,d]$, where $0\leq c\leq d$, and let $R$ be the region bounded by the graph of $f$ on the interval $[c,d]$ and the $y$-axis. 
The volume $V$ of the solid of revolution generated by revolving $R$ about the $x$-axis is
\begin{equation}
V = \lim_{n\to \infty} \sum_{k=1}^n 2\pi a_k f(a_k) \Delta y = \int_c^d 2\pi y f(y) \, dy.
\end{equation}
::: 

::: {#exm- } 
The region bounded by the curve $y=\sqrt{x}$, the $x$-axis, and the line $x=4$ is revolved about the $x$ axis to generate a solid.
Find the volume of the solid.  
::: 

::: {.solution }
First we sketch the bounded region. 

We find the volume using the Shell Method
\begin{align*}
V & = \int_0^2 2\pi y (4-y^2)\, dy 
= \int_0^2 2\pi (4y-y^3)\, dy = 8 \pi
\end{align*}
as desired. 
::: 

::: {#exm- } 
The region bounded by the curve $y=x^2$, the $x$-axis, and the line $x=1$ is revolved about the line $y=2$ to generate a solid. 
Find the volume of the solid.  
::: 

::: {.solution }
First we sketch the bounded region. 

\begin{align*}
V & = 2\pi \int_0^1 (2-y)(1-\sqrt{y}) \, dy  \\
& = 2\pi \int_0^1 (2-y-2y^{1/2}+y^{3/2})\, dy 
= \frac{17\pi}{15}
\end{align*}
as desired. 
::: 

## Exercises

::: {#exr- } 
Find the volumes of the solids generated by revolving the regions bounded by the lines and curves about the the given axis.
 - $y=x^2+1$, $y=x+3$, about the $x$-axis
- $y=4-x^2$, $y=2-x$, about the $x$-axis
- $x=1/y$, $x=0$, $y=1$, $y=2$, about the $y$-axis
- $x=\sqrt{4-y^2}$, $x=0$, $y=0$, about the $y$-axis
::: 

::: {#exr- } 
Use the disk method to verify that the volume of a sphere is $\frac{4}{3} \pi r^2$, where $r$ is the radius. 
::: 

::: {#exr- } 
Use the disk method to verify that the volume of a cone is $\frac{1}{3} \pi r^2 h$, where $r$ is the radius of the base and $h$ is the height. 
::: 


::: {#exr- } 
Find the volume of the solid generated by revolving the region bounded by $y=\sqrt{x}$ and the lines $y=2$ and $x=0$ about 
 
 - the $x$-axis
- the line $y=2$
- the $y$-axis
- the line $x=4$
 
::: 

::: {#exr- } 
Find the volume of the solid region.
The solid lies between planes perpendicular to the $x$-axis at $x=0$ and $x=4$.
The cross-sections perpendicular to the axis on the interval $0\leq x \leq 4$ are squares whose diagonals run form the parabola $y-\sqrt{x}$ to the parabola $y=\sqrt{x}$. 
::: 

::: {#exr- } 
Find the volume of the solid generated by revolving the region bounded by $y=4+2x-x^2$ and the line $y=4-x$. 
 
 - the $x$-axis
- the line $y=1$
 
::: 

::: {#exr- } 
Using integration, find the volume of the solid generated by revolving the triangular region with vertices $(0,0), (b,0), (0,h)$ about
 
 - the $x$-axis
- the $y$-axis
 
::: 


::: {#exr- } 
Find the volume of the solid generated by revolving the region bounded by the graphs of the equations about the indicated line.
 - $y=x$, $y=x^2$, the line $y=2$
- $y=x^2$, $y=\frac{1}{2} x^2+2$, about the line $y=5$
- $x=\sqrt{9-y^2}$, $x=0$, $y=0$, about the $x$-axis
- $y=\sqrt{x-1}$, $y=x-1$, about the $y$-axis
- $x=y-y^2$, $x=0$; about the $y$-axis
- $y=1/x$, $y=0$, $x=1$, $x=3$, about the line $y=-1$
- $y=x$, $y=0$, $x=2$, $x=4$, about the line $x=1$
::: 


::: {#exr- } 
Use the shell method to find the volume of the solids generated by revolving the regions bounded by the curves and lines.
 - $x=1+y^2$, $x=0$, $y=1$, $y=2$, about the $x$-axis
- $x=1+(y-2)^2$, $x=2$, about the $x$-axis
- $y=\sqrt{9-x^2}$, $y=\frac{2}{3}\sqrt{9-x^2}$, $x\geq 0$, about the $y$-axis
- $y=x^2+1$, $y=0$, $x=0$, $x=2$, about the line $x=3$
- $y=\frac{1}{\sqrt{2\pi}} e^{-x^2/2}$, $y=0$, $x=0$, $x=1$, about the $y$-axis
- $y=\frac{1}{3} x^2$, $y=6x-x^2$, about the line $x=3$
::: 

::: {#exr- } 
Let $f$ be the function defined by 
\begin{equation}
f(x) =\begin{cases}
\sqrt{x} & \text{ if $0\leq x \leq 1$} \\
x^2-2x+2 & \text{ if $1< x \leq 2$.}
\end{cases}
\end{equation}
Find the volume of the solid generated by revolving the region under the graph of $f$ on $[0,2]$ about the $x$-axis.
::: 

::: {#exr- } 
Compute the volume of the solid generated by revolving the region bounded by $y=x$ and $y=x^2$ about each coordinate axis using 
 
 - the shell method
- the washer method
 
::: 

::: {#exr- } 
Compute the volume of the solid generated by revolving the triangular region bounded by the lines $2y=x+4$, $y=x$, and $x=0$ about  
 
 - the $x$-axis using the washer method
- the $y$-axis using the shell method
- the line $x=4$ using the shell method
- the line $y=8$ using the washer method
 
::: 

::: {#exr- } 
Each integral represents the volume of a solid. 
Describe the solid. 
 - $2\pi \int_0^2 \frac{y}{1+y^2} \, dy$
- $\int_0^{\pi/4} 2\pi (\pi-x) (\cos x -\sin x) \, dx$
- $\pi \int_{-r}^r [(R+\sqrt{r^2-x^2})^2 -(R-\sqrt{r^2-x^2})^2 ] \, dx$
::: 

::: {#exr- } 
Use the disk method or the shell method to find the volumes of the solid generated by revolving the region bounded by the graphs of $y=10/x^2$, $y=0$, $x=1$, $x=5$. 
 
 - the $x$-axis
- the $y$-axis
- the line $y=10$
 
::: 

::: {#exr- } 
Use the disk method or the shell method to find the volumes of the solid generated by revolving the region bounded by the graphs of $x^{1/2}+y^{1/2}=a^{a^1/2}$, $x=0$, $y=0$.  
 
 - the $x$-axis
- the $y$-axis
- the line $x=a$
 
::: 

::: {#exr- } 
A solid has a circular base of radius 2, and its parallel cross-sections perpendicular to its base are isosceles right triangles oriented so that the endpoints of the hypotenuse of a triangle lie on the circle. 
Find the volume of the solid.
::: 

::: {#exr- } 
The region in the first quadrant that is bounded above by the curve $y=1/\sqrt{x}$ on the left by the line $x=1/4$, and below by the line $y=1$ is revolved about the $y$-axis to generate a solid. Find the volume of the solid by 
 
 - the washer method
- the shell method
 
::: 


::: {#exr- } 
Use the method of cylindrical shells to find the volume of the ellipsoid obtained by revolving the elliptical region enclosed by the graph of 
\begin{equation}
\frac{x^2}{a^2}+ \frac{y^2}{b^2} =1, \quad x\geq 0
\end{equation}
about the $y$-axis. 
::: 

::: {#exr- } 
Set up an integral for the volume of a solid \index{torus} **torus**  (doughnut) with radii $r$ and $R$.
By interpreting the integral as an area, find the volume of the torus. 
::: 

::: {#exr- } 
A bowl is shaped like a hemisphere with diameter 30 cm. 
A ball with diameter 10 cm is placed in the bowl and water is poured into the bowl to a depth of $h$ centimeters. 
Find the volume of water in the bowl.
::: 

::: {#exr- } 
A hole of radius $r$ is bored through the center of a sphere of radius $R>r$. 
Find the volume of the remaining portion of the sphere. 
::: 



