# Multivariable Calculus

project:
  type: book
  resources: 
    - assets
    - images
  post-render: 
    - ../_webtools/html_revise_mvc.py

book:
  title: "Multivariable Calculus"
  chapters:
    - index.qmd
    - vector-functions.qmd
    - limits-and-continuity.qmd
    - differentiation.qmd
    - applications-of-derivatives.qmd
    - double-integrals.qmd
    - triple-integrals.qmd
    - vector-fields.qmd
    - line-integrals.qmd
    #- surface-integrals.qmd
    #- electromagnetism.qmd
    - references.qmd
  sidebar:
    title: "Multivariable Calculus"
  site-url: https://directknowledge.com/multivariable-calculus/
  description: "Multivariable Calculus"  

metadata-files:
  - ../_meta/book-html.yml
  - ../_meta/format.yml
  #- _meta/_book-epub.yml
  #- _meta/_book-hardcover.yml
  - _meta/_book-paperback.yml
