---
pagetitle: "Derivatives and Integrals of Vector Functions - Exploring Calculus"
---
# Derivatives and Integrals of Vector Functions



## Derivatives of Vector Functions

As with functions of one variable we define the derivative as the limit of a difference quotient; and then we develop a theorem which allows us to compute derivatives based on previously known differentiation rules.  
Recall the definition of difference quotient from single variable calculus, namely, the difference quotient of $y=f(x)$ with respect to a change $\Delta x$ in $x$ is defined by 
$$
\frac{f(x+\Delta x)-f(x)}{\Delta x}.
$$
We now generalize this idea to vector functions. 


::: {#def- } 
The \index{difference quotient} **difference quotient** of a vector function $\vec{F}$ is the vector function 
$$
\frac{\Delta  \vec{F}}{\Delta  t}=\frac{\vec{F}(t+\Delta  t)-\vec{F}(t)}{\Delta  t}
$$ 
where $\Delta  t$ is an increment of the variable $t.$
::: 

Notice that if the component functions of a vector function $\vec{F}$ are $f_1$, $f_2$, and $f_3$, then 
\begin{equation}
\label{diffvec}
\frac{\Delta  \vec{F}}{\Delta x}
=\frac{\Delta f_1}{\Delta x} \vec{i} +\frac{\Delta f_2}{\Delta x} \vec{j}+\frac{\Delta f_3}{\Delta x} \vec{k}
\end{equation}

In light of \ref{diffvec}, the definition of the derivative of vector function seems natural. 


::: {#def- } 
\label{vecdefn}
The \index{derivative} **derivative** of a vector function $\vec{F}$ is the vector function $\vec{F}\,'$ defined as the limit   
$$
\vec{F}\,'(t)=\lim_{\Delta  t\to 0} \frac{\Delta \vec{F}}{\Delta  t}=\lim_{\Delta  t\to 0} \frac{\vec{F}(t+\Delta  t)-\vec{F}(t)}{\Delta  t}
$$ 
provided this limit exists. If $\vec{F}\,'(t)$ exists for a given value of $t$, then we say $\vec{F}$ is \index{differentiable} **differentiable**  at $t$.
::: 

::: {#lem- } [Differentiable Vector Functions]
\label{vfder}
Any vector function   
$$
\vec{F}(t)=f_1(t) \vec{i}+f_2(t) \vec{j}+f_3(t) \vec{k}
$$ 
is differentiable whenever the component functions $f_1$, $f_2$, and $f_3$ are each differentiable and in this case 
$$
\vec{F}\, '(t)=f_1'(t) \vec{i} +f_2'(t) \vec{j}+f_3'(t)\vec{k}.
$$
::: 
 

::: {.proof }
By the definition of the derivative of a vector function and \ref{diffvec} we find that 
\begin{align*}
\vec{F}\, '(t) 
& =\lim_{\Delta  t\to 0} \frac{\vec{F}(t+\Delta  t)-\vec{F}(t)}{\Delta  t} 
\\
& = \lim_{\Delta  t\to 0} \left[ \frac{\Delta f_1}{\Delta x} \vec{i} +\frac{\Delta f_2}{\Delta x} \vec{j}+\frac{\Delta f_3}{\Delta x} \vec{k} \right] \\
& = \left(\lim_{\Delta  t\to 0} \frac{\Delta f_1}{\Delta x} \right) \vec{i} +   \left(\lim_{\Delta  t\to 0} \frac{\Delta f_2}{\Delta x} \right) \vec{j}+  \left( \lim_{\Delta  t\to 0} \frac{\Delta f_3}{\Delta x} \right) \vec{k}
\end{align*}
By the hypothesis that the component functions $f_1$, $f_2$, and $f_3$ are each differentiable we have 
$$
\vec{F}\, '(t) = f_1'(t) \vec{i} +f_2'(t) \vec{j}+f_3'(t)\vec{k}.
$$ 
as needed. 
::: 


::: {#exm- } 
Find the derivative of the vector function 
$$
\vec{F}(t)=(\ln  t)\vec{i}+\frac{1}{2}t^3\vec{j}-t \vec{k}.
$$
::: 
  
::: {.solution }
By \ref{vfder}, we find that
$$
\vec{F}\, '(t)=\frac{1}{t}\vec{i}+\frac{3}{2}t^2\vec{j}-\vec{k}
$$  
is the derivative is the vector function $\vec{F}$.
::: 

::: {#lem- } [Derivative Rules for Vector Functions]
\label{VFD}
If the vector functions $\vec{F},$ $\vec{G}$ and the scalar function $h$ are differentiable at $t$, and if $a$ and $b$ are constants, then $a \, \vec{F}+b\,  \vec{G},\vec{F}\cdot \vec{G}, \text{and}\text{  }\vec{F}\times \vec{G}$ are differentiable at $t$ and,  
 
- $(a \, \vec{F}+b \, \vec{G})'(t)=a \, \vec{F}\, '(t)+b \, \vec{G}'(t)$ 
- $(h \, \vec{F})'(t)=h'(t)\vec{F}(t)+h(t)\vec{F}\, '(t)$  
- $(\vec{F}\cdot \vec{G})'(t)=\vec{F}\, '(t)\cdot \vec{G}(t)+\vec{F}(t)\cdot \vec{G}'(t)$ 
- $(\vec{F}\times \vec{G})'(t)=\vec{F}\, '(t)\times \vec{G}(t)+\vec{F}(t)\times \vec{G}'(t)$  
- $\vec{F}(h(t))'=h'(t)\vec{F}\, '(h(t)).$  
 
::: 

::: {.proof }
The proof is left for the reader.
::: 


::: {#exm- } 
Compute the derivative of the vector function given by $\vec{F}(t)\times \vec{G}(t)$ where $\vec{F}(t)=t^2\vec{i}+t \vec{j}+\vec{k}$ and $\vec{G}(t)=\vec{i}+t \vec{j}+t^2\vec{k}.$ 
::: 

::: {.solution }
By  \ref{VFD}, we find
\begin{align*}
& [\vec{F}(t)\times \vec{G}(t)]'=\vec{F}\, '(t)\times \vec{G}(t)+\vec{F}(t)\times \vec{G}'(t) \\
&  \qquad =\left[(2t \vec{i}+\vec{j})\times \left(\vec{i}+t \vec{j}+t^2\vec{k}\right)\right]+\left[\left(t^2\vec{i}+t \vec{j}+\vec{k}\right)\times ( \vec{j}+2t \vec{k})\right] \\
&  \qquad = \left|
\begin{array}{ccc}
 \vec{i} & \vec{j} & \vec{k}  \\
 2 t & 1 & 0 \\  
 1 & t & t^2 \\
\end{array}
\right| + \left| 
\begin{array}{ccc}
 \vec{i} & \vec{j} & \vec{k}  \\
 t^2 & t & 1 \\  
 0 & 1 & 2t
\end{array}
\right| \\
&  \qquad 
=\left(3t^2-1\right)\vec{i}-4t^3\vec{j}+\left(3t^2-1\right)\vec{k}. 
\end{align*}
::: 


## Tangent Vectors

::: {#thm- } [Tangent Vectors]
Suppose $\vec{F}(t)$ is differentiable at $t_0$ and that $\vec{F}'\left(t_0\right)\neq 0.$ Then $\vec{F}'\left(t_0\right)$ is a tangent vector to the graph of $\vec{F}(t)$ at the point where $t=t_0$ and points in the direction of increasing $t$.  
::: 
 
::: {.proof }
Let $t_0$ be a number in the domain of the vector function $\vec{F}$, and let $P$ be the point on the graph of $\vec{F}$ that corresponds to $t_0$. Then for any positive number $\Delta t$, the difference quotient 
$$
\frac{\Delta \vec{F}}{\Delta t}=\frac{\vec{F}(t+\Delta t)-\vec{F}(t)}{\Delta t}
$$ 
is a vector that points in the same direction as the secant vector 
$$
P Q=\vec{F}\left(t_0+\Delta t\right)-\vec{F}\left(t_0\right)
$$
where $Q$ is the point on the graph of $\vec{F}$ that corresponds to $t=t_0+\Delta  t$. Suppose the difference quotient $\Delta \vec{F}/\Delta t$ has a limit as $\Delta  t\to 0$ and that 
$$
\lim_{\Delta \to 0} \frac{\Delta \vec{F}}{\Delta t}\neq 0.
$$
Then, as $\Delta  t\to 0$, the direction of the \index{secant vector} **secant vector**, $P Q$, and hence that of the difference quotient $\Delta \vec{F}\Delta  t$, will approach the direction of the tangent vector of $P$. Thus we expect the tangent vector at $P$ to be the limit vector 
$$
\lim_{\Delta \to 0} \frac{\Delta \vec{F}}{\Delta t}
$$ 
which is the vector derivative $\vec{F}'\left(t_0\right).$ 
::: 
 

::: {#exm- } 
Find a tangent vector at the point where $t=2$ for   
$$
\vec{F}(t)=\left(t^2+t\right)\vec{i}-e^t\vec{j}+\sqrt{t}\vec{k}.
$$ 
Also find parametric equations for the tangent line to the graph of $\vec{F}$ that passes through the point corresponding to $t=2$. 
::: 

::: {.solution }
Using \ref{vfder}, we find a tangent vector
$$
\vec{F}\, '(2)=\left.(2t+1)\vec{i}-e^t\vec{j}+\frac{1}{2\sqrt{t}}\vec{k}\right|_{t=2}=5\vec{i}-e^2\vec{j}+\frac{1}{2\sqrt{2}}\vec{k};
$$
and the tangent line to the graph of $\vec{F}(t)$ for $t=2$ is the line that passes through the point $\left(6,-e^2,\sqrt{2}\right)$ and is determined
by the parametric equations 
$$
x(t)=6+5t, \quad y(t)=-e^2-e^2t, \quad \text{ and  } \quad z(t)=\sqrt{2}+\frac{1}{2\sqrt{2}}t
$$ 
because this line passes through $\vec{F}(2)=6\vec{i}-e^2\vec{j}+\sqrt{2}\vec{k}$ and is parallel to the tangent vector at $t=2.$
::: 


::: {#exm- } 
Find parametric equations for the tangent line to the graph of  
$$
\vec{R}(t)=t e^{-2t}\vec{i}+t^2\vec{j}+t e^{-2t}\vec{k}
$$
at the highest point on the graph.  
::: 
  
::: {.solution }
We want $\frac{d z}{d t}=0$ where $z=t e^{-2t}$ and since   
$\frac{dz}{dt}=e^{-2t}-2t e^{-2t}$  
we find that $t=1/2.$ Further,  
$$
\vec{R}'(t)=\left(e^{-2t}-2t e^{-2t}\right)\vec{i}+2t \vec{j}+\left(e^{-2t}-2t e^{-2t}\right)\vec{k}
$$ 
and so  
$$
\vec{R}'\left(\frac{1}{2}\right)=\left(e^{-1}- e^{-1}\right)\vec{i}+\vec{j}+\left(e^{-1}- e^{-1}\right)\vec{k}=0\vec{i}+\vec{j}+0\vec{k}.
$$ 
Also, 
$$
\vec{R}\left(\frac{1}{2}\right)=\frac{1}{2e^{1/2}}\vec{i}+\frac{1}{4}\vec{j}+\frac{1}{2e}\vec{k}
$$ 
and therefore, 
$$
x(s)=\frac{1}{2e}, \quad y(s)=s+\frac{1}{4}, \quad z(s)=\frac{1}{2e}.
$$ 
are the parametric equations for the tangent line at the highest point.
::: 

## Unit Tangent and Unit Normal Vectors


::: {#def- } 
If  the graph of the vector function $\vec{R}(t)$ is smooth, then at each point $t$ a \index{unit tangent vector} **unit tangent vector**  is defined by 
$$
\vec{T}(t)=\frac{\vec{R}'(t)}{\norm{\vec{R}'(t)}}
$$ 
and the principal \index{unit normal vector function} **unit normal vector function**  is defined by 
$$
\vec{N}(t)=\frac{\vec{T}'(t)}{\norm{\vec{T}'(t)}}.
$$
::: 

The unit normal vector is orthogonal (or normal, or perpendicular) to the unit tangent vector and hence to the curve as well.

::: {#lem- } 
Suppose that $\vec{R}$ is a vector such that $\norm{R(t)}=c$ for all t. 
Then $\vec{R}(t)$ is orthogonal to $\vec{R}'(t)$. 
::: 

::: {.proof }
Notice $\vec{R}(t)\cdot \vec{R}(t)=\norm{\vec{R}(t)}^2=c^2$, for all $t$.
We differentiate with respect to $t$ to find,
$$
\vec{R}'(t)\cdot \vec{R}(t)+\vec{R}'(t)\cdot \vec{R}(t)=0
$$
which yields $\vec{R}'(t)\cdot \vec{R}(t)=0$ and so $\vec{R}'(t)$ is orthogonal to $\vec{R}(t)$. 
::: 



::: {#exm- } 
Given the vector function defined by 
$$
\vec{R}(t)=\langle -4t,\sin  2t,-\cos  2t\rangle
$$
find the unit tangent vector $\vec{T}(t)$ and unit normal vector $\vec{N}(t).$  
::: 

::: {.solution }
We find
\begin{align*}
& \vec{T}(t) = \displaystyle  \frac{\vec{R}'(t)}{\norm{\vec{R}'(t)}} 
\\
& \qquad =\frac{\left\langle -4,2\cos  2t,2\sin 2 t\right\rangle }{\sqrt{(-4)^2+4\cos ^22t+4\sin ^22t}} 
\\
&\qquad  =\frac{\langle -4, 2\cos  2t, 2\sin2t \rangle}{2\sqrt{5}}
\\
& \qquad =\left\langle -\frac{4}{2\sqrt{5}},\frac{2}{2\sqrt{5}}\cos  2t,\frac{2}{2\sqrt{5}}\sin 2 t \right\rangle 
\\
& \qquad =\left\langle -\frac{2}{\sqrt{5}},\frac{1}{\sqrt{5}}\cos  2t,\frac{1}{\sqrt{5}}\sin 2 t\right\rangle\end{align*}
and  
$$
\vec{N}(t) =\frac{\vec{T}'(t)}{\norm{\vec{T}'(t)}} 
=\frac{\left\langle 0,\frac{-2}{\sqrt{5}}\sin  2t,\frac{2}{\sqrt{5}}\cos  2t\right\rangle }{\sqrt{\frac{4}{5}}} =\langle 0,-\sin 2t,\cos 2t\rangle.  
$$
as the unit normal vector. 
::: 



## Integrals of Vector Functions

Next we study \index{vector integration} **vector integration** . Since integration is a linear process, studying vector functions and integration together is natural.
Indeed recall that with functions of one variable, definite integration is the process of taking a limit of a Riemann sum. Basically, since taking
limits and Riemann sums both are linear processes, so is integration.


::: {#def- } 
Let  
$\vec{F}(t)=f_1(t)\vec{i}+f_2(t)\vec{j}+f_3(t)\vec{k}$,  
where $f_1(t)$, $f_2(t)$, and $f_3(t)$ are continuous on the closed interval $a\leq t\leq b.$ Then the indefinite integral of $\vec{F}(t)$ is
$$
\int \vec{F}(t)\, dt=\left[\int f_1(t)\, dt\right]\vec{i}+\left[\int f_2(t)\, dt\right]\vec{j}+\left[\int f_3(t)\, dt\right]\vec{k}.
$$
::: 
 
Recall integration by parts:
$$
\int u \, dv =u v -\int v du
$$
and so use $u=\ln t$ and $dv=t \, dt.$

::: {#exm- } 
Evaluate $\int \langle t \ln  t,-\sin (1-t),t\rangle \, dt.$  
::: 

::: {.solution }
We find that the given integral is equal to 
\begin{align*}
& =\left(\int t \ln t \, dt\right)\vec{i}+\left(\int -\sin(1-t)\, dt\right)\vec{j}+\left(\int t\, dt\right)\vec{k} \\
& =\left(\frac{-t^2}{4}+\frac{t^2}{2}\ln  t\right)\vec{i}-\cos (1-t)\vec{j}+\left(\frac{t^2}{2}\right)\vec{k}+\vec{C} 
\end{align*}
where $\vec{C}$ is a constant vector.  
::: 


::: {#def- } 
Let $\vec{F}(t)=f_1(t)\vec{i}+f_2(t)\vec{j}+f_3(t)\vec{k}$,  
where $f_1(t)$, $f_2(t)$, and $f_3(t)$ are continuous on the closed interval $a\leq t\leq b.$ Then the definite integral of $\vec{F}(t)$ is the
vector 
$$
\int _b^a\vec{F}(t)\, dt=\left[\int _b^af_1(t)\, dt\right]\vec{i}+\left[\int _b^af_2(t)\, dt\right]\vec{j}+\left[\int _b^af_3(t)\, dt\right]\vec{k}.
$$
::: 


::: {#exm- } 
Given the vector function   
$$
\vec{F}(t)=\left(t\sqrt{1+t^2}\right)\vec{i}+\left(\frac{1}{1+t^2}\right)\vec{j}.
$$
Find a value of $a$ for which $\int_0^a \vec{F}(t) \, dt=\frac{2\sqrt{2}}{3}\vec{i}+\frac{\pi }{4}\vec{j}.$ 
::: 

::: {.solution }
By definition, we find
\begin{align*}
\int_0^a \vec{F}(t) \, dt
& =\left(\int _0^at\sqrt{1+t^2}\, dt\right)\vec{i}+\left(\int _0^a\frac{1}{1+t^2}\, dt\right)\vec{j} \\
&  =\left(\frac{1}{3}\sqrt{\left(1+a^2\right)^3}\right)\vec{i}+\left(\tan ^{-1} a\right)\vec{j}.
\end{align*}
Thus we require $\left(1+a^2\right)^3=8$ and $\tan ^{-1}a=\frac{\pi }{4}.$ 
Therefore we find $a=1.$  
::: 


vMotion of an Object

If the graph of a vector function $\vec{R}(t)$ is a smooth curve $C$ then the nonzero derivative $\vec{R}'(t)$ is tangent to $C$ at the point $P$ that corresponds to $t$; and in this case we can make the following definition. 


::: {#def- } 
If an object moves in such a way that its position at time $t$ is given by the vector function $\vec{R}(t)$ whose graph is a smooth curve $C,$ then   
 
- $\vec{V(t)}=\frac{d \vec{R}}{d t}$  is the object's velocity vector at time $t$,
- $\|\vec{V(t)}\|$ is the speed of the object at time $t$,  
- $\frac{\vec{V(t)}}{\|\vec{V(t)}\|}$ is the direction of the object's motion at time $t$, and
- $\frac{d \vec{V(t)}}{d t}$ is the object's acceleration at time $t$.  
 
::: 
 

::: {#exm- } 
Suppose the position vector for a particle in space at time $t$ is given by 
$$
\vec{R}(t)=e^t\vec{i}+e^{-t}\vec{j}+e^{2t}\vec{k}.
$$
Find the particle's velocity vector, acceleration vector, speed, and direction of motion vector at time $t=\ln  2.$   
::: 

::: {.solution }
At time $t=\ln  2$, the particle's velocity vector is   
$$
\vec{R}'(t)|_{t=\ln  2}=e^t\vec{i}-e^{-t}\vec{j}+2e^{2t}\vec{k}|_{t=\ln  2}=2\vec{i}-\frac{1}{2}\vec{j}+8\vec{k},
$$
the acceleration vector is 
$$
\vec{R}''(t)|_{t=\ln  2}=e^t\vec{i}+e^{-t}\vec{j}+4e^{2t}\vec{k}|_{t=\ln  2}=2\vec{i}+\frac{1}{2}\vec{j}+16\vec{k},
$$ 
the speed is  
$$
\vec{R}'(t)|_{t=\ln  2}=\sqrt{2^2+\left(\frac{-1}{2}\right)^2+8^2}=\sqrt{68.25},
$$
and the direction of motion vector is   
\begin{equation}
\frac{2}{\sqrt{68.25}}\vec{i}-\frac{1}{2\sqrt{68.25}}\vec{j}+\frac{8}{\sqrt{68.25}}\vec{k}.
\tag*{}
\end{equation}
::: 


::: {#exm- } 
Find the position vector $\vec{R}(t)$ and velocity vector $\vec{V}(t),$ given the acceleration vector function 
$$
\vec{A}(t)=t^2 \vec{i}-2\sqrt{t } \vec{j}+e^{3t} \vec{k},
$$ 
initial position vector $\vec{R}(0)=2 \vec{i}+\vec{j}-\vec{k},$ and initial velocity vector $\vec{V}(0)=\vec{i}-\vec{j}-2\vec{k}.$  
::: 

::: {.solution }
Given $\vec{A}(t)=t^2 \vec{i}-2\sqrt{t } \vec{j}+e^{3t} \vec{k}$ the velocity vector function is      
$$
\vec{V}(t)=\left(\int t^2 dt\right)\vec{i}-\left(\int 2\sqrt{t }dt\right) \vec{j}+\left(\int e^{3t} dt\right) \vec{k}
$$
$$
\vec{V}(t)=\left(\frac{t^3}{3}+C_1\right) \vec{i}-\left(\frac{4 t^{3/2}}{3}+C_2\right)\vec{j}+\left(\frac{e^{3 t}}{3}+C_3\right) \vec{k}
$$
where $C_1, C_2,$ and $C_3$ are constants to be determined. By using  
$$
\vec{V}(0)=\vec{i}-\vec{j}-2\vec{k} =\left(0+C_1\right)\vec{i}+\left(-0+C_2\right)\vec{j}+\left(\frac{1}{3}+C_3\right)\vec{k}
$$
we find $C_1=1,$ $C_2=1,$ $C_3=-7/3.$ Therefore,  
$$
\vec{V}(t)=\left(\frac{t^3}{3}+1\right)\vec{i}+\left(-\frac{4 t^{3/2}}{3}-1\right)\vec{j}+\left(\frac{e^{3 t}-7}{3}\right) \vec{k}.
$$
So the position vector function is  
$$
\vec{R}(t)=\left(\int \left(\frac{t^3}{3}+1\right) \, dt\right) \vec{i}+\left(\int \left(-\frac{4 t^{3/2}}{3}-1\right) \, dt\right)\vec{j}+\left(\int \frac{e^{3 t}-7}{3} \, dt\right) \vec{k}
$$
which is 
$$
\vec{R}(t)=\left(\frac{t^4}{12}+t+K_1\right) \vec{i}+\left(-\frac{8 t^{5/2}}{15}-t+K_2\right)\vec{j}+\left(\frac{1}{3} \left(\frac{e^{3 t}}{3 }-7 t\right)+k_3\right) \vec{k}
$$ 
where $K_1, K_2,$ and $K_3$ are constants to be determined. By using  
$$
\vec{R}(0)=2 \vec{i}+\vec{j}-\vec{k} =\left(0+K_1\right)\vec{i}+\left(-0+K_2\right)\vec{j}+\left(\frac{1}{9}+K_3\right)\vec{k}
$$
we find $K_1=2,$ $K_2=1,$ $K_3=-10/9.$ 
Therefore,  
$$
\vec{R}(t)=\left(\frac{t^4}{12}+t+2\right) \vec{i}+\left(-\frac{8 t^{5/2}}{15}-t+1\right)\vec{j}+\left(\frac{1}{3} \left(\frac{e^{3 t}}{3 }-7 t\right)-\frac{10}{9}\right) \vec{k}
$$
is the required vector function. 
::: 

::: {#thm- } 
Neglecting air resistance, the path of a projectile launched from an initial height $h$ with initial speed $v_0$ and an angle of elevation $\theta$ is described by the vector function
\begin{equation}
\label{prolaueq}
\vec{R}(t)
=(v_0\cos \theta)t\vec{i}+\left[h+(v_0\sin \theta)t-\frac{1}{2}g t^2)\right]\vec{j}
\end{equation}
where $g$ is he gravitional constant. 
::: 

::: {.proof }
Suppose a projectile of mass $m$ is launched from an initial position $\vec{R}_0$ with an initial velocity $\vec{V}_0$.
First we will find its position vector as a function of time. 
We begin with acceleration $\vec{A}(t)=-g \vec{j}$ and we integrate twice, namely, 
\begin{align*}
& \vec{V}(t)=\int \vec{A}(t)\, dt=\int -g \vec{j} \, dt =-g t \vec{j}+\vec{C}_1 \\
& \vec{R}(t)= \int \vec{V}(t) \, dt =\int (g t \vec{j}+\vec{C}_1) \, dt  =-\frac{1}{2} g t^2 \vec{i}+\vec{C}_1 t+\vec{C}_2
\end{align*}
where $\vec{C}_1$ and $\vec{C}_2$ can be determined from the initial conditions. 
Using $\vec{V}(0)=\vec{V}_0$, $\vec{R}(0)=\vec{R}_0$, produces $\vec{C}_1=\vec{V}_0$ and $\vec{C}_2=\vec{R}_0$. 
Therefore the position vector function is
\begin{equation}
\label{proeq}
\vec{R}(t)=-\frac{1}{2} g t^2 \vec{j} +t \vec{V}_0 +\vec{R}_0.
\end{equation}
Now from the given height $h$ we realize that 
$$
\vec{R}_0=h \vec{j}
$$
and because speed is the magnitude of the velocity, that is $V_0=||\vec{V}_0||$, we have
$$
\vec{V}_0=x\vec{i}+y \vec{j}
=\left(||\vec{V}_0|| \cos \theta \right) \vec{i}+\left(||\vec{V}_0|| \sin \theta \right) \vec{j} 
=V_0\cos \theta\vec{i}+V_0\sin \theta\vec{j}.
$$
Now we can derive \ref{prolaueq} as follows
\begin{align*}
R(t) & =-\frac{1}{2} g t^2 \vec{j} +t \vec{V}_0+\vec{R}_0 \\
& = -\frac{1}{2} g t^2 \vec{j} +tV_0 \cos \theta \vec{i} + t (V_0\cos \theta\vec{i}+V_0\sin \theta\vec{j}) +h \vec{j} \\
& =(v_0\cos \theta)t\vec{i}+\left[h+(v_0\sin \theta)t-\frac{1}{2}g t^2)\right]\vec{j}
\end{align*}
as desired. 
::: 


## Exercises

::: {#exr- } 
Evaluate $\int_0^6 \langle t^3-t,t^2-2\rangle \, dt$.
::: 

::: {#exr- } 
Evaluate $\int \left( 2t \vec{i}+9t^2 \vec{j} +7\vec{k}\right) \, dt$. 
::: 

::: {#exr- } 
Find the vector derivative $\vec{F}\, '$ for each of the following functions.
 
- $\vec{F}(s)=\left(s \vec{i}+s^2\vec{j}+s^2\vec{k}\right)+\left(2s^2 \vec{i}-s \vec{j}+3\vec{k}\right).$  
- $\vec{F}(s)=\left(1-2s^2\right)\vec{i}+(s \cos  s) \vec{j}-s \vec{k}.$   
- $\vec{F}(\theta )=\left(\sin ^2\theta \right)\vec{i}+(\cos  2\theta ) \vec{j}+\theta ^2 \vec{k}.$   
 
::: 

::: {#exr- } 
Find the indefinite vector integral for each of the following.
 
- $\int \langle\cos  t,\sin  t,-2t\rangle \, dt.$  
- $\int \langle 3 e ,t^2, t \sin  t\rangle \,dt.$  
- $\int e^{-t} \langle 3,t,\sin  t\rangle \,dt.$  
- $\int \langle\sinh  t, -3, \cosh  t\rangle \, dt.$  
 
::: 

::: {#exr- } 
Given $\vec{F}(t)=t^2\vec{i}+2t \vec{j}+\left(t^3+t^2\right)\vec{k}$ determine all real numbers $a$ such that $\vec{F}\, '(0)+\vec{F}\, '(1)+\vec{F}\, '(-1)=a \vec{j}+a \vec{k}.$ 
::: 

::: {#exr- } 
Given $\vec{F}(t)=t^2\vec{i}+\cos  t \vec{j}+t^2\cos  t \vec{k}$ determine all real numbers $a$ such that   $\vec{F}\, '(0)+\vec{F}\, '(a)=\pi  \vec{i} -\vec{j}-a^2 \vec{k}.$ 
::: 

::: {#exr- } 
Determine all real numbers $a$ such that the parametric equations for the tangent line to the graph of the vector function $\vec{F}(t)=t^{-3}\vec{i}+t^{-2}\vec{j}+t^{-1}\vec{k}$ at the point corresponding to $t=-1$ are  
$$
x=\frac{-3}{a}-a t, \quad
y=\frac{a}{3}+\frac{6}{a}t, \quad
z=\frac{-3}{a}-\frac{3}{a}t.
$$ 
::: 

::: {#exr- } 
Find the first and second derivatives for each of the following functions.
 
- $\vec{F}(t)=(\ln  t)\left[t \vec{i}+5 \vec{j}-e^t\vec{k}\right]$  
- $\vec{F}(t)=(\sin  t) \vec{i}+(\cos  t) \vec{j}+t^2\vec{k}$ 
- $f(x)=\left\|\left(x \vec{i}+x^2\vec{j}-20\vec{k}\right)+\left(x^3 \vec{i}+ x \vec{j}-x \vec{k}\right)\right\|$. 
 
::: 

::: {#exr- } 
Determine all real numbers $a$  such that 
$$
f'(x)=-a x^2-\frac{18}{a}x
$$ 
given 
$$
f(x)=[x \vec{i}+(x+1)\vec{j}]\cdot \left[2x \vec{i}-3x^2\vec{j}\right].
$$ 
::: 

::: {#exr- } 
Determine all real numbers $a$ such that 
$$
F''(t)=a \vec{i}+a t^{-3}\vec{j}+2a e^{a t}\vec{k}
$$ 
given $\vec{F}(t)=t^2\vec{i}+t^{-1}\vec{j}+e^{2 t}\vec{k}.$ 
::: 

::: {#exr- } 
Determine all real numbers $a$ such that $\vec{F}\, '(t)$ and $\vec{F}\, '''(t)$ are parallel for all $t$ given $\vec{F}(t)=e^{a t}\vec{i}+e^{- a t}\vec{j}.$ 
::: 

::: {#exr- } 
Prove that if $\vec{F}$ is a differentiable vector function such that $\vec{F}(t)\neq 0,$ then  
$$
\frac{d}{d t}\left(\frac{\vec{F}(t)}{\|\vec{F}(t)\|}\right)=\frac{\vec{F}\, '(t)}{\|\vec{F}(t)\|}-\frac{[\vec{F}(t)\cdot \vec{F} '(t)]\vec{F}(t)}{\left\|\vec{F}(t)\|^3\right.}.
$$ 
::: 

::: {#exr- } 
Prove that if $\vec{F}, \vec{G},$ and $\vec{H}$ are differentiable vector functions, then  
\begin{align*}
%& 
[\vec{F}\cdot (\vec{G}\times \vec{H})] ' 
%\\  & \qquad 
=\vec{F} \, '\cdot (\vec{G}\times \vec{H})+\vec{F}\cdot (\vec{G} \, ' \times \vec{H})+\vec{F}\cdot (\vec{G}\times \vec{H} \,' ).
\end{align*}
::: 

::: {#exr- } 
Prove that if $\vec{F}, \vec{G},$ and $\vec{H}$ are differentiable vector functions, then 
$$
[\vec{F}\times (\vec{G}\times \vec{H})] ' =[(\vec{H}\cdot \vec{F})\vec{G}] '-[(\vec{G}\cdot \vec{F})\vec{H}] '.
$$ 
::: 

::: {#exr- } 
Find a value of $a$ and $b$ such that  
$$
\int_0^a \left[t\sqrt{1+t^2}\vec{i}+\left(\frac{1}{1+t^2}\right)\vec{j}\right] \, dt=\frac{2\sqrt{2}-1}{3}\vec{i}+\frac{\pi }{4}\vec{j}
$$
and  
$$
\int_0^b [\cos  t \vec{i}+\sin  t \vec{j}+\sin  t \cos  t \vec{k}] \, dt=\vec{i}+\vec{j}+\frac{1}{2}\vec{k}.
$$ 
::: 

::: {#exr- } 
Show that if $\vec{R}(t)= f(t)\, \vec{i}+g(t)\, \vec{j}+h(t)\, \vec{k}$ is differentiable at $t=t_0$, then it is continuous at $t_0$ as well.
::: 

::: {#exr- } 
Suppose that the scalar function $u(t)$ and the vector function $\vec{R}(t)$ are both defined for $a \leq t \leq b$. Show that $u \, \vec{R}$ is continuous on $[a,b]$ if $u$ and $\vec{R}$ are continuous on $[a,b]$. If $u$ and $\vec{R}$ are both differentiable on $[a,b]$, show that $u \, \vec{R}$ is differentiable on $[a,b]$ and that 
$$
\frac{d}{dt}(u\, \vec{R} )=u\, \frac{d \vec{R}}{dt}+\vec{R} \frac{du}{dt}.
$$
::: 

::: {#exr- } 
Use the Mean Value Theorem to show that if $\vec{R}_1(t)$ and $\vec{R}_2(t)$ have identical derivatives on an interval $I$, then the vector functions differ by a constant vector value throughout $I$. 
::: 

::: {#exr- } 
Suppose  $\vec{r}$ is a continuous vector function on $[a,b]$. Show that if $\vec{R}$ is any antiderivative of a $\vec{r}$ on $[a,b]$ then if 
$$
\vec{r}(t)=\frac{d}{dt} \int_a^t \vec{r}(s) \, ds
\quad \text{and} \quad 
\int_a^b \vec{r}(t)\, dt = \vec{R}(a)-\vec{R}(b). 
$$
::: 

::: {#exr- } 
Find a vector function describing the curve of intersection of the plane $x+y+2z=2$ and the paraboloid $z=x^2+y^2$. Also find the point(s) on the curve that are closest to and farthest from the origin. 
::: 

::: {#exr- } 
Prove that 
$$
\frac{d}{dt}\left[\vec{R}(t)\times \vec{R}\,'(t)\right] =\vec{R}(t)\times \vec{R}\,''(t).
$$
::: 

::: {#exr- } 
Let $\vec{R}(t)=\sin t \, \vec{i}+\cos t \, \vec{j} +t \, \vec{k}$ and $c=2\, \vec{i}+3\, \vec{j}-\vec{k}$ show that 
$$
\int_a^b \vec{c}\cdot \vec{R}(t)= \vec{c} \cdot \int_a^b  \vec{R}(t);
$$
also show that this formula holds true for any vector function $\vec{R}(t)$ that is integrable on $[a,b]$ and for any vector constant $\vec{c}$.
::: 

::: {#exr- } 
Find the unit tangent vector $\vec{T}(t)$ for $\vec{r}(t)=8t\vec{i}+8t\vec{j}+4t\vec{k}$ at $t=2$. 
::: 

::: {#exr- } 
Find the unit tangent vector $\vec{T}(t)$ and the unit normal vector $\vec{N}(t)$.
 
- $\vec{R}(t)=t^2\vec{i}+\sqrt{t}\vec{j},$ with $t>0$
- $\vec{R}(t)=(t \cos  t)\vec{i}+(t \sin  t)\vec{j}$
- $\vec{R}(t)=t\vec{i}+(\ln \cos t)\vec{j}, \ -\pi/2<t<\pi/2$
- $\vec{R}(t)=(2t+3)\vec{i}+(4-t^2)\vec{j}$
- $\vec{R}(t)=(\ln \sec t)\vec{i}+t\vec{j} \ -\pi/2<t<\pi/2$
- $\vec{R}(t)=\sin  t \vec{i}-\cos  t \vec{j}+t \vec{k}$
- $\vec{R}(t)=(3\sin t)\vec{i}+(3\cos t)\vec{j}+4t\vec{k}$
- $\vec{R}(t)=(e^t\cos t)\vec{i}+(e^t \sin t)\vec{j}+4\vec{k}$
- $\vec{R}(t)=(t^3/3)\vec{i}+\vec{j}+(t^2/2)\vec{k}, \ t>0$
- $\vec{R}(t)=(\cos^3 t)\vec{i}+(\sin^3 t)\vec{j}+\vec{k}, \ 0<t<\pi/2$
 
::: 

::: {#exr- } 
Given $\vec{R}(t)=(\ln  t)\vec{i}+t^2\vec{j}$ find $a$ so that  
$$
\vec{N}(t)=\frac{-2}{\sqrt{1+a t^a}}\vec{i}+\frac{1}{\sqrt{1+a t^a}}\vec{j}.
$$
::: 

::: {#exr- } 
Given $\vec{R}(t)=(\cos  t)\vec{i}+(\sin  t)\vec{j}+t \vec{k}$ find $a$ so that  $\vec{N}(t)=(- \cos  a t) \vec{i}+(-\sin  a t)\vec{j}.$ 
::: 

::: {#exr- } 
Determine values for $a$ and $b$ so that the following vector functions are smooth over $[a,b].$  
 
- $\vec{F}(t)=a t^3\vec{i}+b t^2\vec{j}+ a b t \vec{k}$  
- $\vec{G}(t)=(a \sin  b t)\vec{i}+(a \cos  b t)\vec{j}+ a b \vec{k}$  
- $\vec{H}(t)=\left(e^{a t}-b t\right)\vec{i}+t^{a/b}\vec{j}+ (b \cos  a t) \vec{k}$  
 
::: 

::: {#exr- } 
The velocity of a particle moving in space is $\vec{V}(t)=e^t\vec{i}+t^2\vec{j}.$ Find the vector $\vec{R}(0)$ so that the particle's position as a function of $t$ is  
$$
\vec{R}(t)=e^t\vec{i}+\left(\frac{1}{3}t^3-1\right)\vec{j}.
$$
::: 

::: {#exr- } 
The acceleration of a moving particle is $\vec{A}(t)=24t^2\vec{i}+4 \vec{j}.$ Find the vectors $\vec{R}(0)$ and $\vec{V}(0)=0$ so that the particle's position as a function of $t$ is 
$$
\vec{R}(t)=\left(2t^4+1\right)\vec{i}+\left(2t^2+2\right)\vec{j}.
$$ 
::: 

::: {#exr- } 
Show that $\vec{N}(t)=-g'(t)\vec{i}+f'(t)\vec{j}$ and $-\vec{N}(t)=g'(t)\vec{i}-f'(t)\vec{j}$ are both normal to the curve $\vec{R}(t)+f(t)\vec{i}+g(t)\vec{j}$ at the point $(f(t),g(t))$.
::: 

::: {#exr- } 
A baseball is hit above ground at 100 feet per second at an angle of $\pi/4$ with respect to the ground.
Find the maximum height reached by the baseball. 
Will it clear a 10-foot high fence located 300 feet from home plate?
::: 

::: {#exr- } 
Find the vector function for the path pf a projectile launched at a height of 10 feet above the ground with an initial velocity of 88 feet per second and at an angle of $30^\circ$ above the horizontal. 
Sketch the path of the projectile. 
::: 

::: {#exr- } 
Find the angle at which an object must be thrown to obtain (a) the maximum range, and (b) he maximum m height. 
::: 

::: {#exr- } 
A projectile is fired from ground level at an angle of $10^\circ$ with the horizontal.
Find the minimum initial velocity necessary of the projectile is to have a range of 100 feet.  
::: 

::: {#exr- } 
Use linear approximation by finding a set of parametric equations for the tangent line to the graph at $t=t_0$ and use the equations for the line to approximate $\vec{R}(t_0+.01)$.  
 
- $\vec{R}(t)=t \vec{i}-t^2 \vec{j} +\frac{t^3}{4}$, $t_0=1$
- $\vec{R}(t)=t \vec{i}+\sqrt{25-t^2} \vec{j} +\sqrt{25-t}$, $t_0=3$
::: 



