---
pagetitle: "Green's Theorem - Exploring Calculus"
---
# Green's Theorem



## Simple Connected Regions

Suppose $C$ is a piecewise smooth closed curve oriented counterclockwise in the Cartesian plane whose bounded region $R$ is \index{simply connected} **simply connected** . 
Suppose further that we have a \index{continuously differentiable} vector field of the form $\vec{F}=M(x,y)\vec{i} **continuously differentiable} vector field of the form $\vec{F}=M(x,y)\vec{i** $.  
Let $[a,b]$ be the projection of $R$ onto the $x$-axis, let $y_1(x)$ represent the lower part of the curve $C$,  and let $y_2(x)$ represent the upper part of $C$. 
We can write 
\begin{align}
\label{gr1}
\oint_C \vec{F}\cdot \, d\vec{r}
& = \int_a^b M(x,y_1(x)) \, dx  + \int_b^a M(x,y_2(x)) \, dx \notag \\
& = \int_a^b \left[M(x,y_1(x)) - M(x,y_2(x)) \right] \, dx \notag \\
& = - \int_a^b M(x,y)\vert_{y_1(x)}^{y_2(x)} \, dx \notag \\
& = - \int_a^b \int_{y_1(x)}^{y_2(x)} \frac{\partial M}{\partial y} \, dy \, dx \notag \\
& =-\iint_R  \frac{\partial M}{\partial y} \, dy \, dx 
\end{align}
Now let us suppose that we have a continuously differentiable vector field of the form $\vec{F}=N(x,y)\vec{j}$.  
Let $[a,b]$ be the projection of $R$ onto the $y$-axis, let $x_1(y)$ represent the lower part of the curve $C$,  and let $x_2(y)$ represent the upper part of $C$. 
We can write 
\begin{align}
\label{gr2}
\oint_C \vec{F}\cdot \, d\vec{r}
& = \int_a^b N(x_1(x),y) \, dy + \int_b^a N(x_2(x),y) \, dy\notag \\
& = \int_a^b \left[N(x_1(y),y) - N(x_2(y),y) \right] \, dy \notag \\
& = - \int_a^b N(x,y)\vert_{x_1(y)}^{x_2(y)} \, dy \notag \\
& = \int_a^b \int_{x_2(y)}^{x_1(y)} \frac{\partial N}{\partial x} \, dx \, dy \notag \\
& =\iint_R  \frac{\partial N}{\partial x} \, dx \, dy
\end{align}
Finally, suppose that $\vec{F}$ is a continuously differentiable vector field in the plane, say 
$$
\vec{F}(x,y)=M(x,y)\vec{i}+N(x,y)\vec{j}.
$$ 
Using \ref{gr1} and \ref{gr2} we find 
\begin{align*}
\oint_C \vec{F}\cdot \, d\vec{r}
& = \oint_C M(x,y)\, dx +N(x,y)\, dy \\
& = \oint_C M(x,y) \, dx +\oint_C N(x,y)\, dy \\
& = -\iint_R  \frac{\partial M}{\partial y} \, dy \, dx + \iint_R  \frac{\partial N}{\partial x} \, dx \, dy \\
& = \iint_R \left( \frac{\partial N}{\partial  x}-\frac{\partial M}{\partial  y} \right)d A
\end{align*}
as needed to prove the following theorem. 

::: {#thm- } [\index{Green's Theorem} **Green's Theorem** ]
Let $R$ be a simply connected region with a piecewise smooth boundary curve $C$ oriented counterclockwise and let 
$$
\vec{F}= M \vec{i}+ N \vec{j}+0 \vec{k}
$$ 
be a continuously differentiable vector field on $R,$ then 
\begin{equation}
\label{gr}
\oint _C M dx+Ndy
= \iint_R \left( \frac{\partial N}{\partial  x}-\frac{\partial M}{\partial  y} \right)d A.
\end{equation}
::: 

::: {#exm- } 
Use Green's theorem to evaluate the line integral
$$
\oint _C4 y \, dx-3x \, dy
$$
around the curve $C$ defined by the ellipse $2x^2+y^2=4$ oriented counterclockwise.
::: 

::: {.solution }
Let $\vec{F}(x,y)=4y \vec{i}+(-3x)\vec{j}$ and let $R$ be the region enclosed by $C$.
Notice that $\vec{F}$ and $R$ satisfy the hypothesis of Green's theorem, so that
\begin{equation*}
\oint _C 4 y \, dx-3x \, dy
= \iint_R (-3-4)d A 
=-7(2)\left(\sqrt{2}\right)\pi.
\end{equation*}
::: 
    
::: {#exm- } 
Use Green's theorem to evaluate the line integral
$$
\oint _C4x y \, dx$$ 
around the curve $C$ defined by the unit circle oriented clockwise.
::: 

::: {.solution }
Let $\vec{F}(x,y)=4x y \vec{i}+0 \vec{j}$ and let $R$ be the region enclosed by $C$.
Notice that $\vec{F}$ and $R$ satisfy the hypothesis of Green's theorem, so that
\begin{equation*}
\oint _C4x  y \, dx
% & =\oint _C M \, dx+N \, dy
%=-\iint_R \left( \frac{\partial N}{\partial  x}-\frac{\partial M}{\partial  y} \right) \,d A
%=-\iint_R (-4x) \, d A \\
=4\iint_R x \, d A
=4\int _0^{2\pi }\int _0^1 r^2 \cos  \theta drd\theta
=0
\end{equation*}
::: 
    
::: {#exm- } 
Use Green's theorem to evaluate the line integral
$$
\oint _Cy^2 \, dx+x\, dy
$$ 
around the curve $C$ defined by the square with vertices $(0,0),$ $(2,0),$ $(2,2),$ $(0,2)$ oriented counterclockwise.
::: 

::: {.solution }
Let $\vec{F}(x,y)=y^2 \vec{i}+x \vec{j}$, then $M(x,y)=y^2$ which is continuously differentiable over the square as well as $N(x,y)=x.$
Therefore $\vec{F}$ and $R$ satisfy the hypothesis of Green's theorem and 
\begin{equation*}
\oint _C y^2 \, dx+x \, dy
=\int _0^2\int _0^2(1-2y) \, dy \, dx
=\int_0^2 (-2) \, dx
=-4.
\end{equation*}
::: 

::: {#exm- } 
Find the work done on an object that moves in the force field 
$$
\vec{F}(x,y)=y^2 \vec{i}+x^2 \vec{j}
$$ 
once counterclockwise around the circular
path $x^2+y^2=2$.
::: 

::: {.solution }
Let $\vec{F}(x,y)=y^2 \vec{i}+x^2 \vec{j}$, then $M(x,y)=y^2$ which is continuously differentiable over the circle as well as $N(x,y)=x^2.$
Let $R$ be the region bounded by the curve $x^2+y^2=2.$ 
Then $\vec{F}$ and $R$ satisfy the hypothesis of Green's theorem and 
\begin{align*}
W& =\oint _C \vec{F}\cdot d\vec{R}
=\oint _C \left(y^2 \vec{i}+x^2 \vec{j}\right)\cdot ( dx \vec{i}+dy \vec{j}) 
=\oint _C \left(y^2dx +x^2dy\right) \\
& =\oint _C M \, dx+N\,dy
= \iint_R \left( \frac{\partial N}{\partial  x}-\frac{\partial M}{\partial  y} \right)\, d A
=2 \iint_R (x-y) \, dA \\
& =2\int _0^{2\pi }\int _0^{\sqrt{2}}r^2(\cos  \theta -\sin  \theta )\, dr \, d\theta
=\frac{4\sqrt{2}}{3}\int_0^{2\pi }  (\cos  \theta -\sin  \theta ) \, \, d\theta 
=0.
\end{align*}
::: 

::: {#exm- } 
Find the work done on an object that moves in the force field 
$$
\vec{F}(x,y)=\left(x+2y^2\right)  \vec{j}
$$ 
once counterclockwise around the circular path $(x-2)^2+y^2=1$.
::: 

::: {.solution }
Let $\vec{F}(x,y)=0 \vec{i}+\left(x+2y^2\right) \vec{j}$. Then $M(x,y)=0$ which is continuously differentiable over the circle as well as $N(x,y)=x+2y^2.$ Let $R$ be the region bounded by the curve $(x-2)^2+y^2=1.$ Then $\vec{F}$ and $R$ satisfy the hypothesis of Green's theorem and 
\begin{align*}
W& =\oint _C \vec{F}\cdot d\vec{R}
=\oint _C \left(x+2y^2\right)\vec{j}\cdot ( dx \vec{i}+dy \vec{j})
=\oint _C  \left(x+2y^2\right) dy \\
& =\oint _C M dx +N dy
= \iint_R \left( \frac{\partial N}{\partial  x}-\frac{\partial M}{\partial  y} \right)d A
= \iint_R dA
=\pi.
\end{align*}
::: 

::: {#exm- } 
Evaluate the closed line integral 
\[
\oint _C \frac{-y dx+(x-1)dy}{(x-1)^2+y^2}
\] 
where $C$ is any Jordan curve whose interior does not contain the point $(1,0)$ transversed counterclockwise.
::: 

::: {.solution }
Let 
$$
\vec{F}(x,y)=\frac{-y }{(x-1)^2+y^2}  \vec{i}+ \frac{x-1 }{(x-1)^2+y^2} \vec{j},
$$
then 
$$
M(x,y)=\frac{-y }{(x-1)^2+y^2}
$$
which is continuously differentiable over the circle as well as 
$$
N(x,y)=\frac{x-1 }{(x-1)^2+y^2}.
$$ 
Let $R$ be the region bounded by the given curve $C.$ 
Then $\vec{F}$ and $R$ satisfy the hypothesis of Green's theorem and
\begin{align*}
& \oint _C \frac{-y dx+(x-1)dy}{(x-1)^2+y^2} \\[5pt]
& \qquad =\oint _C \frac{-y }{(x-1)^2+y^2}dx+\frac{x-1}{(x-1)^2+y^2}dy 
\\[5pt]
& \qquad = \iint_R \left(\partial _x \left(\frac{x-1 }{(x-1)^2+y^2}\right)-\partial _y \left(\frac{-y }{(x-1)^2+y^2}\right)\right)dA 
\\[5pt]
& \qquad = \iint_R  0 \, dA
=0.
\end{align*}
::: 

## Doubly-Connected Regions

::: {#def- } 
A \index{Jordan curve} **Jordan curve**  is a closed curve $C$ that does not intersect itself and a simply connected region $R$ has the property that it is connected
and the interior of every Jordan curve $C$ in $R$ also lies in $R.$ 
::: 

::: {#thm- } [Green's Theorem for Doubly-Connected Regions]
Let $R$ be a doubly-connected region with a piecewise smooth outer boundary curve $C_1$ oriented counterclockwise and a piecewise smooth inner boundary curve $C_2$ oriented clockwise and let $\vec{F}= M \vec{i}+ N \vec{j}+0 \vec{k}$ be a continuously differentiable vector field on $R,$ then
\[
\oint _{C_1} M \, dx+N \, dy+\oint _{C_2} M \, dx+N \, dy= \iint_R \left( \frac{\partial N}{\partial  x}-\frac{\partial M}{\partial  y} \right) \, d A.\]
::: 

::: {#exm- } 
Evaluate the closed line integral 
\[
\oint _C \frac{x dx+ydy}{x^2+y^2}
\] 
where $C$ is any Jordan curve whose interior contains the point $(0,0)$ transversed counterclockwise
::: 

::: {.solution }
Let $C_1$ be a circle centered at $(0,0)$ with radius $r$ so small that all of $C_1$ is contained within $C.$ Let $C_1$
be oriented clockwise and let $R$ be the region between $C_1$ and $C.$ Then by Green's theorem for doubly-connected regions, 
\begin{align*}
& \oint _C \frac{x}{x^2+y^2}dx+\frac{y}{x^2+y^2}dy+\oint _{C_1} \frac{x}{x^2+y^2}dx+\frac{y}{x^2+y^2}dy 
\\[5pt]
& \qquad = \iint_R \left(\frac{\partial }{\partial  x}\left(\frac{y}{x^2+y^2}\right)-\frac{\partial }{\partial  y}\left(\frac{x}{x^2+y^2}\right)\right)d
A
\\[5pt]
& \qquad = \iint_R \left(\frac{-2 x y}{x^2+y^2}-\frac{-2 x y}{x^2+y^2}\right)d A =0.\end{align*}
Thus,
\[
\oint _C \frac{x dx+ydy}{x^2+y^2}=-\oint _{C_1} \frac{x dx+ydy}{x^2+y^2}
\]
which is something that can be easily evaluated, using say, the parametrization 
$ C_1: x=r \sin  \theta , y=r \cos  \theta; 0\leq \theta \leq 2\pi $. 
Therefore 
\begin{align*}
\oint _C \frac{x dx+ydy}{x^2+y^2} & 
=-\oint _{C_1} \frac{x dx+ydy}{x^2+y^2} 
\\ & 
=\int_0^{2\pi } \frac{(r \sin  \theta ) (r \cos  \theta )+(r \cos  \theta )(-r \sin  \theta )}{\sin  ^2\theta +\cos ^2\theta } \, d\theta
=0.
\end{align*}
::: 

::: {#exm- } 
Evaluate the closed line integral 
\[
\oint _C\left(x^2y dx-y^2xdy\right)
\] 
where $C$ is the boundary of the region between the $x$-axis and the semicircle $y=\sqrt{a^2-x^2},$ traversed counterclockwise (including the $x$-axis). 
::: 

::: {.solution }
Using Green's Theorem, we find
\begin{align*}
\oint _C\left(x^2y dx-y^2xdy\right)
& =\int \int \left(-y^2\right)-\left(x^2\right)dA 
 =-\int \int \left(x^2+y^2\right) \, dA \\
& =-\int _0^{\pi }\int _0^ar^3drd\theta 
 =-\int_0^{\pi } \frac{a^4}{4} \, d\theta 
=-\frac{a^4 \pi }{4}
\end{align*}
::: 

::: {#exm- } 
Evaluate the closed line integral 
\[
\oint _C\frac{-(y+2)dx+(x-1)dy}{(x-1)^2+(y+2)^2}\]
where $C$ is any Jordan curve whose interior does not contain the point $(1,-2)$.
::: 

::: {.solution }
Green's theorem applies because we are using any Jordan curve which does not contain the point $(1,-2).$ 
\begin{align*}
& \oint _C\frac{-(y+2)dx+(x-1)dy}{(x-1)^2+(y+2)^2} 
\\[5pt]
& \quad =\oint _C-\frac{(y+2)}{(x-1)^2+(y+2)^2}dx+\frac{(x-1)}{(x-1)^2+(y+2)^2}dy 
\\[5pt]
& \quad =\iint_D \left(\partial _x \left(\frac{(x-1)}{(x-1)^2+(y+2)^2}\right)\right)-\left(\partial _y \left(-\frac{(y+2)}{(x-1)^2+(y+2)^2}\right)\right)dA 
\\[5pt]
& \quad =\iint_D\left(\frac{-x^2+2 x+y^2+4 y+3}{\left(x^2-2 x+y^2+4 y+5\right)^2}\right)-\left(\frac{-x^2+2 x+y^2+4 y+3}{\left(x^2-2 x+y^2+4 y+5\right)^2}\right) \, dA =0
\end{align*}
::: 

::: {#exm- } 
Evaluate the closed line integral 
\[
\oint _C\left[(x-3y)dx+\left(2x-y^2\right)dy\right]
\]
where $A$ is the region $D$ enclosed by a Jordan curve $C$.
::: 

::: {.solution }
Green's theorem applies and  
\begin{align*}
\oint _C(x-3y)dx+\left(2x-y^2\right)dy
& =\iint_D \left(\partial _x \left(2x-y^2\right)\right)-\left(\partial _y (x-3y)\right)dA 
\\ & 
=\iint_D (2+3)dA
=5A.
\end{align*}
::: 

::: {#exm- } 
Use a line integral to find the area enclosed by the region $R$
defined by the circle $x^2+y^2=4$
::: 

::: {.solution }
We can parametrize the circle by $x=2 \cos  t$ and $y=2 \sin  t$ for $0\leq t\leq  2\pi .$ Then the area is 
\[
\frac{1}{2}\oint _C x dy-ydx=
\frac{1}{2}\int _0^{2\pi } [4\cos (t)\cos (t)+4 \sin (t)\sin (t)] \, dt=4\pi. 
\]
- We can parametrize the line segments by 
\begin{align*}
& C_1:  x=t, y=t; 0\leq t\leq 1 \\
& C_2: x=1-t, y=1+t; 0\leq t\leq 1 \\
& C_3: x=0, y=2(1-t); 0\leq t\leq 1
\end{align*}
Then the area is
\begin{align*}
\oint _C x dy 
& =\int _{C_1} x dy+\int _{C_2} x dy+\int _{C_3} x dy \\[5pt]
& =\int_0^1 t \, dt+\int_0^1 (1-t) \, dt+\int _0^10(-2)dt 
=\frac{1}{2}+\frac{1}{2}+0 
=1.
\end{align*}
::: 

::: {#exm- } 
Use a line integral to find the area enclosed by the region $R$
defined by the curve $C: x=\cos  ^3t,$ $y=\sin^3 t$ for $0\leq t\leq 2\pi $
::: 

::: {.solution }
The required area is 
\begin{align*}
A& =\oint _C x dy 
=\int _0^{2\pi }\cos  ^3t \left(3 \sin ^2 t \cos  t\right)dt \\
& =\int _0^{2\pi }\cos ^4 t \left(1-\cos ^2 t \right) dt 
 =\int _0^{2\pi }\left(\cos ^4 t -\cos ^6 t \right) dt
%& =3\int _0^{2\pi }\left(\cos ^4 t -\cos ^6 t \right) dt
%& =3\int _0^{2\pi }\left(\cos ^4(t)-\frac{5}{6}\cos ^4(t)\right) dt \\
%& =\frac{1}{2}\int _0^{2\pi }\cos ^4(t) dt \\
%=\frac{1}{2}\left(\frac{3}{4}\right)\int _0^{2\pi }\cos ^2(t) dt 
% =\frac{1}{2}\left(\frac{3}{4}\right)\left(\frac{1}{2}\right)\int _0^{2\pi } dt 
%=\frac{3 \pi }{8}.\end{align*}
\end{align*}
by using the reduction formula,
\[
\int \cos ^nx \, dx=\frac{\cos ^{n-1}x \sin  x}{n}+\frac{n-1}{n}\int \cos ^{n-2}xdx.
\]
::: 

## Exercises

::: {#exr- } 
Use Green's theorem to evaluate the closed line integral 
\[ \oint _C y^2 dx+x^2 dy\] where $C$ is the boundary of the square with vertices $(0,0),$ $(1,0),$ $(1,1),$ and $(0,1)$ traversed counterclockwise.
::: 

::: {#exr- } 
Use Green's theorem to evaluate the closed line integral 
\[\oint _C4x y dx \] where $C$ is the boundary of the circle $x^2+y^2=1$ traversed
clockwise.
::: 

::: {#exr- } 
Use Green's theorem to evaluate the closed line integral 
\[\oint _C x \sin  x dx-e^{y^2} dy\] where $C$ is the boundary of the triangle
with vertices $(-1,-1),$ $(1,-1),$ and $(2,5)$ traversed counterclockwise.
::: 

::: {#exr- } 
Use Green's theorem to evaluate the closed line integral 
\[\oint _C \sin  x \cos  y \, dx+\cos  x \sin  y \, dy \] 
where $C$ is the boundary of the square with vertices $(0,0),$ $(2,0),$ $(2,2),$ and $(0,2)$ traversed clockwise.
::: 

::: {#exr- } 
Use Green's theorem to evaluate a closed line integral that represents the area enclosed by the region defined by the curve $x^2+y^2=4.$
::: 

::: {#exr- } 
Use Green's theorem to evaluate a closed line integral that represents the area enclosed by the region defined by the trapezoid with vertices
$(0,0),$ $(4,0),$ $(1,3),$ and $(0,3).$
::: 

::: {#exr- } 
Evaluate the closed line integral 
\[ \oint _C\frac{x dx+ydy}{x^2+y^2}\] where $C$ is any piecewise smooth Jordan curve enclosing the origin,
traversed counterclockwise.
::: 

::: {#exr- } 
Evaluate the closed line integral 
\[
\oint _C x^2y \, dx-y^2x \, dy,
\] where $C$ is the boundary of the region between the $x$-axis and
the semicircle $y=\sqrt{a^2-x^2},$ traversed counterclockwise (including the $x$-axis). 
::: 

::: {#exr- } 
Evaluate 
\[\oint _C\frac{-(y+2)dx+(x-1)dy}{(x-1)^2+(y+2)^2}\] where $C$ is any Jordan curve whose interior does not contain the point $(1,-2).$
::: 

::: {#exr- } 
If $C$ is a Jordan curve, show that 
\[ \oint _C (x-3y)dx+\left(2x-y^2\right)dy =5A\]
where $A$ is the region $D$ enclosed by $C.$
::: 

::: {#exr- } 
Suppose $\vec{F}=M(x,y)\, \vec{i}+N(x,y)\, \vec{j}$ is continuously differentiable in a doubly-connected region $R$ and that
$$
\frac{\partial N}{\partial x}=\frac{\partial M}{\partial y}
$$ 
throughout $R.$ How many distinct values of $I$ are there for the integral
\[ 
I=\oint _C M(x,y)\, dx+N(x,y)\, dy
\]
where $C$ is a piecewise smooth Jordan curve in $R?$
::: 

::: {#exr- } 
Evaluate the line integral 
\[
\oint _C x^2y \, dx-y^2x \, dy,
\]
where $C$ is the boundary of the region between the $x$-axis and the semicircle $y=\sqrt{a^2-x^2},$ transversed counterclockwise (including
the $x$-axis). 
::: 

::: {#exr- } 
Find the work done if an object that moves in the force field 
$\vec{F}(x,y)=y^2 \vec{i}+x^2 \vec{j}$
once counterclockwise around the circular
path $x^2+y^2=2$.
::: 



