---
pagetitle: "Iterated Integrals - Exploring Calculus"
---
# Iterated Integrals


## Iterate Integrals Over Rectangular Regions


::: {#thm- } [Fubini's Theorem for Rectangular Regions]
\label{fubrect}
If $f$ is a continuous function of $x$ and $y$ over the rectangle $R:$ $a\leq x\leq b,$ $c\leq y\leq d,$ then the double integral of $f$ over $R$ may be evaluated by either iterated integral: 
$$
\iint_R f(x,y)d A=\int _a^b \left[\int_c^d f(x,y) \, dy\right]dx=\int _c^d \left[\int_a^b f(x,y) \, dx\right]dy.
$$
::: 


::: {#exm- } 
Evaluate the double integral 
\begin{equation*}
\iint_R x \sin  x y \,dA
\end{equation*}
over the region 
$R=\{ (x,y) \mid  0\leq x\leq \pi ,$ $0\leq y\leq 1\}$.
::: 

::: {.solution }
Since the integrand is continuous over $R$ we use \ref{fubrect} to find
\begin{equation}
\iint_R x \sin  x y \, dA
=\int _0^{\pi }\int _0^1 x \sin  x y \, dy \, dx
=-\int_0^{\pi } (\cos  x-1) \, dx=\pi .
\end{equation}
See \ref{figfub:surboundvolone} for a visualization. 
::: 


::: {#exm- } 

Evaluate the double integral 
\begin{equation*}
\iint_R \left(\frac{4+x^2}{1+y^2}\right)d A 
\end{equation*}
over the region 
$R=\{ (x,y) \mid  0\leq x\leq 1 ,$ $0\leq y\leq 1\}$.
::: 

::: {.solution }
Since the integrand is continuous over $R$ we use \ref{fubrect} to find
\begin{equation}
\iint_R \left(\frac{4+x^2}{1+y^2}\right)d A 
=\int _0^1\int _0^1\left(\frac{4+x^2}{1+y^2}\right)dx dy 
=\int_0^1 \frac{13}{3 \left(y^2+1\right)} \, dy 
=\frac{13 \pi }{12}.
\end{equation}
See \ref{figfub:surboundvoltwo} for a visualization. 
::: 


::: {#exm- } 

Evaluate the double integral 
\begin{equation*}
\iint_R \frac{2 x y}{x^2+1}dA
\end{equation*}
over the region
$R=\{(x,y) \mid  0\leq x\leq 1, 1\leq  y\leq 3\}$. 
::: 

::: {.solution }
Since the integrand is continuous over $R$ we use \ref{fubrect} to find
\begin{equation}
\iint_R \frac{2 x y}{x^2+1} \, dA
=\int _0^1\int _1^3\frac{2x y}{x^2+1} \, dy \, dx
=\int_0^1 \frac{8 x}{x^2+1} \, dx=4 \ln (2).
\end{equation}
See \ref{figfub:surboundvolthree} for a visualization. 
::: 


::: {#exm- } 

Evaluate the double integral 
\begin{equation*}
\iint_R \left(x^2e^{x y}\right)d A
\end{equation*}
over the region 
$R=\{ (x,y) \mid  0\leq x\leq 1 ,$ $0\leq y\leq 1\}$.
::: 

::: {.solution }
Since the integrand is continuous over $R$ we use \ref{fubrect} to find
$$
\iint_R \left(x^2e^{x y}\right)d A
=\int _0^1\int _0^1x^2e ^{x y}dy dx
=\int_0^1 \left(x e^x-x\right) \, dx=\frac{1}{2}.
$$
See \ref{figfub:surboundvol} for a visualization. 
::: 

 

::: {#exm- } 
Evaluate the double integral 
\begin{equation*}
\int _3^4\int _1^2\frac{x}{x-y}dy\, dx.
\end{equation*}
::: 

::: {.solution }
Since the integrand is continuous over $R$ we use \ref{fubrect} to find
$$
\int _3^4\int _1^2\frac{x}{x-y} \, dy \, dx
=\int_3^4 x (\ln (1-x)-\ln (2-x)) \, dx 
=\frac{1}{2}-10 \ln (2)+\frac{15}{2} \ln (3).
$$
See \ref{figfub:surboundvolfive} for a visualization. 
::: 


::: {#exm- } 
Evaluate the double integral 
\begin{equation*}
\int _2^3\int _{-1}^2\frac{1}{(x+y)^2}dy\, dx.
\end{equation*}
::: 

::: {.solution }
Since the integrand is continuous over $R$ we use \ref{fubrect} to find
$$
\int _2^3\int _{-1}^2\frac{1}{(x+y)^2} \, dy \, dx 
=\int_2^3 \left(\frac{1}{-x-2}-\frac{1}{1-x}\right) \, dx 
=\ln (2)+\ln (4)-\ln (5)
=\ln \left(\frac{8}{5}\right). 
$$
See \ref{figfub:surboundvolsix} for a visualization. 
::: 

How does this example not contradiction \ref{fubrect}?

::: {#exm- } 

Show that the iterated integrals 
\begin{equation*}
\int _0^1\int _0^1\frac{y-x}{(x+y)^3} \, dy \, dx 
\quad \text{ and } \quad 
\int _0^1\int _0^1\frac{y-x}{(x+y)^3} \, dx \, dy
\end{equation*}
have different values. 
::: 

::: {.solution }
The first integral 
\begin{equation}
\int _0^1\int _0^1\frac{y-x}{(x+y)^3} \, dy \, dx 
=\int_0^1 -\frac{1}{(x+1)^2} \, dx =-\frac{1}{2}.
\end{equation}
and the second integral 
\begin{equation}
\int _0^1\int _0^1\frac{y-x}{(x+y)^3} \, dx \, dy 
=\int_0^1 \frac{1}{(y+1)^2} \, dy =\frac{1}{2}.
\end{equation}
do indeed have different values. 
::: 
  

## Iterated Integrals Over Non-Rectangular Regions


Let $R$ be a region in the $xy$-plane. Then $R$ is called a 
 
- \index{vertically simple region} **vertically simple region**  if $R$ can be described by the inequalities 
\begin{equation*}
D_1:  \quad a\leq x\leq b, \quad g_1(x)\leq y\leq  g_2(x)
\end{equation*}
where $g_1(x)$ and $g_2(x)$ are continuous functions of $x$ on $[a,b].$ 
- \index{horizontally simple region} **horizontally simple region**  if $R$ can be described by the inequalities 
\begin{equation*}
D_2: \quad c\leq y\leq d, \quad h_1(y)\leq x\leq  h_2(y)
\end{equation*}
where $h_1(x)$ and $h_2(x)$ are continuous functions of $y$ on $[c,d].$
 


::: {#thm- } [Fubini's Theorem for Non-Rectangular Regions]
\label{fubthmrect}
If $D_1$ is a vertically simple region, then 
$$
\iint_{D_1}  f(x,y) \, d A=\int _a^b \int _{g_1(x)}^{g_2(x)}f(x,y) \, dy \, dx
$$ 
whenever both integrals exist. Similarly, for a horizontally region $D_2,$ 
$$
\iint_{D_2}  f(x,y) \, d A=\int _c^d \int _{h_1(y)}^{h_2(y)}f(x,y)\, dx \, dy$$
whenever both integrals exist.
::: 

 
::: {#exm- } 

Evaluate the double integral
\begin{equation*}
\iint_D x y \, d A
\end{equation*}
where $D$ is the region bounded by the line $y=x-1$ and the parabola $y^2=2x+6$.  
::: 

::: {.solution }
The region $D$ is both a vertically simple and a horizontally simple region, but the description of $D$ as a vertically simple region is more complicated because the lower boundary consists of two parts. Therefore we express 
$D$ as a horizontally simple region: 
$$
D=\left\{(x,y)\mid-2\leq y\leq 4,\frac{y^2}{2}-3\leq x\leq y+1\right\}.
$$
as shown below. 
Then the double integral becomes  
$$
\iint_D x y \, d A
=\int _{-2}^4\int _{(1/2)y^2-3}^{y+1}x y \, dx \,dy
=\frac{1}{2}\int_{-2}^4 \left(-\frac{y^5}{4}+4 y^3+2 y^2-8y\right) \, dy
=36.
$$
If we had expressed $D$ as a vertically simple region, then we would have obtained  
$$
\iint_D x y \, d A=\int _{-3}^{-1}\int _{-\sqrt{2x+6}}^{\sqrt{2x+6}}x y \, dy \, dx+\int _{-1}^5\int _{x-1}^{\sqrt{2x+6}}x y \, dy \, dx=36.
$$ 
See \ref{figreg:surboundvol} for a visualization. 
::: 


 

::: {#exm- } 

Evaluate the iterated integral
$$
\int _0^1\int _{x^2}^{\sqrt{x}}x y^2 \, dy \, dx.
$$
::: 

::: {.solution }
We express the region of integration $D$ as a vertically simple region: 
$$
D=\left\{(x,y)\mid 0\leq x\leq 1, x^2 \leq y \leq \sqrt{x} \right\}.
$$
We use \ref{fubthmrect} to obtain
$$
\int _0^1\int _{x^2}^{\sqrt{x}}x y^2 \, dy \, dx
=\int _0^1x \left(\frac{x^{3/2}}{3}-\frac{x^6}{3}\right) \, dx
=\frac{3}{56}.
$$
See \ref{figreg:surboundvoltwo} for a visualization. 
::: 


 

::: {#exm- } 
Evaluate the iterated integral
$$
\int _0^{2\sqrt{3}}\int _{\left.y^2\right/6}^{\sqrt{16-y^2}}
\, dx \, dy.
$$
::: 

::: {.solution }
We express the region of integration $D$ as a horizontally simple region: 
$$
D=\left\{(x,y)\mid 0\leq y\leq 2\sqrt{3}, \frac{y^2}{6} \leq x \leq \sqrt{16-y^2} \right\}.
$$
We use \ref{fubthmrect} to obtain
$$
\int _0^{2\sqrt{3}}\int _{\left.y^2\right/6}^{\sqrt{16-y^2}} \, dx \, dy
=\int _0^{2\sqrt{3}}\left(\sqrt{16-y^2}-\frac{y^2}{6}\right) \, dy 
=\left(\frac{1}{18} \left(12 \sqrt{3}+48 \pi \right) \right).
$$
See \ref{figreg:surboundvolthree} for a visualization. 
::: 


 
::: {#exm- } 

Evaluate the iterated integral 
$$
\int _0^1\int _{-x^2}^{x^2} \, dy \, dx.
$$
::: 

::: {.solution }
We express the region of integration $D$ as a vertically simple region: 
$$
D=\left\{(x,y)\mid 0\leq x\leq 1, -x^2 \leq y \leq x^2 \right\}.
$$
The region of integration is sketched in \ref{fig:surboundvolfour}.
We find
\begin{align*}
& 
\int _0^1\int _{-x^2}^{x^2} \, dy \, dx
=\int _0^12 x^2 \, dx  
=\frac{2}{3}.
\end{align*}
::: 


 

::: {#exm- } 
Sketch the region of integration and evaluate
\begin{equation*}
\int _{-2}^1\int _{y^2+4y}^{3y+2} \, dx \, dy. 
\end{equation*}
::: 

::: {.solution }
The region is horizontally simple region as $-2\leq y\leq 1$ and $y^2+4y\leq x\leq 3y+2.$ 
We find 
$$
\int _{-2}^1\int_{y^2+4y}^{3y+2} dx \, dy=\int_{-2}^1 \left(-y^2-y+2\right) \, dy=\frac{9}{2}.
$$
This region could also be considered as a vertically simple region as $-4\leq x\leq 5$ and $\frac{x-2}{3}\leq y\leq -2+\sqrt{x+4}.$ 
We find
$$
\int _{-4}^5\int_{(x-2)/3}^{-2+\sqrt{x+4}} dy \, dx=\int_{-4}^5 \left(\left(-2+\sqrt{x+4}\right)-\left(\frac{x-2}{3}\right)\right)
\, dx =\frac{9}{2}.
$$
See \ref{figreg:surboundvolfive} for a visualization. 
::: 



::: {#exm- } 
Sketch the region of integration and evaluate
\begin{equation*}
\int _0^{\pi /2}\int _0^{\sin  x}e^y \cos  x \, dy \, dx. 
\end{equation*}
::: 

::: {.solution }
The region is vertically simple region as $0\leq x\leq \frac{\pi }{2}$ and $0\leq y\leq \sin  x.$ We find  
$$
\int _0^{\pi /2}\int _0^{\sin  x}e^y \cos  x \, dy \, dx=\int_0^{\pi /2} \left(e^{\sin  x}\cos  x-\cos  x\right) \, dx=e-2.$$
The region is also horizontally simple region as $0\leq y\leq 1$ and 
$\text{Arcsin}(y)\leq x\leq \frac{\pi }{2}.$ 
We find 
$$
\int _0^1\int _{\arcsin y }^{\pi /2}e^y \cos  x \, dx \, dy=e-2.
$$
See \ref{figreg:surboundvolsix} for a visualization. 
::: 



::: {#exm- } 

Sketch the region of integration and evaluate the iterated integral 
\begin{equation*}
\int _0^1\int _x^1\sin \left(y^2\right) \, dy \, dx.  
\end{equation*}
::: 

::: {.solution }
If we try to evaluate the integral as it stands, we are faced with the task of first evaluating 
\begin{equation}
\int \sin y^2 \,dy.
\end{equation}
We elect to change the order of integration. This is accomplished by first expressing the given iterated integral as a double integral. We have  
$$
\int _0^1\int _x^1\sin y^2 \, dy \, dx=\iint_D \sin y^2 \, d A
$$
where $D=\{(x,y) \mid 0\leq x\leq 1,x\leq y\leq 1\}.$ 
This region has an alternate description: 
$$
D=\{(x,y) \mid 0\leq y\leq 1,0\leq x\leq y\}.
$$
Thus we can express the double integral as an iterated integral in the reverse order: 
$$
%\int _0^1\int _x^1\sin y^2 \, dy \, dx
%=
\iint_D \sin y^2 \, d A
=\int _0^1\int _0^y\sin y^2 \, dx \, dy
=\int _0^1\left.\left[x \sin y^2\right]\right|_{0}^{y}dy
=\frac{1}{2}(1-\cos  1).
$$
::: 



## Volume as a Double Integral

::: {#thm- } [Volume as a Double Integral]
If $f(x,y)\geq 0$ on the rectangular region $R,$ then the product $f\left(x_k^*,y_k^*\right)\text{$\triangle $A}_k$ is the volume
of a parallelepiped (a box) with height $f\left(x_k^*,y_k^*\right)$ and base area $\text{$\triangle $A}_k.$ The Riemann sum
\begin{equation}
\sum _{k=1}^N f\left(x_k^*,y_k^*\right)\text{$\triangle $A}_k
\end{equation}
provides an estimate of the total volume under the surface $z=f(x,y)$ over $R,$ and if $f$ is continuous, we expect the approximation to improve
by using more refined partitions. That is, the volume under $z=f(x,y)$ over the domain $R$ is given by  
\begin{equation}
\lim _{\|P\|\to 0}\sum _{k=1}^N f\left(x_k^*,y_k^*\right)\triangle  A_k=\iint_R f(x,y)d A
\end{equation}
when $f(x,y)\geq 0$ on the rectangular region $R.$
::: 

::: {#exm- } 

Find the volume of the bounded solid that lies inside both the cylinder $x^2+y^2=3$ and the sphere $x^2+y^2+z^2=7$. 
::: 

::: {.solution }
The volume is given by  
$$
V=4\int _0^{\sqrt{3}}\int _0^{\sqrt{3-y^2}}\sqrt{7-x^2-y^2} \, dx \, dy$$
or also 
$$
V=4\int _0^{\sqrt{3}}\int _0^{\sqrt{3-x^2}}\sqrt{7-x^2-y^2} \, dy \, dx\approx  22.0336.
$$ 
::: 
  
::: {#exm- } 
Find the volume of the solid region bounded below by the given rectangle in the $x y$-plane and above by the graph of the given surface 
$$
f(x,y)=\frac{x y}{\sqrt{x^2+y^2+1}}
$$
on $0\leq  x\leq 1, 0\leq y\leq 1$ 
::: 

::: {.solution }
The volume is given by  
\begin{align*}
& \int _0^1\int _0^1\frac{x y}{\sqrt{x^2+y^2+1}} \, dy \, dx
 =\int_0^1 x \left(\sqrt{x^2+2}-\sqrt{x^2+1}\right) \, dx \\
& \qquad =\frac{1-2 \sqrt{2}}{3}+\frac{-2 \sqrt{2}+3 \sqrt{3}}{3} 
 =\frac{1-4 \sqrt{2}+3 \sqrt{3}}{3} 
\approx 0.179766
\end{align*}
::: 

::: {#exm- } 
Find the volume of the solid region bounded below by the given rectangle in the $x y$-plane and above by the graph of the surface 
$$
f(x,y)=(x+y)^5
$$ 
on $0\leq  x\leq 1, 0\leq y\leq 1$.
::: 

::: {.solution }
The volume is 
\begin{equation}
\int _0^1\int _0^1(x+y)^5dy\, dx
=\int_0^1 \left(\frac{1}{6} (x+1)^6-\frac{x^6}{6}\right) \, dx 
=3. 
\end{equation}
::: 

::: {#exm- } 

Find the volume of the bounded solid
between the two elliptic paraboloids 
$$
z=\left.x^2\right/(9+y^2-4)
\quad \text{and}\quad
z=\left.-x^2\right/(9-y^2+4).
$$ 
::: 

::: {.solution }
Using symmetry, the volume is given by  
\begin{align*} 
V& =8\int _0^6\int _0^{\sqrt{4-\left.x^2\right/9}}\int _0^{4-\left.x^2\right/9-y^2} \, dz \, dy \, dx
\\
& =8\int _0^6\int _0^{\sqrt{4-\left.x^2\right/9}}\left(-\frac{x^2}{9}-y^2+4\right) \, dy \, dx 
\\
& =8\int _0^6\left(\frac{8}{3} \sqrt{4-\frac{x^2}{9}}-\frac{2}{27} x^2 \sqrt{4-\frac{x^2}{9}}\right) \, dx
= 48 
\approx 150.796.
\end{align*}
::: 
  
::: {#exm- } 
Find the volume of the bounded solid bounded below by the rectangle 
$R: 1\leq x\leq 2, 1\leq y\leq 2$  
in the $x y$-plane and above by the graph of 
\begin{equation}
z=f(x,y)=\frac{x}{y}+\frac{y}{x}.
\end{equation}
::: 

::: {.solution }
The volume is given by the following double integral and can be compute using Fubini's theorem.  
\begin{align*}
\iint_R \left(\frac{x}{y}+\frac{y}{x}\right) \, dA
& =\int _0^2\int _1^2\left(\frac{x}{y}+\frac{y}{x}\right) \, dy \, dx 
\\
& =\int _0^2 \left.\left[x \ln |y|+\frac{y^2}{2x}\right]\, \right|^2_1 dx
\\
& =\left.\left[\frac{3}{2}\ln |x|\frac{+1}{2}(\ln  2)x^2\right]\, \right|^2_1
= \text{3 ln 2}.
\end{align*}
::: 
  
  
## Exercises

::: {#exr- } 
Sketch the region of integration and evaluate
$\int _{-2}^1\int _{y^2+4y}^{3y+2} \, dx \, dy$. 
::: 

::: {#exr- } 
Evaluate $\iint_R (x^2+y^2)^{3/2} \, dA$ where $R$ is the unit circle centered at $(0,0)$.
::: 

::: {#exr- } 
Evaluate the following iterated integrals.
 
- $\int _0^2\int _0^1\left(x^2+x y+y^2\right)dy\, dx.$ 
- $\int _1^2\int _0^{\pi }x \cos  y \, dy\, dx.$ 
- $\int _0^{\ln (2)}\int _0^1e^{x+2y}dx\, dy.$ 
- $\int _3^4\int _1^2\frac{x}{x-y}dy\, dx$ 
- $\int _2^3\int _{-1}^2\frac{1}{(x+y)^2}dy\, dx$ 
  
::: 

::: {#exr- } 
Use iterated integration to compute the double integral of the given rectangular region for each of the following.
 
- $R=\{(x,y)\mid1\leq x\leq  2,0\leq y\leq 1\}$  
$$
\iint_R x^2y\, dA
$$ 
- $R=\{(x,y)\mid-1\leq x\leq  0,0\leq y\leq \ln (2)\}$ 
$$
\iint_R2x e^y\, dA
$$ 
- $R=\left\{(x,y)\mid 0\leq  x\leq  \frac{\pi }{4}, \, 0\leq y\leq \frac{\pi }{2}\right\}$  
$$
\iint_R\sin (x+y)\, dA
$$
- $R=\{(x,y)\mid0\leq  x\leq  \pi ,0\leq y\leq 1\}$ 
$$
\iint_Rx \sin (x y)\, dA
$$
- $R=\{(x,y)\mid0\leq x\leq 1,0\leq y\leq 2\}$
$$
\iint_Rx\sqrt{1-x^2}e^{3y}\, dA
$$ 
- $R=\{(x,y)\mid0\leq x\leq 1,1\leq y\leq
2\}$ 
$$
\iint_Rx e^{x y}\, dA
$$
  
::: 

::: {#exr- } 
Find the volume of the solid bounded below by the given rectangular region  in the $x y$-plane and above the graph of the given function.
 
- $z=2x+3y$,  
$
R=\{(x,y)\mid0\leq x\leq 1,0\leq  y\leq  2\}
$
- $z=x \ln ( x y)$,
$
R=\{(x,y)\mid1\leq x\leq 2,1\leq  y\leq  e\} 
$
- $z=x \cos  y+y \sin  x.$ 
$$
R=\left\{(x,y)\mid0\leq x\leq \frac{\pi }{2}\, ,0\leq  y\leq  \frac{\pi}{2}\right\}
$$ 
  
::: 

::: {#exr- } 
Find the volume of the solid region bounded below by the given rectangle in the $x y$-plane and above by the graph of the given surface.  
 
- $f(x,y)=\frac{x y}{\sqrt{x^2+y^2+1}}$ on $0\leq  x\leq 1, 0\leq y\leq 1$ 
- $f(x,y)=(x+y)^5$ on $0\leq  x\leq 1, 0\leq y\leq 1$ 
  
::: 

::: {#exr- } 
Sketch the region and evaluate the iterated integral over the non-rectangular region. 
 
- $\int _0^4\int _0^{4-x}x ydy\, dx.$ 
- $\int _1^e\int _0^{\ln (x)}x ydy\, dx.$ 
- $\int _0^2\int _0^{\sin (x)}y \cos  xdy\, dx.$ 
- $\int _{-2}^1\int _{y^2+4y}^{3y+2} dx\, dy.$ 
- $\int _0^{2\sqrt{3}}\int _{\left.y^2\right/6}^{\sqrt{16-y^2}}
dx\, dy.$ 
- $\int _0^1\int _{-x^2}^{x^2} dy\, dx.$ 
- $\int _0^4\int _{x^2}^{4x} dy\, dx.$ 
- $\int _0^1\int _{x^2}^{\sqrt{x}}x y^2dy\, dx$ 
- $\int _{-1}^3\int _{\tan ^{-1}x}^{\pi /4}x ydy\, dx.$ 
- $\int _0^4\int _0^{4-x}x ydy\, dx.$ 
- $\int _0^7\int _{x^2-6x}^x \sin x dy\, dx$ 
 
::: 

::: {#exr- } 
Find the volume of the solid bounded by 
$$
\frac{x^2}{a^2}+\frac{y^2}{b^2}+\frac{z^2}{c^2}=1.
$$ 
(Setup but do not evaluate the double integral)
::: 

::: {#exr- } 
Find the volume of the solid that lies inside both the cylinder $x^2+y^2=3$ and the sphere $x^2+y^2+z^2=7$. (Setup but do not evaluate the double integral). 
::: 

::: {#exr- } 
For each of the following sketch the region of integration and write an equivalent integral with the order of integration reversed for 
 
- $\int _0^1\int _0^{2y}f(x,y)\, dx\, dy.$  
- $\int _0^1\int _{x^2}^{\sqrt{x}}f(x,y)\, dy\, dx.$  
- $\int _0^4\int _{y/2}^{\sqrt{y}}f(x,y)\, dx\, dy.$ 
- $\int _1^2\int _{\ln (x)}^2f(x,y)\, dy\, dx.$  
- $\int _0^3\int _{y/3}^{\sqrt{4-y}}f(x,y)\, dx\, dy.$ 
  
::: 

::: {#exr- } 
Evaluate the double integral
$$
\iint_D x y \, dA
$$
where $D$ is the triangular region in the $x y$-plane with vertices $(0,0),$ $(1,0),$ and
$(4,1).$ 
::: 

::: {#exr- } 
Evaluate the double integral
$$
\iint_D \left(x^2-x y-1\right)\, dA
$$ 
where $D$ is the triangular region in the $x y$-plane bounded by the lines
$x-2y+2=0,$ $x+3y-3=0,$ and $y=0.$  
::: 

::: {#exr- } 
(a) Write the iterated integral $I=\int_0^1 \int_y^1 \sin ( x^2 ) \, dx \, dy$ as a double integral over a domain $R$. 
(b) Sketch the domain $R$. 
(c) Evaluate the double integral by reversing the order of integration. 
::: 




