---
pagetitle: "Line Integrals - Exploring Calculus"
---
# Line Integrals

  
Let $C$ be a smooth curve, with parametric equations $x=x(t),$ $y=y(t),$ and $z=z(t)$ for $a\leq t\leq b,$ that lies within the domain of a function $f(x,y,z).$ We say that $C$ is \index{orientable} **orientable** if it is possible to describe direction along the curve for increasing $t.$ Partition $C$ into $n$ sub-arcs, the $k \text{th}$ of which has length $\triangle s_k.$ Let $\left(x_k^*,y_k^*,z_k^*\right)$ be a point chosen (arbitrarily) from the $k \text{th}$ sub-arc. Form the Riemann sum 
$$
\sum _{k=1}^n f\left(x_k^*,y_k^*,z_k^*\right)\triangle  s_k$$
and let $\|\triangle  s\|$ denote the largest sub-arc length in the partition. 
The following limit 
$$
\lim _{\|\text{$\triangle $s}\|\to 0}\sum _{k=1}^n f\left(x_k^*,y_k^*,z_k^*\right)\triangle  s_k$$
is called the \index{line integral} **line integral**  of $f$ over $C$ and is denoted by 
$$
\int _Cf(x,y,z)\, dS.
$$
Additionally, if $C$ is a closed curve, then we denote the line integral by 
$$
\oint _C\text{  }f \, dS.
$$
 
::: {#thm- } 

Let $f,$ $f_1,$ and $f_2$ be continuous scalar functions defined on a piecewise smooth orientable curve $C.$
Then for any constants $k_1$and $k_2,$
 
- $\int _C \left(k_1 f_1+k_2f_2\right) \, dS=k_1\int _Cf_1 \, dS+k_2\int _Cf_2 \, dS$
- $\int _C f \, dS=\int _{C_1}f \,\, dS+\cdots+\int _{C_n}f \,\, dS$
where $C$ is the union of smooth orientable sub-arcs $C=C_1\cup C_2\cup \cdots \cup C_n$ with only endpoints in common.
- $\int _{-C} f \, dS=-\int _C f \, dS.$
 
::: 


## Evaluating Line Integrals Using Parametrization

::: {#thm- }  

Suppose that the function $f$ is continuous at each point on a smooth curve $C$, with parametric equations $x=x(t),$ $y=y(t),$ and $z=z(t)$ for $a\leq t\leq b,$ that lies within the domain of $f.$ 
Then 
$$
\int _Cf(x,y,z)\, dS=\int _a^bf( x(t),y(t),z(t) )\sqrt{[x'(t)]^2+[y'(t)]^2+[z'(t)]^2} \, dt .
$$
where
$\, dS=\sqrt{[x'(t)]^2+[y'(t)]^2+[z'(t)]^2} \, dt$. 
::: 

The definition of a line integral can be extended to curves that are piecewise smooth in the sense that they are the union of a finite number of smooth curves with only endpoints in common. In particular, if $C$ is comprised of a number of smooth sub-arcs $C_1,C_2,\ldots,C_n,$ then 
$$
\int _C f(x,y,z)\, dS=\int _{C_1} f(x,y,z)\, dS+\cdots +\int _{C_n} f(x,y,z)\, dS.
$$

::: {#exm- } 

Evaluate the line integral
$$
\int _Cy \sin  z \, dS,
$$ 
where $C$ is the circular helix given by the equations   $x=\cos  t, y=\sin t, z=t,$ and $0\leq t\leq 2\pi$.
::: 

::: {.solution }
We determine
\begin{align*}
\int _C y \sin  z \, dS
& =\int _0^{2\pi }(\sin  t) \sin  t \sqrt{\left(\frac{d x}{d t}\right)^2+\left(\frac{d y}{d t}\right)^2+\left(\frac{d z}{d t}\right)^2}dt 
\\
& =\int _0^{2\pi }\sin ^2 t \sqrt{\sin ^2t+\cos ^2t+1}dt 
\\
& =\sqrt{2}\int _0^{2\pi }\frac{1}{2}(1-\cos  2t)dt 
\\
& =\frac{\sqrt{2}}{2}\left[t-\frac{1}{2}\sin  2t\right]_0^{2\pi } 
 =\sqrt{2}\pi.
 \end{align*}
::: 
  
::: {#thm- } 

Let $C$ be a smooth curve and let $f(x,y,z)$ be a continuous function with domain containing the trace of $C.$ Then the value of the integrals 
$$
\int _C f \, dS, \quad \int _C f dx, \quad \int _C f dy, \quad \int _C f dz$$
depen\, dS only on the initial point $A,$ terminal point $B,$ and the trace of $C.$ That is, two different parameterizations having the same trace
from $A$ to $B$ yield the same values for these integrals.
::: 

::: {#exm- } 

Suppose the smooth curves $C_1$ and $C_2$ are given by  
\begin{align*}
& C_1: \quad x=t, \, y=t^2 \quad \text{ for }  0\leq t\leq 1, \text{ and} 
\\
& C_2:  \quad x=\sin  t, \, y=\sin ^2 t\quad \text{ for }  0\leq t\leq \frac{\pi }{2}. 
\end{align*}
Evaluate  
$$
\int _{C_1} x \, dS
\quad \text{ and } \quad 
\int _{C_2} x \, dS.
$$
::: 

::: {.solution }
Both $C_1$ and $C_2$ are smooth curves from $(0,0)$ to $(1,1)$ with the same trace which is the portion of the parabola
$y=x^2$ for $0\leq x\leq 1.$ For $C_1,$ we have   $x=t$ and $\, dS=\sqrt{1+4t^2}dt,$ therefore 
$$
\int _{C_1} x \, dS=\int _0^1t\sqrt{1+4t^2}dt=\frac{1}{12}\left(17^{3/2}-1\right).
$$ 
For $C_2,$ we have   $x=\sin  t$ and $\, dS=\sqrt{\cos ^2t+4\sin ^2t\text{  }\cos ^2t}dt,$ therefore 
\begin{equation*}
\int _{C_2} x \, dS=\int _0^{\pi /2} \sin  t\text{  }\cos  t\sqrt{1+4\sin ^2t}dt=\frac{1}{12}\left(17^{3/2}-1\right).
\end{equation*}
::: 
 
## Line Integrals with Respect to Coordinate Variables

Other line integrals are obtained by replacing $\triangle  s_k$ by $\triangle  x_k=x_k-x_{k-1}.$ 
This is called the \index{line integral} **line integral**  of $f$ along $C$ with respect to $x$: 
$$
\int _C f(x,y,z) \,dx=\lim _{\| \triangle x\|\to  0}\sum _{k=1}^n f\left(x_k^*,y_k^*,z_k^*\right)\triangle  x_k.$$
Similarly with respect to $y$ and $z$, we define
$$
\int _C f(x,y,z) \,dy=\lim _{\| \triangle y \|\to  0}\sum _{k=1}^n f\left(x_k^*,y_k^*,z_k^*\right)\triangle  y_k$$
$$
\int _C f(x,y,z) \,dz=\lim _{\| \triangle z\|\to  0}\sum _{k=1}^n f\left(x_k^*,y_k^*,z_k^*\right)\triangle  z_k.$$
When we want to distinguish the original line integral $\int _Cf \,\, dS$ from these, we call it the \index{line integral} **line integral**  with respect to arc length. 

The following formulas say that the line integrals with respect to $x,$ $y,$ or $z$ can also be evaluated by expressing everything in terms of $t$: $x=x(t),$ $y=y(t),$ $z=z(t),$ $dx=x'(t),$ $dy=y'(t),$ and $dz=z'(t)$ yielding: 
$$\int _C f(x,y,z)\,d x=\int _a^b f( x(t),y(t),z(t) )x'(t)\,dt$$
$$\int _C f(x,y,z)\,d y=\int _a^b f( x(t),y(t),z(t) )y'(t)\,dt$$
and
$$\int _C f(x,y,z)\,d z=\int _a^b f( x(t),y(t),z(t) )z'(t)\,dt$$
assuming $f$ is continuous and $C$ lies within the domain of $f$.

::: {#exm- } 

Evaluate the line integral
$$
\int _C y \,dx+z \,dy+x \,dz,
$$ 
where $C$ consists of the line segment $C_1$ from $(2,0,0)$ to $(3,4,5)$ followed by the vertical line segment $C_2$ from $(3,4,5)$ to $(3,4,0)$
::: 

::: {.solution }
The curve $C$ is the union of the curves
\begin{align*}
& C_1: \vec{R}_1(t)=(1-t)\langle 2,0,0\rangle+t \langle 3,4,5\rangle = \langle 2+t,4t,5t\rangle  \text{ for } 0\leq t\leq 1
\\
& C_2: \vec{R}_2(t)=(1-t)\langle3,4,5\rangle+t\langle3,4,0\rangle=\langle3,4,5-5t\rangle \text{ for } 0\leq t\leq 1.
\end{align*}
Thus 
\begin{align*}
\int _C y \, dx+z\, dy+x\, dz 
& =\int _{C_1} y \, dx+z\, dy+x\, dz+\int _{C_2} y \, dx+z \, dy+x \, dz  \\
& =\int_0^1 ( (4t)+5t(4)+(2+t)5) \, dt +\int _0^1( 0+0+3(-5) )\, dt \\
& =\int_0^1 (10+29t) \, dt +\int _0^1 (-15)\, dt 
%\\ & =\left[10t+29\frac{t^2}{2}\right]_0^1 +\left[-15t\right]_0^1  
%= 24.5 -15
=9.5
\end{align*}
::: 
  
## Line Integral of Vector Field Along a Curve

::: {#thm- } 
Let 
$$
\vec{V}(x,y,z)=u(x,y,z)\vec{i}+v(x,y,z)\vec{j}+w(x,y,z)\vec{k}
$$
be a continuous vector field, and let $C$ be a piecewise smooth orientable curve with parametric representation 
$$
\vec{R}(t)=x(t) \vec{i}+y(t) \vec{j}+z(t) \vec{k} 
$$
for $a\leq  t\leq  b.$
Using $d\vec{R}=dx  \vec{i}+dy  \vec{j}+dz  \vec{k}$ we define the \index{line integral} **line integral** of $\vec{V}$ along $C$ by
\begin{align*}
& \int _C \vec{V}\cdot d \vec{R}  
=\int _C ( u \, dx +v \, dy +w \, dz) 
=\int _C \left( \vec{V}[\vec{R}(t)]\cdot \vec{R}'(t) \right)dt \\
&  \qquad =\int _a^b \left[u[x(t),y(t),z(t)]\frac{dx}{dt}+v[x(t),y(t),z(t)]\frac{dy}{dt}+w[x(t),y(t),z(t)]\frac{dz}{dt}\right]d t.\end{align*}
::: 

::: {#thm- }  
Let $\vec{F}$ be a continuous force field over a domain $D.$ Then the work $W$ performed as an object moves along a smooth curve $C$ in $D$ is given by the integral 
$$
W=\int _C \vec{F}\cdot \vec{T} \, \, dS=\int _C \vec{F}\cdot d\vec{R}
$$ 
where  $\vec{T}$ is the unit tangent at each point on $C$ and $\vec{R}$ is the position vector of the object moving on $C.$
::: 

::: {#exm- } 

Evaluate the line integral
$$
\oint \vec{F}\cdot \, d\vec{R}
$$ 
where $\vec{F}=y^2\vec{i} +x^2 \vec{j}-(x+z)\vec{k}$ and $C$ is the boundary of the triangle with vertices $(0,0,0),$ $(1,0,0),$ and $(1,1,0)$, transversed once clockwise, as viewed from above.
::: 

::: {.solution }
First let $C_1$ be the line segment from $(1,0,0)$ to $(0,0,0).$ Then $C_1$ can be represented by the vector function  
$$
\vec{R}_1(t)=(1-t)\langle 1,0,0\rangle +t\langle 0,0,0\rangle =\langle 1-t,0,0\rangle
$$ 
with $0\leq t\leq 1.$ 
Let $C_2$ be the line segment from $(0,0,0)$ to $(1,1,0)$ and so can be represented by the vector function,  
$$
\vec{R}_2(t)=(1-t)\langle 0,0,0\rangle +t\langle1,1,0\rangle =\langle t,t,0\rangle
$$  
with $0\leq t\leq 1.$ 
Let $C_3$ be the line segment from $(1,1,0)$ to $(1,0,0)$ and so can be represented by the vector function,  
$$
\vec{R}_3(t)=(1-t)\langle1,1,0\rangle+t\langle1,0,0\rangle =\langle 1,1-t,0\rangle
$$ 
with $0\leq t\leq 1$. 
Then  
\begin{align*}
& \vec{F}_1=\left(1-t^2\right)\vec{j}-(1-t)\vec{k} & 
& d\vec{R}_1=\langle -dt,0,0\rangle \\
& \vec{F}_2=t^2\vec{i}+t^2\vec{j}-t \vec{k} & 
 & d\vec{R}_2=\langle dt,dt,0\rangle \\
& \vec{F}_3=(1-t)^2\vec{i}+\vec{j}-\vec{k} & 
& d\vec{R}_3=\langle 0,-dt,0\rangle\end{align*}
We find 
\begin{align*}
\int_C \vec{F}\cdot d\vec{R}
& =\underset{C_1}{\int }\vec{F}_1\cdot d\vec{R}_1+\underset{C_2}{\int }\vec{F}_2\cdot d\vec{R}_2+\underset{C_3}{\int }\vec{F}_3\cdot d\vec{R}_3 \\
& =\int_0^1 0 \, dt+\int_0^1 2t^2 \, dt+\int_0^1 (-1) \, dt=-\frac{1}{3}.
\end{align*}
::: 
  




## Independence of Path

::: {#def- } 
The line integral is called \index{independent of path} **independent of path**  if in a region $D$, if for any two points $P$ and $Q$ in $D$ then the line integral along every piecewise smooth curve in $D$ from $P$ to $Q$ has the same value. 
::: 

::: {#thm- } [Independence of Path] 
If $\vec{V}$ is a continuous vector field on the open connected set $D,$ then the following three conditions are either all true or all false:
 
- $\vec{V}$ is conservative on $D$
- $\int _C \vec{V}\cdot d\vec{R}=0$ for every piecewise smooth closed curve $C$ in $D$.
- $\int _C \vec{V}\cdot d\vec{R}$ is independent of path within $D$.
 
::: 

::: {#exm- } 
Let $F=\langle y,-x\rangle$ and let $C_1$ and $C_2$ be the following two paths joining $(0,0)$ to $(1,1)$; $C_1$: $y=x$ for $0\leq x\leq 1$ and $C_2$: $y=x^2$ for $0\leq x\leq 1$. 
Show that 
$$
\int _{C_1}\vec{F}\cdot d \vec{R}\neq \int _{C_2}\vec{F}\cdot d \vec{R}. 
$$
Explain what this means?
On $C_1:$ $x=t,$ $y=t$ with $0\leq  t\leq  1,$ 
$$
\int_{C_1} y \, dx-x \, dy=\int_0^1 (t-t) \, dt=0.
$$
On $C_2:$ $x=t,$ $y=t^2,$ with $0\leq t\leq 1,$ 
$$
\int_{C_2}y \,dx-x\,dy=\int_0^1 \left(t^2-t(2t)\right) \, dt=-\frac{1}{3}.
$$
::: 

::: {.solution }
Since these two line integrals do not have the same value we see that not all line integrals are independent of path.  
::: 


## Fundamental Theorem of Line Integrals

::: {#thm- } [Fundamental Theorem of Line Integrals] 
Let $C$ be a piecewise smooth curve that is parametrized by the vector function $\vec{R}(t)$ for ${a\leq t\leq b}$ and let $\vec{V}$ be a vector field that is continuous on $C$. 
If $f$ is a scalar function such that $\vec{V}=\nabla  f,$ then 
$$
\int _C \vec{V}\cdot d\vec{R}=f(Q)-f(P)$$
where $Q=R(b)$ and $P=R(a)$ are the endpoints of $C$.
::: 

::: {.proof } 
Suppose $\vec{R}(t)=x(t) \vec{i}+y(t) \vec{j}+z(t) \vec{k}$ and let $G$ be the composite function $G(t)=f(x(t),y(t),z(t))$. 
We have
\begin{align*}
\int _C \vec{F}\cdot d\vec{R} 
& =\int _C\nabla f\cdot d\vec{R} 
=\int _C \left[\frac{\partial f}{\partial x}dx+\frac{\partial f}{\partial y}dy+\frac{\partial f}{\partial z}dz\right] 
\\
& =\int_a^b \left[\frac{\partial f}{\partial x}\frac{dx}{dt}+\frac{\partial f}{\partial y}\frac{dy}{dt}+\frac{\partial f}{\partial z}\frac{dz}{dt}\right] 
\, dt 
\\
& =\int_a^b \frac{d G}{d t} \, dt 
=G(b)-G(a)
=f(Q)-f(P).
\end{align*}
::: 

::: {#exm- } 
Show that the vector field 
$$
\vec{F}(x,y,z)=\left( \frac{y}{1+x^2}+\tan ^{-1}z\right)\vec{i}+\left(\tan ^{-1}x\right) \vec{j}+\left(\frac{x}{1+z^2}\right)\vec{k} 
$$  
is conservative and find a scalar potential $f$ for $F$. 
Then evaluate the line integral 
$$
\int _C \vec{F}\cdot d \vec{R}.
$$
where $C$ is any piecewise smooth path connecting $A(1,0,-1)$ to $B(0,-1,1)$.
::: 

::: {.solution }
Since $\text{curl}  \vec{V}=\vec{0},$ $\vec{V}$ is conservative. 
Now we set out to find $f$. 
Since  
$$
\frac{\partial f}{\partial x}=\frac{y}{1+x^2}+\tan ^{-1}z
$$ 
we set 
$$
f(x,y,z)=y \tan ^{-1}x+x \tan ^{-1}z+c(y,z).
$$
Since  
$$
\frac{\partial f}{\partial y}=\tan ^{-1}z=\frac{\partial }{\partial y}\left(y \tan ^{-1}x+x \tan ^{-1}z+c\right)=\tan ^{-1}x+\frac{\partial
c}{\partial y},
$$  
so  $\frac{\partial c}{\partial y}=0$ and $c=c_1(z)$ and so we set   
$f(x,y,z)=y \tan ^{-1}x+x \tan ^{-1}z+c_1(z)$. 
Since 
$$
\frac{\partial f}{\partial z}=\frac{x}{1+z^2}=\frac{\partial }{\partial z}\left[y \tan ^{-1}x+x \tan ^{-1}z+c_1(z)\right]=\frac{x}{1+z^2}+c'_1(z),$$
so  $c_1'(z)=0,$ $c_1=0$ and so we set  
$f(x,y,z)=y \tan ^{-1}x+x \tan ^{-1}z$.  
\begin{equation*}
\int _C\vec{F}\cdot d \vec{R}=f(1,0,-1)-f(0,-1,1)
 =\frac{3\pi }{4}+\frac{\pi }{4}
=\pi .
\end{equation*}
::: 

::: {#exm- } 
Show that the vector field 
$$
\vec{V}(x,y,z)=\left(x y^2+y z\right)\vec{i}+\left(x^2y+x z+3y^2z\right)\vec{j}+\left(x y+y^3\right)\vec{k}
$$
is conservative and find a scalar potential $f$ for $\vec{V}$. 
Then evaluate the line integral 
$$
\int _C \vec{F}\cdot d \vec{R}.
$$ 
where $C$ is any piecewise smooth path joining $A(8,6,1)$ to $B(1,3,5)$. 
::: 

::: {.solution }
First we determine $\text{curl}  \vec{V}$. 
We find
\begin{align*}
\text{curl}  \vec{V} & =\left|
\begin{array}{cc}
\begin{array}{c}
 \vec{i} \\ 
\begin{array}{c}
\partial / \partial x \\
 x y^2+y z
\end{array}
\end{array}
 & 
\begin{array}{cc}
\vec{j} & \vec{k} \\ 
\begin{array}{c}
\partial / \partial y \\
 x^2y+x z+3y^2z
\end{array}
 & 
\begin{array}{c}
\partial / \partial z \\
 x y+y^3
\end{array}
\end{array}
\end{array}
\right|  \\
& =\left(x+3y^2-x-3y^2\right)\vec{i}-(y-y)\vec{j}+(2x y+z-2x y-z)\vec{k}
=\vec{0}\end{align*}
and so the vector field is conservative and we can find the scalar potential function. 
Now we set out to find $f$ with $\nabla f=\vec{V}$. 
Since $f_x=x y^2+y z$ we know that  
$$
f(x,y,z)=\frac{x^2}{2}y^2+x y z+C_1(y,z).
$$
Then we find 
$$
f_y=x^2y+x z+\frac{ \partial  C_1}{\partial  y};
$$ 
and so comparing this with the given $x^2y+x z+3y^2z$ we determine that 
$$
\frac{ \partial  C_1}{\partial  y}=3y^2z.
$$ 
So $C_1=y^3z+C_2(z)$. 
So far we have 
$$
f=\frac{x^2}{2}y^2+x y z+y^3z+C_2(z).
$$ 
Also since $f_z=x y+y^3+\frac{dC_2}{d z}$ and comparing this to the given $x y+y^3$ we determine $\frac{dC_2}{dz}=0$. 
So $C_2$ is a constant with respect to $x,$ $y,$ and $z$. 
Therefore a scalar potential function is 
$$
f(x,y,z)=\frac{x^2}{2}y^2+x y z+y^3z$$
(taking the constant to be zero). 
Finally
\begin{equation}
\int _C \vec{V}\cdot d\vec{R}=f(1,3,5)-f(8,6,1)
%=\frac{2523}{2}.
\end{equation}
::: 

::: {#exm- } 
Show that the vector field is conservative and find a scalar potential $f$ for $F$. 
Then evaluate the line integral 
$$
\int _C \vec{F}\cdot d \vec{R}
= \vec{F}(x,y)=\frac{(y+1)\vec{i}-x \vec{j}}{(y+1)^2}
$$  
where $C$ is any smooth path connecting $A(0,0)$ to $B(1,1)$.
::: 

::: {.solution }
Let $\vec{F}(x,y)=u(x,y)\vec{i}+v(x,y)\vec{j}$, then since 
$$
\frac{\partial u}{\partial y}=\frac{-1}{(y+1)^2}=\frac{\partial v}{\partial x},
$$ 
we know that $F$ is conservative. 
By definition, we know 
$$
f_x(x,y)=\frac{1}{y+1} 
\qquad \text{and}\qquad
f_y(x,y)=\frac{-x}{(y+1)^2}.
$$ 
Integrating with respect to $x,$ $f(x,y)=\frac{x}{y+1}+c(y)$. 
Since,   
$$ 
f_y(x,y)=-\frac{x}{(y+1)^2}+c'(y)=-\frac{x}{(y+1)^2},
$$ 
so $c'(y)=0$.  
For $c(y)=0;$ and then $f(x,y)=\frac{x}{y+1}$ is a scalar potential function for $\vec{F}$. 
By the fundamental theorem of line integrals, 
\begin{equation*}
\int_C \vec{F}\cdot d\vec{R}=f(1,1)-f(0,0)=\frac{1}{2}-0=\frac{1}{2}.
\end{equation*}
::: 

## Work

::: {#exm- } 
Find the work done on an object moves in the force field 
$$
\vec{F}(x,y,z)=x  \vec{i}+y  \vec{j}+(x z-y)\vec{k}
$$ 
along the curve $C$ defined parametrically by 
$\vec{R}(t)=t^2\vec{i}+2t \vec{j}+4t^3 \vec{k}$ for $0\leq t\leq 1$.
::: 

::: {.solution }
We determine
\begin{align*}
& d\vec{R}=\left(2t \vec{i}+2\vec{j}+12t^2\vec{k}\right)dt, 
\qquad \vec{F}(t)=t^2\vec{i}+2t\vec{j}+\left(4t^5-2t\right)\vec{k},
\end{align*}
(from $x(t)=t^2, y(t)=2t,$ and $z=4t^3$) and
$$
\vec{F}\cdot d\vec{R}=\left(2t^3+4t+48t^7-24t^3\right)dt.
$$
Thus, 
\begin{equation*}
W=\int _C \vec{F}\cdot d\vec{R}=\int_0^1 \left(2t^3+4t+48t^7-24t^3\right) \, dt=\frac{5}{2}.
\end{equation*}
::: 

::: {#exm- } 
Find the work done when an object moves along a closed path in a connected domain where the force field is conservative.
::: 

::: {.solution }
In such a force field $\vec{F},$ where $f$ is a scalar potential of $\vec{F}$ and because the path of motion is closed, it begins and ends at the same point $P$. 
Thus, the work is given by 
$$
W=\oint _C \vec{F}\cdot d\vec{R}=f(P)-f(P)=0.
$$
::: 
 
::: {#exm- } 
Let   
$$
\vec{F}(x,y)=\frac{-y  \vec{i}+x  \vec{j}}{x^2+y^2}.
$$ 
Evaluate the line integral 
$$
\int _{C_1}\vec{F}\cdot d \vec{R}
$$ 
where $C_1$ is the upper semicircle $y=\sqrt{1-x^2}$ transversed counterclockwise. 
What is the value of 
$$
\int _{C_2}\vec{F}\cdot d \vec{R}
$$
if $C_2$ is the lower semicircle $y=-\sqrt{1-x^2}$ also transversed counterclockwise?  
::: 

::: {.solution }
On the upper semi-circle $C_1$, we let $x=\cos (t)$ and $y=\sin (t)$ for $0\leq t\leq \pi ,$ and then  
$$
\int_{C_1} \frac{-y \, dx+x \, dy}{x^2+y^2}=\int_0^{\pi } \frac{-\sin (t)(-\sin (t))+\cos (t)(\cos (t))}{\sin ^2(t)+\cos ^2(t)} \, dt=\int _0^{\pi }dt=\pi .
$$ 
For $\pi \leq t\leq 2\pi ,$ we have the lower semi-circle $C_2$:  
\begin{equation*}
\int_{C_2}\frac{-y\, dx+x\, dy}{x^2+y^2}=\int _{\pi }^{2\pi }dt=\pi .
\end{equation*}
::: 
  
## Finding Area with Line Integral

::: {#thm- } 
If $R$ is a region bounded by a piecewise smooth simple closed curve $C$ oriented counterclockwise, then the area of $R$ is given by 
$$
A=\oint _C x dy=-\oint _C y dx=\frac{1}{2}\oint _C x dy-ydx.
$$
::: 

## Exercises

::: {#exr- } 
Evaluate the line integral 
$$
\int _C\frac{1}{3+y}\, dS
$$ 
where $C$ is the curve with parametric equations $x=2t^{3/2}$ and $y=3t$ with $0\leq t\leq
1.$
::: 

::: {#exr- } 
Evaluate the line integral 
$$
\int _C\left(x^2+y^2\right)\, dS
$$ 
where $C$ is the curve with parametric equations $x=e^{-t}\cos  t$ and $y=e^{-t}\sin t$ with $0\leq t\leq \frac{\pi }{2}.$ 
::: 

::: {#exr- } 
Evaluate the line integral 
$$
\int _C xdy-ydx
$$ 
where $C$ is the curve defined by $2x-4y=1$ with $4\leq x\leq 8.$ 
::: 

::: {#exr- } 
Evaluate the line integral 
$$
\int _C -xdy+\left(y^2-x^2\right)dx
$$ 
where $C$ is the quarter-circle $x^2+y^2=4$ from $(0,2)$
to $(2,0).$
::: 

::: {#exr- } 
Evaluate the line integral 
$$
\int _C (x+y)^2dx-(x-y)^2 dy
$$ 
where $C$ is the curve defined by $y=|2x|$ from $(-1,2)$ to $(1,2).$
::: 

::: {#exr- } 
Evaluate the line integral 
$$
\oint \vec{F} \cdot d\vec{R}
$$ 
where $\vec{F}=y^2 \vec{i} +x^2 \vec{j}-(x+z)\vec{k}$ and $C$ is the boundary of the triangle with vertices $(0,0,0),$ $(1,0,0),$ and $(1,1,0)$, transversed once clockwise, as viewed from above.
::: 

::: {#exr- } 
Let $\vec{F}=y \, \vec{i}-x \, \vec{j}$ and let $C_1$ and $C_2$ be the following two paths joining 
$(0,0)$ to $(1,1).$
$$
C_1: y=x  \text{ for } 0\leq x\leq 1 
\quad \text{and} \quad 
C_2: y=x^2 \text{ for } 0\leq x\leq 1.
$$ 
Show that 
$$
\int _{C_1}\vec{F}\cdot d \vec{R}\neq \int _{C_2}F\cdot d \vec{R}. 
$$
Explain what this means? 
::: 

::: {#exr- } 
Evaluate the closed line integral 
$$
\oint _C \vec{F}\cdot \, dS
$$ 
where $\vec{F}=-x \, \vec{i}+2\,\vec{j}$ and $C$ is the boundary of the trapezoid with vertices $(0,0),$
$(1,0),$ $(2,1)$ and $(0,1)$ transversed once clockwise, as viewed from above. 
::: 

::: {#exr- } 
Find the work done by the force field 
$$
\vec{F}(x,y,z)=\left(y^2-z^2\right) \vec{i}+2 y z \vec{j}-x^2 \vec{k}
$$ 
on any object moving along the curve 
$C$ where $C$ is the path given by $x(t)=t,$ $y(t)=t^2,$ and $z(t)=t^3,$ for $0\leq t\leq 1.$ 
::: 

::: {#exr- } 
Find the work done by the force field 
$$
\vec{F}(x,y,z)=2 x y \, \vec{i}+\left(x^2+2\right)\, \vec{j}+y \,\vec{k}
$$ 
on any object moving along the curve $C$ where $C$ is the line segment from $(1,0,2)$ to $(3,4,1).$ 
::: 

::: {#exr- } 
Show that the vector field 
$$
\vec{F}(x,y)=(x+2y)\, \vec{i}+(2x+y)\, \vec{j}
$$ 
is conservative and find a scalar potential function $f$ for $F.$ 
Then evaluate the line integral $\int _C \vec{F}\cdot d\vec{R}$ where $C$ is any smooth path connecting $A(0,0)$to $B(1,1).$
::: 

::: {#exr- } 
Show that the vector field 
$$
\vec{F}(x,y)=\left(y-x^2\right) \, \vec{i}+\left(x+y^2\right) \, \vec{j}
$$ 
is conservative and find a scalar potential function $f$ for
$\vec{F}.$ 
Then evaluate the line integral 
$$
\int _C \vec{F}\cdot dR
$$ 
where $C$ is any smooth path connecting $A(0,0)$to $B(1,1).$
::: 

::: {#exr- } 
Show that the vector field 
$$
\vec{F}(x,y)=e^{-y}\, \vec{i}-x e^{-y}\, \vec{j}
$$ 
is conservative and find a scalar potential function $f$ for $\vec{F}.$ 
Then evaluate the line integral 
$$
\int _C\vec{F}\cdot d\vec{R}
$$ 
where $C$ is any smooth path connecting $A(0,0)$to $B(1,1).$
::: 

::: {#exr- } 
Show that the vector field 
$$
\vec{F}(x,y,z)=e^{x y}y z \, \vec{i}+e^{x y}x z \, \vec{j}+e^{x y} \, \vec{k}
$$ 
is conservative and find a scalar potential function $f$ for $\vec{F}.$ 
::: 

::: {#exr- } 
Show that the vector field  $\vec{F}$ with component functions
$f(x,y,z)=\left(2 x z^3-e^{-x y}y \sin  z\right)$,
$g(x,y,z)=-x e^{-x y}\sin  z$, and
$h(x,y,z)=\left(3x^2z^2+e^{-x y}\cos  z\right)$ 
is conservative and find a scalar potential function $f$ for $\vec{F}.$ 
Then evaluate the line integral 
$$
\int _C\vec{F}\cdot d\vec{R}
$$ 
where $C$ is any smooth
path connecting $A(1,0,-1)$to $B(0,-1,1).$
::: 

::: {#exr- } 
Show that the vector field 
$$
\vec{F}(x,y)=\frac{(y+1)\vec{i}-x \vec{j}}{(y+1)^2}
$$ 
is conservative and find a scalar potential $f$ for $\vec{F}.$ 
Then evaluate the line integral 
$$
\int _C\vec{F}\cdot d \vec{R}
$$ 
where $C$ is any smooth path connecting $A(0,0)$ to $B(1,1).$
::: 


  

## Green's Theorem

Suppose $C$ is a piecewise smooth closed curve oriented counterclockwise in the Cartesian plane whose bounded region $R$ is \index{simply connected} **simply connected** . 
Suppose further that we have a \index{continuously differentiable} **continuously differentiable** vector field of the form $\vec{F}=M(x,y)\vec{i}$.  
Let $[a,b]$ be the projection of $R$ onto the $x$-axis, let $y_1(x)$ represent the lower part of the curve $C$,  and let $y_2(x)$ represent the upper part of $C$. 
We can write 
\begin{align}
\label{gr1}
\oint_C \vec{F}\cdot \, d\vec{r}
& = \int_a^b M(x,y_1(x)) \, dx  + \int_b^a M(x,y_2(x)) \, dx \notag \\
& = \int_a^b \left[M(x,y_1(x)) - M(x,y_2(x)) \right] \, dx \notag \\
& = - \int_a^b M(x,y)\vert_{y_1(x)}^{y_2(x)} \, dx \notag \\
& = - \int_a^b \int_{y_1(x)}^{y_2(x)} \frac{\partial M}{\partial y} \, dy \, dx \notag \\
& =-\iint_R  \frac{\partial M}{\partial y} \, dy \, dx 
\end{align}
Now let us suppose that we have a continuously differentiable vector field of the form $\vec{F}=N(x,y)\vec{j}$.  
Let $[a,b]$ be the projection of $R$ onto the $y$-axis, let $x_1(y)$ represent the lower part of the curve $C$,  and let $x_2(y)$ represent the upper part of $C$. 
We can write 
\begin{align}
\label{gr2}
\oint_C \vec{F}\cdot \, d\vec{r}
& = \int_a^b N(x_1(x),y) \, dy + \int_b^a N(x_2(x),y) \, dy\notag \\
& = \int_a^b \left[N(x_1(y),y) - N(x_2(y),y) \right] \, dy \notag \\
& = - \int_a^b N(x,y)\vert_{x_1(y)}^{x_2(y)} \, dy \notag \\
& = \int_a^b \int_{x_2(y)}^{x_1(y)} \frac{\partial N}{\partial x} \, dx \, dy \notag \\
& =\iint_R  \frac{\partial N}{\partial x} \, dx \, dy
\end{align}
Finally, suppose that $\vec{F}$ is a continuously differentiable vector field in the plane, say 
$$
\vec{F}(x,y)=M(x,y)\vec{i}+N(x,y)\vec{j}.
$$ 
Using \ref{gr1} and \ref{gr2} we find 
\begin{align*}
\oint_C \vec{F}\cdot \, d\vec{r}
& = \oint_C M(x,y)\, dx +N(x,y)\, dy \\
& = \oint_C M(x,y) \, dx +\oint_C N(x,y)\, dy \\
& = -\iint_R  \frac{\partial M}{\partial y} \, dy \, dx + \iint_R  \frac{\partial N}{\partial x} \, dx \, dy \\
& = \iint_R \left( \frac{\partial N}{\partial  x}-\frac{\partial M}{\partial  y} \right)d A
\end{align*}
as needed to prove the following theorem. 

::: {#thm- } 

## Green's Theorem
Let $R$ be a simply connected region with a piecewise smooth boundary curve $C$ oriented counterclockwise and let 
$$
\vec{F}= M \vec{i}+ N \vec{j}+0 \vec{k}
$$ 
be a continuously differentiable vector field on $R,$ then 
\begin{equation}
\label{gr}
\oint _C M dx+Ndy
= \iint_R \left( \frac{\partial N}{\partial  x}-\frac{\partial M}{\partial  y} \right)d A.
\end{equation}
::: 

::: {#exm- } 
Use Green's theorem to evaluate the line integral
$$
\oint _C4 y \, dx-3x \, dy
$$
around the curve $C$ defined by the ellipse $2x^2+y^2=4$ oriented counterclockwise.
::: 

::: {.solution }
Let $\vec{F}(x,y)=4y \vec{i}+(-3x)\vec{j}$ and let $R$ be the region enclosed by $C$.
Notice that $\vec{F}$ and $R$ satisfy the hypothesis of Green's theorem, so that
\begin{equation*}
\oint _C 4 y \, dx-3x \, dy
= \iint_R (-3-4)d A 
=-7(2)\left(\sqrt{2}\right)\pi.
\end{equation*}
::: 
    
::: {#exm- } 
Use Green's theorem to evaluate the line integral
$$
\oint _C4x y \, dx$$ 
around the curve $C$ defined by the unit circle oriented clockwise.
::: 

::: {.solution }
Let $\vec{F}(x,y)=4x y \vec{i}+0 \vec{j}$ and let $R$ be the region enclosed by $C$.
Notice that $\vec{F}$ and $R$ satisfy the hypothesis of Green's theorem, so that
\begin{equation*}
\oint _C4x  y \, dx
% & =\oint _C M \, dx+N \, dy
%=-\iint_R \left( \frac{\partial N}{\partial  x}-\frac{\partial M}{\partial  y} \right) \,d A
%=-\iint_R (-4x) \, d A \\
=4\iint_R x \, d A
=4\int _0^{2\pi }\int _0^1 r^2 \cos  \theta drd\theta
=0
\end{equation*}
::: 
    
::: {#exm- } 
Use Green's theorem to evaluate the line integral
$$
\oint _Cy^2 \, dx+x\, dy
$$ 
around the curve $C$ defined by the square with vertices $(0,0),$ $(2,0),$ $(2,2),$ $(0,2)$ oriented counterclockwise.
::: 

::: {.solution }
Let $\vec{F}(x,y)=y^2 \vec{i}+x \vec{j}$, then $M(x,y)=y^2$ which is continuously differentiable over the square as well as $N(x,y)=x.$
Therefore $\vec{F}$ and $R$ satisfy the hypothesis of Green's theorem and 
\begin{equation*}
\oint _C y^2 \, dx+x \, dy
=\int _0^2\int _0^2(1-2y) \, dy \, dx
=\int_0^2 (-2) \, dx
=-4.
\end{equation*}
::: 

::: {#exm- } 
Find the work done on an object that moves in the force field 
$$
\vec{F}(x,y)=y^2 \vec{i}+x^2 \vec{j}
$$ 
once counterclockwise around the circular
path $x^2+y^2=2$.
::: 

::: {.solution }
Let $\vec{F}(x,y)=y^2 \vec{i}+x^2 \vec{j}$, then $M(x,y)=y^2$ which is continuously differentiable over the circle as well as $N(x,y)=x^2.$
Let $R$ be the region bounded by the curve $x^2+y^2=2.$ 
Then $\vec{F}$ and $R$ satisfy the hypothesis of Green's theorem and 
\begin{align*}
W& =\oint _C \vec{F}\cdot d\vec{R}
=\oint _C \left(y^2 \vec{i}+x^2 \vec{j}\right)\cdot ( dx \vec{i}+dy \vec{j}) 
=\oint _C \left(y^2dx +x^2dy\right) \\
& =\oint _C M \, dx+N\,dy
= \iint_R \left( \frac{\partial N}{\partial  x}-\frac{\partial M}{\partial  y} \right)\, d A
=2 \iint_R (x-y) \, dA \\
& =2\int _0^{2\pi }\int _0^{\sqrt{2}}r^2(\cos  \theta -\sin  \theta )\, dr \, d\theta
=\frac{4\sqrt{2}}{3}\int_0^{2\pi }  (\cos  \theta -\sin  \theta ) \, \, d\theta 
=0.
\end{align*}
::: 

::: {#exm- } 
Find the work done on an object that moves in the force field 
$$
\vec{F}(x,y)=\left(x+2y^2\right)  \vec{j}
$$ 
once counterclockwise around the circular path $(x-2)^2+y^2=1$.
::: 

::: {.solution }
Let $\vec{F}(x,y)=0 \vec{i}+\left(x+2y^2\right) \vec{j}$. Then $M(x,y)=0$ which is continuously differentiable over the circle as well as $N(x,y)=x+2y^2.$ Let $R$ be the region bounded by the curve $(x-2)^2+y^2=1.$ Then $\vec{F}$ and $R$ satisfy the hypothesis of Green's theorem and 
\begin{align*}
W& =\oint _C \vec{F}\cdot d\vec{R}
=\oint _C \left(x+2y^2\right)\vec{j}\cdot ( dx \vec{i}+dy \vec{j})
=\oint _C  \left(x+2y^2\right) dy \\
& =\oint _C M dx +N dy
= \iint_R \left( \frac{\partial N}{\partial  x}-\frac{\partial M}{\partial  y} \right)d A
= \iint_R dA
=\pi.
\end{align*}
::: 

::: {#exm- } 
Evaluate the closed line integral 
$$
\oint _C \frac{-y dx+(x-1)dy}{(x-1)^2+y^2}
$$ 
where $C$ is any Jordan curve whose interior does not contain the point $(1,0)$ transversed counterclockwise.
::: 

::: {.solution }
Let 
$$
\vec{F}(x,y)=\frac{-y }{(x-1)^2+y^2}  \vec{i}+ \frac{x-1 }{(x-1)^2+y^2} \vec{j},
$$
then 
$$
M(x,y)=\frac{-y }{(x-1)^2+y^2}
$$
which is continuously differentiable over the circle as well as 
$$
N(x,y)=\frac{x-1 }{(x-1)^2+y^2}.
$$ 
Let $R$ be the region bounded by the given curve $C.$ 
Then $\vec{F}$ and $R$ satisfy the hypothesis of Green's theorem and
\begin{align*}
& \oint _C \frac{-y dx+(x-1)dy}{(x-1)^2+y^2} \\
& \qquad =\oint _C \frac{-y }{(x-1)^2+y^2}dx+\frac{x-1}{(x-1)^2+y^2}dy 
\\
& \qquad = \iint_R \left(\partial _x \left(\frac{x-1 }{(x-1)^2+y^2}\right)-\partial _y \left(\frac{-y }{(x-1)^2+y^2}\right)\right)dA 
\\
& \qquad = \iint_R  0 \, dA
=0.
\end{align*}
::: 

## Doubly-Connected Regions

::: {#def- } 
A \index{Jordan curve} **Jordan curve**  is a closed curve $C$ that does not intersect itself and a simply connected region $R$ has the property that it is connected
and the interior of every Jordan curve $C$ in $R$ also lies in $R.$ 
::: 

::: {#thm- } [Green's Theorem for Doubly-Connected Regions]
Let $R$ be a doubly-connected region with a piecewise smooth outer boundary curve $C_1$ oriented counterclockwise and a piecewise smooth inner boundary curve $C_2$ oriented clockwise and let $\vec{F}= M \vec{i}+ N \vec{j}+0 \vec{k}$ be a continuously differentiable vector field on $R,$ then
$$
\oint _{C_1} M \, dx+N \, dy+\oint _{C_2} M \, dx+N \, dy= \iint_R \left( \frac{\partial N}{\partial  x}-\frac{\partial M}{\partial  y} \right) \, d A.$$
::: 

::: {#exm- } 
Evaluate the closed line integral 
$$
\oint _C \frac{x dx+ydy}{x^2+y^2}
$$ 
where $C$ is any Jordan curve whose interior contains the point $(0,0)$ transversed counterclockwise
::: 

::: {.solution }
Let $C_1$ be a circle centered at $(0,0)$ with radius $r$ so small that all of $C_1$ is contained within $C.$ Let $C_1$
be oriented clockwise and let $R$ be the region between $C_1$ and $C.$ Then by Green's theorem for doubly-connected regions, 
\begin{align*}
& \oint _C \frac{x}{x^2+y^2}dx+\frac{y}{x^2+y^2}dy+\oint _{C_1} \frac{x}{x^2+y^2}dx+\frac{y}{x^2+y^2}dy 
\\
& \qquad = \iint_R \left(\frac{\partial }{\partial  x}\left(\frac{y}{x^2+y^2}\right)-\frac{\partial }{\partial  y}\left(\frac{x}{x^2+y^2}\right)\right)d
A
\\
& \qquad = \iint_R \left(\frac{-2 x y}{x^2+y^2}-\frac{-2 x y}{x^2+y^2}\right)d A =0.\end{align*}
Thus,
$$
\oint _C \frac{x dx+ydy}{x^2+y^2}=-\oint _{C_1} \frac{x dx+ydy}{x^2+y^2}
$$
which is something that can be easily evaluated, using say, the parametrization 
$C_1: x=r \sin  \theta , y=r \cos  \theta; 0\leq \theta \leq 2\pi$. 
Therefore 
\begin{align*}
\oint _C \frac{x dx+ydy}{x^2+y^2} & 
=-\oint _{C_1} \frac{x dx+ydy}{x^2+y^2} 
\\ & 
=\int_0^{2\pi } \frac{(r \sin  \theta ) (r \cos  \theta )+(r \cos  \theta )(-r \sin  \theta )}{\sin  ^2\theta +\cos ^2\theta } \, d\theta
=0.
\end{align*}
::: 

::: {#exm- } 
Evaluate the closed line integral 
$$
\oint _C\left(x^2y dx-y^2xdy\right)
$$ 
where $C$ is the boundary of the region between the $x$-axis and the semicircle $y=\sqrt{a^2-x^2},$ traversed counterclockwise (including the $x$-axis). 
::: 

::: {.solution }
Using Green's Theorem, we find
\begin{align*}
\oint _C\left(x^2y dx-y^2xdy\right)
& =\int \int \left(-y^2\right)-\left(x^2\right)dA 
 =-\int \int \left(x^2+y^2\right) \, dA \\
& =-\int _0^{\pi }\int _0^ar^3drd\theta 
 =-\int_0^{\pi } \frac{a^4}{4} \, d\theta 
=-\frac{a^4 \pi }{4}
\end{align*}
::: 

::: {#exm- } 
Evaluate the closed line integral 
$$
\oint _C\frac{-(y+2)dx+(x-1)dy}{(x-1)^2+(y+2)^2}$$
where $C$ is any Jordan curve whose interior does not contain the point $(1,-2)$.
::: 

::: {.solution }
Green's theorem applies because we are using any Jordan curve which does not contain the point $(1,-2).$ 
\begin{align*}
& \oint _C\frac{-(y+2)dx+(x-1)dy}{(x-1)^2+(y+2)^2} 
\\
& \quad =\oint _C-\frac{(y+2)}{(x-1)^2+(y+2)^2}dx+\frac{(x-1)}{(x-1)^2+(y+2)^2}dy 
\\
& \quad =\iint_D \left(\partial _x \left(\frac{(x-1)}{(x-1)^2+(y+2)^2}\right)\right)-\left(\partial _y \left(-\frac{(y+2)}{(x-1)^2+(y+2)^2}\right)\right)dA 
\\
& \quad =\iint_D\left(\frac{-x^2+2 x+y^2+4 y+3}{\left(x^2-2 x+y^2+4 y+5\right)^2}\right)-\left(\frac{-x^2+2 x+y^2+4 y+3}{\left(x^2-2 x+y^2+4 y+5\right)^2}\right) \, dA =0
\end{align*}
::: 

::: {#exm- } 
Evaluate the closed line integral 
$$
\oint _C\left[(x-3y)dx+\left(2x-y^2\right)dy\right]
$$
where $A$ is the region $D$ enclosed by a Jordan curve $C$.
::: 

::: {.solution }
Green's theorem applies and  
\begin{align*}
\oint _C(x-3y)dx+\left(2x-y^2\right)dy
& =\iint_D \left(\partial _x \left(2x-y^2\right)\right)-\left(\partial _y (x-3y)\right)dA 
\\ & 
=\iint_D (2+3)dA
=5A.
\end{align*}
::: 

::: {#exm- } 
Use a line integral to find the area enclosed by the region $R$
defined by the circle $x^2+y^2=4$
::: 

::: {.solution }
We can parametrize the circle by $x=2 \cos  t$ and $y=2 \sin  t$ for $0\leq t\leq  2\pi .$ Then the area is 
$$
\frac{1}{2}\oint _C x dy-ydx=
\frac{1}{2}\int _0^{2\pi } [4\cos (t)\cos (t)+4 \sin (t)\sin (t)] \, dt=4\pi. 
$$
- We can parametrize the line segments by 
\begin{align*}
& C_1:  x=t, y=t; 0\leq t\leq 1 \\
& C_2: x=1-t, y=1+t; 0\leq t\leq 1 \\
& C_3: x=0, y=2(1-t); 0\leq t\leq 1
\end{align*}
Then the area is
\begin{align*}
\oint _C x dy 
& =\int _{C_1} x dy+\int _{C_2} x dy+\int _{C_3} x dy \\
& =\int_0^1 t \, dt+\int_0^1 (1-t) \, dt+\int _0^10(-2)dt 
=\frac{1}{2}+\frac{1}{2}+0 
=1.
\end{align*}
::: 

::: {#exm- } 
Use a line integral to find the area enclosed by the region $R$ defined by the curve $C: x=\cos  ^3t,$ $y=\sin^3 t$ for $0\leq t\leq 2\pi$
::: 

::: {.solution }
The required area is 
\begin{align*}
A& =\oint _C x dy 
=\int _0^{2\pi }\cos  ^3t \left(3 \sin ^2 t \cos  t\right)dt \\
& =\int _0^{2\pi }\cos ^4 t \left(1-\cos ^2 t \right) dt 
 =\int _0^{2\pi }\left(\cos ^4 t -\cos ^6 t \right) dt
%& =3\int _0^{2\pi }\left(\cos ^4 t -\cos ^6 t \right) dt
%& =3\int _0^{2\pi }\left(\cos ^4(t)-\frac{5}{6}\cos ^4(t)\right) dt \\
%& =\frac{1}{2}\int _0^{2\pi }\cos ^4(t) dt \\
%=\frac{1}{2}\left(\frac{3}{4}\right)\int _0^{2\pi }\cos ^2(t) dt 
% =\frac{1}{2}\left(\frac{3}{4}\right)\left(\frac{1}{2}\right)\int _0^{2\pi } dt 
%=\frac{3 \pi }{8}.\end{align*}
\end{align*}
by using the reduction formula,
$$
\int \cos ^nx \, dx=\frac{\cos ^{n-1}x \sin  x}{n}+\frac{n-1}{n}\int \cos ^{n-2}xdx.
$$
::: 

## Exercises

::: {#exr- } 
Use Green's theorem to evaluate the closed line integral 
$$ \oint _C y^2 dx+x^2 dy$$ where $C$ is the boundary of the square with vertices $(0,0),$ $(1,0),$ $(1,1),$ and $(0,1)$ traversed counterclockwise.
::: 

::: {#exr- } 
Use Green's theorem to evaluate the closed line integral 
$$\oint _C4x y dx $$ where $C$ is the boundary of the circle $x^2+y^2=1$ traversed
clockwise.
::: 

::: {#exr- } 
Use Green's theorem to evaluate the closed line integral 
$$\oint _C x \sin  x dx-e^{y^2} dy$$ where $C$ is the boundary of the triangle
with vertices $(-1,-1),$ $(1,-1),$ and $(2,5)$ traversed counterclockwise.
::: 

::: {#exr- } 
Use Green's theorem to evaluate the closed line integral 
$$\oint _C \sin  x \cos  y \, dx+\cos  x \sin  y \, dy $$ 
where $C$ is the boundary of the square with vertices $(0,0),$ $(2,0),$ $(2,2),$ and $(0,2)$ traversed clockwise.
::: 

::: {#exr- } 
Use Green's theorem to evaluate a closed line integral that represents the area enclosed by the region defined by the curve $x^2+y^2=4.$
::: 

::: {#exr- } 
Use Green's theorem to evaluate a closed line integral that represents the area enclosed by the region defined by the trapezoid with vertices
$(0,0),$ $(4,0),$ $(1,3),$ and $(0,3).$
::: 

::: {#exr- } 
Evaluate the closed line integral 
$$ \oint _C\frac{x dx+ydy}{x^2+y^2}$$ where $C$ is any piecewise smooth Jordan curve enclosing the origin,
traversed counterclockwise.
::: 

::: {#exr- } 
Evaluate the closed line integral 
$$
\oint _C x^2y \, dx-y^2x \, dy,
$$ where $C$ is the boundary of the region between the $x$-axis and
the semicircle $y=\sqrt{a^2-x^2},$ traversed counterclockwise (including the $x$-axis). 
::: 

::: {#exr- } 
Evaluate 
$$\oint _C\frac{-(y+2)dx+(x-1)dy}{(x-1)^2+(y+2)^2}$$ where $C$ is any Jordan curve whose interior does not contain the point $(1,-2).$
::: 

::: {#exr- } 
If $C$ is a Jordan curve, show that 
$$ \oint _C (x-3y)dx+\left(2x-y^2\right)dy =5A$$
where $A$ is the region $D$ enclosed by $C.$
::: 

::: {#exr- } 
Suppose $\vec{F}=M(x,y)\, \vec{i}+N(x,y)\, \vec{j}$ is continuously differentiable in a doubly-connected region $R$ and that
$$
\frac{\partial N}{\partial x}=\frac{\partial M}{\partial y}
$$ 
throughout $R.$ How many distinct values of $I$ are there for the integral
$$ 
I=\oint _C M(x,y)\, dx+N(x,y)\, dy
$$
where $C$ is a piecewise smooth Jordan curve in $R?$
::: 

::: {#exr- } 
Evaluate the line integral 
$$
\oint _C x^2y \, dx-y^2x \, dy,
$$
where $C$ is the boundary of the region between the $x$-axis and the semicircle $y=\sqrt{a^2-x^2},$ transversed counterclockwise (including
the $x$-axis). 
::: 

::: {#exr- } 
Find the work done if an object that moves in the force field 
$\vec{F}(x,y)=y^2 \vec{i}+x^2 \vec{j}$
once counterclockwise around the circular
path $x^2+y^2=2$.
::: 






