---
pagetitle: "Multivariable Limits and Continuity - Exploring Calculus"
---
# Multivariable Limits and Continuity


## Intuitive Meaning of Multivariable Limit

Recall when considering 
$$
\lim_{x\to c} f(x)=L
$$ 
we need to examine the approach of $x$ to $c$ from two directions --namely the left-hand limit and the right-hand limit. 
However for functions of two variables, we write $(x,y)\to (a,b)$ to mean that the point $(x,y)$ is allowed to approach $(a,b)$ along any path in the domain of $f$ that passes through $(a,b)$. 


Open and closed disks are analogous to open and closed intervals on a coordinate line.  An \index{open disk} **open disk** (or \index{open ball} **open ball** centered at the point $(a,b)$ is the set of all points $(x,y)$ such that 
$$
\sqrt{(x-a)^2+(y-b)^2}<r
$$
for $r>0$. If the \index{boundary} **boundary** of the disk is included, the disk is called a \index{closed disk} **closed disk**.

A point $(a,b)$ is called an \index{interior point} **interior point** 
of a set $S$ in $\mathbb{R}^2$ if some open disk centered at $(a,b)$ is contained entirely within $S$. If $S$ is the empty set, or if every point of $S$ is an interior point, then $S$ is called an \index{open set} **open set** . 
The point $(a,b)$ is called a \index{boundary point} **boundary point** of $S$ if every open disk centered at $(a,b)$ contains both points that belong to $S$ and points that do not. The collection of all boundary points of $S$ is called the \index{boundary} **boundary**  of $S$, and $S$ is a closed disk if it contains its boundary. 


::: {#def- } 
Let $f$ be a function that is defined for all points $(x,y)$ in an open disk around $(a,b)$ with the possible exception of $(a,b)$ itself. 
Then the  \index{limit} **limit**  of $f(x,y)$ as $(x,y)$ approaches $(a,b)$ is $L$, written by 
$$
\lim_{(x,y)\to(a,b)} f(x,y)=L
$$
if $f(x,y)$ can be made as close to $L$ as we please by restricting $(x,y)$ to be sufficiently close to $(a,b)$. 
::: 



## Limit Properties

If $a$, $b$, and $c$ are real numbers then 
\begin{equation}
\label{linmultlimit}
\lim_{(x,y)\to(a,b)}c=c,\qquad 
\lim_{(x,y)\to(a,b)}x=a, \qquad
\lim_{(x,y)\to(a,b)}y=b.
\end{equation}
The three limits in \ref{linmultlimit} can be used with \ref{limthmmult} to show that 
\begin{equation}
\label{polratlimit}
\lim_{(x,y)\to(a,b)}p(x,y)=p(a,b)
\qquad \text{and}\qquad
\lim_{(x,y)\to(a,b)}r(x,y)=r(a,b)
\end{equation}
where $p$ is a polynomial function of $x$ and $y$ and $r$ is a rational function of
 $x$ and $y$, provided $(a,b)$ is in the domain of $r$.

::: {#thm- } [Limit Law]
\label{limthmmult}
Suppose 
$$
\lim _{(x,y)\to \left(x_0,y_0\right)}f(x,y)=L
\quad \text{and} \quad
\lim _{(x,y)\to \left(x_0,y_0\right)}g(x,y)=M
$$ 
and $a$ is a real number. Then 
 
- $\lim _{(x,y)\to \left(x_0,y_0\right)}(a f)(x,y)=a L$ 
- $\lim _{(x,y)\to \left(x_0,y_0\right)}(f+g)(x,y)=L+M$ 
- $\lim _{(x,y)\to \left(x_0,y_0\right)}(f g)(x,y)=L M$ 
- $\lim _{(x,y)\to \left(x_0,y_0\right)}(f/g)(x,y)=L/M$  
whenever $M\neq 0.$ 
::: 

::: {.proof }
The proof is left for the reader.
::: 


::: {#exm- } 

Evaluate $\lim _{(x,y)\to (1,1)}\dfrac{x^4+y^4}{x^2+y^2}$. 
::: 

::: {.solution }
Since 
$$
r(x,y)=(x^4+y^4)/(x^2+y^2)
$$ 
is a rational function and $(1,1)$ is in the domain of $r$, we use \ref{limthmmult} to find
$$
\lim _{(x,y)\to (1,1)}\dfrac{x^4+y^4}{x^2+y^2}
=r(2,2)=1.
$$
::: 


::: {#exm- } 

Evaluate $\lim _{(x,y)\to (0,0)}\dfrac{x^4-y^4}{x^2+y^2}$. 
::: 

::: {.solution }
By canceling 
\begin{equation}
\label{cancellim}
\lim _{(x,y)\to (0,0)}\frac{\left(x^2-y^2\right)\left(x^2+y^2\right)}{x^2+y^2}=\lim _{(x,y)\to (0,0)}\left(x^2-y^2\right)=0.
\end{equation}
Notice the functions $f$ and $g$ defined by 
$$
f(x,y)=x^2-y^2
\qquad \text{and}\qquad
g(x,y)=\dfrac{x^4-y^4}{x^2+y^2}
$$
are not the same functions, because they have different domains. However $f$ and $g$ have the same limit because whenever $(x,y)\neq(0,0)$ we do indeed have 
$(x^4-y^4)/(x^2+y^2)=x^2-y^2$. 
Therefore, the ``canceling" step in \ref{cancellim} is valid.
::: 


::: {#exm- } 

Evaluate
$\lim_{(x,y)\to (1,2)}\dfrac{\left(x^2-1\right)\left(y^2-4\right)}{(x-1)(y-2)}$.
::: 

::: {.solution }
By factoring and then canceling we have
\begin{align*}
\lim _{(x,y)\to (1,2)}\frac{\left(x^2-1\right)\left(y^2-4\right)}{(x-1)(y-2)}
& =\lim _{(x,y)\to (1,2)}\frac{(x-1)(x+1)(y-2)(y+2)}{(x-1)(y-2)} \\
& =\lim _{(x,y)\to (1,2)}(x+1)(y+2) 
=(1+1)(2+2) =8.
\tag*{}
\end{align*}
::: 


::: {#exm- } 
Evaluate
$\lim _{(x,y)\to (a,a)}\dfrac{x^4-y^4}{x^2-y^2}$. 
::: 

::: {.solution }
By factoring and then canceling we have
\begin{align*}
\lim _{(x,y)\to (a,a)}\frac{x^4-y^4}{x^2-y^2}
& =\lim _{(x,y)\to (a,a)}\frac{\left(x^2-y^2\right)\left(x^2+y^2\right)}{x^2-y^2} \\
& =\lim _{(x,y)\to (a,a)}\left(x^2+y^2\right) = 2a^2.
\tag*{}
\end{align*}
::: 



## Limits that Do Not Exist

It is sometimes possible to show that the limit of a function does not exist by showing that the limit has different values depending on which path in the domain is used.

::: {#thm- } [Limits Along Paths]
\label{dnelim}

If $f(x,y)$ approaches two different numbers as $(x,y)$ approaches  $(a,b)$ along two different paths, then 
the limit 
$$
\lim_{(x,y)\to(a,b)}f(x,y)
$$ 
does not exist.
::: 

::: {.proof }
The proof is left for the reader.
::: 


::: {#exm- } 

Evaluate
$\lim _{(x,y)\to (0,0)}\dfrac{x y}{x^2+y^2}$. 
::: 

::: {.solution }
Along the $x$-axis we have
$$
\plim{(x,y)\to (0,0)}{y=0}\dfrac{x y}{x^2+y^2}
=\lim _{(x,0)\to (0,0)}\frac{0}{x^2+0^2}=\lim _{x\to 0}0=0.$$
We have along the $y$-axis, 
$$
\plim{(x,y)\to (0,0)}{x=0}\dfrac{x y}{x^2+y^2}
=\lim _{(0,y)\to (0,0)}\frac{0}{0^2+y^2}=\lim _{y\to 0}0=0.$$
Along the line $y=x$ we have
$$
\plim{(x,y)\to (0,0)}{y=x}\dfrac{x y}{x^2+y^2}
=\lim _{(x,x)\to (0,0)}\frac{ x^2 }{x^2+x^2}=\lim _{x\to 0}\frac{1}{2}=\frac{1}{2}.
$$  
Therefore, by \ref{dnelim}, the given limit does not exist (see \ref{fig:limdne}).
::: 


::: {#exm- } 
Evaluate
$\lim _{(x,y)\to (0,0)}\dfrac{x y^2}{x^2+y^4}$. 
::: 

::: {.solution }
Along the curves $y=m x$ we have
$$
\plim{(x,y)\to (0,0)}{y=mx}\dfrac{x y^2}{x^2+y^4}
=\lim _{(x,m x)\to (0,0)}\frac{m^2x^3}{x^2+m^4x^4}=\lim _{x\to 0}\frac{m^2x}{1+m^4x^2}=0 .
$$
But along the curve $x=y^2$ we have
$$
\plim{(x,y)\to (0,0)}{x=y^2}\dfrac{x y^2}{x^2+y^4}
=\lim _{\left(y^2,y\right)\to (0,0)}\frac{y^4}{y^4+y^4}=\lim _{y\to 0}\frac{y^4}{y^4+y^4}=\frac{1}{2}.
$$
Therefore, by \ref{dnelim}, the given limit does not exist.
::: 



::: {#exm- } 
Evaluate
$\lim _{(x,y)\to (0,0)}\dfrac{x^2y^2}{x^4+y^4}$.
::: 

::: {.solution }
Let $m$ be any real number, then along the paths $y=m x$ we have
$$
\plim{(x,y)\to (0,0)}{y=mx}\dfrac{x^2y^2}{x^4+y^4}
=\lim _{(x,y)\to (0,0)}\frac{x^2y^2}{x^4+y^4} 
=\lim _{(x,m x)\to (0,0)}\frac{x^2(m x)^2}{x^4+(m x)^4} 
=\frac{m^2}{1+m^4}.
$$
Notice as the path $y=m x$ changes (as $m$ changes) so does the value 
$m^2/(1+m^4)$.
Therefore, by \ref{dnelim}, the given limit does not exist.
::: 
 


::: {#exm- } 
Evaluate
$\lim _{(x,y)\to (0,0)}\dfrac{x^4y^4}{\left(x^2+y^4\right)^3}$.
::: 

::: {.solution }
Along the line $y=0$ we have 
$$
\plim{(x,y)\to (0,0)}{y=0}\dfrac{x^4y^4}{\left(x^2+y^4\right)^3}
=\lim _{x\to 0}\frac{0}{\left(x^2+0\right)^3}=0
$$
and along the path $y=\sqrt{x}$ we have 
$$
\plim{(x,y)\to (0,0)}{y=\sqrt{x}}\dfrac{x^4y^4}{\left(x^2+y^4\right)^3}
=\lim_{x\to 0}\frac{x^4x^2}{\left(2x^2\right)^3}=\frac{1}{8}.
$$
Therefore, by \ref{dnelim}, the given limit does not exist.
::: 

::: {#exm- } 
Find a function $f(x,y)$ and a point $\left(x_0,y_0\right)$ such that
$$
\lim _{x\to x_0}\left(\lim _{y\to y_0}f(x,y)\right)\neq \lim _{y\to y_0}\left(\lim _{x\to x_0}f(x,y)\right).
$$ 
::: 

::: {.solution }
Consider the function $f(x,y)=\frac{a x+b y}{c x+d y}$ and the point $(0,0).$ 
Then 
$$
\lim _{x\to 0}\left(\lim _{y\to 0}\frac{a x+b y}{c x+d y}\right)=\frac{a}{c}\neq \lim _{y\to 0}\left(\lim _{x\to 0}\frac{a x+b y}{c
x+d y}\right)=\frac{b}{d}$$
for some values of $a,b , c,$ and $d.$ What does this say about
$$
\lim _{(x,y)\to (0,0)}\left(\frac{a x+b y}{c x+d y}\right) \ ?
$$
::: 



::: {#exm- } 
Consider the function 
$$
f(x,y)=\frac{x y }{x^2y^2+(x-y)^2}.
$$ 
Notice that  
\begin{equation}
\label{multex}
\lim _{x\to 0}\left(\lim _{y\to 0}f(x,y)\right)=\lim _{y\to 0}\left(\lim _{x\to 0}f(x,y)\right).
\end{equation}
Is it true, then, that 
\begin{equation}
\label{dnemultex}
\lim _{(x,y)\to (0,0)}\left(\frac{xy}{x^2y^2+(x-y)^2}\right)
\end{equation}
exists? 
::: 

::: {.solution }
First we notice the (iterated) limits in \ref{multex} are both $-1/2$ as the following shows
$$
\lim_{x\to0}\left[ \lim_{y\to0} \left(\frac{xy}{x^2y^2+(x-y)^2}\right) \right]
=\lim_{x\to0}\left[ \lim_{y\to0} \left(\frac{x}{2x^2y+2(x-y)(-1)}\right) \right] 
=-\frac{1}{2}
$$
$$
\lim_{y\to0}\left[ \lim_{x\to0} \left(\frac{xy}{x^2y^2+(x-y)^2}\right) \right]
=\lim_{y\to0}\left[ \lim_{x\to0} \left(\frac{y}{2y^2x+2(x-y)(1)}\right) \right] 
=-\frac{1}{2}
$$
using L'Hopitals rule.
Secondly, we find that the limit in \ref{dnemultex} does not exist because along the paths $y=m x$ we have 
$$
\plim{(x,y)\to (0,0)}{y=mx}\frac{xy}{x^2y^2+(x-y)^2}
=\lim _{x\to 0}\left(\frac{mx^2}{m^2 x^4+(x-mx)^2}\right) 
=\frac{m}{(1-m)^2}
$$
which varies as the path $y=m x$ does. 
::: 


## Continuity of a Function of Two Variables

::: {#def- } 

Let $f$ be a function that is defined on any open disk around $(a,b)$. Then $f$ is \index{continuous} **continuous**  at the point  $(a,b)$ if 
$$
\lim _{(x,y)\to (a,b)}f(x,y)=f(a,b).
$$
::: 

::: {#thm- } [Continuous Multivariable Functions]
\label{multlimprop}
If $k$ is a real number and $f$ and both $g$ are continuous functions at $(a,b)$, then the following functions are also continuous at $(a,b)$, provided $(a,b)$ is in the domain of the function. 
 
- $kf$
- $f+g$
- $f-g$
- $f/g$ 
- $f\circ g$ 
- $\sqrt[n]{f}$
::: 

::: {.proof }
The basic properties of limits can be used to proof this theorem.
The details are left for the reader.
::: 

Since any polynomial and rational function can be built out of the continuous functions $f(x)=x$, $g(x,y)=y$, and $h(x,y)=k$ we can use the limits in \ref{multlimprop} to realize that every polynomial is continuous on the entire plane and that rational functions are continuous on their domains. 


::: {#exm- } 

What is the largest set on which the function
$$
f(x,y)=\left\{
\begin{array}{ll}
\dfrac{3x^2y}{x^2+y^2} & \text{if} \quad (x,y)\neq (0,0)  \\
  0& \text{if} \quad (x,y)=(0,0) 
\end{array}
\right.
$$
is continuous?
::: 

::: {.solution }
We know $f$ is continuous for $(x,y)\neq (0,0)$ since $f$ is a rational function. 
Since 
$$
\lim _{(x,y)\to (0,0)}f(x,y)=0=f(0,0)
$$
we have that $f$ is continuous on $\mathbb{R}^2$. 
::: 


::: {#exm- } 
What is the largest set on which the function 
$$
h(x,y)=\ln \left(x^2+y^2-1\right)
$$ 
is continuous? 
::: 

::: {.solution }
Let $f(x,y)=x^2+y^2-1$ and $g(t)=\ln  t$. Then
$$
h(x,y)=\ln \left(x^2+y^2-1\right)=(g\circ f)(x,y).
$$
Now $f$ is continuous everywhere since it is a polynomial and $g$ is continuous on its domain 
$\{t \mid t\geq 0\}$. 
Thus, $h$ is continuous on
its domain 
$$
D=\left\{(x,y) \mid x^2+y^2>1 \right\}
$$
which consists of all points outside the circle $x^2+y^2=1.$ 
::: 

## Exercises

::: {#exr- } 
Where is $f(x,y)=\sqrt{\frac{x^2+y^2}{(x-y)^2+1}}$ is continuous?
::: 

::: {#exr- } 
Given $\lim _{(x,y)\to (0,0)}\frac{x^4y^4}{\left(x^2y^2\right)^{3/2}}$, find the limit.
::: 

::: {#exr- } 
Find  $\lim _{(x,y)\to (\pi /2,1)}\frac{1+\cos 2x}{y-e^y}.$
Explain why.
::: 

::: {#exr- } 
Evaluate the limit.
 
- $\lim_{(x,y)\to (-1,0)}\left(x y^2+x^3y+5\right)$ 
- $\lim_{(x,y)\to (0,0)}\left(5x^2-2 x y+y^2+3\right)$
- $\lim_{(x,y)\to (0,1)}e^{x^2+x}\ln \left(e y^2\right)$ 
- $\lim_{(x,y)\to (a,a)}\frac{x^4-y^4}{x^2-y^2}$ 
- $\lim_{(x,y)\to (1,2)}\frac{\left(x^2-1\right)\left(y^2-4\right)}{(x-1)(y-2)}$ 
- $\lim_{(x,y)\to (0,0)}\frac{x^2y^2}{x^4+y^4}$ 
- $\lim_{(x,y)\to (0,0)}\frac{x^2y^2}{x^2+y^2}$
- $\lim_{(x,y)\to (0,0)}\sin  x+ \sin  y$ 
- $\lim_{(x,y)\to (0,0)}\frac{x^2+y^2}{\sqrt{x^2+y^2+4}-2}$ 
- $\lim_{(x,y)\to (0,0)}\frac{1-\cos \left(x^2+y^2\right)}{x^2+y^2}$ 
- $\lim_{(x,y)\to (0,0)}\frac{\sin \left(x^3+y^3\right)}{\sqrt{x^6+y^6}}$ 
- $\lim_{(x,y)\to (-1,0)}\left(x y^2+x^3y+5\right)$ 
- $\lim_{(x,y)\to (0,0)}\left(5x^2-2 x y+y^2+3\right)$ 
- $\lim_{(x,y)\to (0,1)}e^{x^2+x}\ln \left(e y^2\right)$ 
- $\lim_{(x,y)\to (0,0)}\frac{x^2y^2}{x^2+y^2}$ 
- $\lim_{(x,y)\to (0,0)}\sin  x+ \sin  y$ 
- $\lim_{(x,y)\to (0,0)}\frac{x^2+y^2}{\sqrt{x^2+y^2+4}-2}$ 
- $\lim_{(x,y)\to (0,0)}\frac{1-\cos \left(x^2+y^2\right)}{x^2+y^2}$ 
- $\lim_{(x,y)\to (0,0)}\frac{\sin \left(x^3+y^3\right)}{\sqrt{x^6+y^6}}$ 
 
::: 

::: {#exr- } 
Is the function $f$ defined by 
$$
f(x,y)=
\begin{cases}
\dfrac{x y^2}{x^2+y^4} & \quad (x,y)\neq (0,0)  \\
 0 &  \quad (x,y)=(0,0)
\end{cases}
$$ 
continuous at $(0,0)?$ Explain.
::: 

::: {#exr- } 
Is the function  $f$ defined by 
$$
g(x,y)=
\begin{cases}
  \dfrac{x y^3}{x^2+y^6} & \quad (x,y)\neq (0,0)  \\
 0 & \quad (x,y)=(0,0)
\end{cases}
$$
continuous at $(0,0)?$ Explain.
::: 

::: {#exr- } 
Given that the function $f$ defined by 
$$
f(x,y)=
\begin{cases}
 \dfrac{3x^3-3y^3}{x^2-y^2} & \quad x^2\neq y^2  \\
 B & \text{otherwise}
\end{cases}
$$
is continuous at the point $(0,0)$ what is the value of $B?$ Explain. 
::: 

::: {#exr- } 
Given that the function $f$ defined by 
$$
f(x,y)=
\begin{cases}
\dfrac{x^3+y^3}{x^2+y^2} & \quad (x,y)\neq (0,0)  \\
 A & \quad (x,y)=(0,0)
\end{cases}
$$
is continuous at the point $(0,0)$ what is the value of $A?$ Explain. 
::: 

::: {#exr- } 
Let $f(x,y)=\begin{cases} \frac{x^2 y^2}{x^4+y^4+1} & \text{if } (x,y)\neq (0,0)  \\ 0 & \text{if } (x,y)= (0,0).  \end{cases}$ 
Explain why $f$ is continuous at $(0,0)$.
::: 





