---
pagetitle: "Surface Area - Exploring Calculus"
---
# Surface Area



We apply double integrals to the problem of computing the surface area over a region. We demonstrate a formula that is analogous to the formula for finding the arc length of a one variable function and detail how to evaluate a double integral to compute the surface area of the graph of a differentiable function of two variables.

## Surface Area of a Differentiable Function

::: {#thm- } [Surface Area]
Assume that the function $f(x,y)$ has continuous partial derivatives 
$f_x$ and $f_y$ in a region $R$ of the $x y$-plane. Then the portion of the surface $z=f(x,y)$ that lies over $R$ has surface area 
\[
S=\iint _R
\sqrt{ \left[ f_x(x,y)\right]^2 + \left[ f_y(x,y) \right]^2 +1 }\, dA.
\]
::: 

::: {.proof }
Consider a surface defined by $z=f(x,y)$ over a region $R$ of the $x y-\text{plane}.$ Enclose the region $R$ in a rectangle partitioned by a grid with lines parallel to the coordinate axes. This creates a number of cells, and we let $R_1,$ $R_2,$ ...., $R_n$ denote those that lie entirely within $R.$ For $m=1,2,3,... ,n,$ let 
$P_m\left(x_m^*,y_m^*\right)$ be any corner of the rectangle $R_m,$ and let $T_m$ be the tangent plane above $P_m$ on the surface of $z=f(x,y).$ Let $\text{$\triangle $S}_m$ denote the area of the patch of the surface that lies directly above $R_m.$ The rectangle $R_m$ projects onto a parallelogram $A B D C$ in the tangent plane $T_m,$ and if $R_m$ is small we would expect the area of this parallelogram to approximate closely the element of the area $\text{$\triangle $S}_m.$ If $\triangle  x_m$ and $\triangle  y_m$ are the lengths of the sides of the rectangle $R_m,$ the approximating parallelogram will have sides determined by the vectors 
\[
\vec{A B}=\triangle  x_m \vec{i}+\left[f_x\left(x_m^*,y_m^*\right)\triangle  x_m\right]\vec{k} 
\] 
and 
\[
\vec{A C}=\triangle  y_m \vec{j}+\left[f_y\left(x_m^*,y_m^*\right)\triangle  y_m\right] \vec{k}.
\]
If $K_m$ is the area of the approximating parallelogram, we have 
\[
K_m=\|\vec{A B}\times \vec{A C}\|.
\]
To determine $K_m,$ we first find the cross product: 
\begin{align*}
\vec{A B} \times \vec{A C} & =\left|
\begin{array}{ccc}
 \vec{i} & \vec{j} & \vec{k} \\
 \triangle  x_m & 0 & f_x\left(x_m^*,y_m^*\right)\triangle  x_m \\
 0 & \triangle  y_m & f_y\left(x_m^*,y_m^*\right)\triangle  y_m
\end{array}
\right| \\
& =\triangle  x_m\triangle  y_m\left(-f_x\left(x_m^*,y_m^*\right)\, \vec{i}-f_y\left(x_m^*,y_m^*\right)\, \vec{j}+\vec{k}\right).
\end{align*}
Then we calculate the norm, 
\[
K_m=\|\vec{A B} \times \vec{A C}\|
=\triangle  x_m\triangle  y_m \sqrt{ \left[f_x\left(x_m^*,y_m^*\right)\right]{}^2+\left[f_y\left(x_m^*,y_m^*\right)\right]{}^2+1}.
\]
Finally, summing over the entire partition, we see that the surface area over $R$ may be approximated by the sum
\[
\triangle S_n=\sum _{m=1}^n \sqrt{\left[f_x\left(x_m^*,y_m^*\right)\right]{}^2+\left[f_y\left(x_m^*,y_m^*\right)\right]{}^2+1}\left(\triangle A_m\right)
\] 
where $\triangle A_m=\triangle  x_m\triangle  y_m.$ This is a Riemann sum, and by taking an appropriate limit (as the partition becomes
more refined), we find that the surface area $S,$ satisfies
\begin{align*}
S& =\lim _{n\to \infty }\sum _{m=1}^n \triangle A_m\sqrt{\left[f_x\left(x_m^*,y_m^*\right)\right]^2+\left[f_y\left(x_m^*,y_m^*\right)\right]^2+1} \\
& =\iint_R\sqrt{\left[f_x(x,y)\right]^2+\left[f_y(x,y)\right]^2+1} \, d A.
\end{align*}
::: 

::: {#exm- } 

Find the surface area of the part of the surface $z=x^2+2y$ that lies above the triangular region $T$ in the $x y-\text{plane}$ with vertices
$(0,0),$ $(1,0),$ and $(1,1).$
::: 

::: {.solution }
The region $T$ is described by 
$T=\{(x,y) \mid 0\leq x\leq 1,0\leq y\leq x\}.$
We have 
\begin{align*}
S& =\iint_R\sqrt{(2x)^2+(2)^2+1} \, d A
=\int _0^1\int _0^x\sqrt{4x^2+5}\, dy\, dx \\
& =\int _0^1x\sqrt{4x^2+5}\, dx
=\frac{1}{12}\left(27-5\sqrt{5}\right).
\end{align*}
::: 

::: {#exm- } 

Find the surface area of a sphere of radius $a$.
::: 

::: {.solution }
Let 
$z=f(x,y)=\sqrt{a^2-x^2-y^2}.$
Then
\[
f_x=\frac{-x}{\sqrt{a^2-x^2-y^2}}, \qquad 
f_y=\frac{-y}{\sqrt{a^2-x^2-y^2}},\]
and 
\[
\sqrt{f_x^2+f_y^2+1}=\sqrt{\frac{x^2+y^2+\left(a^2-x^2-y^2\right)}{a^2-x^2-y^2}}=\frac{a}{\sqrt{a^2-x^2-y^2}}.
\] 
In polar form we have 
\begin{align*}
& 8\int _0^{\pi /2}\int _0^a\frac{a}{\sqrt{a^2-r^2}}r \, drd\theta 
\\[5pt]
& =-4a\int _0^{\pi /2}\int _0^a\frac{(-2r)}{\sqrt{a^2-r^2}} \, drd\theta =-8a\int_0^{\pi /2} (-a) \, d\theta
=4\pi  a^2.
\end{align*}
::: 
  
::: {#exm- } 
Find the surface area of a cylinder of radius $a$ and height $h$. 
::: 

::: {.solution }
Let
$z=f(x,y)=\sqrt{a^2-x^2}.$
Then
$
f_x=\frac{-x}{\sqrt{a^2-x^2}},
f_y=0,
$
and 
\[
\sqrt{f_x^2+f_y^2+1}=\sqrt{\frac{x^2+a^2-x^2}{a^2-x^2}}=\frac{a}{\sqrt{a^2-x^2}}.\]
We find the surface area as
\begin{align*}
4\int _0^a\int _0^h\frac{a}{\sqrt{a^2-x^2}} \, dy\, dx
& =4a\int _0^a\frac{h a}{\sqrt{a^2-x^2}} dx 
\\[5pt]
& =\left. 4 a h \sin ^{-1}\left(\frac{x}{a}\right) \right|_0^a
=2\pi  a h.
\end{align*}
::: 
  
::: {#exm- } 

Find the surface area the part of the paraboloid $z=x^2+y^2$ that lies under the plane $z=9.$
::: 

::: {.solution }
The plane intersects the paraboloid in the circle $x^2+y^2=9$ when $z=9.$ Therefore, the given surface lies above the disk $D$ with center at the origin and radius 3. Converting to polar coordinates we have
\begin{align*}
S& = \iint_R \sqrt{(2x)^2+(2y)^2+1} \, d A
=\int _0^{2\pi }\int _0^3\sqrt{4r^2+1}r \, dr \, d\theta \\
& =\int _0^{2\pi }d \theta \int _0^3\frac{1}{8}\sqrt{4r^2+1}(8r) \, dr
=\frac{\pi }{6}\left(37\sqrt{37}-1\right).
\end{align*}
::: 
  
::: {#exm- } 

Find the surface area the portion of the sphere $x^2+y^2+z^2=4$ that lies inside the cylinder $x^2+y^2=2y.$
::: 

::: {.solution }
Let $z=f(x,y)=\sqrt{4-x^2-y^2}.$ Then 
\[f_x=\frac{-x}{\sqrt{4-x^2-y^2}}, \qquad 
f_y=\frac{-y}{\sqrt{4-x^2-y^2}},
\] 
and 
\[
\sqrt{f_x^2+f_y^2+1}=\sqrt{\frac{x^2+y^2+\left(4-x^2-y^2\right)}{4-x^2-y^2}}=\frac{2}{\sqrt{4-x^2-y^2}}.
\]
The projected region in polar form is $r=2 \sin  \theta .$ Since half the surface is above the $x y-\text{plane}$ and half the surface is below 
we have 
\begin{align*}
S& =2\int _0^{\pi }\int _0^{2 \sin  \theta }\frac{2r}{\sqrt{4-r^2}}drd\theta 
=-8\int_0^{\pi } \left(\sqrt{4-4\sin ^2\theta }-2\right) \, d\theta \\
& =-8\int_0^{\pi /2} (2 \cos  \theta -2) \, d\theta -8\int_{\pi /2}^{\pi } (-2 \cos  \theta -2) \, d\theta
=8(\pi -2).
\end{align*}
::: 
  

## Surface Area Defined Parametrically

We show a way to find the surface area of the graph of a surface given a parameterization of the surface. We also illustrate how to find the surface area with two examples and then show how to find the surface area of a torus with given inner and outer radii.

::: {#thm- } [Surface Area (Parametrically)]
Let $S$ be a surface defined parametrically by
\[
\vec{R}(u,v)=x(u,v)\vec{i}+y(u,v)\vec{j}+z(u,v)\vec{k}
\]
on the region $D$ in the $u v$-plane, and assume that $S$ is smooth in the sense that $\vec{R}_u$ and $\vec{R}_v$ are continuous with $\vec{R}_u\times \vec{R}_v\neq \vec{0}$ on $D.$ Then the surface area $S$ is given by 
\[
S=\underset{D}{\iint }\left\|\vec{R}_u\times \vec{R}_v\right\| d u d v.
\]
The quantity $\left\|\vec{R}_u\times \vec{R}_v\right\|$ is called the \index{fundamental cross product} **fundamental cross product** .
::: 

::: {.proof }
Suppose a surface $S$ is defined parametrically by the vector function 
\[
\vec{R}(u,v)=x(u,v)\vec{i}+y(u,v)\vec{j}+z(u,v)\vec{k}
\] 
for parameters $u$ and $v.$ Let $D$ be a region in the $x y$-plane on which $x,$ $y,$ and $z,$ as well as their partial derivatives with respect to $u$ and $v$ are continuous. The partial derivatives of $R(u,v)$ are given by 
\[
\vec{R}_u=\frac{\partial x}{\partial u}\vec{i}+\frac{\partial y}{\partial u}\vec{j}+\frac{\partial z}{\partial u}\vec{k} 
\qquad \text{ and } \qquad
\vec{R}_v=\frac{\partial x}{\partial v}\vec{i}+\frac{\partial y}{\partial v}\vec{j}+\frac{\partial z}{\partial v}\vec{k}. 
\] 
Suppose the region $D$ is subdivided into cells. Consider a typical rectangle in this partition, dimension $\triangle  x$ and $\triangle  y$,
where $\triangle  x$ and $\triangle  y$ are small. If we project this rectangle onto the surface $\vec{R}(u,v),$ we obtain a curvilinear parallelogram
with adjacent sides $\vec{R}_u(u,v)\triangle  u$ and $\vec{R}_v(u,v)\triangle  v.$ The area of this rectangle is approximated by 
\[
\triangle S=\left\|\vec{R}_u(u,v)\triangle  u\times \vec{R}_v(u,v)\triangle  v\right\| =\left\|\vec{R}_u(u,v)\times \vec{R}_v(u,v)\right\|\triangle  u \triangle  v.
\]
By taking an appropriate limit, we find the surface area to be a double integral.  
::: 

::: {#exm- } 
Find the area of the surface given parametrically by the equation
\[
\vec{R}(u,v)= u v  \vec{i}+(u-v) \vec{j}+(u+v) \vec{k}
\]
for $u^2+v^2\leq 1$.
::: 

::: {.solution }
We find
\[
\vec{R}_u\times \vec{R}_v=\left|
\begin{array}{ccc}
 \vec{i} & \vec{j} & \vec{k} \\
 v & 1 & 1 \\
 u & -1 & 1
\end{array}
\right|=2\vec{i}+(u-v)\vec{j}-(u+v)\vec{k}.
\] 
Therefore the fundamental cross product is
\[
\left\|\vec{R}_u\times \vec{R}_v\right\|=\sqrt{4+(u-v)^2+(-u-v)^2}=\sqrt{4+2u^2+2v^2}.
\] 
Using polar coordinates the surface area is
\begin{align*}
S& =\int _0^{2\pi }\int _0^1\sqrt{4+2r^2}rdrd\theta
=\frac{1}{4}\int _0^{2\pi }\int _0^1\sqrt{4+2r^2}4rdrd\theta \\
& =\frac{1}{6}\int_0^{2\pi } \left(6\sqrt{6}-8\right) \, d\theta 
=\frac{2\pi }{3}\left(3\sqrt{6}-4\right).
\end{align*}
::: 

::: {#exm- } 
Find the area of the surface given parametrically by the equation
\[
\vec{R}(u,v)=(u \sin  v)\vec{i}+(u \cos  v)\vec{j}+ v \vec{k}
\]
for $0\leq u\leq a$ and $0\leq v\leq b$.
::: 

::: {.solution }
We find
\[ 
\vec{R}_u=(\sin  v)\vec{i}+(\cos  v)\vec{j}, \quad \vec{R}_v=(u \cos  v)\vec{i}+(-u \sin  v)\vec{j}+\vec{k},\]
and 
\[
\vec{R}_u\times \vec{R}_v=\left|
\begin{array}{ccc}
 \vec{i} & \vec{j} & \vec{k} \\
 \sin  v & \cos  v & 0 \\
 u \cos  v & -u \sin  v & 1
\end{array}
\right|=(\cos  v)\vec{i}-(\sin  v)\vec{j}-u \vec{k}.\]
Therefore the fundamental cross product is 
$\left\|\vec{R}_u\times \vec{R}_v\right\|=\sqrt{1+u^2}.$
So the surface area is
\begin{align*}
S& =\int _0^b\int _0^a\sqrt{1+u^2} \, du dv 
=\int_0^b \left[\frac{\ln \left|u+\sqrt{1+u^2}\right|}{2}+\frac{u\sqrt{1+u^2}}{2}|_0^a\right] \, dv \\
& =\frac{b}{2}\left[\ln \left(a+\sqrt{1+a^2}\right)+a\sqrt{1+a^2}\right].
\end{align*}
::: 

::: {#exm- } 
Find the area of the torus which is given parametrically by 
\[
\vec{R}(u,v)=(a+b \cos  v)\cos  u  \vec{i}+(a+b \cos  v)\sin  u  \vec{j}+ (b \sin  v)  \vec{k}
\]
for $0<b<a,$ $0\leq u\leq 2\pi ,$ and $0\leq v\leq 2\pi.$
::: 

::: {.solution }
We find 
\begin{align*}
& \vec{R}_u=-(a+b \cos  v)\sin  u \vec{i}+(a+b \cos  v)\cos u\vec{j}, \\
& \vec{R}_v=-b \sin  v \cos  u \vec{i}-b \sin  v \sin  u\vec{j}
+b \cos  v \vec{k}, \text{ and} \\
&  \vec{R}_u\times \vec{R}_v =\left|
\begin{array}{ccc}
 \vec{i} & \vec{j} & \vec{k} \\
 -(a+b \cos  v) \sin  u & (a+b \cos  v)\cos  u & 0 \\
 -b \sin  v \cos  u & -b \sin  v \sin  u & b \cos  v
\end{array}
\right| \\
& \qquad  \qquad =\left(b^2\cos  ^2v+a b \cos  v\right)(\cos  u)\vec{i} 
+\left(b^2\cos ^2v+a b \cos  v\right)(\sin  u)\vec{j} \\
& \qquad  \qquad  \qquad \qquad +\left(b^2\sin  v \cos  v+a b \sin  v\right)\vec{k}.\end{align*}
Therefore 
$ \left\|\vec{R}_u\times \vec{R}_v\right\|=\left|a b+b^2\cos  v\right|.$ 
So the surface area is 
\begin{align*}
S& =\int _0^{2\pi }\int _0^{2\pi }\left|a b+b^2\cos  v\right| du dv
=\int _0^{2\pi }2\pi \left(a b+b^2\cos  v\right)dv
=4\pi ^2 a b.
\end{align*}
::: 

## Exercises

::: {#exr- } 
Find the surface area of the part of the paraboloid $z=x^2+y^2$ that lies under the plane $z=9.$
::: 

::: {#exr- } 
Find the surface area of the surface of the portion of the plane $4x+y+z=9$ that lies in he first octant.
::: 

::: {#exr- } 
Find the surface area of the surface of the portion of the paraboloid $z=3x^2+3y^2$ that lies inside the cylinder $x^2+y^2=1.$
::: 

::: {#exr- } 
Find the surface area of the surface of the portion of the plane $2x+2y-z=0$ that is above the square in the plane with vertices $(0,1,0),$
$(0,0,0),$ $(1,0,0),$ and $(1,1,0).$ 
::: 

::: {#exr- } 
Find the surface area of the surface of the portion of the surface $z=x^2$ that lies over the triangular region in the plane with vertices
$(0,0,0),$ $(0,1,0),$ and $(1,0,0).$ 
::: 

::: {#exr- } 
Find the surface area of the surface of the portion of the sphere $x^2+y^2+z^2=25$ inside the cylinder $x^2+y^2=9.$
::: 

::: {#exr- } 
Find the surface area of the surface of the portion of the cone $z=2\sqrt{x^2+y^2}$ inside the cylinder $x^2+y^2=4.$
::: 

::: {#exr- } 
Find the surface area of the surface of the portion of the sphere $x^2+y^2+z^2=a^2$ inside the cylinder $x^2+y^2=a x$ and above the $x y$-plane.
::: 

::: {#exr- } 
Setup, but do not evaluate, the iterated integral for the surface area of the portion of the surface given by $z=e^{-x}\sin  y$ over the triangle with vertices $(0,0,0),$ $(0,1,1),$ $(0,1,0).$
::: 

::: {#exr- } 
Setup, but do not evaluate, the iterated integral for the surface area of the portion of the surface given by $x=z^3-y z+y^3$ over the square
$(0,0,0),$ $(0,0,2),$ $(0,2,0),$ and $(0,2,2).$ 
::: 

::: {#exr- } 
Setup, but do not evaluate, the iterated integral for the surface area of the portion of the surface given by $z=\cos \left(x^2+y^2\right)$
over the disk $x^2+y^2\leq \frac{\pi }{2}.$ 
::: 

::: {#exr- } 
Setup, but do not evaluate, the iterated integral for the surface area of the portion of the surface given by $z=e^{-x}\cos  y$ over the disk
$x^2+y^2\leq 2.$  
::: 

::: {#exr- } 
Setup, but do not evaluate, the iterated integral for the surface area of the portion of the surface given by $z=x^2+5 x y+y^2$ over the region
in the $x y$-plane bounded by the curve $x y=5$ and the line $x+y=6.$ 
::: 

::: {#exr- } 
Setup, but do not evaluate, the iterated integral for the surface area of the portion of the surface given by $z=x^2+3 x y+y^2$ over the region
in the $x y$-plane bounded by $0\leq x\leq 4,$ $0\leq y\leq x.$ 
::: 

::: {#exr- } 
Compute the magnitude of the fundamental cross product for the surface defined parametrically by $\vec{R}(u,v)=(2 u \sin  v)\, \vec{i}+(2 u \cos  v)\, \vec{j}+u^2\, \vec{k}.$
::: 

::: {#exr- } 
Compute the magnitude of the fundamental cross product for the surface defined parametrically by $\vec{R}(u,v)=(4 \sin  u \cos  v )\vec{i}+(4 \sin  u \sin v) \, \vec{j}+(5 \cos  u) \vec{k}.$
::: 

::: {#exr- } 
Compute the magnitude of the fundamental cross product for the surface defined parametrically by $\vec{R}(u,v)=u \, \vec{i}+ v^2 \, \vec{j}+u^3 \, \vec{k}.$
::: 

::: {#exr- } 
Compute the magnitude of the fundamental cross product for the surface defined parametrically by $\vec{R}(u,v)=(2 u \sin  v)\, \vec{i}+(2 u \cos  v)\, \vec{j}+\left(u^2\sin 2 v\right)\vec{k}.$ 
::: 

::: {#exr- } 
Find the area of the surface given parametrically by the equation 
$\vec{R}(u,v)=u v \, \vec{i}+(u-v)\, \vec{j}+(u+v) \vec{k}$
for $u^2+v^2\leq 1.$
::: 

::: {#exr- } 
A spiral ramp has the vector parametric equation  $\vec{R}(u,v)=(u \cos  v) \, \vec{i}+(u \sin  v) \, \vec{j}+v \, \vec{k}$ for $0\leq u\leq 1,$ $0\leq v\leq \pi .$ Find the surface area of this ramp. 
::: 



