---
pagetitle: "Triple Integrals - Exploring Calculus"
---
# Triple Integrals


## The Definition of a Triple Integral

Suppose $f(x,y,z)$ is defined on a closed bounded solid region $R,$ which in turn is contained in a box $B$ in space. We partition $B$ into a finite number of smaller boxes, call this partition $P,$ we choose a representative point $\left(x_k^*,y_k^*,z_k^*\right)$ from each subdivision in the partition and we form the sum, 
$$
\sum _{k=1}^N f\left(x_k^*,y_k^*,z_k^*\right)\triangle  V_k
$$ 
where $\triangle  V_k$ is the volume of the $k$-th representative subdivision. This sum is called the \index{Riemann sum} **Riemann sum**  of $f(x,y,z)$ with respect to the partition $P$ and the cell representation $\left(x_k^*,y_k^*,z_k^*\right).$ To measure the size of the rectangles in the partition $P,$ we define the norm $\|P\|$ of the partition to be the length of the longest diagonal of any of the subdivisions in the partition. We refine the partition by subdividing the subdivisions in such a way that the norm decreases. When this process is applied to the Riemann sum and the norm decreases to zero, we write 

$$
\iiint_R f(x,y,z) \, d V = \lim _{\|P\|\to 0}\sum _{k=1}^N f\left(x_k^*,y_k^*,z_k^*\right)\triangle  V_k.
$$ 
If this limit exists, its value is called the \index{triple integral} **triple integral**  of $f$ over the closed bounded region $R.$ 


## Basic Properties of Triple Integrals


::: {#thm- } [Properties of Triple Integrals]
Assume that all the given integrals exist on a rectangular region $R$ for given functions $f(x,y,z)$ and $g(x,y,z).$  
 
- For constants $a$ and $b,$ 
$$
\iiint_R (a f+b g)(x,y,z) \, dV
=a \iiint_R f(x,y,z) \, dV + b \iiint_R g(x,y,z) \, dV.$$
- If $f(x,y,z)\geq g(x,y,z)$ throughout a closed bounded region $R,$ then 
$$
\iiint_R f(x,y,z) \, dV\geq \iiint_R g(x,y,z) \, dV.$$
- If the closed bounded region of integration $R$ is subdivided into two disjoint subdivisions $R_1$ and $R_2$ whose union is $R$, then 
$$
\iiint_R f(x,y,z) \, dV= \iiint_{R_1} f(x,y,z) \, dV+\iiint_{R_2} f(x,y,z) \, dV.$$
 
::: 



## Fubini's Theorem for Triple Integrals


::: {#thm- } [Fubini's Theorem for Triple Integrals]
If $f(x,y,z)$ is continuous over a rectangular box 
$B =\{(x,y,z) \mid  a\leq x\leq b, c\leq y\leq d, r\leq z\leq s \},$
then the triple integral may be evaluated by the iterated integral 
$$
\iiint_R f(x,y) \, d V=\int _r^s\int _c^d\int _a^bf(x,y,z) \, dx dy dz$$
The iterated integral can be performed in any order, with appropriate adjustments to the limits of integration. 
::: 


::: {#exm- } 
Evaluate the triple integral over $B$ given 
$$
\iiint_B x y z^2 \, d V
\quad \text{and} \quad 
B=\{(x,y,z)\mid  0\leq x\leq 1,-1\leq y\leq 2,0\leq z\leq 3\}.
$$
::: 

::: {.solution }
Since $f(x,y)=x y z^2$ is continuous on $B$, we can use Fubini's theorem for triple integrals
$$
\int _0^3\int _{-1}^2\int _0^1x y z^2 \, dx dy dz =\int _0^3\int _{-1}^2\frac{y z^2}{2} \, dy dz =\int_0^3 \frac{3 z^2}{4} \, dz =\frac{27}{4}.
$$
::: 

::: {#exm- } 
Evaluate the triple integral over $B$ given 
$$
\iiint_B z^2 y e^x \, d V
\quad \text{and} \quad 
B=\{(x,y,z) \mid  0\leq x\leq 1,1\leq y\leq 2,-1\leq z\leq 1\}.
$$
::: 

::: {.solution }
Since $f(x,y)=z^2 y e^x$ is continuous on $B$, we can use Fubini's theorem for triple integrals
\begin{align*}
\int _{-1}^1\int _1^2\int _0^1z^2 y e^x \, dx dy dz 
& =\int _{-1}^1\int _1^2(-1+e) y z^2 \, dy dz
\\
& =\int_{-1}^1 \frac{3}{2} (-1+e) z^2 \, dz 
=-1+e
\end{align*}
::: 

::: {#exm- } 
Evaluate the iterated integral
$\int _0^{2\pi }\int _0^4\int _0^1z r \, dz \, dr \,d\theta$
::: 

::: {.solution }
We find  
$$
\int _0^{2\pi }\int _0^4\int _0^1z r \, dz \, dr \, d\theta 
=\int _0^{2\pi }\int _0^4\frac{r}{2} \, dr \, d\theta
=\int_0^{2\pi } 4 \, d\theta
=8 \pi.
$$
::: 

In many examples a sketch of the region of integration in the plane, can explain how to visualize the solid region of integration, and how to setup the limits of integration. 
Recall from studying double integrals, that a vertically simple region $D_1$ is a region of the plane that can be described by the inequalities 
$$D_1=\left\{(x,y) \mid a\leq x\leq b, g_1(x)\leq y\leq  g_2(x)\right\}$$
where $g_1(x)$ and $g_2(x)$ are continuous functions of $x$ on $[a,b].$ 
Similarly, a horizontally simple region $D_2$, in the plane is a region that can be described by the inequalities 
$$D_2=\left\{(x,y) \mid c\leq y\leq d, h_1(y)\leq x\leq  h_2(y)\right\}$$ 
where $h_1(x)$ and $h_2(x)$ are continuous functions of $y$ on $[c,d].$
In some cases it is possible to evaluate a triple integral by evaluating a triple iterated integral over a solid region that when projected onto the $x y$-plane can be described as a vertically simple or a horizontally simple region.  

::: {#thm- } [Fubini's Theorem for $z$-Simple Regions]

Suppose $R$ is a solid region bounded below by the surface $z=u(x,y)$ and above by the surface $z=v(x,y)$ that projects onto the region $D$ in the $x y$-plane. If $D$ is either a vertically simple or a horizontally simple region, then the triple integral of the continuous function $f(x,y,z)$ over $R$ is 
$$
\iiint_R f(x,y) \, d V=\iint_D \left(\int_{u(x,y)}^{v(x,y)} f(x,y,z) \, dz\right)dA.
$$
::: 

::: {#exm- } 

Evaluate 
$$
\iiint_D\frac{z}{\sqrt{x^2+y^2}} \, dx \, dy \, dz
$$
and $D$ is the solid bounded above by the plane $z=2$ and below by the surface $x^2+y^2-2z=0.$
::: 

::: {.solution }
We consider the region of integration as being $z$-simple by projecting onto the $x y$-plane; and in the $x y$-plane the region is bounded by $x^2+y^2=4$. Using polar coordinates the triple integral is evaluated as
\begin{align*}
\iiint_D \frac{z}{\sqrt{x^2+y^2}}\, dx \, dy \, dz 
& =4\int _0^{\pi /2}\int _0^2\int _{\left.r^2\right/2}^2\frac{z}{\sqrt{r^2}} r \, dz \, dr \, d\theta 
\\
& =4\int _0^{\pi /2}\int _0^2\frac{r \left(2-\frac{r^4}{8}\right)}{\sqrt{r^2}} \, dr \, d\theta 
\\
& =4\int_0^{\pi /2} \frac{16}{5} \, d\theta 
=\frac{32 \pi }{5}.
\end{align*}
::: 

::: {#exm- } 
Change the order of integration to show that  
$$
\int _0^x\int _0^vf(u) \, du \, dv=\int _0^x(x-u)f(u) \, du
$$
Also, show that 
$$
\int _0^x\int _0^v\int _0^uf(w) \, dw \, du \, dv=\frac{1}{2}\int _0^x(x-w)2f(w)dw.
$$
::: 

::: {.solution }
Let $u$ be the horizontal axis, $v$ be the vertical axis, and consider the triangular region $T$ determined by $u=0,$ $v=x,$
and $v=u.$ Switching the order of integration, we obtain: 
\begin{align*}
\int _0^x\int _0^vf(u) \, du \, dv
=\int _0^x\int _u^xf(u) \, dv \, du 
=\int _0^x(x-u)f(u) \, du\end{align*}
as desired. 
::: 
  


## Volume as a Triple Integral

::: {#exm- } 

Find the volume of the bounded solid
bounded by the sphere $x^2+y^2+z^2=2$ and the paraboloid $x^2+y^2=z$.
::: 

::: {.solution }
By solving for the intersection, $x^2+y^2+z^2=2$ with $z=x^2+y^2$ and so $z^2+z-2=0$ leads to $z=1.$ Therefore region of integration is $x^2+y^2=1$ and so we have a $z$-simple region with  
\begin{align*} 
V& =4\int _0^1\int _0^{\sqrt{1-x^2}}\int _{x^2+y^2}^{\sqrt{2-x^2-y^2}} \, dz\, dy \, dx  
\\
& =4\int _0^1\int _0^{\sqrt{1-x^2}}\left(-x^2-y^2+\sqrt{-x^2-y^2+2}\right) \, dy \, dx
\\
& =4\int _0^{\pi /2}\int _0^1\left(\sqrt{2-r^2}-r^2\right)r \, dr \, d\theta 
\\
&=4\int _0^{\pi /2}\left(-\frac{7}{12}+\frac{2 \sqrt{2}}{3}\right) \, d\theta 
=\left(\frac{8 \sqrt{2} -7}{6}\right)\pi 
\approx 2.25865 .
\end{align*}
::: 
  
::: {#exm- } 
Find the volume of the bounded solid
bounded by the cylinders $y=z^2$ and $y=2-z^2$ and the planes $x=1$ and $x=-2.$ 
::: 

::: {.solution }
We represent this solid as a $x$-simple region. 
The curves intersect where $y=z^2$ and $y=2-z^2$ and so $z=\pm 1.$ Therefore the volume is given by,  
\begin{align*}
V& =2\int _0^1\int _{z^2}^{2-z^2}\int _{-2}^1 \, dx \, dy \, dz
=2\int _0^1\int _{z^2}^{2-z^2}3 \, dy \, dz
\\
& =2\int _0^1\left(6-6 z^2\right) \, dz
=8
\end{align*}
::: 

::: {#exm- } 

Find the volume of the bounded solid
the tetrahedron $T$ bounded by the planes $x+2y+z=2,$ $x=2y,$ $x=0,$ and $z=0.$ 
::: 

::: {.solution }
The vertices of the tetrahedron are $(0,0,2),$ $\left(1,\frac{1}{2},0\right),$ and $(0,1,0).$ So the region of integration in the $x y$-plane is bounded by the lines $x=0,$ $y=\frac{1}{2}x,$ and $y=1-\frac{1}{2}x$ and is described by the set 
$$
R=\{(x,y) \mid  0\leq x \leq 1, x/2 \leq y \leq 1-x/2\}
$$  
This is determined by the vertices of the tetrahedron in the $x y$-plane and by determining the equations of the lines through these vertices. So the upper boundary is the plane $x+2y+z=2;$ that is $z=2-x-2y.$ Therefore, the volume of the tetrahedron $T$ bounded by the planes $x+2y+z=2,$ $x=2y,$ $x=0,$ and $z=0$ is
\begin{align*}
V& =\iiint_R \, d V 
=\int _0^1\int _{x/2}^{1-x/2}\int _0^{2-x-2y} \, dz \, dy \, dx \\
& =\int _0^1\int _{x/2}^{1-x/2}(-x-2 y+2) \, dy \, dx 
=\int_0^1 \left(x^2-2 x+1\right) \, dx 
=\frac{1}{3}.
\end{align*}
::: 
  
  


## Applications of Triple Integrals

::: {#def- } 
The \index{average value} **average value**  of a function $f$ of three variables over a solid region $R$ is defined to be 
$$f_{\text{av}}=\frac{1}{V(R)}\underset{R}{\int \int \int} f(x,y,z)\, dV$$
where $V(R)$ is the volume of the solid $R$. 
::: 

If a body in space occupies a region $R$ then the mass of the body is the triple integral of the mass density. The first moment of the body about a plane is the triple integral of the product of the signed distance to the plane and the mass density function where the distance is from the differential element of volume $dx\, dydz.$ The second moment (called \index{moment of inertia} **moment of inertia** ) of a body about an axis is the triple integral of the product square of the distance from the axis and the mass density function where the distance is from the differential element of volume $dx\, dydz.$ For example, a moment of inertia is used in computing kinetic energy of rotation $(1/2)I \omega ^2$ where $\omega$ is the angular speed of rotation. 

Suppose $R$ is a region in space and that $\delta$ is a continuous density function of $R$. Then for a body occupying a region $R$ in space the center of mass is located at the point $(\overline{x},\overline{y}, \overline{z})$ where 
$$
\overline{x}=\frac{M_{yz}}{m}, \qquad
\overline{y}=\frac{M_{xz}}{m}, \qquad
\overline{z}=\frac{M_{xy}}{m}
$$
and the \index{first moments} **first moments** $M_{x y}$, $M_{y x},$ and $M_{x z}$ about the $x y$-plane, $y z$-plane,
and the $x z$-plane, respectively are  
\begin{align*}
& M_{x y}=\underset{R}{\int \int \int }z \delta (x,y,z)dx\, dydz, \\
& M_{y z}=\underset{R}{\int \int \int }x \delta (x,y,z)dx\, dydz, \text{ and } \\
& M_{x z}=\underset{R}{\int \int \int }y \delta (x,y,z)dx\, dydz,.
\end{align*}
where
$$
m=\underset{R}{\int \int \int} \delta(x,y,z) dV
$$
is the mass of the body. Further, $I_x ,$ $I_y ,$ and $I_z ,$ the \index{second moments} **second moments** (or \index{moments of inertia} **moments of inertia**) about the coordinate axes are  
\begin{align*}
& I_x=\underset{R}{\int \int \int }\left(y^2+z^2\right) \delta (x,y,z)dx\, dydz, \\
& I_y=\underset{R}{\int \int \int }\left(x^2+z^2\right) \delta (x,y,z)dx\, dydz, \text{ and } \\
& I_z=\underset{R}{\int \int \int }\left(x^2+y^2\right) \delta (x,y,z)dx\, dydz.
\end{align*}
More generally the \index{moments of inertia} **moments of inertia**  about a line $L$ is  
$$ I_L=\underset{R}{\int \int \int } r^2 \delta (x,y,z)dV$$
where $r(x,y,z)$ is the distance from the point $(x,y,z)$ to the line $L.$ 
Intuitively speaking, the moment of inertia $I$ is a measure of the resistance of a body to rotational motion. 

% Moreover, the \index{radius of gyration} **radius of gyration** about a line $L$ is given as $R_L=\sqrt{\left.I_L\right/M}$ where $M$ is the total mass of the object.

::: {#exm- } 
Find the moment of inertia about the $z$-axis of the solid tetrahedron $S$ with vertices $(0,0,0)$, $(0,1,0)$, $(1,0,0)$, $(0,0,1)$, and density $\delta(x,y,z)=x$.
::: 

::: {.solution }
The solid $S$ can be described as the set of all $(x,y,z)$ such that $0\leq x\leq 1$, $0\leq y \leq 1-x$, and $0\leq z\leq 1-x-y$. Thus, 
\begin{align*}
I_z&=\underset{S}{\int \int \int}(x^2+y^2)\delta(x,y,z) \, dV 
\\
& =\int_0^1\int_0^{1-x}\int_0^{1-x-y} x(x^2+y^2) \, dz \, dy \, dx 
\\
& =\int_0^1 \int_0^{1-x}x(x^2+y^2)(1-x-y) dy \, dx 
\\
& = \int_0^1 \left(\frac{x^3(1-x^2)}{2}-\frac{x(1-x^4)}{12}\right) \,dx
=\frac{1}{90}.
\end{align*}
::: 


## Exercises

::: {#exr- } 
Find the following iterated integrals. 
 
- $\int _1^4\int _{-2}^3\int _2^5 \, dx \, dy \, dz.$ 
- $\int _{-1}^3\int _0^2\int _{-2}^2 \, dy \, dz \, dx.$
- $\int _1^2\int _0^1\int _{-1}^28x^2y z^3 \, dx \, dy \, dz.$ 
- $\int _4^7\int _{-1}^2\int _0^3x^2y^2z^2 \, dx \, dy \, dz.$
- $\int _0^2\int _0^x\int _0^{x+y}x y z \, dz \, dy \, dx.$ 
- $\int _0^1\int _{\sqrt{x}}^{\sqrt{1+x}}\int_0^{x y}y^{-1} z \, dz \, dy \, dx.$ 
- $\int _{-1}^2\int _0^{\pi }\int _1^4y z \cos  x y \, dz \, dx \, dy.$ 
- $\int _0^{\pi }\int _0^1\int _0^1x^2y \cos  x y z \, dz \, dy \, dx.$ 
- $\int _0^1\int _0^y\int _0^{\ln (y)}e^{z+2x} \, dz \, dx \, dy.$
::: 

::: {#exr- } 
Evaluate the triple integral over the given region

- $\underset{D}{\int \int \int }\left(x^2y+y^2z\right)\,dV$ where $D$ is the boxed region defined by $1\leq x\leq 3$, $-1\leq y\leq 1$, and $2\leq z\leq 4.$
- $\underset{D}{\int \int \int }(x y+2 y z)\, dV$ where $D$ is the boxed region defined by $2\leq x\leq 4$, $1\leq y\leq 3$, and $-2\leq z\leq 4.$
- $\underset{D}{\int \int \int }x y z \, dV$ where $D$ is the region bounded by the paraboloid$z=x^2+y^2$ and the plane $z=1.$ 
- $\underset{D}{\int \int \int }y z \, dV$ where $D$ is the solid in the first octant bounded by the hemisphere $x=\sqrt{9-y^2-z^2}$ and the coordinate planes. 
::: 

::: {#exr- } 
Find the volume of the region between the two elliptic paraboloids $z=\left.x^2\right/(9+y^2-4)$ and $z=\left.-x^2\right/(9-y^2+4).$  
::: 

::: {#exr- } 
Change the order of integration to show that 
$$
\int _0^x\int _0^vf(u) \, du \, dv=\int _0^x(x-u)f(u) \, du.
$$ 
Also, show that
$$
\int _0^x\int _0^v\int _0^uf(w) dw du dv =\frac{1}{2}\int _0^x(x-w)2f(w) \, dw.
$$
::: 

::: {#exr- } 
Higher-dimensional multiple integrals can be defined and evaluated in essentially the same way as double integrals and triple integrals. Evaluate the multiple integrals 
$$
\underset{H}{\int \int \int \int }x y w^2 \, dx \, dy \, dz \, dw
$$ where $H$ is the four-dimensional (hyperbox) defined by $0\leq  x\leq  1,$ $0\leq y\leq 2,$ $-1\leq z\leq 1,$ and $1\leq
w\leq 2.$ 
::: 

::: {#exr- } 
Find the volume $V$ of the solids bounded by the graphs of the equations by using triple integration. The solid bounded by the sphere $x^2+y^2+z^2=2$ and the paraboloid $x^2+y^2=z.$ The solid of the region bounded by the cylinders $y=z^2$ and $y=2-z^2$ and the planes $x=1$ and $x=-2.$ 
::: 

::: {#exr- } 
Evaluate the multiple integral 
$$
\underset{H}{\int \int \int \int }e^{x-2y+z+w} \, dw \, dz \, dy \, dx
$$ where $H$ is the four-dimensional region bounded by the hyperplane $x+y+z+w=4$ and the coordinate spaces $x=0,$ $y=0,$ $z=0,$ and $w=0$ in the first hyperoctant (where $x\geq 0,$ $y\geq 0,$ $z\geq 0,$ $w\geq 0$). 
::: 

::: {#exr- } 
A solid of constant density is bounded below by the plane $z=0,$ on the sides by the elliptical cylinder $x^2+4y^2=4,$ and above by the plane $z=2-x.$ Find $\bar{x} ,$ $\bar{y} ,$ and then evaluate the integral 
$$
M_{x y}=\int _{-2}^2\int _{-(1/2)\sqrt{4-x^2}}^{1/2\sqrt{4-x^2}}\int_0^{2-x}z \, dz \, dy \, dx
$$ to determine $\bar{z}.$ 
::: 

::: {#exr- } 
Find the centroid and the moments of inertia $I_x ,$ $I_y ,$ and $I_z$ of the tetrahedron whose vertices are $(0,0,0),$ $(1,0,0),$ and $(0,0,1).$ Find the radius of gyration of the tetrahedron about the $x$-axis. Compare it with the distance from the centroid to the $x$-axis. 
::: 

::: {#exr- } 
A solid cube, 2 units on a side, is bounded by the planes $x=\pm 1,$ $z=\pm 1,$ $y=3$ and $y=5.$ Find the center of mass, moments of inertia, and radii of gyration about the coordinate axes. 
::: 

::: {#exr- } 
A solid in the first octant is bounded by the coordinate lanes and the plane $x+y+z=2.$ The density of the solid is $\delta (x,y,z)=2x.$ Find the mass and the center of mass. 
::: 

::: {#exr- } 
Find the mass of the solid region bounded by the parabolic surface $z=16-2x^2-2y^2$ and $z=2x^2+2y^2$ if the density of the solid is $\delta (x,y)=\sqrt{x^2+y^2}.$
::: 

::: {#exr- } 
The container is in the shape of the region bounded by $y=0,$ $z=0,$ $z=4-x^2,$ and $x=y^2.$ The density of the liquid filling the region is $\delta (x,y)=k x y$ where $k$ is a constant. 
::: 

::: {#exr- } 
Find the centroid for the part of the spherical solid with density $\delta =2$ described by $x^2+y^2+z^2\leq 9,$ $x\geq 0,$ $y\geq 0,$
and $z\geq 0.$
::: 

::: {#exr- } 
Find the centroid for the solid bounded by the surface $z=\sin  x,$ $x=0,$ $x=\pi ,$ $y=0,$ $z=0,$ and $y+z=1,$ where the density
is $\delta =1.$
::: 




## Cylindrical Coordinates


Each point in three dimensions is uniquely represented in cylindrical coordinates by $(r,\theta ,z)$ using $0\leq r<\infty ,$ $0\leq
\theta < 2\pi ,$ and $-\infty <z<+\infty .$ The conversion formulas involving rectangular coordinates $(x,y,z)$ and cylindrical coordinates $(r,\theta ,z)$ are 
\begin{align*}
 r=\sqrt{x^2+y^2} & \qquad & 
 \tan  \theta =\frac{y}{x} &  \qquad  & 
 z=z \\
 x=r \cos  \theta &  & 
 y=r \sin  \theta  &  & 
 z=z.\end{align*}
A triple integral 
%$$\iiint_Rf(x,y,z) \, dV$$ 
over a region $R$ can sometimes be evaluated by transforming to cylindrical coordinates if the region of integration $R$ is $z$-simple and the projection of $R$ onto the $x y$-plane is a region $D$ that can be described naturally in terms of polar coordinates.


::: {#thm- } [Triple Integrals in Cylindrical Coordinates]
Assume $R$ is a solid region with continuous upper surface $z=v(r,\theta )$ and continuous lower surface $z=u(r,\theta )$ and assume is $D$ be the projection of the solid onto the $x y$-plane expressed in polar coordinates:
$$
D=\{(r,\theta):\alpha \leq r \leq \beta, r_1(\theta) \leq r(\theta) \leq r_2(\theta) \}
$$
where $r_1$ and $r_2$ are continuous functions of $\theta$.
If $f(x,y,z)$ is continuous on $R,$ then the triple integral of $f$ over $R$ can be evaluated as follows 
$$
\iiint_Rf(x,y,z)dV=\int _{\alpha }^{\beta }\int _{r_1(\theta )}^{r_2(\theta )}\int _{u(r,\theta )}^{v(r,\theta )}f(r \cos  \theta ,r \sin  \theta ,z) r dz dr \, d\theta .
$$
::: 

::: {#exm- } 

Find the volume of the bounded solid
bounded by the paraboloid $4x^2+4y^2+z=1$ and the $x y$-plane.
::: 

::: {.solution }
The projection of the solid region onto the $x y$-plane is the region enclosed by $x^2+y^2=\frac{1}{4}$. In cylindrical coordinates the volume is determined as,
\begin{align*}
4\int _0^{\pi /2}\int _0^{1/2}\int _0^{1-4r^2}rdzdrd\theta 
& =4\int _0^{\pi /2}\int _0^{1/2}\left(r-4 r^3\right)drd\theta 
\\
& =4\int_0^{\pi /2} \frac{1}{16} \, d\theta
 =\frac{\pi }{8}.
\end{align*}
::: 
  
::: {#exm- } 
Evaluate the iterated integral
$$
I=\int _{-1}^1\int _{-\sqrt{1-x^2}}^{\sqrt{1-x^2}}\int _{x^2+y^2}^{\sqrt{2-x^2-y^2}}z \, dz \, dy \, dx.
$$ 
::: 

::: {.solution }
In Cartesian coordinates the region of integration $D$ is given as
$$
\left\{(x,y,z) \mid x^2+y^2\leq z\leq  \sqrt{2-x^2-y^2},  -\sqrt{1-x^2}\leq y\leq  \sqrt{1-x^2}, -1\leq  x\leq 1\right\}
$$
We use cylindrical coordinates to evaluate the triple iterated integral 
$I$ as follows
\begin{align*}
I& =\int _0^{2\pi }\int _0^1\int _{r^2}^{\sqrt{2-r^2}}z r dzdrd\theta 
\\
& =\int _0^{2\pi }\int _0^1r \left(-\frac{r^4}{2}-\frac{r^2}{2}+1\right)drd\theta 
=\int_0^{2\pi } \frac{7}{24} \, d\theta 
=\frac{7 \pi }{12}.
\end{align*}
::: 

::: {#exm- } 

Evaluate the triple integral over the given region
$$
I=\iiint_R\left(x^4+2x^2y^2+y^4\right) \, dx \, dy \, dz
$$
where $R$ is the cylindrical solid $x^2+y^2\leq a^2$ with $0\leq z\leq \frac{1}{\pi }$
::: 

::: {.solution }
We consider the region of integration as being $z$-simple by projecting onto the $x y$-plane; and in the $x y$-plane the region is bounded by 
$x^2+y^2=a^2$. 
Notice that  
$$
x^4+2x^2y^2+y^4=\left(x^2+y^2\right)^2.
$$
In cylindrical coordinates the triple integral is evaluated as, 
\begin{align*}
I
& =4\int _0^{\pi /2}\int _0^a\int _0^{1/\pi }r^4r dzdrd\theta 
\\
& =4\int _0^{\pi /2}\int _0^a\frac{r^5}{\pi }drd\theta 
=4\int_0^{\pi /2} \frac{a^6}{6 \pi } \, d\theta 
=\frac{a^6}{3}.
\end{align*}
::: 

::: {#exm- } 
Evaluate the iterated integral
$$
\int _0^{\pi }\int _0^2\int _0^{\sqrt{4-r^2}}r \sin  \theta \,dz \, dr \,d\theta .
$$
::: 

::: {.solution }
We find  
\begin{align*}
\int _0^{\pi }\int _0^2\int _0^{\sqrt{4-r^2}}r \sin \theta  \, dz \, dr \, d\theta 
& =\int _0^{\pi }\int _0^2r \sqrt{4-r^2} \sin \theta \, dr \, d\theta 
\\
& =\int_0^{\pi } \frac{8 \sin \theta }{3} \, d\theta 
=\frac{16}{3}
\end{align*}
::: 

::: {#exm- } 
Evaluate the iterated integral
$$
\int _0^{\pi /4}\int _0^1\int _0^{\sqrt{r}}r^2 \sin  \theta \, dz \, dr \, d\theta.
$$
::: 

::: {.solution }
We find  
\begin{align*}
\int _0^{\pi /4}\int _0^1\int _0^{\sqrt{r}}r^2 \sin \theta  \, dz \, dr \, d\theta
& =\int _0^{\pi /4}\int _0^1r^{5/2} \sin \theta \, dr \, d\theta 
\\
& =\int_0^{\pi /4} \frac{2 \sin \theta }{7} \, d\theta 
=\frac{2}{7} \left(1-\frac{1}{\sqrt{2}}\right)
=\frac{2-\sqrt{2}}{7}
\end{align*}
::: 


## Spherical Coordinates


Each point in three dimensions is uniquely represented in spherical coordinates by $(\rho ,\theta ,\phi )$ using $0\leq \rho <\infty ,$
$0\leq \theta < 2\pi ,$ and $0\leq  \phi \leq \pi .$ The conversion formulas from rectangular coordinates $(x,y,z)$ to spherical coordinates
$(\rho ,\theta ,\phi )$ are 
$$\begin{array}{lllll}
 \rho =\sqrt{x^2+y^2+z^2} & \qquad &  \theta = \tan^{-1} \left( \frac{y}{x}\right) & \qquad &\phi =\cos ^{-1}\left(\frac{z}{\sqrt{x^2+y^2+z^2}}\right) \\
x=\rho  \sin \phi  \cos \theta  & & y =\rho  \sin \phi \sin \theta  & & z=\rho  \cos \phi
\end{array}$$
Using Jacobians, we can show that the element of volume in spherical coordinates is 
$$
dV=\rho ^2 \sin \phi \,d\rho \, d\theta \, d\phi.
$$


::: {#thm- } [Triple Integrals in Spherical Coordinates]
If $f(x,y,z)$ is continuous on the closed bounded region $R$, then the triple integral
of $f$ over $R$ is given by 
\begin{align*}
& \iiint_Rf(x,y,z)dV 
\\
& = \iiint_S f(\rho  \sin \phi \cos  \theta ,\rho  \sin \phi \sin \theta ,\rho  \cos \phi ) \, \rho ^2 \sin \phi \, d\rho \, d\phi \, d\theta
\end{align*}
where $S$ is the region $R$ expressed in spherical coordinates.
::: 

::: {#exm- } 

Find the volume of the bounded solid $S$ inside the sphere of radius $a$. 
::: 

::: {.solution }
Since an equation of the sphere is $\rho =a$ for $0\leq \theta <2\pi$ and $0\leq \phi \leq \pi ,$ the volume is determined by evaluating a triple iterated integral in spherical coordinates
\begin{align*}
\iiint_S  \, dV 
& =\int _0^{2\pi }\int _0^{\pi }\int _0^a\rho ^2 \sin \phi \, d\rho \, d\phi \, d\theta 
\\
& = \int _0^{2\pi }\int _0^{\pi }\frac{1}{3} a^3 \sin \phi \, d\phi \, d\theta
%=\int_0^{2\pi } \frac{2 a^3}{3} \, d\theta 
=\frac{4 a^3 \pi }{3}.
\end{align*}
::: 

::: {#exm- } 
Evaluate the triple integral over the given region
$$
I=\iiint_D z^2 \, dx \, dy \, dz
$$
where $D$ is the solid hemisphere $x^2+y^2+z^2\leq 1$ and $z\geq 0$
::: 

::: {.solution }
Using spherical coordinates to evaluate the triple integral
\begin{align*}
I=&4\int _0^{\pi /2}\int _0^{\pi /2}\int _0^1 \rho ^4 \cos ^2 \phi  \sin \phi  \ d\rho \, d\theta \, d\phi 
\\
& =4\int _0^{\pi /2}\int _0^{\pi /2}\frac{1}{5} \cos ^2 \phi \sin \phi  \ d\theta \, d\phi 
\\
&=4\int_0^{\pi /2} \frac{1}{10} \pi  \cos ^2 \phi  \sin \phi  \, \ d\phi
\\
& =\frac{4\pi }{10}\left(-\frac{\cos \phi }{4}-\frac{1}{12} \cos (3 \phi )\right)
=\frac{2 \pi }{15}.
\end{align*}
::: 

::: {#exm- } 
Evaluate the triple integral over the given region
$$
I=\iiint_D \frac{dx\, dydz}{\sqrt{x^2+y^2+z^2}}
$$
where $D$ is the solid sphere $x^2+y^2+z^2\leq 3.$
::: 

::: {.solution }
Since the integrand is symmetric about the origin we can use symmetry. In spherical coordinates the triple integral $I$ evaluates to, 
\begin{align*}
I
& =8\int _0^{\pi /2}\int _0^{\pi /2}\int _0^{\sqrt{3}} \rho  \sin \phi  \, d\rho \, d\theta \, d\phi 
\\
& =8\int _0^{\pi /2}\int _0^{\pi /2}\frac{3 \sin \phi }{2} \, d\theta \, d\phi
\\
& =8\int_0^{\pi /2} \frac{3}{4} \pi  \sin (\phi ) \, d\phi 
=6 \pi.
\end{align*}
::: 

::: {#exm- } 
Evaluate the iterated integral
$$
I =\int _0^{\pi /2}\int _0^{2\pi }\int _0^2 \cos  \phi  \sin  \phi \,d\rho \,d\theta d\phi.
$$
::: 

::: {.solution }
We find  
\begin{align*}
I & =\int _0^{\pi /2}\int _0^{2\pi }2 \cos \phi  \sin \phi \, d\theta \, d\phi 
\\
& = \int_0^{\pi /2} 4 \pi  \cos \phi  \sin \phi  \, d\phi 
=2 \pi.
\end{align*}
::: 

::: {#exm- } 
Evaluate the iterated integral
$$
I=\int _0^{\pi /2}\int _0^{\pi /4}\int _0^{\cos  \phi }\rho ^2 \sin  \phi \, d\rho \, d\theta \, d\phi.
$$
::: 

::: {.solution }
We find  
\begin{align*}
I& =\int _0^{\pi /2}\int _0^{\pi /4}\frac{1}{3} \cos ^3 \phi  \sin \phi \, d\theta \, d\phi  
\\
& =\int_0^{\pi /2} \frac{1}{12} \pi  \cos ^3(\phi ) \sin \phi  \, d\phi 
=\frac{\pi }{48}.
\end{align*}
::: 

::: {#exm- } 

Find the volume of the bounded solid in the spherical solid $\rho \leq 4$ after the solid cone $\phi \leq \pi /6$ has been removed. 
::: 

::: {.solution }
We will use spherical coordinates and evaluate a triple iterated integral to find the volume 
\begin{align*}
V& =\int _0^{2\pi }\int _{\pi /6}^{\pi }\int _0^4\rho ^2 \sin \phi  \, d\rho \, d\phi \, d\theta 
 =\int _0^{2\pi }\int _{\pi /6}^{\pi }\frac{64 \sin \phi }{3} \, d\phi \, d\theta 
\\
& =\int_0^{2\pi } \frac{64}{3} \left(1+\frac{\sqrt{3}}{2}\right) \, d\theta
=\frac{64\pi }{3} \left(2+\sqrt{3}\right).
\end{align*}
::: 

::: {#exm- } 
Evaluate the triple iterated integral
$$
I=\int _0^3\int _0^{\sqrt{9-y^2}}\int _{\sqrt{x^2+y^2}}^{\sqrt{18-x^2-y^2}}\left(x^2+y^2+z^2\right) \, dz \, dx \,dy.
$$
::: 

::: {.solution }
Converting to spherical coordinates we evaluate $I$ as follows,
\begin{align*}
I&=\int _0^{\pi /4}\int _0^{\pi /2}\int _0^{3\sqrt{2}}\rho ^4 \sin \phi  \, d\rho \, d\theta \, d\phi 
\\
& =\int _0^{\pi /4}\int _0^{\pi /2}\frac{972}{5} \sqrt{2} \sin \phi  \, d\theta \, d\phi 
\\
&=\int_0^{\pi /4} \frac{486}{5} \sqrt{2} \pi  \sin \phi  \, d\phi
=\frac{486\pi }{5} \left(\sqrt{2} -1\right).
\end{align*}
::: 

## Exercises

::: {#exr- } 
Evaluate the following iterated integrals. 
 
- $\int _0^{\pi }\int _0^2\int _0^{\sqrt{4-r^2}}r \sin  \theta \, dz \, dr \, d\theta$
- $\int _0^{\pi /4}\int _0^1\int _0^{\sqrt{r}}r^2 \sin  \theta \, dz \, dr \, d\theta$
- $\int _0^{2\pi }\int _0^4\int _0^1z r \, dz \, dr \, d\theta$
- $\int _{-\pi /4}^{\pi /3}\int _0^{\sin  \theta }\int _0^{4 \cos  \theta } r \, dz \, dr \, d\theta$
- $\int _0^{\pi /2}\int _0^{\pi /4}\int _0^{\cos  \phi }\rho ^2 \sin  \phi \, d\rho \, d\theta \, d\phi$
- $\int _0^{\pi /2}\int _0^{2\pi }\int _0^2 \cos  \phi  \sin  \phi \, d \rho \, d\theta \, d\phi$ 
::: 





## Change of Variables In Multiple Integrals

 
### Jacobians


If $x=x(u,v)$ and $y=y(u,v)$ then the \index{Jacobian} **Jacobian**  of $x$ and $y$ with respect to $u$ and $v$ is 
$$
\frac{\partial (x,y)}{\partial (u,v)}
=J(u,v)=\left|
\begin{array}{cc}
 \frac{\partial x}{\partial u} & \frac{\partial x}{\partial v} \\
 \frac{\partial y}{\partial u} & \frac{\partial y}{\partial v}
\end{array}
\right|=\frac{\partial x}{\partial u}\frac{\partial y}{\partial v}-\frac{\partial y}{\partial u}\frac{\partial x}{\partial v}.
$$

::: {#exm- } 

Determine the Jacobian for the transformation from the rectangular plane to the polar plane. 
::: 

::: {.solution }
 The conversion formulas are $x=r \cos  \theta$ and $y=r \sin  \theta .$ So the Jacobian is
$$
J(r,\theta )=\left|
\begin{array}{cc}
 \frac{\partial x}{\partial r} & \frac{\partial x}{\partial \theta }  \\
 \frac{\partial y}{\partial r} & \frac{\partial y}{\partial \theta }
\end{array}
\right|=\left|
\begin{array}{cc}
 \cos  \theta  & -r \sin  \theta  \\
 \sin  \theta  & r \cos  \theta 
\end{array}
\right|
=r \cos ^2 \theta -\left(-r \sin ^2 \theta \right)=r.
$$
::: 

More generally for
$$
x_1=x_1\left(u_1,\text{\ldots},u_n\right), \quad 
x_2=x_2\left(u_1,\ldots,u_n\right), \quad \ldots \quad 
x_n=x_n\left(u_1,\text{\ldots},u_n\right)
$$
the \index{Jacobian} **Jacobian** of $x_1,\ldots, x_n$ with respect to $u_1,\ldots,u_n$ is 
$$
J\left(u_1,\text{\ldots},u_n\right)=\left|
\begin{array}{ccc}
 \frac{\partial x_1}{\partial u_1} & \text{\ldots} & \frac{\partial x_1}{\partial u_n} \\
 \text{\ldots} & \text{\ldots} & \text{\ldots} \\
 \frac{\partial x_n}{\partial u_1} & \text{\ldots} & \frac{\partial x_n}{\partial u_n}
\end{array}
\right|.
$$

::: {#exm- } 

Determine the Jacobian for the transformation
from rectangular coordinates to cylindrical coordinates
::: 

::: {.solution }
 The conversion formulas are $x=r \cos  \theta ,$ $y=r \sin  \theta ,$ and $z=z.$ So the Jacobian is
\begin{align*}
J(r,\theta ,z)
=\left|
\begin{array}{ccc}
 \frac{\partial x}{\partial r} & \frac{\partial x}{\partial \theta } & \frac{\partial x}{\partial z}  \\
 \frac{\partial y}{\partial r} & \frac{\partial y}{\partial \theta } & \frac{\partial y}{\partial z}  \\
 \frac{\partial z}{\partial r} & \frac{\partial z}{\partial \theta } & \frac{\partial z}{\partial z}
\end{array}
\right| 
& =\left|
\begin{array}{ccc}
 \cos  \theta  & -r \sin  \theta  & 0 \\
 \sin  \theta  & r \cos  \theta  & 0 \\
 0 & 0 & 1
\end{array}
\right| 
\\
& =r \cos ^2 \theta -\left(-r \sin ^2 \theta \right)=r.
\end{align*}
::: 

::: {#exm- } 

Determine the Jacobian for the transformation
from rectangular coordinates to spherical coordinates.
::: 

::: {.solution }
 The conversion formulas are $x=\rho  \sin  \phi  \cos  \theta ,$ $y=\rho  \sin  \phi  \sin  \theta$ and $z=\rho  \cos  \phi
.$ 
So the Jacobian $J(\rho ,\theta ,\phi )$ is
\begin{align*}
\left|
\begin{array}{ccc}
 \frac{\partial x}{\partial \rho } & \frac{\partial x}{\partial \theta } & \frac{\partial x}{\partial \phi } \\
 \frac{\partial y}{\partial \rho } & \frac{\partial y}{\partial \theta } & \frac{\partial y}{\partial \phi } \\
 \frac{\partial z}{\partial \rho } & \frac{\partial z}{\partial \theta } & \frac{\partial z}{\partial \phi }
\end{array}
\right| 
& =\left| 
\begin{array}{ccc}
 \sin  \phi  \cos  \theta  & -\text{$\rho $sin} \phi  \sin  \theta  & \rho  \cos  \phi  \cos  \theta  \\
 \sin  \phi  \sin  \theta  & \rho  \sin  \phi  \cos  \theta  & \rho  \cos  \phi  \sin  \theta  \\
 \cos  \phi  & 0 & -\rho  \sin  \phi 
\end{array}
\right|
\\
& =-\rho ^2 \sin  \phi .
\end{align*}
::: 

::: {#exm- } 
Find the Jacobian $\frac{\partial (x,y)}{\partial (u,v)}$ given 
$$
u=\frac{x}{x^2+y^2}
\quad \text{and} \quad
v=\frac{y}{x^2+y^2}.
$$
::: 
  
::: {.solution }
 The Jacobian is  
\begin{align*}
J(x,y) & = \left|
\begin{array}{cc}
\partial _x \left(\frac{x}{x^2+y^2}\right) & \partial _y \left(\frac{x}{x^2+y^2}\right)  \\
\partial _x \left(\frac{y}{x^2+y^2}\right) & \partial _y \left(\frac{y}{x^2+y^2}\right)
\end{array}
\right| 
=\left|
\begin{array}{cc}
 \frac{y^2-x^2}{\left(x^2+y^2\right)^2} & -\frac{2 x y}{\left(x^2+y^2\right)^2}  \\
 -\frac{2 x y}{\left(x^2+y^2\right)^2} & \frac{x^2-y^2}{\left(x^2+y^2\right)^2}
\end{array}
\right| 
\\
& =\frac{y^2-x^2}{\left(x^2+y^2\right)^2}\frac{x^2-y^2}{\left(x^2+y^2\right)^2}-\frac{2 x y}{\left(x^2+y^2\right)^2}\frac{2 x y}{\left(x^2+y^2\right)^2}
=-\frac{1}{\left(x^2+y^2\right)^2}.
\end{align*}
Since  
$$
u^2+v^2=\left(\frac{x}{x^2+y^2}\right)^2+\left(\frac{y}{x^2+y^2}\right)^2=\frac{1}{x^2+y^2}
$$ 
we find
$$
J(u,v)=\frac{1}{J(x,y)}=\frac{-1}{\left(u^2+v^2\right)^2}.
$$
::: 

## Change of Variable in a Double Integral

::: {#thm- } [Change of Variable in a Double Integral]

Let $z=f(x,y)$ be a continuous function on a region $R$ in the $x y$-plane, and let $T$ be a one-to-one transformation that maps the region $D$ in the 
$u v$-plane onto $R$ under the change of variables $x=x(u,v)$ and $y=y(u,v),$ where $x$ and $y$ are continuously differentiable functions on $R.$ If $J(u,v)\neq 0,$ then  
$$
\iint_R f(x,y)dx\, dy=\iint_D f(x(u,v),y(u,v))| J(u,v)| du dv.
$$
::: 

::: {.proof }
Let $T$ be the transformation from the $u v$-plane to the $x y$-plane given by $x=x(u,v)$ and $y=y(u,v)$. We will consider the effect that $T$ has  on the area of a small rectangular region $D$ in the $uv$-plane with vertices 
$(u_0,v_0)$, $(u_0+\Delta u,v_0)$, $(u_0,v_0+\Delta v)$, and $(u_0+\Delta u,v_0+\Delta v)$ where $(u_0,v_0)$ is a given point and both $\Delta u$ and $\Delta v$ are increments of $u$ and $v$ respectively. Let $L_1$ be the line segment between the vertices $(u_0,v_0)$ and $(u_0+\Delta u,v_0)$ and also let $L_2$ be the line segment between the vertices $(u_0,v_0)$ and 
$(u_0,v_0+\Delta v)$.

Define the vector function $\vec{r}$ by 
$$
\vec{r}(u,v)=x(u,v)\vec{i}+y(u,v)\vec{j}
$$ and also 
$$
\vec{a}=\vec{r}(u_0+\Delta u,v_0)-\vec{r}(u_0,v_0)
\quad \text{and} \quad 
\vec{b}=\vec{r}(u_0,v_0+\Delta v)-\vec{r}(u_0,v_0).
$$
Notice that $T(D)=R$ is a region in the $xy$-plane whose area can be approximated by $|\vec{a}\times \vec{b}|$ because we are assuming $\Delta u$ and  $\Delta v$ are small increments in $u$ and $v$ and $T$ is a continuous one-to-one onto transformation. Let $\Delta A$ denote the area of $R$, it follows
\begin{align*}
\Delta A \approx |\vec{a}\times \vec{b}| & =
\left| 
\frac{\vec{r}(u_0+\Delta u,v_0)-\vec{r}(u_0,v_0) \Delta u}{ \Delta u} \times \frac{\vec{r}(u_0,v_0+\Delta v)-\vec{r}(u_0,v_0) \Delta v}{ \Delta v}
\right | \\
& \approx \left| \vec{r}_u \Delta u \times \vec{r}_v \Delta v \right|
= \left| \vec{r}_u \times \vec{r}_v \right| \Delta u \Delta v \end{align*}
If we consider the factor  $\left| \vec{r}_u \times \vec{r}_v \right|$ in terms of the functions which define the transformation $T$ we are lead to 
$$
\vec{r}_u \times \vec{r}_v 
=\left| \begin{array}{ccc} \vec{i} & \vec{j} & \vec{k} \\ x_u & y_u & 0 \\ x_v & y_v & 0 \end{array} \right| 
=0\vec{i}-0\vec{j}+(x_u y_v-x_v y_u) \vec{k}
$$
which implies 
$$
|\vec{r}_u \times \vec{r}_v | 
=x_u y_v-x_v y_u
=\left| \begin{array}{cc} x_u & y_u \\ x_v & y_v \end{array} \right|
=\left| \begin{array}{cc} x_u & x_v \\ y_u & y_v \end{array} \right|
=\left| \frac{\partial (x,y)}{\partial (u,v)} \right|.
$$
::: 

::: {#exm- } 

Use a change of variables to evaluate the integral 
$$
\iint_R e^{(x+y)/(x-y)} \, dA,
$$
where $R$ is the trapezoidal region with vertices $(1,0),$ $(2,0),$ $(0,-2),$ and $(0,-1)$. 
::: 

::: {.solution }
 Since it is not easy to integrate $f(x,y)=e^{(x+y)/(x-y)},$ we make a change of variables suggested by the form of $f$ namely: $u=x+y$ and $v=x-y.$ Solving for $x$ and $y$
$$
x=\frac{1}{2}(u+v)\qquad \text{and} \qquad y=\frac{1}{2}(u-v)
$$  
to find the Jacobian is
$$
J(u,v)=\left|\! 
\begin{array}{cc}
1/2 & 1/2 \\
1/2 & -1/2
\end{array}
\! \right|=-\frac{1}{2}.
$$
To find the region $D$ in the $u v$-plane corresponding to $R$ we note that the sides of $R$ lie on the lines $y=0,$ $x-y=2,$ $x=0,$
$x-y=1$ and using the rules for the transformation, $x=(u+v)/2$ and $y=(u-v)/2$ the images of the lines in the $u v$-plane are
$u=v, v=2, u=-v ,$  and $v=1.$ 
Thus the region $D$ is the trapezoidal region with vertices $(1,1),$ $(2,2),$ $(-2,2)$ and $(-1,1);$ that is
$$
D=\{(u,v)|1\leq v\leq 2, -v\leq u\leq v\}.
$$
Therefore we can evaluate the integral as follows
\begin{align*}
\iint_R e^{(x+y)/(x-y)} \, dA 
& =\iint_D  e^{u/v} \left(\frac{1}{2}\right) \, dA 
\\
&=\int _1^2\int _{-v}^ve^{u/v}\left(\frac{1}{2}\right) \, du \, dv 
\\
& =\frac{1}{2}\int _1^2\left(e-e^{-1}\right)v dv 
=\frac{3}{4}\left(e-e^{-1}\right).
\end{align*}
::: 

::: {#exm- } 

Use a change of variables to evaluate the integral 
$$
\iint_R 3 x y \, dA
$$ 
where $R$ is the region bounded by the lines $x-2y=0,$ $x-2y=-4,$ $x+y=4,$ and $x+y=1$. 
::: 

::: {.solution }
 Let $u=x+y$ and $v=x-2y.$ 
 Then solving for $x$ and $y$ produces $x=\frac{1}{3}(2u+v)$ and $y=\frac{1}{3}(u-v).$ 
 The Jacobian of $u$ and $v$ is 
$$
J(u,v)=\left|\! 
\begin{array}{cc}
 \frac{2}{3} & \frac{1}{3} \\
 \frac{1}{3} & \frac{-1}{3}
\end{array}
\! \right|=\left(\frac{2}{3}\right)\left(\frac{-1}{3}\right)-\left(\frac{1}{3}\right)\left(\frac{1}{3}\right)=-\frac{1}{3}.
$$
The bounds under the transformation determined by the following equations
\begin{align*}
& x+y =1 \Longrightarrow u=1 &  x+y =4 \Longrightarrow u=4 \\
&  x-2y =0 \Longrightarrow  v =0 &  x-2y =-4 \Longrightarrow  v=-4\end{align*}
We consider the region $D$ in the $u v$-plane as vertically simple. Then it  follows 
\begin{align*}
\iint_R 3 x y \, dA 
& =\iint_D 3 \frac{1}{3}(2u+v) \frac{1}{3}(u-v)\, |J(u,v)| \, dv \, du 
\\
& =\int _1^4\int _{-4}^0\frac{1}{3}\left(2u^2-u v-v^2\right)\left|-\frac{1}{3}\right| \, dv \, du 
\\
& =\int _1^4\int _{-4}^0\frac{1}{9}\left(2u^2-u v-v^2\right) dv du 
\\
& =\int_1^4 \frac{1}{9} \left(8 u^2+8 u-\frac{64}{3}\right) \, du  
=\frac{164}{9}.
\end{align*}
::: 

::: {#exm- } 
Use a change of variables to evaluate the integral 
$$
\iint_R (x+y)^2\sin ^2(x-y)\, dA,
$$
where $R$ is the region bounded by the square with vertices $(0,1),$ $(1,2),$ $(2,1),$ and $(1,0).$
::: 

::: {.solution }
 The region $R$ is bounded by the lines $x-y=1,$ $x-y=-1,$ $x+y=1,$ and $x+y=3.$ Let $u=x+y$ and $v=x-y,$ then solving
for $x$ and $y$ produces 
$x=\frac{1}{2}(u+v)$ and $y=\frac{1}{2}(u-v).$ 
The Jacobian of $u$ and $v$ is
$$
J(u,v)=\left|\! 
\begin{array}{cc}
1/2 & 1/2 \\
1/2 & -1/2
\end{array}
\! \right|=\left(\frac{1}{2}\right)\left(\frac{-1}{2}\right)-\left(\frac{1}{2}\right)\left(\frac{1}{2}\right)=-\frac{1}{2}.
$$
The bounds under the transformation determined by the following equations
\begin{align*}
&  x+y=1  \Longrightarrow  u=1 &  x+y=3  \Longrightarrow  u=3 \\
&  x-y=-1  \Longrightarrow  v=-1 &  x-y=1 \Longrightarrow  v=1
\end{align*}
Let's consider the region $D$ in the $u v$-plane as horizontally simple. It follows 
\begin{align*}
\iint_R (x+y)^2\sin ^2(x-y) \, dA 
& =\iint_D u^2 \sin ^2v |J(u,v)| \, du \, dv 
\\
&=\frac{1}{2}\int _{-1}^1\int _1^3u^2 \sin ^2(v) \, du \, dv 
\\
& =\frac{1}{2}\int_{-1}^1 \frac{26 \sin ^2(v)}{3} \, dv 
=\frac{13}{6} (2-\sin 2).
\end{align*}
::: 

::: {#exm- } 
Use a change of variables to evaluate the integral 
$$
\iint_R y^3(2x-y)\cos (2x-y) \, dy \, dx.
$$
where $R$ is the region bounded by the parallelogram with vertices $(0,0),$ $(2,0),$ $(3,2),$ and $(1,2).$
::: 

::: {.solution }
 The boundary lines of the parallelogram are $y=0,$ $y=2,$ $y=2x,$ and $y=2x-4.$ Let $u=2x-y$ and $v=y$ with boundary lines $u=0,$ $u=4,$ $v=0,$ and $v=2.$ Solving for $x$ and $y$ produces $x=\frac{1}{2}(u+v)$ and $y=v.$  Since the Jacobian is
$$
J(u,v)=\left|
\begin{array}{cc}
1/2 & 1/2 \\
 0 & 1
\end{array}
\right|=\frac{1}{2},
$$
we evaluate the integral as follows
\begin{align*}
&\iint_D y^3(2x-y)\cos (2x-y) \, dy \, dx
=\int _0^4\int _0^2v^3u \cos (u)\frac{1}{2} \, dv \, du \\
&\quad =\int_0^4 2 u \cos (u) \, du 
=-2+2 \cos (4)+8 \sin (4).
\end{align*} 
::: 

::: {#exm- } 
Use a change of variables to evaluate the integral 
$$
\iint_R \left(x^4-y^4\right)e^{x y} \, dA
$$
where $R$ is the region bounded by the hyperbolas $x y=1,$ $x y=2,$ $x^2-y^2=1,$ and $x^2-y^2=4.$
::: 

::: {.solution }
 Let $u=x y$ and $v=x^2-y^2.$ Then
$$
\frac{\partial (u,v)}{\partial (x,y)}=\left|
\begin{array}{cc}
 y & x \\
 2x & -2y
\end{array}
\right|=-2y^2-2x^2=-2(x^2+y^2).
$$
Notice 
% $v^2=\left(x^2-y^2\right)^2=x^4-2x^2y^2+y^4$ we have
$$
\left(x^2+y^2\right)^2
=x^4-2x^2y^2+y^4+4x^2y^2
=v^2+4u^2.
$$
Thus
$x^2+y^2=\sqrt{v^2+4u^2}$
and so
$J(u,v)=\frac{-1}{2\sqrt{v^2+4u^2}}.$
We will make use of  
$$
\frac{\partial  (u,v)}{\partial (x,y)}\frac{\partial  (x,y)}{\partial (u,v)}=1
$$ 
because it is easier not to solve for $x$ and $y$ in terms of $u$ and $v.$ 
So we evaluate the integral as follows
\begin{align*}
\iint_R\left(x^4-y^4\right)e^{x y} \, dA 
& =\int _1^4\int _1^2e^uv\sqrt{v^2+4u^2}\left|\frac{-1}{2\sqrt{v^2+4u^2}} \right|dudv 
\\
& =\frac{1}{2}\int _1^4\int _1^2v e^u \, du \, dv
\\
& =\frac{1}{2}\int_1^4 \left(-e+e^2\right) v \, dv 
=\frac{15}{4}e(e-1).
\end{align*}
::: 

::: {#exm- } 
Use a change of variables to evaluate the integral 
$$
I=\iint_R \ln \left(\frac{x-y}{x+y}\right) \, dy \, dx
$$
where $R$ is the triangular region bounded by the vertices $(1,0),$ $(4,-3),$ $(4,1)$
::: 

::: {.solution }
 Let $u=x-y$ and $v=x+y$ so that $x=\frac{1}{2}(u+v)$ and $y=\frac{-1}{2}u+\frac{1}{2}.$ 
 Then the Jacobian is 
$$
J(u,v)=\left|
\begin{array}{cc}
1/2 & 1/2 \\
-1/2 & 1/2
\end{array}
\right|=\frac{1}{2}.
$$
The given the region $R$ is bounded by the lines $x-3y=1,$ $x+y=1,$ and $x=4$ which transform into $2u-v=1,$ $v=1,$ and $u+v=8.$ Therefore we evaluate the integral as follows,
\begin{align*}
I& =\frac{1}{2}\int _1^5\int _{(v+1)/2}^{8-v}\ln \left(\frac{u}{v}\right)du dv 
\\
&=\frac{1}{4}\int_1^5 \left[-(v+1)\ln \left(\frac{v+1}{2v}\right)+2(8-v)\ln \left(\frac{8-v}{v}\right)+3(v-5)\right] \, dv 
\\
&=\frac{1}{4}\left(49\ln  7-\frac{75}{2}\ln  5-27\ln  3+6\right). 
\end{align*}
::: 

::: {#exm- } 
Use a change of variables to evaluate the integral 
$$
I=\iint_D\exp \left(-\frac{x^2}{a^2}-\frac{y^2}{b^2}\right) \, dy \, dx,
$$
where $D$ is the region bounded by the quarter ellipse $\frac{x^2}{a^2}+\frac{y^2}{b^2}=1,$ in the first octant.
::: 

::: {.solution }
 Let's try the change of variables 
$x=a r \cos  \theta$ and $y=b r \sin  \theta$ 
with $0\leq  r<\infty$ and $0\leq  \theta <2\pi ;$ to see if we can simply the region of integration and the integrand. Notice 
$$
-\frac{x^2}{a^2}-\frac{y^2}{b^2}=-\left[\frac{x^2}{a^2}+\frac{y^2}{b^2}\right]=-\left[\frac{(a r \cos  \theta )^2}{a^2}+\frac{(b r \sin 
\theta )^2}{b^2}\right]=-r^2
$$ 
using $\sin ^2\theta +\cos ^2\theta =1.$ Further the region of becomes $r^2=1$ or $r=1$ which is the circle of radius 1. We wish to use  
$$
\iint_D f(x,y)dx\, dy=\iint_R f(x(u,v),y(u,v)) |J(u,v)| \, du \, dv
$$ 
so we compute the Jacobian, 
$$
J(r,\theta )=\left|
\begin{array}{cc}
 a \cos  \theta  & -a \text{rsin} \theta \\
 b \sin  \theta  & b r \cos  \theta 
\end{array}
\right|=a b r \cos  \theta +a b r \sin ^2\theta =a b r.
$$ 
Now then we have, 
\begin{align*}
I& =\int _0^{\pi /2}\int _0^1e^{-r^2}|a b r| \, dr \, d\theta
=\int _0^{\pi /2}\int _0^1e^{-r^2}a b r \, dr \, d\theta \\ 
&  =\int_0^{\pi /2} a b \left(\frac{1}{2}-\frac{1}{2 e}\right) \, d\theta 
=\frac{a b \pi }{4}\left(1-e^{-1}\right).
\end{align*}
::: 

::: {#exm- } 
Use a change of variables to evaluate the integral 
$$
\iint_D \left(\frac{x-y}{x+y}\right)^4 \, dy \, dx,
$$
where $D$ be the region in the $x y$-plane that is bounded by the coordinate axes and the line $x+y=1$ 
::: 

::: {.solution }
 The region is transformed into $0\leq v\leq 1$ and $-v\leq u\leq v$ and so 
$$
\iint_R \left(\frac{x-y}{x+y}\right)^4 \, dy \, dx
=\int _0^1\int _{-v}^v\frac{u^4}{v^4}\left(\frac{1}{2}\right) \, du \, dv
=\int_0^1 \frac{v}{5} \, dv
=\frac{1}{10}.
$$
::: 
  
::: {#exm- } 
Use integration and a change of variables determine the area of an ellipse
::: 

::: {.solution }
 Assume the ellipse is given in standard form by 
$$
\left(\frac{x}{a}\right)^2+\left(\frac{y}{b}\right)^2=1.
$$ 
 Let $u=\frac{x}{a}$ and $v=\frac{y}{b},$ then the ellipse in the $x y$-plane corresponds to the unit circle $u^2+v^2=1$ in the $u v$-plane. Since $x=a u$ and $y=b v,$ the Jacobian is 
%$\left| \begin{array}{cc} a & 0 \\ 0 & b \end{array}\right|=$
$a b$ and so the area of an ellipse is given by 
\begin{align*}
A&=4\int _0^a\int_0^{b \sqrt{1-x^2/a^2}} dy \, dx 
=4\int _0^1\int _0^{ \sqrt{1-u^2}}a b dv du 
%=ab 4\int _0^1\int _0^{ \sqrt{1-u^2}} dv du 
% \\ & =4\int_0^1 a b \sqrt{1-u^2} \, du 
= a b \pi\end{align*}
since $\pi$ is the area of the unit circle. 
::: 

::: {#exm- } 
A rotation of the $x y$-plane through the fixed angle $\theta$ is given by  
$$
x=u \cos\theta -v \sin  \theta 
\qquad \text{and} \qquad 
y=u \sin  \theta +v \cos  \theta 
$$
Compute the Jacobian $\frac{\partial (x,y)}{\partial (u,v)}.$ Let $E$ denote the region bounded by the ellipse $x^2+x y+y^2=3.$ Use a rotation of $\pi /4$ to obtain an integral that is equivalent to  
$$
\iint_E y \, dy \, dx.
$$
Evaluate the transformed integral. 
::: 

::: {.solution }
We find $J(u,v)=1$ and so $dx\, dy=du\, dv.$ A rotation of $\frac{\pi }{4}$ eliminates the $u v$-term so we use the transformation  
$$
x=\frac{\sqrt{2}}{2}(u-v)
\qquad \text{and}\qquad 
y=\frac{\sqrt{2}}{2}(u+v)
$$
Then $x^2+x y+y^2$ becomes $\left(\frac{u}{\sqrt{2}}\right)^2+\left(\frac{v}{\sqrt{6}}\right)^2=1.$ Therefore,  
\begin{align*}
\iint_E y \, dy \, dx
& =4\int _0^{\sqrt{2}}\int _0^{\sqrt{6-3u^2}}\frac{\sqrt{2}}{2}(u+v)(1)\, dv \, du \\
& =4\int_0^{\sqrt{2}} \frac{-\frac{3 u^2}{2}+\sqrt{6-3 u^2} u+3}{\sqrt{2}} \, du 
=8+\frac{8}{\sqrt{3}}=\frac{8\sqrt{3}+8}{\sqrt{3}} 
% \\ & 
%=\frac{24+8\sqrt{3}}{3}=\frac{8}{3}\left(3+\sqrt{3}\right)
%\approx 12.6188.
\end{align*}
::: 
  

## Change of Variable in a Triple Integral

::: {#thm- } [Change of Variable in a Triple Integral]
Let $f$ be a continuous function on a region $R$ in the $x y z$-space, and let $T$ be a one-to-one transformation that maps the region $D$ in the $u v w$-space onto $R$ under the change of variables $x=x(u,v,w),$ $y=y(u,v,w),$ and $z=z(u,v,w)$ where functions $x,$ $y,$ and $z$ are continuously differentiable functions on $D.$ If $J(u,v,w)\neq 0,$ then
\begin{align*}
& \iiint_Rf(x,y,z) \, dx \, dy \, dz 
\\
& \qquad = \iiint_D f(x(u,v,w),y(u,v,w),z(u,v,w)) \left|J(u,v,w)\right| \, du \, dv \, dw.
\end{align*}
::: 


::: {#exm- } 

Use integration and a change of variables the volume of an ellipsoid
::: 

::: {.solution }
 Assume the ellipsoid is given in standard form by 
$$
\left(\frac{x}{a}\right)^2+\left(\frac{y}{b}\right)^2+\left(\frac{z}{c}\right)^2=1.
$$
Let $u=\frac{x}{a},$ $v=\frac{y}{b},$ and $w=\frac{z}{c}$ then the ellipsoid corresponds to the unit sphere $u^2+v^2+w^2=1.$ Since $x=a
u,$ $y=b v,$ $z=c w,$ the Jacobian is $a b c$ 
$$
J(u,v,w)=\left| \begin{array}{ccc}  a & 0 & 0 \\  0 & b & 0 \\  0 & 0 & c \end{array} \right|=a b c 
$$
and so the volume of an ellipsoid is given by
\begin{align*}
V & = 8\int _0^a\int _0^{ \sqrt{1-x^2/a^2}}\int _0^{ \sqrt{1-x^2/a^2-y^2/b^2}} \, dz \, dy \, dx 
\\
& =8\int _0^1\int _0^{ \sqrt{1-u^2}}\int _0^{ \sqrt{1-u^2-v^2}}a b c \, dw \, dv \, du 
= \frac{4}{3}a b c \pi .
\end{align*}
::: 

## Exercises

In Exercises \ref{jst}-\ref{jfn}, find the Jacobian of the change of variables.

::: {#exr- } 
\label{jst}
$x=u^2$ and $y=u+v$ 
::: 

::: {#exr- } 
$x=u \cos v$ and $y=u \sin  v$ 
::: 

::: {#exr- } 
$x=\frac{u}{v},$ $y=\frac{v}{w},$ and $z=\frac{w}{u}$
::: 

::: {#exr- } 
$u=y e^{-x}$ and $v=e^x$
::: 

::: {#exr- } 
$u=\frac{x}{x^2+y^2}$ and $v=\frac{y}{x^2+y^2}$
::: 

::: {#exr- } 
\label{jfn}
\begin{minipage}[t]{.4\textwidth}
$x=u+v-w,$ $y=2u-v+3w,$ and $z=-u+2v-w$ 
\end{minipage}
::: 

In Exercises \ref{cvst}-\ref{cvfn}, use a change of variables to compute the following integrals.

::: {#exr- } 
\label{cvst}
$\iint_D \left(\frac{x-y}{x+y}\right)^5 \, dy \, dx$
where $D$ is the region in the $x y$-plane bounded by the coordinate axes and the line $x+y=1$ 
::: 

::: {#exr- } 
$\iint_D(x-y)e^{x^2+y^2} \, dy \, dx$
where $D$ is the region in the $x y$-plane bounded by the coordinate axes and the line $x+y=1$
::: 

::: {#exr- } 
$\iint_D\left(\frac{2x+y}{x-2y+5}\right)^2 \, dy \, dx$
where $D$ is the square in the $x y$-plane with vertices $(0,0),$ $(1,-2),$ $(3,-1),$ and $(2,1)$ 
::: 

::: {#exr- } 
$\iint_D\sqrt{(2x+y)(x-2y)} \, dy \, dx$
where $D$ is the square in the $x y$-plane with vertices $(0,0),$ $(1,-2),$ $(3,-1),$ and $(2,1)$ 
::: 

::: {#exr- } 
$\iint_D e^{(2y-x)(y+2x)} \, dA$
where $D$ is the trapezoid with vertices $(0,2),$ $(1,0),$ $(4,0),$ and $(0,8)$ 
::: 

::: {#exr- } 
\label{cvfn}
$\iint_Ry^3(2x-y)\cos (2x-y)\, dy \, dx$
where $D$ is the region bounded by the parallelogram with vertices $(0,0),$ $(2,0),$ $(3,2),$ and $(1,2)$
::: 

::: {#exr- } 
Under the change of variables $x=s^2-t^2,$ $y=2s t,$ the quarter circle region in the $s t$-plane given by $s^2+t^2\leq 1,$ $s\geq 0,$ $t\geq 0$ is mapped onto a certain region $D$ of the $x y$-plane. Evaluate 
$$
\iint_R\frac{1}{\sqrt{x^2+y^2}} \, dy \, dx.
$$
::: 

::: {#exr- } 
A rotation of the $x y$-plane through the fixed angle $\theta$ is given by 
$x=u \cos \theta -v \sin  \theta$ and $y=u \sin  \theta +v \cos  \theta.$
Determine the Jacobian 
$J(u,v).$ 
Let $E$ denote the region bounded by the ellipse $x^2+x  +y^2=3.$ Use a rotation of $\pi /4$ to obtain an integral that is equivalent to
$$
\iint_E y \, dy \, dx.
$$
Evaluate the transformed integral.
::: 




