# Learning Linear Algebra

project:
  type: book
  resources: 
    - assets
    - images
  post-render: 
    - ../_webtools/html_revise_lla.py

book:
  title: "Learning Linear Algebra"
  chapters:
    - index.qmd
    - systems-of-linear-equations.qmd
    - vector-spaces.qmd
    - linear-transformations.qmd
    - inner-products-spaces.qmd
    - determinants.qmd
    - eigenvalues-and-eigenvectors.qmd
    - canonical-forms.qmd
    - references.qmd
  sidebar:
    title: "Learning Linear Algebra"
  site-url: https://directknowledge.com/learning-linear-algebra/
  description: "Learning Linear Algebra"
  isbn: "978-1-951290-04-7"

metadata-files:
  - ../_variables.yml
  - ../_meta/book-html.yml
  - ../_meta/format.yml
  #- _meta/_book-epub.yml
  #- _meta/_book-hardcover.yml
  - _meta/_book-paperback.yml

