---
pagetitle: "Finite-dimensional Linear Spaces - Learning Linear Algebra"
---
# Finite-dimensional Linear Spaces

::: {#def- } 
The vector space $V$ is a \index{direct sum} **direct sum** of subspaces $\vlist{U}{m}$ of $V$, written 
$V=U_{1} \oplus  \cdots \oplus U_{m}$, if each element of $V$ can be written uniquely as a sum $u_1 + u_2+\cdots + u_m$ where each $u_j\in U_j$.
::: 

::: {#lem- } 
If $\vlist{U}{m}$ are subspaces of $V$, then $V=U_{1} \oplus \cdots \oplus U_{m}$ if and only if both conditions hold:
 
- $V=U_{1} + \cdots + U_{m}$.
- the only way to write $0$ as a sum  $u_{1} + u_{2}+\cdots+ u_{m}$ where each  $u_{j} \in U_{j}$, is by taking all the $u_{j}$'s equal to $0$.
 
:::  

::: {.proof } 
If $V=U_{1} \oplus U_2 \oplus \cdots \oplus U_{m}$, then every element in $V$ can be written uniquely in the form $u_1+ u_2+\cdots +u_m$ where each $u_j\in U_j$ for $1\leq i \leq m$. 
Thus both conditions listed above are satisfied. 
Conversely, suppose both conditions hold and assume $u=u_1  + \cdots +u_m$ where 
$u_i \in U_i$ and $u=v_1  + \cdots + v_m$ where $v_i\in U_i$. 
Since 
$$
u-u=(u_1 + \cdots +u_m)-(v_1 + \cdots +v_m)=(u_1-v_1)+\cdots +(u_m-v_m)=0
$$ 
it follows $u_i=v_i$ for $1\leq i \leq m$; and so uniqueness is established.
::: 

::: {#exm- } 
Let $V$ be the linear space of all functions from $\mathbb{R}$ to $\mathbb{R}$ and let $V_e$ and $V_o$ be the set of all even functions ($f(-x)=f(x)$) and the set of odd functions ($f(-x)=-f(x)$), respectively. 

- Prove that $V_e$ and $V_o$ are subspaces of $V$.
- Prove that $V_e+V_o=V$
- Prove that $V_e\cap V_o=\{0\}$.
::: 

::: {#lem- } 
If $U$ and $W$ are subspaces of $V$, then $V=U \oplus W$ if and only if $V=U+W$ and $U \cap W= \{0\}$.
:::  

::: {.proof } 
If  $V=U \oplus W$ then $V=U+W$ and $\{0\} \subseteq U\cap W$ are immediate. Suppose $v\in U \cap W$. Since $v\in U \oplus W$, there exists unique $u\in U$ and $w\in W$ such that $v=u+w$. Assume for a contradiction, $u\not = 0$. Then $u=u+0$ where $0\in W$ and $u \in U$ shows that $u\not \in W$ since $V=U\oplus W$. Also, $v=u+w\in U\cap W$ so $u+w\in W$ and $w\in W$ implies $u\in W$. This contradiction leads to $u=0$. Similarly, $w=0$ and so $v=u+w=0$ which yields $U \cap W= \{0\}$. Conversely, suppose $V=U+W$ and $U \cap W= \{0\}$. If $0=u+w$ then $u=-w\in W$ and together with $u\in U$ yields $u=0$. Thus, $w=0$ also. So the only way to write 0 as a sum $u+w$ is to have $u=w=0$ therefore  $V=U \oplus W$.
::: 

::: {#exm- } 
Prove or give a counterexample: if $U_1, U_2$, and $W$ are subspaces of $V$ such that $U_1 +W=U_2+W$, then $U_1=U_2$. 
False, here is a counterexample. Let $V=\mathbb{R}^2=W$ with $U_1=\{(x,0) \mid x \in \mathbb{R}\}$ and $U_2=\{(0,y) \mid y\in \mathbb{R}\}$. Then $U_1+W=U_2+W=\mathbb{R}^2$. However, $U_1\neq U_2$.

::: 

::: {#exm- } 
Prove or give a counterexample: if $U_1, U_2, W$ are subspaces of $V$ such that $V=U_1 \oplus W$ and $V=U_2 \oplus W$, then $U_1=U_2$.
False, here is a counterexample.  Let $V=\mathbb{R}^2$ with $W=\{(x,x) \mid x\in \mathbb{R}\}$, $U_1=\{(x,0) \mid x \in \mathbb{R}\}$, and $U_2=\{(0,y) \mid y\in \mathbb{R}\}$. All of these sets are subspaces. Let $u\in U_1\cap W$, then $u=(x,0)$ and $u=(z,z)$ so $z=0$ and $x=0$ which implies $u=(0,0)$. In fact $U_1\cap W=\{0\}$. Thus, $\mathbb{R}^2=U_1\oplus W$. Also $\mathbb{R}^2=U_2\oplus W$. However, $(1,0)\in U_1$ and $(1,0)\not \in U_2$ showing $U_1\neq U_2$.

::: 

::: {#exm- } 
Suppose $m$ is a positive integer. Is the set consisting of 0 and all polynomials with coefficients in $F$ and with degree equal to $m$ a subspace of $\mathcal{P}(\mathbb{F})$?
::: 

::: {#def- } 
We call a linear space $V$ a \index{finite-dimensional linear space} **finite-dimensional linear space** if there is a finite list of vectors $(v_1, \ldots, v_m)$ with $\text{span}(v_1, \ldots, v_m)=V.$ If a linear space is not a finite-dimensional vector space it is called an \index{infinite-dimensional vector space} **infinite-dimensional vector space**.
::: 

::: {#lem- } 
\label{Linearly Independent List of Vectors}
Let $V$ be a finite-dimensional vector space. Then
the length of every linearly independent list of vectors in $V$ is less than or equal to the length of every spanning list of vectors in $V$.
:::  

::: {.proof } 
::: 

::: {#lem- } 
Let $V$ be a finite-dimensional vector space. Then
$V$ only has finite-dimensional subspaces.
:::  

::: {.proof } 
::: 

::: {#thm- } 
\label{basisspacethm}
Let $V$ be a finite-dimensional vector space. Then 
every spanning list $(v_1,\ldots,v_m)$ of a vector space can be reduced to a basis of the vector space, 
:::  

::: {.proof } 
::: 

::: {#thm- } 
Let $V$ be a finite-dimensional vector space. Then 
if $V$ is finite-dimensional then $V$ has a basis.
:::  

::: {.proof } 
By definition, every finite-dimensional vector space has a finite spanning set. By \ref{spanning reduce lemma}, every spanning set can be reduced to a basis, and so every finite-dimensional vector space does indeed have a basis.
::: 

::: {#thm- } 
Let $V$ be a finite-dimensional vector space. Then 
if $W$ is a subspace of $V$, every linearly independent subset of $W$ is finite and is part of a finite basis for $W$. 
:::  

::: {.proof } 
::: 

::: {#thm- } 
Let $V$ be a finite-dimensional vector space. Then  every linearly independent list of vectors in $V$ can be extended to a basis of $V$,
:::  

::: {.proof } 
::: 

::: {#thm- } 
Let $V$ be a finite-dimensional vector space. Then 
if $U$ is a subspace of $V$, then there is a subspace $W$ of $V$ such that $V=U \bigoplus  W$, and
:::  

::: {.proof } 
::: 

::: {#thm- } 
Let $V$ be a finite-dimensional vector space. Then 
any two bases of $V$ have the same length.
:::  

::: {.proof } 
::: 

::: {#def- } 
The \index{dimension} **dimension**  of a finite-dimensional vector space is defined to be the length of any basis of the vector space.
::: 

::: {#thm- } 
Let $V$ be a finite-dimensional vector space. Then 
if $U$ is a subspace of $V$ then $\text{dim} U \leq \text{dim} V$.
:::  

::: {.proof } 
::: 

::: {#thm- } 
Let $V$ be a finite-dimensional vector space. Then every spanning list of vectors in $V$ with length dim $V$ is a basis of $V$.
:::  

::: {.proof } 
::: 

::: {#thm- } 
Let $V$ be a finite-dimensional vector space. Then  every linearly independent list of vectors in $V$ with length dim $V$ is a basis of $V$.
:::  

::: {.proof } 
::: 

::: {#thm- } 
Prove that if $U_1$ and $U_2$ are subspaces of a finite-dimensional vector space, then
$$
\text{dim}  (U_1+U_2)= \text{dim}  U_1 + \text{dim}  U_2 -\text{dim}  (U_1 \cap U_2).
$$
::: 

::: {.proof }
::: 

::: {#thm- } 
If $V$ is finite-dimensional,  and $U_1, \ldots, U_m$ are subspaces of $V$ such that
 
- $V=U_1+\cdots+U_m$ and
- $\text{dim} V=\text{dim} U_1+\cdots+\text{dim} U_m$, 
 
then $V=U_1 \oplus \cdots \oplus U_m.$
:::  

::: {.proof } 
Choose a basis for each $U_j$. Put these bases together in one list, forming a list that spans $V$ and has length $\text{dim} (V)$. Thus this list is a basis of $V$ and in particular it is linearly independent. Now suppose that $u_j\in U_j$ for each $j$ are such that $0=u_1+\cdots + u_m$. We can write each $u_j$ as a linear combination of the basis vectors of $U_j$. Substituting these expressions above, we have written $0$ as a linear combination of the basis vectors of $V$. Thus all scalars used in the linear combinations must be zero. Thus each $u_j=0$ which proves $V=U_1 \oplus \cdots \oplus U_m.$
::: 


