---
pagetitle: "Gram-Schmidt Process and QR Factorization - Learning Linear Algebra"
---
# Gram-Schmidt Process and QR Factorization

The Gram-Schmidt process represents a change of basis from a basis $\mathcal{B}=(\vec v_1, \vec v_2, ..,,\vec v_m)$ of a subspace $V$ of $\mathbb{R}^n$ to an orthonormal basis $\mathcal{U}=(\vec u_1, \vec u_2, \ldots,\vec u_m)$ of $V$; it is most sufficiently described in terms of the change of basis matrix $R$ from $\mathcal{B}$ to $\mathcal{U}$ via,
\begin{equation}
M:=\begin{bmatrix} \vec v_1 & \vec v_2 & \cdots & \vec v_m \end{bmatrix}
=\begin{bmatrix} \vec u_1 &\vec u_2 & \cdots & \vec u_m \end{bmatrix}R=:QR
\end{equation}

::: {.content-hidden }
We can represent the relationship among the matrices $M, Q$, and $R$ in a commutative diagram:
$$
\xymatrix{
[\vec x]_{\, \mathcal{U}} \ar[dd]_R  \ar[rd]^Q & \\
& \vec x \\
[\vec x]_{\, \mathcal{B}}  \ar[ru]_M  &
}
$$
:::

The $QR$ factorization is an effective way to organize and record the work performed in the Gram-Schmidt process; it is also useful for many computational and theoretical purposes. 

::: {#thm- } 

## Gram-Schmidt Process
Let $\vec v_1, \vec v_2, \ldots, \vec v_m$ be a basis of a subspace $V$ of $\mathbb{R}^n$. 
Then
\begin{equation}
\begin{array}{cccc}
\vec u_1 = \frac{1}{||\vec v_1 || } \vec v_1,  &
\vec u_2 = \frac{1}{||\vec v_2^\perp || } \vec v_2^\perp, & \ldots, &
 \vec u_m = \frac{1}{||\vec v_m^\perp || } \vec v_m^\perp
\end{array}
\end{equation}
is an orthonormal basis of $V$ where
\begin{equation}
\vec v_j ^\perp 
= \vec v_j - \vec v_j^\parallel 
= \vec v_j - (\vec u_1 \cdot \vec v_j) \vec u_1 - (\vec u_2 \cdot \vec v_j) \vec u_2 - \cdots - (\vec u_{j-1} \cdot \vec v_j) \vec u_{j-1}.
\end{equation}
::: 

::: {.proof }
For each $j$, we resolve the vectors $\vec v_j$ into its components parallel and perpendicular to the span of the preceding vectors $\vec v_1, \vec v_2, \ldots, \vec v_{j-1}$:
$$\vec v_j = \vec v_j^\parallel + \vec v_j^\perp \hspace{1cm} \text{with respect to } \text{span}(\vec v_1, \vec v_2, \ldots, \vec v_{j-1}).$$
Then use \ref{Orthogonal Projection}.
::: 

::: {#exm- } 
Perform the Gram-Schmidt process on the vectors 
$$
\vec v_1=\vectorthree{4}{0}{3}, \qquad
\vec v_2=\vectorthree{25}{0}{-25}, \qquad
\vec v_3=\vectorthree{0}{-2}{0}.
$$
By Theorem \eqref{Gram-Schmidt Process},  we determine $\vec u_1, \vec u_2, \vec u_3$ as follows:
$$
\vec u_1= \vectorthree{4/5}{0}{3/5}, 
\hspace{1cm}
\vec u_2=\frac{\vec v_2^\perp}{\norm{\vec v_2^\perp}}
=\frac{\vec v_2-\left(\vec u_1 \cdot \vec v_2\right) \vec u_1}{\norm{\vec v_2-\left(\vec u_1 \cdot \vec v_2\right)\vec u_1}}
=\vectorthree{3/5}{0}{-4/5},
$$
and
$$
\vec u_3=\frac{v_3^\perp}{\norm{v_3^\perp}}
=\frac{\vec v_3-\left(\vec u_1 \cdot \vec v_3\right) \vec u_1-\left(\vec u_2 \cdot \vec v_3\right) \vec u_2}{\norm{\vec v_3-\left(\vec u_1 \cdot \vec v_3\right) \vec u_1-\left(\vec u_2 \cdot \vec v_3\right) \vec u_2}}
=\vectorthree{0}{-1}{0}.
$$
Therefore 
$$
\left( \vectorthree{4/5}{0}{3/5},  \vectorthree{3/5}{0}{-4/5}, \vectorthree{0}{-1}{0}\right).
$$
is an orthonormal basis for $\text{span} (\vec v_1, \vec v_2, \vec v_3)$. 
::: 

::: {#thm- } [QR Factorization]
Let $M$ be an $n \times m$ matrix with linearly independent columns $\vec v_1 , \vec v_2, \ldots,\vec v_m$. 
Then there exists an $n\times m$ matrix $Q$ whose columns $\vec u_1, \vec u_2, \ldots, \vec u_m$ are orthonormal and an upper triangular matrix $R$ with positive diagonal entries such that $M=Q R$; and this representation is unique. 
Furthermore, the entries $r_{ij}$ of $R$ are given by
 
- $r_{11}=\norm{\vec v_1}$, 
- $r_{jj}=||\vec v_j^\perp||$ (for $j=2,\ldots,m$), and 
- $r_{i j}=\vec u_i \cdot \vec v_j$ (for $i<j$).
::: 

::: {.proof }
The proof is left for the reader.
::: 

::: {#exm- } 
Find the $QR$ factorization of the matrix and display the commutative diagram.
$$
M=\begin{bmatrix} 4 & 25 & 0 \\ 0 & 0 & -2 \\ 3 & -25 & 0\end{bmatrix}
$$
Let 
$$
\begin{array}{ccc}
\vec v_1=\vectorthree{4}{0}{3}, & 
\vec v_2=\vectorthree{25}{0}{-25}, & 
\vec v_3=\vectorthree{0}{-2}{0}
\end{array}
$$
then (as determined above) an orthonormal basis for the column vectors of $M$ is  
$$\left(\vec u_1, \vec u_2, \vec u_3\right)=\left( \vectorthree{4/5}{0}{3/5},  \vectorthree{3/5}{0}{-4/5}, \vectorthree{0}{-1}{0}\right).$$
Determining the entries of $R$ (also as determined above):
$$
\begin{array}{ccc}
r_{11}=\norm{\vec v_1}=5, &
r_{22}=\norm{\vec v_2^\perp}=35, &
r_{33}=\norm{\vec v_3^\perp}=2
\end{array}
$$
$$
\begin{array}{ccc}
r_{12}=\vec u_1 \cdot \vec v_2=5, &
r_{13}=\vec u_1 \cdot \vec v_3=0, &
r_{23}=\vec u_2 \cdot \vec v_3=0
\end{array}
$$
and therefore, the $QR$-factorization of $M$ is
$$
M= \begin{bmatrix} 4 & 25 & 0 \\ 0 & 0 & -2 \\ 3 & -25 & 0\end{bmatrix}
= \begin{bmatrix}4/5 & 3/5 & 0 \\ 0 & 0 & -1 \\ 3/5 & -4/5 & 0 \end{bmatrix}
\begin{bmatrix}5 & 5 & 0 \\ 0 & 35 & 0 \\ 0 & 0 & 2\end{bmatrix}
=QR.
$$
::: 


::: {.content-hidden }
The commutative diagram is:
$$
\xymatrix{
[\vec x]_{\, \mathcal{U}} \ar[dd]_{R=\begin{bmatrix}5 & 5 & 0 \\ 0 & 35 & 0 \\ 0 & 0 & 2\end{bmatrix} \qquad}  \ar[rd]^{Q=\begin{bmatrix}4/5 & 3/5 & 0 \\ 0 & 0 & -1 \\ 3/5 & -4/5 & 0 \end{bmatrix}} & \\
& \vec x \\
[\vec x]_{\, \mathcal{B}}  \ar[ru]_{M=\begin{bmatrix} 4 & 25 & 0 \\ 0 & 0 & -2 \\ 3 & -25 & 0\end{bmatrix}}  &
}
$$
::: 

::: {#exm- } 
(a) Perform the Gram-Schmidt process on the vectors 
$$
\vec v_1=\vectorfour{1}{7}{1}{7}, \qquad
\vec v_2= \vectorfour{0}{7}{2}{7}, \qquad
\vec v_3 = \vectorfour{1}{8}{1}{6}.
$$
(b) Find the $QR$ factorization of the matrix 
$M=\begin{bmatrix} \vec v_1 & \vec v_2 & \vec v_3\end{bmatrix}.$

By Theorem \eqref{Gram-Schmidt Process},  we determine $\vec u_1, \vec u_2, \vec u_3$ as follows:
$$
\vec u_1= \vectorfour{1/10}{7/10}{1/10}{7/10}, 
\vec u_2=\frac{\vec v_2^\perp}{\norm{\vec v_2^\perp}}
=\frac{\vec v_2-\left(\vec u_1 \cdot \vec v_2\right) \vec u_1}{\norm{\vec v_2-\left(\vec u_1 \cdot \vec v_2\right)\vec u_1}}
=\vectorfour{-1/\sqrt{2}}{0}{1/\sqrt{2}}{0},
$$
and
$$
\vec u_3=\frac{\vec v_3^\perp}{\norm{\vec v_3^\perp}}
=\frac{\vec v_3-\left(\vec u_1 \cdot \vec v_3\right) \vec u_1-\left(\vec u_2 \cdot \vec v_3\right) \vec u_2}{\norm{\vec v_3-\left(\vec u_1 \cdot \vec v_3\right) \vec u_1-\left(\vec u_2 \cdot \vec v_3\right) \vec u_2}}
=\vectorfour{0}{1/\sqrt{2}}{0}{-1/\sqrt{2}}.
$$
Therefore an orthonormal basis for $\text{span} (\vec v_1, \vec v_2, \vec v_3)$ is
$$
\left( \vectorfour{1/10}{7/10}{1/10}{7/10},  \vectorfour{-1/\sqrt{2}}{0}{1/\sqrt{2}}{0}, \vectorfour{0}{1/\sqrt{2}}{0}{-1/\sqrt{2}}\right).
$$
Determining the entries of $R$ (also as determined above):
$$
\begin{array}{ccc}
r_{11}=\norm{\vec v_1}=10, &
r_{22}=\norm{\vec v_2^\perp}=\sqrt{2}, &
r_{33}=\norm{\vec v_3^\perp}=\sqrt{2}
\end{array}
$$
$$
\begin{array}{ccc}
r_{12}=\vec u_1 \cdot \vec v_2=10, &
r_{13}=\vec u_1 \cdot \vec v_3=10, &
r_{23}=\vec u_2 \cdot \vec v_3=0
\end{array}
$$
and therefore, the $QR$-factorization of $M$ is
$$
M=\begin{bmatrix} 1 & 0 & 1 \\ 7 & 7 & 8 \\ 1 & 2 & 1 \\ 7 & 7 & 6 \end{bmatrix}
= \begin{bmatrix}1/10 & -1/\sqrt{2} & 0 \\ 7/10 & 0 & 1/\sqrt{2} \\ 1/10 & 1/\sqrt{2} & 0 \\ 7/10 & 0 & -1/\sqrt{2}\end{bmatrix}
\begin{bmatrix}10 & 10 & 10 \\ 0 & \sqrt{2} & 0 \\ 0 & 0 & \sqrt{2}\end{bmatrix}
=QR.
$$
::: 

::: {.content-hidden }
The commutative diagram is
$$
\xymatrix{
[\vec x]_{\, \mathcal{U}} \ar[dd]_{R=\begin{bmatrix}10 & 10 & 10 \\ 0 & \sqrt{2} & 0 \\ 0 & 0 & \sqrt{2}\end{bmatrix}\qquad}  \ar[rd]^{Q= \begin{bmatrix}1/10 & -1/\sqrt{2} & 0 \\ 7/10 & 0 & 1/\sqrt{2} \\ 1/10 & 1/\sqrt{2} & 0 \\ 7/10 & 0 & -1/\sqrt{2}\end{bmatrix}} & \\
& \vec x \\
[\vec x]_{\, \mathcal{B}}  \ar[ru]_{M=\begin{bmatrix} 1 & 0 & 1 \\ 7 & 7 & 8 \\ 1 & 2 & 1 \\ 7 & 7 & 6 \end{bmatrix}}  &
}
$$
:::

