---
pagetitle: "Infinite-dimensional Linear Spaces - Learning Linear Algebra"
---
# Infinite-dimensional Linear Spaces


::: {#exm- } 
Prove that $k^\infty$ is infinite-dimensional.
Suppose $\mathbb{F}^\infty$ is finite-dimensional with dimension $n$.  Let $v_i$ be the vector in $\mathbb{F}^\infty$ consisting of all 0's except with 1 in the $i$-th position for $i=1,...,n$. The vectors $(v_1,...,v_n)$ are linearly independent in $\mathbb{F}^\infty$ and so they must form a basis; however they do not span since the vector $v_{n+1}$ consisting of all 0's except with $1$ in the $(n+1)$-th position. Thus $\mathbb{F}^\infty$ can not be finite-dimensional. 

::: 

::: {#exm- } 
Prove that the real vector space consisting of all continuous real-valued functions on the interval $[0,1]$ is infinite-dimensional.
Notice that $f(x)=x^n$ is continuous on $[0,1]$ for every positive integer $n$. If this vector space is finite-dimensional of say dimension $n$ then the list of vectors $(1,x,x^2,...,x^{n-1})$ must form a basis since they are linearly independent and there are $n$ of them. However, $x^n$ is not in the span of this list and so this list can not be a basis. This contradiction shows that this vector space must be infinite-dimensional.

::: 

::: {#exm- } 
Prove that $V$ is infinite-dimensional if and only if there is a sequence $v_1, v_2,...$ of vectors in $V$ such that $(v_1, ..., v_n)$ is linearly independent for every positive integer $n$.
Suppose $V$ is infinite-dimensional. Then $V$ has no finite spanning list. Pick $v_1\neq 0$. For each positive integer $n$ choose $v_{n+1}\not \in \text{ span}(v_1,...,v_n)$, by the linear independence lemma, and for each positive integer $n$, the list $(v_1,...,v_n)$ is linearly independent. Conversely, suppose there is a sequence $v_1,v_2,...,$ of vectors in $V$ such that $(v_1,...,v_n)$ is linearly independent for every positive integer $n$. If $V$ is finite-dimensional, then it has a spanning list with $M$ elements. By the previous theorem, every linearly independent list has no more than $M$ elements. Therefore, $V$ is infinite-dimensional. 

::: 

::: {#thm- } 
Every vector space has a basis.
Moreover, any two bases have the same carnality. 
:::  

::: {.proof }
Let $V$ be a nonzero vector space and consider the collection $A$ of all linearly independent subsets of $V$. This collection is nonempty, since any single nonzero vector forms a linearly independent set. Now, if $I_1\subset I_2 \subset \cdots$ is a chain of linearly independent subsets of $V$, then the union $U$ is also a linearly independent set. Hence, every chain in $A$ has an upper bound in $A$, and according to Zorn's lemma, $A$ must contain a maximal element, that is, $V$ has a maximal linearly independent set, which is a basis for $V$.

We may assume that all bases for $V$ are infinite sets, for if any basis is finite, then $V$ has a finite spanning set and so is a finite-dimensional vector space. Let $B$ be a basis for $V$. We may write $B=\{b_i \mid i\in I\}$ where $I$ is some indexed set, used to index the vectors in $B$. Note that $|I|=|B|$. Now let $C$ be another basis for $V$. Then any vector $c\in C$ can be written as a finite linear combination of the vectors in $B$, where all the coefficients are nonzero, say $c=\sum_{i\in U_c} r_i b_i$. Here $U_c$ is a finite subset of the index set $I$. 
Now, because $C$ is a basis for $V$, the union of all of the $U_c$'s as $C$ varies over $C$ must be in $I$, in symbols, $\bigcup_{c\in C} U_c=I$. 
For if all vectors in the basis $C$ can be expressed as a finite linear combination of the vectors $B-\{ b_k\}$ spans $V$, which is not the case. Therefore, $|B|=|I|\leq |C| \alpha_0=|C|.$ But we may also reverse the roles of $B$ and $C$ we obtain the reverse inequality. 
Therefore, $|B|=|C|$ as desired.
::: 



