---
pagetitle: "Introduction to Linear Maps - Learning Linear Algebra"
---
# Introduction to Linear Maps



::: {#def- } 
Let $V$ and $W$ be linear spaces. A function $T$ from $V$ to $W$ is called a \index{linear map} **linear map** if 
$$
T(f+g)=T(f)+T(g) 
\qquad \text{and}\qquad
T(k f)=k T(f)
$$
for all elements $f$ and $g$ of $V$ and for all scalars $k$. 
::: 

The collection of all linear maps from $V$ to $W$ is denoted by $\mathcal{L}(V,W)$ and if $T$ is a linear map from $V$ to $W$ we denote this by $T\in \mathcal{L}(V,W)$.

::: {#def- } 
Let $T\in \mathcal{L}(V,W)$. 
 
- Then the \index{kernel} **kernel**  of $T$ is the subset of $V$ consisting of the vectors that $T$ maps to 0; that is  
$\ker(T)=\{v\in V \, | \, T v=0\}.$
- Then the \index{image} **image**  of $T$ is the subset of $W$ consisting of the vectors of the form $Tv$ for some $v\in V$; that is 
$\text{im}(T)=\{w\in W \, | \, \text{ there exists } v \in V \text{ such that } w=T v\}.$
 
::: 
 
::: {#exm- } 
The function from $C^{\infty}$ to $C^{\infty}$ defined by $T(f)=f''$ is a linear map.  Find the kernel and image of $T$. 

::: 

::: {#exm- } 
The function from $C^{\infty}$ to $C^{\infty}$ defined by $T(f)=\int_0^1 f(x) \, dx $ is a linear map.  Find the kernel and image of $T$.  

::: 
 
::: {#thm- } 
If $T \in \mathcal{L}(V,W),$ then null $T$ is a subspace of $V$.
::: 

::: {.proof }
By definition, $\text{ker} T=\{v\in V \mid T v=0\}$ and so $\text{ker} T \subseteq W$. Let $u, v\in \text{ker} T$. Then, $T(u+v)=T u+ Tv=0+0=0$ which shows, $u+v\in \text{ker} T$, for all $u , v \in \text{ker} T$. Let $k$ be a scalar and $u\in \text{ker} T$. Then $T(k u)=k T u= k(0)=0$, which shows, $k u\in \text{ker} T$ for all scalars $k$ and all $u\in \text{ker} T$. Since $T(0)=T(0+0)=T(0)+T(0)$, $T(0)=0$ in $W$ which shows, $0\in \text{ker} T$. Therefore, $\text{ker} T$ is a subspace of $W$. 
::: 

::: {#def- } 
A linear map $T: V\rightarrow W$ is called \index{injective} **injective**  whenever $u, v\in V$ and $T u=T v$, we have $u=v$.
::: 
 
::: {#thm- } 
Let $T\in \mathcal{L}(V,W)$, then $T$ is injective if and only if null $T=\{0\}$.
::: 

::: {.proof }
Suppose $T$ is injective. Since $T(0)=0$, $0\in \text{ker} T$ and so $\{0\}\subseteq \text{ker} T$. Let $v\in \text{ker} T$. Then $T(0)=0=T(v)$ yields $v=0$ because $T$ is injective. Thus, $\text{ker} T\subseteq \{0\}$. Therefore, $\text{ker} T=\{0\}$. Conversely, assume $\text{ker} T=\{0\}$. Let $u, v\in V$. If $Tu=Tv$, then $T(u-v)=Tu - T v=0$ which shows $u-v \in \text{ker} T$. Thus $u=v$ and therefore, $T$ is injective. 
::: 

::: {#def- } 
For $T\in \mathcal{L}(V,W)$, the \index{image} **image**  of $T$, denoted by 
$\text{im}(T)$, is the subset of $W$ consisting of those vectors that are of the form $T v$ for some $v\in V$.
::: 

::: {#def- } 
A linear map $T: V\rightarrow W$ is called \index{surjective} **surjective**  if its range equals $W$.
::: 
 
::: {#thm- } 
If $T\in \mathcal{L}(V,W)$, then $\text{im} T$ is a subspace of $W$.
::: 

::: {.proof }
By definition, $\text{im} T=\{T v \mid v\in V\}\subseteq W$. Let $w_1,w_2\in W \in \text{im} T$. Then there exists $v_1,v_2\in V$ such that $w_1=Tv_1$ and $w_2=T v_2$. By linearity of $T$, $w_1+w_2=Tv_1+Tv_2=T(v_1+v_2)$ which shows $w_1+w_2\in \text{im} T$ for all $w_1,w_2 \in \text{im} T$. Let $w\in \text{im} T$ and let $k$ be a scalar. Then there exists $v\in V$ such that $w=T v$. By linearity of $T$, $ kw =k Tv =T(k v)$ which shows $kw\in \text{im} T$ for all $w\in \text{im} T$ and for all scalars $k$. Therefore, $\text{im} T$ is a subspace of $W$. 
::: 

::: {#thm- } [Rank-Nullity Theorem]
If $V$ is finite-dimensional and $T\in \mathcal{L}(V,W)$, then range $T$ is finite-dimensional and $\text{dim}  V= \text{dim}  (\text{im} T) + \text{dim}  (\text{ker}  T)$. 
::: 

::: {.proof }
Since $V$ is a finite-dimensional and $\text{ker} T$ is a subspace of $V$, $\text{ker} T$ is finite-dimensional and so let $(u_1,\ldots,u_n)$ be a basis of $\text{ker} T$. Since $(u_1,\ldots,u_n)$ is linearly independent in $V$, it can be extended to a basis of $V$, say $\mathcal{B}=(u_1,\ldots,u_n,v_1,\ldots,v_m)$. It suffices to show $(T v_1,\ldots, T v_m)$ is a basis of $\text{im} T$, for then $\text{im} T$ is finite-dimensional is proven and $\text{dim} V=n+m=\text{dim}  \text{ker} T+\text{dim} \text{im} T$ holds as well. 

Let $w\in \text{im} T$. Then there exists $v\in V$ and scalars $a_1,\ldots,a_n, b_1,\ldots,b_m$ such that 
$$w=Tv=T(a_1 u_1+\cdots + a_n u_n+b_1 v_1+\cdots + b_m v_m)=b_1 T v_1+\cdots + b_m T v_m.$$
 Thus  $(T v_1,\ldots,T v_m)$ spans $\text{im} T$. Suppose $c_1,\ldots,c_m$ are scalars such that $c T v_1+\cdots + c_m T v_m=0$. Then there exist scalars $d_1,\ldots,d_n$ such that 
 $$c_1 v_1+\cdots + c_m v_m=d_1 u_1+\cdots +d_n u_n.$$ 
 Since $\mathcal{B}$ is a basis of $V$ and $c_1 v_1+\cdots c_m v_m+(-d_1) u_1 + \cdots +(-d_n)u_n=0$ it follows $c_1=\cdots = c_m = d_1 = \cdots = \cdots =d_n=0$. In particular, $c_1=\cdots = c_m=0$ shows $T v_1,\ldots, T v_m$ are linearly independent. Therefore, $(T v_1,\ldots, T v_m)$ is a basis fo $\text{im} T$.
::: 

::: {#cor- } 
If $V$ and $W$ are finite-dimensional vector spaces with $T\in \mathcal{L}(V,W)$, then 
 
- $\text{dim}  V > \text{dim}  W \implies T$ is not injective, and
- $\text{dim}  V < \text{dim}  W \implies T$ is not surjective.
 
::: 

::: {.proof }
The proof of each part follows.
 
- By the Rank-Nullity Theorem, 
$\text{dim}  V=\text{dim}  \text{ker} T+ \text{dim}  \text{im} T \leq \text{dim}  \text{ker} T +\text{dim}  W.$
Since $\text{dim}  V > \text{dim}  W $, it follows 
$0<\text{dim}  V-\text{dim}  W\leq \text{dim}  \text{ker} T.$
Thus, $\text{ker} T \neq \{0\}$ and so $T$ is not injective. 
- Again by the Rank-Nullity Theorem, $\text{dim}  V=\text{dim}  \text{ker} T+ \text{dim}  \text{im} T$ and so $\text{dim}  \text{im} T\leq \text{dim}  V$. Since $\text{dim}  V < \text{dim}  W $, $0<\text{dim}  W-\text{dim}  V\leq \text{dim}  W-\text{dim}  \text{im} T$ and so there exists a nonzero element $w\in W$ with $w\in \text{im} T$. Therefore, $T$ is not surjective. 
 
::: 

::: {#exm- } 
Suppose that $T$ is a linear map from $V$ to $\mathbb{F}$. Prove that if $u \in V$ is not in $\text{ker}  T$, then $V=\text{ker} T \, \oplus \{a u:a\in F\}$.
Let $U=\{a u \mid a\in \mathbb{F}\}$. The following arguments show $V=\text{ker} T +U$ and $\text{ker} T \cap U=\{0\}$, respectively.
 
- Let $v\in V$ with $Tv=b$. Since $Tu\neq 0$ there is a $u_1 \in U$ such that $T u_1=b$. Then we can write $v=u_1+(v-u_1)$, and $v-u_1\in \text{ker} T$. This gives $V=\text{ker} T+ U$.
- Let $v\in \text{ker} T \cap U$, then there exists $a \in \mathbb{F}$ such that $v=a u$ and so $T(v)=a T u=0$ since $T v\in \text{ker} T$. Thus $a=0$ and so $v=0$ meaning $\text{ker} T \cap U\subseteq \{0\}$. Since $0 \in \text{ker} T \cap U$, it follows $\text{ker} T \cap U= \{0\}$. 
 
 

::: 

::: {#exm- } 
Suppose that $T\in \mathcal{L}(U,W)$ is injective and $(v_1,\ldots,v_n)$ is linearly independent in $V$. Prove that $(T v_1,\ldots,T v_n)$ is linearly independent in $W$.
Suppose $a_1 T v_1+ \cdots a_n T v_n=0$ in $W$ where $a_1,\ldots,a_n \in \mathbb{F}$. Then by linearity of $T$, $T(a_1 v_1 + \cdots + a_n v_n)=0$. Since $T(0)$ and $T$ is injective, $a_1 v_1+\cdots + a_n v_n=0$. Since $(v_1,\ldots,v_n)$ is linearly independent $a_1=\cdots = a_n =0$. Therefore, $(T v_1,\ldots, T v_n)$ is linearly independent. 

::: 

::: {#exm- } 
Show that every linear map from a one-dimensional vector space to itself is multiplication by some scalar. More precisely, prove that if $\text{dim}  V=1$ and $T\in \mathcal{L}(V,V)$, then there exists $a\in \mathbb{F}$ such that $T v=a v$ for all $v\in V$.
Let $\{w\}$ be a basis of $V$, and let $v\in V$. Then there exists $c\in \mathbb{F}$ such that $v=c w$. Applying $T$ yields,
$$
T v=T(c w)=cTw=c(a w)=(ca)w=a(cw)=a v
$$
where $Tw=aw$ since $Tw\in V$ and $\{w\}$ is a basis of $V$. 

::: 

::: {#exm- } 
\index{linear extension} **linear extension** 
Suppose that $V$ is finite-dimensional. Prove that any linear map on a subspace of $V$ can be extended to a linear map on $V$. In other words, show that if $U$ is a subspace of $V$ and $S\in \mathcal{L}(U,W)$, then there exists $T\in \mathcal{L}(V,W)$ such that $Tu=Su$ for all $u\in U$.
Let $(u_1,\ldots,u_n)$ be a basis of $U$ and extend this basis of $U$ to a basis of $V$, say $(u_1,\ldots,u_n, v_1,\ldots,v_m)$. Define $T$ as the linear extension of $S$, as follows
$$
T(u_i)=S(u_i) \text{ for } 1\leq i \leq n \hspace{.5cm} \text{ and } \hspace{.5cm}  T(v_j)=v_j \text{ for } 1\leq j \leq m.
$$
Then for all  $u\in U$,
\begin{align*}
T(u) & =T(a_1 u_1+\cdots + a_n u_n) 
 =a_1 T u_1+\cdots a_n T u_n \\
& =a_1 S u_1+\cdots +a_n S u_n 
=S(a_1u_1+\cdots a_n u_n) 
=S(u)
\end{align*} 
where $a_1,\ldots,a_n\in \mathbb{F}$. By definition of $T$, $T\in \mathcal{L}(V,W)$.

::: 

::: {#exm- } 
Prove that if $S_1,\ldots,S_n$ are injective linear maps such that $S_1  \cdots S_n$ makes sense, then $S_1 \cdots S_n$ is injective.
Suppose $v$ and $w$ are any vectors and $(S_1\cdots S_n)v=(S_1\cdots S_n)w$. Then by definition of composition, $S_1(S_2\cdots S_n)v=S_1(S_2\cdots S_n)w$, and since $S_1$ is injective $S_2(S_3\cdots S_n)v=S_2(S_3\cdots S_n)w$. Since $S_2,\ldots,S_n$ are all injective $v=w$ as desired showing $S_1\cdots S_n$ is injective. 

::: 

::: {#exm- } 
Prove that if $(v_1,\ldots,v_n)$ spans $V$ and $T\in \mathcal{L}(V,W)$ is surjective, then $(T v_1,\ldots,T v_n)$ spans $W$.
Let $w\in W$. Then, since $T$ is surjective, there exists $v\in V$ such that $T(v)=w$. Since $(v_1,\ldots,v_n)$ spans $V$ there exists scalars $a_1,\ldots,a_n$ such that $v=a_1 v_1+ \dots a_n v_n$ and by linearity of $T$, $T(v)=a_1 T v_1+ \cdots a_n T v_n=w.$ Therefore, $(T v_1,\ldots,T v_n)$ spans $W$ because every element $w$ in $W$ is a linear combination of the $T v$'s.

::: 

::: {#exm- } 
Suppose that $V$ is finite-dimensional and that $T\in \mathcal{L}(V,W)$. Prove that there exists a subspace $U$ of $V$ such that $U\cap \text{ker} T=\{0\}$ and range $T = \{T u : u\in U\}$.
Since $V$ is finite-dimensional so is $\text{ker} T$. Let $(v_1,\ldots,v_n)$ be a basis of $\text{ker} T$ and extend this basis to a basis of $V$, 
namely let $\mathcal{B}=(v_1,\ldots,v_n,u_1,\ldots,u_m)$ be a basis of $V$.  Let $U=\text{span} (u_1,\ldots,u_m)$, we will show $U\cap \text{ker} T=\{0\}$ and range $T = \{T u : u\in U\}$. Clearly, $\{0\}\subseteq U\cap \text{ker} T$ since both $U$ and $\text{ker} T$ are subspaces. Let $v\in U\cap \text{ker} T$. Then $v\in U$ implies there exists $a_1,\ldots,a_m$ such that $v=a_1 u_1+\cdots +a_m u_m$. Then $v\in \text{ker} T$ implies there exists $b_1,\ldots,b_n$ such that $v=b_1 v_1+\cdots +b_n v_n$.  Then $a_1 u_1+\cdots +a_m u_m+(-b_1)v_1+\cdots +(-b_n)v_n=0$ and since $\mathcal{B}$ is a basis of $V$ the $u$'s and $v$'s are linearly independent and so $a_1=\cdots =a_m=b_1=\cdots =b_n=0$ meaning $v=0$; and so $\text{ker} T = \{0\}$.  Let $v\in V$. Then $T(v)=a_1T v_1+\cdots +a_n T v_n+b_1 T u_1+\cdots + b_m T u_m=b_1 Tu_1+\cdots +b_m T u_m$ showing $\{T v : v\in T\}\subseteq \{T v : v\in U\}$ conversely is obvious, since $U\subseteq V$.

::: 

::: {#exm- } 
Prove that if there exists a linear map on $V$ whose null space and range are both finite-dimensional, then $V$ is finite-dimensional.
::: 

::: {#exm- } 
Suppose that $V$ and $W$ are finite-dimensional and $T\in \mathcal{L}(V,W)$. Prove that there exists a surjective linear map from $V$ onto $W$ if and only if $\text{dim}  W \leq \text{dim}  V$.
Suppose $T$ is a linear map of $V$ onto $W$, then $\text{dim}  V=\text{dim}  \text{ker} T+\text{dim}  \text{im} T$. Since $\text{dim}  \text{ker} T \geq 0$, $\text{dim}  V\geq \text{dim}  \text{im} T=\text{dim}  W$, since $T$ is onto. Conversely, assume $m=\text{dim}  W\leq \text{dim}  V=n$ with bases of $W$ say $(w_1,\ldots,w_m)$ and of $V$ say $(v_1,\ldots,v_n)$. Define $T$ to be the linear extension of:
$$
\begin{cases}
T(v_i)=w_i & \text{ if } 1\leq i\leq m \\
T(v_i)=0 & \text{ if } i>m
\end{cases}
$$
Then $T$ is surjective since: if $w\in W$ then there exists $a_i\in \mathbb{F}$ such that $w=a_1 w_1+\cdots + a_m w_m=a_1 T(v_1)+\cdots + a_m T(v_m)=T(a_1 v_1+\cdots + a_m v_m)$ showing every element in $W$ is in $\text{im} T$.

::: 

::: {#exm- } 
Suppose that $W$ is finite-dimensional and $T\in \mathcal{L}(V,W)$. Prove that $T$ is injective if and only if there exists $S\in \mathcal{L}(W,V)$ such that $S T$ is the identity map on $V$.
Suppose $S\in\mathcal{L}(W,V)$ and $ST$ is the identity on $V$. Then $\text{ker} T\subseteq \text{ker} ST=\{0\}$ and so $\text{ker} T=\{0\}$. Therefore, $T$ is injective. Conversely, suppose $T$ is injective. So we can define $S_1\in\mathcal{L}(W,V)$ by the following: $S_1(w)=v$ where $v=T^{-1}(w)$ (since $T$ is injective). So $S_1:\text{im} T \rightarrow V$ and since $W$ is finite-dimensional, by \ref{Linear Extension}, $S_1$ can be extended to $S: W\rightarrow V$ and by definition of $S_1$, if $v\in V$, then $ST(v)=S(Tv)=T^{-1}(Tv)=v$.

::: 

::: {#exm- } 
Suppose that $V$ is finite-dimensional and $T\in \mathcal{L}(V,W)$. Prove that $T$ is surjective if and only if there exists $S\in \mathcal{L}(W,V)$ such that $T S$ is the identity map on $W$.
We will present two proofs.
 
- Suppose $S\in \mathcal{L}(W,V)$ and $TS=I_W$. Let $w\in W$. Then $v=S(w)\in V$ is such that $T(v)=TS(w)=w$ and therefore $T$ is surjective. Conversely, suppose $T$ is surjective. Since $V$ is a finite-dimensional vector space and $T$ is a linear map, $W$ is finite-dimensional. Let $(v_1,\ldots,v_n)$ be a basis for $V$. Since $T$ is surjective, $(T v_1,\ldots,T v_n)$ spans $W$. Also since $T$ is surjective $\text{dim}  W\leq \text{dim}  V=n$ Any spanning set reduced to a basis say $(T v_1,\ldots,T v_m)$ is a basis of $W$ where $m\leq n$. Define $S$ as the linear extension of $S(T v_i)=v_i$ for each $1\leq i \leq m$. Then, for all $w\in W$, $S(w)=S(a_1 T v_1+\cdots +a_m T v_m)=a_1 ST v_1+\cdots + a_m ST v_m=a_1 v_1+\cdots + a_m v_m=w$ for scalars $a_1,\ldots,a_m\in \mathbb{F}$, and so $TS=I_W$.
- Suppose $T$ is surjective. Using \ref{Null Space Decomposition}, there exists a subspace $U$ of $V$ such that $U\cap \text{ker} T=\{0\}$ and $\text{im} T=\{T u : u\in U\}$. Define $T_1: U\rightarrow W$ by $T_1 u=T u$ for $u\in U$. Notice $T_1$ is injective and surjective and so $T_1$ has an inverse. Define $S=T_1^{-1}$ we have $TS w= T_1 T_1^{-1}w=w$ for all $w\in W$.
 
 

::: 

A linear map $T\in \mathcal{L}(V,W)$ is called \index{invertible} **invertible** if there exists a linear map $S\in \mathcal{L}(W,V)$ such that $S T$ equals the identity map on $V$ and $TS$ equal the identity map on $W$.
Given $T\in\mathcal{L}(V,W)$. A linear map $S\in\mathcal{L}(W,V)$ satisfying $S T=I$ and $T S=I$ is called an \index{inverse} **inverse**  of $T$.
Two vector spaces are called \index{isomorphic} **isomorphic** if there is an invertible linear map from one vector space onto the other one.

::: {#thm- } 
If $\mathcal{B}=(f_1,\ldots,f_n)$ is a basis of a linear space $V$, then the coordinate transformation 
$$
L_{\mathcal{B}}(f) = [f]_{\mathcal{B}}
$$ 
from $V$ to $\mathbb{R}^n$ is an isomorphism. Thus any linear space $V$ is isomorphic to $\mathbb{R}^n$. 
::: 

::: {.proof }
The proof if left for the reader.
::: 

An invertible linear transformation $T$ is called an \index{isomorphism} **isomorphism**. Recall the rank-nullity theorem states that if $V$ and $W$ are finite-dimensional vector spaces and $T$ is a linear transformation from $V$ to $W$ then $\text{dim}  V=\text{dim}  \ker T+\text{dim}  \text{im} T$ where $\text{dim}  \ker T$ is called the \index{nullity} **nullity** and $\text{dim}  \text{im} T$ is called the \index{rank} **rank**.

::: {#thm- } 
If $V$ and $W$ are finite-dimensional linear spaces, then 
 
- $T$ is an isomorphism from $V$ to $W$ if and only if $\ker(T)= \{0\}$ and $\text{im} (T)=W$,
- if $V$ is isomorphic to $W$, then $\text{dim} (V)=\text{dim} (W)$,
- if $\text{dim} (V)=\text{dim} (W)$ and $\ker(T)=\{0\}$, then $T$ is an isomorphism, and
- if $\text{dim} (V)=\text{dim} (W)$ and $\text{im}(T)=W$, then $T$ is an isomorphism.
 
::: 

::: {.proof }
The proof of each part follows.
 
- Suppose $T$ is an isomorphism from $V$ to $W$. This means there exists an invertible linear transformation $T^{-1}$ from $W$ to $V$ such that $T(T^{-1})=I_W$ and $T^{-1}(T)=I_V$, where $I_W$ and $I_V$ are the identity transformations on $W$ and $V$ respectively. We will use $T^{-1}$ to show $\ker  T=\{0\}$ and $\text{im}  T= W$. Since $\ker T$ is a subspace, $\{0\}\subset \ker T$. Conversely, suppose $f\in \ker T$. Then $T(f)=0$ and so $T^{-1}(T(f))=f=0$ so that $\ker T\subseteq \{0\}$. Thus  $\ker T = \{0\}$. Since $\text{im} T$ is a subspace of $W$, $\text{im} T\subseteq W$. To show conversely, let $w\in W$. Then $T^{-1}(w)\in V$ and so $T(T^{-1}w)=w$ shows $w\in \text{im} T$.  Thus $\text{im} T=W$. 

Conversely, suppose $\ker T=\{0\}$ and $\text{im} T=W$. We will show $T$ is an isomorphism, which means we must show $T(f)=g$ has a unique solution $f$ for each $g\in W$. Now since $\text{im} T=W$, $T(f)=g$ has at least one solution, say $f$. Suppose $T(f)=g$ has two solutions, say $T(f_1)=g=T(f_2)$. Then $0=T(f_1)-T(f_2)=T(f_1-f_2)$
shows $f_1-f_2\in \ker T$. Since $\ker T=\{0\}$, $f_1=f_2$ must follow, which means $T(f)=g$ must have only one solution, so that $T^{-1}$ exists, and therefore, $T$ is an isomorphism.  
- If $V$ is isomorphic to $W$, then there exists a linear transformation $T$ such that $\ker T=\{0\}$ and $\text{im} T=W$. By the rank-nullity theorem, $\text{dim}  V=\text{dim}  \ker T + \text{dim}  \text{im} T=0+\text{dim}  W$.
- By the previous part, $T$ is an isomorphism when $\ker =\{0\}$ and $\text{im} T=W$. We are assuming $\ker T=\{0\}$ so it remains to show $\text{im} T=W$. By the rank-nullity theorem $\text{dim}  V=\text{dim}  \ker T+\text{dim}  \text{im} T=\text{dim}  \ker T+\text{dim}  W=\text{dim}  W$. Thus, $\ker T=0$ and so $\ker T=\{0\}$. Therefore, $T$ is an isomorphism.
- By the previous part, $T$ is an isomorphism when $\ker =\{0\}$ and $\text{im} T=W$. We are assuming $\text{im} T=W$ so it remains to show $\ker T=\{o\}$. By the rank-nullity theorem $\text{dim}  V=\text{dim}  \ker T+\text{dim}  \text{im} T=\text{dim}  \text{im} T=\text{dim}  W$. Therefore, $\text{im} T=W$ and so $T$ is an isomorphism.
 
::: 

::: {#exm- } 
Show that the transformation $T(A)=S^{-1}AS$, from $\mathbb{R}^{2\times 2}$ to $\mathbb{R}^{2\times 2}$ where $S=\begin{bmatrix} 1 & 2 \\ 3 & 4  \end{bmatrix}$ is an isomorphism.
Notice that $\text{dim}  \mathbb{R}^{2\times 2}=\text{dim}  \mathbb{R}^{2\times 2}$. Can we determine an invertible linear transformation $T^{-1}$? Checking the linearity conditions,$$
T(A_1+A_2)=S^{-1}(A_1+A_2)S=S^{-1}A_1S+S^{-1}A_2S=T(A_1)+T(A_2)
$$
and$$
T(k A)=S^{-1}(k A)S=kS^{-1}A S=k T(A).
$$
Now we know $T$ is a linear transformation. Is it invertible? We need to solve the equation, $B=S^{-1} A S$ for input $A$. We can do this because $S$ is an invertible matrix, so $S B=S(S^{-1}AS)=AS$ and multiplying by $S^{-1}$ on the right $S BS^{-1}=A$ so that $T$ is invertible, and the linear transformation is $T^{-1}(B)=S B S^{-1}$.

::: 

::: {#exm- } 
Is the transformation $L( f)=\vectorthree{f(1)}{f(2)}{f(3)}$ from $\mathcal{P}_3$ to $\mathbb{R}^3$ an isomorphism?
Since $\text{dim}  \mathcal{P}_3=4$ and $\text{dim}  \mathbb{R}^3=3$, the spaces $\mathcal{P}_3$ and $\mathbb{R}^3$ fail to be isomorphic, so that $L$ is not an isomorphism. 

::: 

::: {#exm- } 
Is the transformation $L( f)=\vectorthree{f(1)}{f(2)}{f(3)}$ from $\mathcal{P}_2$ to $\mathbb{R}^3$ an isomorphism?
Notice $\text{dim}  \mathcal{P}_2=3$ and $\text{dim}  \mathbb{R}^3=3$ so the dimensions of the domain and the target space have the same dimension. 
Checking the linearity conditions,
$$
L(f_1+f_2)
=\vectorthree{(f_1+f_2)(1)}{(f_1+f_2)(2)}{(f_1+f_2)(3)}
=\vectorthree{f_1(1)}{f_1(2)}{f_1(3)}+\vectorthree{f_2(1)}{f_2(2)}{(f_2(3)}=L(f_1)+L(f_2)
$$
and
$$
T(k f)=\vectorthree{(k f)(1)}{(k f)(2)}{(kf)(3)}
=k\vectorthree{f(1)}{f(2)}{f(3)}
=k T(f).
$$
The kernel of $T$ consists of all polynomials $f(x)$ in $\mathcal{P}_2$ such that 
$$
T(f(x))=\vectorthree{f(1)}{f(2)}{f(3)}=\vectorthree{0}{0}{0}.
$$ 
Since a nonzero polynomial in $\mathcal{P}_2$ has at most two zeros, the zero polynomial is the only solution, so that $\ker T=\{0\}$. Therefore, $T$ is an isomorphism. 

::: 

::: {#exm- } 
Determine whether the transformation $$T(M)=M\begin{bmatrix} 2 & 0 \\ 0 & 3  \end{bmatrix}-\begin{bmatrix} 3 & 0 \\ 0 & 4  \end{bmatrix}M$$ from $\mathbb{R}^{2\times 2}$ to $\mathbb{R}^{2\times 2}$ is an isomorphism.
Notice that $\text{dim}  \mathbb{R}^{2\times 2}=\text{dim} \mathbb{R}^{2\times 2}$. Can we determine an invertible linear transformation $T^{-1}$? Checking the linearity conditions,$$
\begin{array}{rl}
T(M+N)
&=(M+N)\begin{bmatrix} 2 & 0 \\ 0 & 3  \end{bmatrix}-\begin{bmatrix} 3 & 0 \\ 0 & 4  \end{bmatrix}(M+N) \\
&=M\begin{bmatrix} 2 & 0 \\ 0 & 3  \end{bmatrix}-\begin{bmatrix} 3 & 0 \\ 0 & 4  \end{bmatrix}M
+ N\begin{bmatrix} 2 & 0 \\ 0 & 3  \end{bmatrix}-\begin{bmatrix} 3 & 0 \\ 0 & 4  \end{bmatrix}N  =T(M)+T(N)
\end{array}
$$
and$$
\begin{array}{rl}
T(k M)
& =(kM)\begin{bmatrix} 2 & 0 \\ 0 & 3  \end{bmatrix}-\begin{bmatrix} 3 & 0 \\ 0 & 4  \end{bmatrix}(Mk) \\
& =k \left ( M\begin{bmatrix} 2 & 0 \\ 0 & 3  \end{bmatrix}-\begin{bmatrix} 3 & 0 \\ 0 & 4  \end{bmatrix}M \right ) k
 = k T(M)
\end{array}
$$
The kernel of $T$ consists of $M=\begin{bmatrix} a & b \\ c & d  \end{bmatrix}$ such that$$
\begin{bmatrix} a & b \\ c & d  \end{bmatrix}
\begin{bmatrix} 2 & 0 \\ 0 & 3  \end{bmatrix}-\begin{bmatrix} 3 & 0 \\ 0 & 4  \end{bmatrix}
\begin{bmatrix} a & b \\ c & d  \end{bmatrix}
=
\begin{bmatrix} -a & 0 \\ -2c & -d  \end{bmatrix}
\begin{bmatrix} 0 & 0 \\ 0 & 0  \end{bmatrix}.
$$
Thus $a=c=d=0$. However, when $M=\begin{bmatrix} 0 & 1 \\ 0 & 0  \end{bmatrix}$ then $T(M)=0$ so that $\ker T \neq \{0\}$, and so $T$ is not an isomorphism. 

::: 

::: {#exm- } 
Determine whether the transformation $T(f(t))=\vectorthree{f(1)}{f'(2)}{f(3)}$ from $\mathcal{P}_2$ to $\mathbb{R}^3$ is a linear transformation. Then determine whether $T$ is an isomorphism and if not then find its image and kernel.
This transformation is linear since$$
T(f(t)+g(t))=\vectorthree{f(1)+g(1)}{f'(2)+g'(2)}{f(3)+g(3)}=
\vectorthree{f(1)}{f'(2)}{f(3)}+ \vectorthree{g(1)}{g'(2)}{g(3)}=
T(f(t))+T(g(t))
$$
and
$$
T(k f(t))=\vectorthree{kf(1)}{k f'(2)}{k f(3)}=
k \vectorthree{f(1)}{f'(2)}{f(3)}=
k T(f(t)).
$$
Since $T(t-1)(t-3))=T(t^2-4t+3)=\vec 0$ shows $\ker T \neq \{0\}$, T is not an isomorphism.

::: 

::: {#thm- } 
A linear map is invertible if and only if it is injective and surjective.
::: 

::: {.proof }
Suppose $T\in \mathcal{L}(V,W)$ is invertible with inverse $T$. Let $u,v\in V$. If $Tu=Tv$ then 
$$u=(T^{-1})u)=T^{-1}(Tu)=T^{-1}(Tv)=(T^{-1}T)(v)=v$$ 
and so $T$ is injective. If $w\in W$, then $v=T^{-1} w\in V$ with $T v=T(T^{-1}w)=w$ shows $T$ is surjective. Assume $T$ is injective and surjective. For each $w\in W$ assign $T(v)=w$. Such $S(w)=v$ exists because $T$ is surjective and is unique since $T$ is injective. Then $T(v)=w$ shows $ST(v)=S(w)=v$ so that $ST$ is the identity on $V$. Also, $TS(w)=T(Sw)=Tv=w$ shows $TS$ is the identity on $W$. Thus $S$ and $T$ are inverses. 

Now $S$ is linear since:
 
- if $w_1,w_2\in W$, then there exists a unique $v_1$ and $v_2$ such that $Tv_1=w_1$ and $Tv_2=w_2$, $S(w_1)=v_1$, and $S(w_2)=v_2$. By linearity of $T$, $S(w_1+w_2)=S(T v_1+Tv_2)=(ST)(v_1+v_2)=v_1+v_2=S(w_1)+S(w_2)$.
- If $w\in W$ and $k\in \mathbb{F}$ then there exists a unique $v\in V$ such that $Tv=w$ and $S(w)=v$. By linearity of $T$, $S(kw)=S(k Tv)=S(T k v)=k v=kS(w)$.
 
Therefore $S$ is linear and is the inverse of $T$.
::: 

Consider the transformation 
$$
L \left( \, \begin{bmatrix} a & b \\ c & d  \end{bmatrix} \, \right)=\vectorfour{a}{b}{c}{d}
$$
from $\mathbb{R}^{2\times 2}$ to $\mathbb{R}^4$. Note that $L$ is the coordinate transformation $L_{\mathcal{B}}$ with respect to the basis
$$
\mathcal{B}=
\left( 
\begin{bmatrix} 1 & 0 \\ 0 & 0  \end{bmatrix},
\begin{bmatrix} 0 & 1 \\ 0 & 0  \end{bmatrix},
\begin{bmatrix} 0 & 0 \\ 1 & 0  \end{bmatrix},
\begin{bmatrix} 0 & 0 \\ 0 & 1  \end{bmatrix}
\right)
$$
Being a coordinate transformation, $L$ is both linear and invertible. Therefore $L$ is an isomorphism. 

::: {#thm- } 
Let $T$ be the linear transformation from $V$ to $V$ and let $B$ be the matrix of $T$ with respect to a basis $\mathcal{B}=(f_1,\ldots,f_n)$ of $V$. Then 
$$
B=
\begin{bmatrix}[T(f_1)]_{\mathcal{B}} & \cdots & [T(f_n)]_{\mathcal{B}}]
\end{bmatrix}
$$
In other words, the columns of $B$ are the $\mathcal{B}$-coordinate vectors of the transformation of the basis elements $f_1,\ldots,f_n$ of $V$. 
::: 

::: {.proof }
The proof if left for the reader.
::: 

::: {#thm- } 
Two finite-dimensional vector spaces are isomorphic if and only if they have the same dimension.
::: 

::: {.proof }
Suppose $V$ and $W$ are finite-dimensional vector spaces that are isomorphic. If $\text{dim}  V > \text{dim}  W$, then no linear map between $T$ and $W$ can be injective. Thus $V$ and $W$ are not isomorphic contrary to hypothesis. If $\text{dim}  V < \text{dim}  W$, then no linear map between $V$ and $W$ can be surjective. Thus $V$ and $W$ are not isomorphic contrary to hypothesis. Therefore, $\text{dim}  V =\text{dim}  W$. 

Suppose $V$ and $W$ are vector spaces with $\text{dim}  V=\text{dim}  W=n$. Let $(v_1,\ldots,v_n)$ ba a basis of $V$ and let $(w_1,\ldots,w_n)$ be a basis of $W$. Define a linear map $T$ by $T(a_1 v_1+\cdots +a_n v_n)=a_1 w_1+\cdots +a_n w_n$. It's an easy exercise to show $T$ is linear, injective, and surjective. Thus $T$ is an isomorphism as required.
::: 

::: {#thm- } 
\label{simrep}
If $A$ and $B$ are matrices of a linear transformation $T$ with respect to different bases, then $A$ and $B$ are similar matrices.
::: 

::: {.proof }
The proof is left for the reader.
::: 

::: {#thm- } 
Suppose $V$ and $W$ are finite-dimensional vector spaces, then $\mathcal{M}$ is an invertible linear map between $\mathcal{L}(V,W)$ and $Mat(m,n,\mathbb{F})$
::: 

::: {.proof }
Suppose $(v_1,\ldots,v_n)$ and $w_1,\ldots,w_m)$ are bases of $V$ and $W$ respectively. For each $T\in \mathcal{L}(V,W)$ we assign,$$
\mathcal{M}(T)=\begin{bmatrix}a_{11} & & a_{1n}  \\ \vdots & \cdots & \vdots \\ a_{m1} & & a_{mn} \end{bmatrix}.
$$
where $T v_k=a_{1k} w_1+\cdots + a_{mk} w_m$. Since $(w_1,\ldots,w_m)$ is a basis of $W$, This assigment is well-defined. The following arguments show $\mathcal{M}$ is linear, injective, and surjective, respectively. 
 
- If $S,T\in \mathcal{L}(V,W)$, then $\mathcal{M}(S+T)=\mathcal{M}(S)+\mathcal{M}(T)$ follows by the definition of matrix addition. If $S\in \mathcal{L}(V,W)$ and $k\mathbb{F}$, then $\mathcal{M}(kS)=k\mathcal{M}(S)$ follows by the definition of scalar multiplication of matrices. 
- If $T\in \mathcal{L}(V,W)$ with $\mathcal{M}(T)=0$, then for entries in $[a_{ij}]$ are zero showing $T v_k=0$ for each $k$. Since $(v_1,\ldots,v_n)$ is a basis of $V$, $T$ must be the zero map, and so $\text{ker} \mathcal{M}=\{0\}$. Therefore, $\mathcal{M}$ is injective. 
- If $A \in Mat(m,n,\mathbb{F})$ then $A$ is an $m\times n$ matrix with entries $[a_{ij}]$. We define $Tv_k=a_{1k} w_1+\cdots a_{mk} w_m$ for each $k$. Then, by the definition of the matrix of a linear map, $\mathcal{M}(T)=A$ and so $\mathcal{M}$ is surjective. 
::: 

::: {#thm- } 
If $V$ and $W$ are finite-dimensional, then $\mathcal{L}(V,W)$ is finite-dimensional and $\text{dim}  \mathcal{L}(V,W) =(\text{dim}  V) (\text{dim}  W)$.
::: 

::: {.proof }
If $V$ and $W$ are  finite-dimensional vector spaces then $\mathcal{L}(V,W)$ is isomorphic to $Mat(m,n,\mathbb{F})$ where $n=\text{dim}  V$ and $m=\text{dim}  W$.
If follows
$$
\text{dim}  \mathcal{L}(V,W) =\text{dim}  Mat(mn,\mathbb{F})= m n=(\text{dim}  W)(\text{dim}  V).
$$
since $\text{dim}  Mat(m,n,\mathbb{F})= m n$.
::: 

::: {#thm- } 
If $V$ is finite-dimensional and $T\in \mathcal{L}(V)$, the the following are equivalent: 

- $T$ is invertible,
- $T$ is injective, and 
- $T$ is surjective.
::: 

::: {.proof }
The proof of each part follows.
 
- Suppose $T$ is invertible, then by definition $T$ is injective. 
- Suppose $T$ is injective. Thus $\text{ker} T=\{0\}$. Since $V$ is finite-dimensional, we can apply the Rank-Nullity Theorem so $\text{dim}  V=\text{dim}  \text{im} T$. Since $\text{im} T$ is a subspace of $V$ with the same dimension as $V$, $\text{im} T=V$. Therefore, $T$ is surjective. 
- Suppose $T$ is surjective. Then $T(V)=V$ and so $\text{dim}  V=\text{dim}  \text{im} T$. Since $V$ is finite-dimensional, $\text{dim}  V=\text{dim}  \text{ker} T+\text{dim}  \text{im}$ T by the Rank-Nullity Theorem. Thus, $\text{dim}  \text{ker} T =0$ and so $\text{ker} T=\{0\}$. Therefore, $T$ is injective, and since $T$ is injective and surjective, $T$ is invertible. 
::: 


