---
pagetitle: "Jordan Canonical Form - Learning Linear Algebra"
---
# Jordan Canonical Form


A basis of $V$ is called a \index{Jordan basis} **Jordan basis**  for $T$ if with respect to this basis $T$ has block diagonal matrix
$$
\begin{bmatrix}
A_1 &   & 0 \\
 & \ddots &  \\
0 &  & A_m \\
\end{bmatrix}
$$
where each $A_j$ is an upper triangular matrix of the form
$$
A_j =
\begin{bmatrix}
\lambda_j & 1 &  & 0 \\
 & \ddots & \ddots & \\
 &  &  \ddots & 1 \\
0 &  &  & \lambda_j \\
\end{bmatrix}
$$
where the diagonal is filled with some eigenvalue $\lambda_j$ of $T$.

Because there exist operators on real vector spaces that have no eigenvalues, there exist operators on real vector spaces for which there is no corresponding Jordan basis. 

::: {#thm- } 
Suppose $V$ is a complex vector space. If $T\in \mathcal{L}(V)$, then there is a basis of $V$ that is a Jordan basis for $T$. 
::: 

::: {.proof }
The proof is left for the reader.
::: 

A basis of $V$ is called a \index{Jordan basis} **Jordan basis**  for $T$ if with respect to this basis $T$ has block diagonal matrix
$$
\begin{bmatrix}
A_1 &   & 0 \\
 & \ddots &  \\
0 &  & A_m \\
\end{bmatrix}
$$
where each $A_j$ is an upper triangular matrix of the form
$$
A_j =
\begin{bmatrix}
\lambda_j & 1 &  & 0 \\
 & \ddots & \ddots & \\
 &  &  \ddots & 1 \\
0 &  &  & \lambda_j \\
\end{bmatrix}
$$
where the diagonal is filled with some eigenvalue $\lambda_j$ of $T$.

An operator $T$ can be put into Jordan canonical form if its characteristic and minimal polynomials factor into linear polynomials. this is always true if the vector space is complex. 

::: {#thm- } 
Let $T\in\mathcal{L}(V)$ whose characteristic and minimal polynomials are, respectively,
$$
c(t)=(t-\lambda_1)^{n_1} \cdots (t-\lambda_r)^{n_r}) 
\qquad \text{and} \qquad 
m(t)=(t-\lambda_1)^{m_1} \cdots (t-\lambda_r)^{m_r}) 
$$ 
where the $\lambda_i$ are distinct scalars. Then $T$ has block diagonal matrix representation $J$ whose diagonal entries are of the form 
$$
J_{ij}=
\begin{bmatrix} 
\lambda_i & 1 & 0 & \cdots & 0 & 0 \\ 
0 & \lambda_i & 1 & \cdots & 0 & 0 \\ 
\vdots & \vdots & \ddots & \ddots & \vdots & \vdots \\ 
0 & 0 & 0 & \cdots & \lambda_i & 1 \\
0 & 0 & 0 & \cdots & 0 & \lambda_i 
\end{bmatrix}
$$
For each $\lambda_i$ the corresponding blocks have the following properties:
 
- There is at least one $J_{ij}$ of order $m_i$; all other $J_{ij}$ are of order $\leq m_i$
- The sum of the orders of the $J_{ij}$ is $n_i$.
- The number of $J_{ij}$ equals the geometric multiplicity of $\lambda_i$.
- The number of $J_{ij}$ of each possible order is uniquely determined by $T$. 
 
::: 

::: {.proof }
The proof is left for the reader.
::: 

The matrix $J$ in the above proposition is called the \index{Jordan canonical form} **Jordan canonical form** of the operator $T$. A diagonal block $J_{ij}$ is called a \index{Jordan block} **Jordan block** belongng to the eigenvalue $\lambda_i$. Observe that 
$$
\begin{bmatrix} 
\lambda_i & 1 & 0 & \cdots & 0 & 0 \\ 
0 & \lambda_i & 1 & \cdots & 0 & 0 \\ 
\vdots & \vdots & \ddots & \ddots & \vdots & \vdots \\ 
0 & 0 & 0 & \cdots & \lambda_i & 1 \\
0 & 0 & 0 & \cdots & 0 & \lambda_i 
\end{bmatrix}
=
\begin{bmatrix} 
\lambda_i & 0 & 0 & \cdots & 0 & 0 \\ 
0 & \lambda_i & 0 & \cdots & 0 & 0 \\ 
\vdots & \vdots & \ddots & \ddots & \vdots & \vdots \\ 
0 & 0 & 0 & \cdots & \lambda_i & 0 \\
0 & 0 & 0 & \cdots & 0 & \lambda_i 
\end{bmatrix}
+
\begin{bmatrix} 
0 & 1 & 0 & \cdots & 0 & 0 \\ 
0 & 0 & 1 & \cdots & 0 & 0 \\ 
\vdots & \vdots & \ddots & \ddots & \vdots & \vdots \\ 
0 & 0 & 0 & \cdots & 0 & 1 \\
0 & 0 & 0 & \cdots & 0 & 0 
\end{bmatrix}
$$
That is, $J_{ij}=\lambda_i I+N$ where $N$ is the nilpotent block. 


::: {#exm- } 
Suppose the characteristic and minimum polynomials of an operator $T$ are, respectively,
$$
c(t)=(t-2)^4(t-3)^3 \qquad \text{and} \qquad m(t)=(t-2)^2(t-3)^2.
$$
Then the Jordan canonical form of $T$ is one of the following matrices:
$$
\begin{bmatrix} 
2 & 1 & 0 & 0 & 0 & 0 & 0 \\
0 & 2 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 2 & 1 & 0 & 0 & 0 \\
0 & 0 & 0 & 2 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 3 & 1 & 0 \\ 
0 & 0 & 0 & 0 & 0 & 3 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 3 
\end{bmatrix}
\qquad \text{or} \qquad
\begin{bmatrix} 
2 & 1 & 0 & 0 & 0 & 0 & 0 \\
0 & 2 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 2 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 2 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 3 & 1 & 0 \\ 
0 & 0 & 0 & 0 & 0 & 3 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 3 
\end{bmatrix}
$$
The first matrix occurs if $T$ has two independent eigenvectors belonging to the eigenvalue 2; and the second matrix occurs if $T$ has three independent eigenvectors belonging to 2. 
::: 

::: {#exm- } 
Suppose $N\in \mathcal{L}(V)$ is nilpotent. Prove that the minimal polynomial of $N$ is $z^{m+1}$, where $m$ is the length of the longest consecutive string of $1'\text{s}$ that appears on the line directly above the diagonal in the matrix of $N$ with respect to any Jordan basis for $N$.
::: 

::: {#exm- } 
Suppose $V$ is a complex vector space and $T\in \mathcal{L}(V)$. Prove that there does not exist a direct sum decomposition of $V$ into two proper subspaces invariant under $T$ if and only if the minimal polynomial of $T$ is of the form $(z-\lambda)^{\text{dim}  V}$ for some $\lambda \in \mathbb{C}$.
::: 

::: {#exm- } 
Suppose $T\in \mathcal{L}(V)$ and $(v_1,\ldots,v_n)$ is a basis of $V$ that is a Jordan basis for $T$. Describe the matrix of $T$ with respect to the basis $(v_n,\ldots,v_1)$ obtained by reversing the order of the $v$'s.
::: 

::: {#exm- } 
Consider a 2-by-2 matrix of real numbers
$$
\begin{bmatrix}
a & c \\
b & d
\end{bmatrix}.
$$
::: 

::: {#exm- } 
Suppose $A$ is a block diagonal matrix
$$
A=\begin{bmatrix}
A_1 & & 0 \\
& \ddots & \\
0 & & A_m
\end{bmatrix},
$$
where each $A_j$ is a square matrix. Prove that the set of eigenvalues of $A$ equals the union of the eigenvalues of $A_1,\ldots,A_m$.
::: 

::: {#exm- } 
Suppose $A$ is a block upper-triangular matrix
$$
A=
\begin{bmatrix}
A_1 & & * \\
& \ddots & \\
0 & & A_m
\end{bmatrix},
$$
where each $A_j$ is a square matrix. Prove that the set of eigenvalues of $A$ equals the union of the eigenvalues of $A_1$,\ldots,$A_m$.
::: 

::: {#exm- } 
Suppose $V$ is a real vector space and $T\in \mathcal{L}(V)$. Suppose $\alpha, \beta \in \mathbb{R}$ are such that $T^2+\alpha T+\beta I=0$. Prove that $T$ has an eigenvalue if and only if $\alpha^2 \geq 4 \beta$.
::: 

::: {#exm- } 
Suppose $V$ is a real inner-product space and $T\in \mathcal{L}(V)$. Prove that there is an orthonormal basis of $V$ with respect to which $T$ has a block upper-triangular matrix
$$
\begin{bmatrix}
A_1 & & * \\
& \ddots & \\
0 & & A_m
\end{bmatrix}.
$$
where each $A_j$ is a 1-by-1 matrix or a 2-by-2 matrix with no eigenvalues.
::: 

::: {#exm- } 
Prove that if $T\in \mathcal{L}(V)$ and $j$ is a positive integer such that $j \leq \text{dim}  V$, then $T$ has an invariant subspace whose dimension equals $j-1$ or $j$.
::: 

::: {#exm- } 
Prove that there does not exist an operator $T\in \mathcal{L}(\mathbb{R}^7)$ such that $T^2+T+I$ is nilpotent.
::: 

::: {#exm- } 
Give an example of an operator $T\in \mathcal{L}(\mathbb{C}^7)$ such that $T^2+T+I$ is nilpotent.
::: 

::: {#exm- } 
Suppose $V$ is a real vector space and $T\in \mathcal{L}(V)$. Suppose $\alpha, \beta \in \mathbb{R}$ are such that $\alpha^2< 4\beta$. Prove that null $(T^2+\alpha T + \beta I)^k$ has even dimension for every positive integer $k$.
::: 

::: {#exm- } 
Suppose $V$ is a real vector space and $T\in \mathcal{L}(V)$. Suppose $\alpha, \beta \in \mathbb{R}$ are such that $\alpha^2< 4\beta$ and $T^2+\alpha T+\beta I$ is nilpotent. Prove that $\text{dim}  V$ is even and $(T^2+\alpha T+\beta I)^{\text{dim}  V/2}=0.$
::: 

::: {#exm- } 
Prove that if $T\in \mathcal{L}(\mathbb{R}^3)$ and 5, 7 are eigenvalues of $T$, then $T$ has no eigenpairs.
::: 

::: {#exm- } 
Suppose $V$ is a real vector space with $\text{dim}  V =n $ and $T\in \mathcal{L}(V)$ is such that null $T^{n-2}\neq $ null $T^{n-1}$. Prove that if $T$ has at most two distinct eigenvalues and that $T$ has no eigenpairs.
::: 

::: {#exm- } 
Prove that 1 is an eigenvalue of every square matrix with the property that the sum of the entries in each row equals 1.
::: 

::: {#exm- } 
Suppose $V$ is a real vector space with $\text{dim}  V =2 $. Prove that if
$$
\begin{bmatrix}
a & c \\
b & d
\end{bmatrix}
$$
is the matrix of $T$ with respect to some basis of $V$, then the characteristic polynomial of $T$ equals $(z-a)(z-d)-b c$.
::: 

::: {#exm- } 
Suppose $V$ is a real inner-product space and $S\in \mathcal{L}(V)$ is an isometry. Prove that if $(\alpha, \beta)$ is an eigenpair of $S$, then $\beta=1$.
::: 


