---
pagetitle: "Linear Transformations in Geometry - Learning Linear Algebra"
---
# Linear Transformations in Geometry


Next we give several examples of linear transformations from $\mathbb{R}^2$ to $\mathbb{R}^2$ that are commonly used in plane geometry.

::: {#thm- } 
Let $T$ be a linear transformation from  $\mathbb{R}^2$ to $\mathbb{R}^2$. If the matrix of $T$ is of the form
$$
\begin{bmatrix} k & 0 \\ 0 & k  \end{bmatrix}
$$
then $T$ is a \index{scaling} **scaling**  transformation.
If $k>1$ then the scaling is called a \index{dilation} **dilation**, and is called a \index{contraction} **contraction** when $k<1$.
::: 

::: {.proof }
The proof is left for the reader.
::: 

::: {#exm- } 
Is the linear transformation given by the system of linear equations
$$
\left\{
\begin{array}{l}
y_1=  7x_1 \\
y_2 =  7x_2 \\
\end{array}
\right.
$$
from $\mathbb{R}^2$ to  $\mathbb{R}^2$ a scaling?
The answer is yes since the matrix of the linear transformation is 
$\begin{bmatrix} 7 & 0 \\ 0 & 7 \end{bmatrix}$, which by definition is a scaling. For example, we can write 
$$
T(\vec x)=\begin{bmatrix} 7 & 0 \\ 0 & 7 \end{bmatrix} \vec x.
$$
We can use $T$ to dilate the vector $\vectortwo{1}{2}$ by $7$ to obtain 
$$
T\vectortwo{1}{2}
=\begin{bmatrix} 7 & 0 \\ 0 & 7 \end{bmatrix}\vectortwo{1}{2}
=\vectortwo{7}{14}.
$$

::: 

::: {#thm- } 
\label{orthproj}
Let $T$ be a linear transformation from  $\mathbb{R}^2$ to $\mathbb{R}^2$. If the matrix of $T$ is of the form
$$
\frac{1}{w_1^2+w_2^2} \begin{bmatrix} w_1^2 & w_1 w_2 \\ w_1 w_2 & w_2^2  \end{bmatrix}
$$
then $T$ is an \index{orthogonal projection} **orthogonal projection** transformation onto the line $L$ spanned by any nonzero vector $\vec w = \begin{bmatrix} w_1 \\ w_2  \end{bmatrix}$ parallel to $L$.
::: 

::: {.proof }
Suppose line $L$ is spanned by $\vec w$. We can decompose any vector $\vec x$ as $\vec x^{||}+\vec x^\perp$ as diagrammed:
Notice $\vec x^\perp$ is the perpendicular component so 
\begin{equation}\label{perpeq}
\vec w \cdot \vec x^\perp =0 
\qquad \text{or equivalently} \qquad
\vec w \cdot (\vec x -\vec x^{||}) =0.
\end{equation}
To project $\vec x$ onto the line $L$ we notice 
\begin{equation}\label{projfac}
\vec x^{||}=k \vec w
\end{equation}
for some scalar $k$. By substitution, of \ref{projfac} into \ref{perpeq} and solving for $k$ we obtain 
\begin{equation}\label{facdef}
k=\frac{\vec w \cdot \vec x}{\vec w \cdot \vec w}.
\end{equation}
Using  \ref{projfac} and \ref{facdef} we define the orthogonal projection of a vector $\vec x$ onto a given line $L$ as
\begin{equation}\label{projdef}
\text{proj}_L(\vec x)
=\frac{\vec w \cdot \vec x}{\norm{\vec w}^2}\vec w.
\end{equation}
We would like to have \ref{projdef} in the form of a matrix. 
To do so let $\vec w=\vectortwo{w_1}{w_2}$  and $\vec x=\vectortwo{x_1}{x_2}$. 
Then from \ref{facdef} and \ref{projdef} we find
\begin{align*}
\text{proj}_L(\vec x) 
& = \frac{1}{\norm{\vec w}^2} \left((x_1 w_1+x_2 w_2)\vectortwo{w_1}{w_2} \right) \\
& = \frac{1}{\norm{\vec w}^2} \left((x_1 w_1\vectortwo{w_1}{w_2}+x_2 w_2 \vectortwo{w_1}{w_2} \right) \\
& = \frac{1}{\norm{\vec w}^2} \left(\vectortwo{x_1 w_1^2}{x_1w_1 w_2}+\vectortwo{x_2w_1w_2}{x_2w_2^2} \right) \\
& = \frac{1}{\norm{\vec w}^2} \vectortwo{x_1 w_1^2+x_2w_1w_2}{x_1w_1 w_2+x_2w_2^2} 
= \frac{1}{\norm{\vec w}^2}
\begin{bmatrix} w_1^2 & w_1 w_2 \\ w_1 w_2 & w_2^2  \end{bmatrix}
\vectortwo{x_1}{x_2}
.
\tag*{ }
\end{align*} 
::: 

::: {#exm- } 
Find the matrix $A$ of the orthogonal projection onto the line $L$ spanned by $\vec w = \begin{bmatrix} 4 \\3  \end{bmatrix}$ 
and project the vector
 $\vec u=\vectortwo{1}{5}$ onto the line $L$ spanned by $\vec w$.
By \ref{orthproj}, the matrix is 
$$
A=\frac{1}{w_1^2+w_2^2}
\begin{bmatrix}
w_1^2 & w_1 w_2 \\
w_1 w_2 & w_2^2
\end{bmatrix}
=\frac{1}{25}
\begin{bmatrix}
16 & 12 \\
12 & 9
\end{bmatrix}
=
\begin{bmatrix}
16/25 & 12/25 \\
12/25 & 9/25
\end{bmatrix}
.
$$
For example, we can project the vector
 $\vec u$ onto the line $L$ spanned by $\vec w$.  The matrix $A$ defines this linear transformation $T$ and so to project onto the line $L$ is just matrix multiplication:
$$
T\vectortwo{1}{5}=\frac{1}{25}
\begin{bmatrix}
16 & 12 \\
12 & 9
\end{bmatrix}
\vectortwo{1}{5}
=\vectortwo{76/25}{57/25}.
%\approx \vectortwo{3.04}{2.28}.
\tag*{ }
$$

::: 

::: {#thm- } 
\label{reflmatrix}
Let $T$ be a linear transformation from  $\mathbb{R}^2$ to $\mathbb{R}^2$. If the matrix of $T$ is of the form
$$
\begin{bmatrix} 2 u_1^2-1 & 2 u_1 u_2 \\ 2 u_1 u_2 & 2 u_2^2 -1   \end{bmatrix}
$$ 
then $T$ defines a \index{reflection} **reflection**  transformation about the line $L$, 
where $\vec u = \begin{bmatrix} u_1 \\ u_2  \end{bmatrix}$ is any unit vector lying on $L$.
::: 

::: {.proof }
Suppose we want to reflect $\vec x$ through the line $L$ as diagrammed:
Then 
\begin{equation}\label{ref1}
\text{ref}_L(\vec x)=\vec x^{||}-\vec x^\perp  
\end{equation}
and
\begin{equation}\label{ref2}
\text{proj}_L(\vec x)=\vec x^{||}.
\end{equation}
By subtracting \ref{ref2} from \ref{ref1}, we obtain
\begin{equation}\label{ref3}
\text{ref}_L(\vec x)=2 \text{proj}_L(\vec x)-\vec x.
\end{equation}
For simplicity assume $L$ is a any line that passes through the origin and let $\vec u$ be a unit vector $\vec u = \begin{bmatrix} u_1 \\ u_2  \end{bmatrix}$ lying on $L$. 
Notice \ref{projdef} in the special case of a unit vector $\vec u$ becomes 
$\text{proj}_L(\vec x)=(\vec u\cdot \vec x)\vec u.$
Then 
\begin{align*}
\text{ref}_L(\vec x)& =2 \text{proj}_L(\vec x)-\vec x 
=2(\vec u\cdot \vec x)\vec u-\vec x \\
& = 2(u_1x_1+u_2x_2)\begin{bmatrix} u_1 \\ u_2  \end{bmatrix}-\begin{bmatrix} x_1 \\ x_2  \end{bmatrix}
=2u_1 x_1 \begin{bmatrix} u_1 \\ u_2  \end{bmatrix}+2u_2x_2 \begin{bmatrix} u_1 \\ u_2  \end{bmatrix}-\begin{bmatrix} x_1 \\ x_2  \end{bmatrix} \\
& = \begin{bmatrix}  
2u_1^2x_1+2u_1 u_2x_2-x_1 \\ 2u_1u_2x_1+2u_2^2 u_2x_2-x_2 
\end{bmatrix} 
= \begin{bmatrix}  
2u_1^2-1 & 2u_1 u_2\\
2u_1 u_2 & 2u_2^2-1
\end{bmatrix}
\vectortwo{x_1}{x_2}.
\tag*{ }
\end{align*}
::: 

::: {#exm- } 
Find the matrix $A$ of a reflection through the line through the origin spanned by $\vec w = \begin{bmatrix} 4 \\3  \end{bmatrix}$ and use it to reflect $\begin{bmatrix} 1 \\5  \end{bmatrix}$ about the line $L$.
Let $\vec u=\vectortwo{4/5}{3/5}$.  We notice $\vec u$ is a unit vector, since $\norm{u}=1$. Then, by \ref{reflmatrix}, the matrix we seek is 
$$
A=\begin{bmatrix}
7/25 & 24/25 \\ 24/25 & -7/25
\end{bmatrix}.
$$
We can reflect the vector $\begin{bmatrix} 1 \\5  \end{bmatrix}$ about the line $L$ using matrix multiplication
$$
T \begin{bmatrix} 1 \\5  \end{bmatrix}
=
\frac{1}{25}
\begin{bmatrix}
7 & 24 \\ 24 & -7
\end{bmatrix}
\begin{bmatrix} 1 \\5  \end{bmatrix}
=\vectortwo{127/25}{-11/25}.
%\approx \vectortwo{5.08}{-0.44}.
\tag*{ }
$$

::: 

::: {#thm- } 
\label{rotmatrix}
Let $T$ be a linear transformation from  $\mathbb{R}^2$ to $\mathbb{R}^2$. If the matrix of $T$ is of the form
$$
\begin{bmatrix} 
\cos \theta & -\sin \theta  \\ 
\sin \theta & \cos \theta  \end{bmatrix}
$$
then $T$ is a (counterclockwise) \index{rotation} **rotation**  transformation through an angle $\theta$.
::: 

::: {.proof }
If a vector $\vec x=\vectortwo{x_1}{x_2}$ is rotated through an angle of $\pi/2$, then a vector $\vec y=\vectortwo{-x_2}{x_1}$ is obtained, via $\vec x\cdot \vec y =\vec 0$. More generally, if we rotate (counterclockwise) a given $\vec x$ through an angle $\theta$ we determine
\begin{align*}
T(\vec x)&=(\cos \theta) \vec x+(\sin\theta) \vec y
=(\cos \theta)\vectortwo{x_1}{x_2}+(\sin \theta)\vectortwo{-x_2}{x_1} \\
&=\vectortwo{(\cos \theta)x_1-(\sin\theta))x_2}{(\sin \theta)x_1-(\cos\theta))x_2} 
=\begin{bmatrix} \cos \theta & -\sin \theta  \\ \sin \theta & \cos \theta  \end{bmatrix} \vectortwo{x_1}{x_2}
=\begin{bmatrix} \cos \theta & -\sin \theta  \\ \sin \theta & \cos \theta  \end{bmatrix} \vec x
\end{align*}
as seen from the diagram.
::: 

::: {#exm- } 
Find the matrix of the linear transformation that rotates the vector $\begin{bmatrix} 4 \\ 2  \end{bmatrix}$ by 30 degrees counterclockwise.
By \ref{rotmatrix}, the matrix of this transformation is $A=\begin{bmatrix} \sqrt{3}/2 & -1/2 \\  1/2 & \sqrt{3}/2 \end{bmatrix}.$
We will use matrix multiplication to perform the transformation
$$
T\vectortwo{4}{2}
= \begin{bmatrix} \frac{\sqrt{3}}{2} & \frac{-1}{2} \\
\frac{1}{2} & \frac{\sqrt{3}}{2}
\end{bmatrix}
\vectortwo{4}{2}
=\cos 30^\circ \vectortwo{4}{2}+\sin 30^\circ \vectortwo{4}{2}
=\vectortwo{2\left(\sqrt{3}+1\right)}{\sqrt{3}+1}.
\approx \vectortwo{2.46}{3.73}
$$
::: 

::: {#thm- } 
\label{shearmatrix}
Let $T$ be a linear transformation from  $\mathbb{R}^2$ to $\mathbb{R}^2$. If the matrix of $T$ is of the form
$$
\begin{bmatrix} 1 & 0  \\ k & 1  \end{bmatrix}
\qquad \text{or} \qquad
\begin{bmatrix} 1 & k  \\ 0 & 1  \end{bmatrix},
$$
where $k$ is any constant, then $T$ defines a \index{vertical shear} **vertical shear** or \index{horizontal shear} **horizontal shear** transformation, respectively. 
::: 

::: {.proof }
The proof is left for the reader.
::: 

::: {#exm- } 
Given the vector $\begin{bmatrix} 2 \\3  \end{bmatrix}$ in $\mathbb{R}^2$ show geometrically a vertical shear of 2 and a horizontal shear of $\frac{1}{2}$.
By \ref{shearmatrix}, we can apply these linear transformations using matrix multiplication by using the matrices 
$\begin{bmatrix} 1 & 0  \\ 2 & 1  \end{bmatrix}$ 
and 
$\begin{bmatrix} 1 & 1/2  \\ 0 & 1  \end{bmatrix}$.
$$
\label{verticalshear}
\text{Vertical Shear: \quad }  T\begin{bmatrix} 2 \\3  \end{bmatrix} 
= \begin{bmatrix} 1 & 0  \\ 2 & 1  \end{bmatrix} \begin{bmatrix} 2 \\3  \end{bmatrix} = \begin{bmatrix} 2 \\7  \end{bmatrix}
$$
$$
\label{horizontalshear}
\text{Horizontal Shear: \quad } T\begin{bmatrix} 2 \\3  \end{bmatrix} 
= \begin{bmatrix} 1 & 1/2  \\ 0 & 1  \end{bmatrix} \begin{bmatrix} 2 \\3  \end{bmatrix} =\begin{bmatrix} 7/2 \\3  \end{bmatrix} 
$$

::: 

::: {#exm- } 
Interpret the linear transformation
$T(\vec x)=\begin{bmatrix} 0 & -1 \\ -1 & 0 \end{bmatrix}\vec x$
geometrically.
The transformation has a matrix of the form
$$
\begin{bmatrix} 2u_1^2-1 & 2 u_1 u_2 \\ 2u_1 u_2 & 2u_2^2-1 \end{bmatrix}
$$
where $u_1=\sqrt{2}/2$ and $u_2=-\sqrt{2}/2$ since $2u_1^2-1=0$, $2u_2^2-1=0$, and $2u_1 u_2=-1$. 
Since $|| \vec u ||=1$ and $\vec u$ lies on the line $y=x$, then matrix $\begin{bmatrix} 0 & -1 \\ -1 & 0 \end{bmatrix}$ represents the linear transformation which is a reflection through the line $y=x$.

::: 

\begin{align*}
\text{scaling} \quad & 
\begin{bmatrix} k & 0 \\ 0 & k  \end{bmatrix} &
\text{shears} \quad &  
\begin{bmatrix} 1 & 0  \\ k & 1  \end{bmatrix}
 \text{ or }
\begin{bmatrix} 1 & k  \\ 0 & 1  \end{bmatrix} \\
\text{reflection} \quad & 
\begin{bmatrix} 2 u_1^2-1 & 2 u_1 u_2 \\ 2 u_1 u_2 & 2 u_2^2 -1   \end{bmatrix} & 
\text{rotation} \quad & 
\begin{bmatrix} \cos \theta & -\sin \theta  \\ \sin \theta & \cos \theta  \end{bmatrix} &  \\
\text{orthogonal projection} \quad &
\frac{1}{w_1^2+w_2^2} \begin{bmatrix} w_1^2 & w_1 w_2 \\ w_1 w_2 & w_2^2  \end{bmatrix} & 
\end{align*}

::: {#exm- } 
Interpret the linear transformation $T(\vec x)=\begin{bmatrix} 1 & 1 \\ -1 & 1 \end{bmatrix} \vec x$, geometrically. Explain.
This is a rotation combined with a scaling. The transformation rotates 45 degrees counterclockwise and has a scaling factor of $\sqrt{2}$. 
::: 


