# Basic Set Theory

project:
  type: book
  resources: 
    - assets
    - images
  post-render: 
    - ../_webtools/html_revise_bst.py

book:
  title: "Basic Set Theory"
  subtitle: "That Anyone Can Learn"
  site-url: https://directknowledge.com/basic-set-theory/
  description: "This book is for beginners who want to explore the fascinating world of logical reasoning, mathematical proofs, and set theory."
  isbn: "978-1-951290-10-8"
  language: "en"
  medium: "digital online"
  public-url: "https://directknowledge.com"
  publisher: "Direct Knowledge"
  url: https://directknowledge.com/basic-set-theory/
  chapters:
    - index.qmd
    - propositional-logic.qmd
    - predicate-logic.qmd
    - mathematical-proofs.qmd
    - set-theory.qmd
    - functions-and-relations.qmd
    - well-founded-confluence.qmd
    - connect-everything.qmd
    - concept-theory.qmd
    - references.qmd
  sidebar:
    title: "Basic Set Theory"

metadata-files:
  - ../_variables.yml
  - ../_meta/book-html.yml
  - ../_meta/format.yml
  #- _meta/_book-epub.yml
  #- _meta/_book-hardcover.yml
  - _meta/_book-paperback.yml
