# Basic Set Theory

project:
  type: book
  resources: 
    - assets
    - images
  post-render: 
    - ../_webtools/html_revise_bst.py

book:
  title: "Basic Set Theory"
  chapters:
    - index.qmd
    - propositional-logic.qmd
    - predicate-logic.qmd
    - mathematical-proofs.qmd
    - set-theory.qmd
    - functions-and-relations.qmd
    - well-founded-confluence.qmd
    - connect-everything.qmd
    - concept-theory.qmd
    - references.qmd
  sidebar:
    title: "Basic Set Theory"
  site-url: https://directknowledge.com/basic-set-theory/
  description: "Basic Set Theory"

metadata-files:
  - ../_meta/book-html.yml
  - ../_meta/format.yml
  #- _meta/_book-epub.yml
  #- _meta/_book-hardcover.yml
  - _meta/_book-paperback.yml
