---
pagetitle: "Basic Set Theory - That Anyone Can Learn"
---
# Preface {.unnumbered}

::: {.content-visible when-format="pdf"}
\pagenumbering{roman}
\pagestyle{preface} 
:::

::: {.content-visible when-format="html"}
{{< meta welcome_bst >}}
:::

::: {.content-visible when-format="html"}
## Short Description
{{< meta short_desc_bst >}}
:::

::: {.content-visible when-format="html"}
## Other Resources 
{{< meta resources_bst >}} 
:::

::: {.content-visible when-format="html"}
## Update History
Here is where I keep a log of the majors changes as I finish writing the book. 

2. First draft of preface published on 1/27/2023.
1. First draft published on 1/14/2023.
:::



::: {.content-hidden }
## Purpose {.unnumbered .unlisted }
**The major themes of the text**.
**Python**.
**Proofs**.
**Connections**.
**Concepts**.
:::

::: {.content-hidden }
## Audience {.unnumbered .unlisted }
**How I wrote this book**.
**Pedagogical features**.
:::

::: {.content-hidden }
## Stucture {.unnumbered .unlisted }
**References**.
:::

::: {.content-hidden }
## Teaching {.unnumbered .unlisted }
**Philosphy**.
**Examples**.
:::




## Acknowledgements {.unnumbered .unlisted }
{{< meta acknowledgements_bst >}} 

David A. Smith \\ Fort Worth, Texas


::: {.content-visible when-format="pdf"}
\setcounter{secnumdepth}{1}
\setcounter{tocdepth}{1}
\clearpage
\pagestyle{toc} 
\tableofcontents
\mainmatter 
\pagenumbering{arabic}
\pagestyle{fancy} 
:::
